### ISSUE TITLE
Policy Attachment doc text does not match examples

### ISSUE THREAD

**Issue by woodgear** [kubernetes-sigs/gateway-api#1000]
**What would you like to be added**:
add missing example in policy-attachment
[drainTimeout ](https://gateway-api.sigs.k8s.io/v1alpha2/references/policy-attachment/#:~:text=we%20can%20see%20how%20the%20override%20attached%20to%20the%20Gateway%20has%20precedence%20over%20the%20default%20drainTimeout%20value%20attached%20to%20the%20Route.)
it seems should have an example about override drainTimeout with policy attachment, but I could not find it.

**Comment by youngnick** [comment]
/remove-lifecycle stale

This issue covers updating the policy attachment example to match the example in the text.
This would be a great early issue for someone who wants to contribute.

/help-wanted
/good-first-issue
