### ISSUE TITLE
Linux Foundation Mentorship project: Perform a docs assessment

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/gateway-api#1003]
This issue covers performing a CNCF-style [docs assessment](https://github.com/cncf/techdocs/blob/main/assessments/howto.md) for the Gateway API documentation, as part of a Linux Foundation Mentorship project.

**Why this is needed**:

Our documentation has grown quickly and organically, and as a result is lacking overarching structure and clarity. I hope that getting some tech writer skills across it will give us some useful recommendations.

In scope:
- reviewing our site's current state
- producing a recommendation

Stretch goal:
- fixing issues found.

/kind documentation

If you are interested, please check out more information and apply at the following links:
- CNCF Mentorship, LFX Spring 2022 URL: https://github.com/cncf/mentoring/blob/main/lfx-mentorship/2022/01-Spring/README.md#documentation-assessment-sig-network-gateway-api
- LFX URL: https://mentorship.lfx.linuxfoundation.org/project/0e4c9797-2dc5-4621-b46a-f1b7371a2495

**Comment by nate-double-u** [comment]
* CNCF Mentorship Spring 2022 URL: https://github.com/cncf/mentoring/blob/main/lfx-mentorship/2022/01-Spring/README.md#documentation-assessment-sig-network-gateway-api
* LFX URL: https://mentorship.lfx.linuxfoundation.org/project/0e4c9797-2dc5-4621-b46a-f1b7371a2495

**Comment by youngnick** [comment]
Hi @deprov447, please apply through the LFX URL above, and we'll assess your application.

**Comment by Kodalien** [comment]
Gateway API  documentation and code locations are at ????  I just start 😄

**Comment by youngnick** [comment]
Sorry @Kodalien, this is intended as a tracking issue for the person who gets the Linux Foundation Spring Mentorship position. If you would like to do it, I'd encourage you to apply at the links Nate posted above.

**Comment by aastha01chauhan** [comment]
@youngnick Hi! The really liked the concept of this project. I am proficient in python programming and Go. Would love to engage with the community and contribute here this spring.

**Comment by youngnick** [comment]
Great to hear @aastha01chauhan! As I said above, we'll need an application through the Linux Foundation Mentorship program. I've updated the description as well so that's more clear. Sorry for the confusion.

**Comment by khabdrick** [comment]
@youngnick are potential candidates required to make contributions to the project prior to getting accepted?

**Comment by akshat5302** [comment]
Hii @youngnick I want to be part of it I'm intermediate in python and DevOps and want to upskill myself by contributing to opensource. I just want to know if this contribution is still open in lfx mentorship or application had been closed?

**Comment by khabdrick** [comment]
@akshat5302 you can just go to the link and find out.
https://mentorship.lfx.linuxfoundation.org/project/0e4c9797-2dc5-4621-b46a-f1b7371a2495

**Comment by youngnick** [comment]
@khabdrick no, no requirements for contributions. I believe that applications close on the 15th of February, so get them in now!

**Comment by ShivamTyagi12345** [comment]
hey I believe my skills perfectly alignwith this mentorship and No mentees were accepted for this  Is there a way to ask for a consideration?

**Comment by shreyadenny** [comment]
Hello I applied for this through the Linux Foundation Mentorship with hopes to be able to work on this particular project. Is there a way to find out the status of my application?

**Comment by akshat5302** [comment]
> Hello I applied for this through the Linux Foundation Mentorship with hopes to be able to work on this particular project. Is there a way to find out the status of my application?

I applied too but didn't got any reply till yet

**Comment by youngnick** [comment]
Hi everyone, currently the process for selection is still ongoing, people will be notified of the results sometime on February 25, 2022 US Pacific time.

**Comment by youngnick** [comment]
Nice work @mehabhalodiya, and sorry for not doing that earlier!

For everyone else watching this, please join me in congratulating @mehabhalodiya on her successful application!

We'll leave this issue open for tracking, and reference the docs assessment here once it's created.

**Comment by youngnick** [comment]
@mehabhalodiya has done a great job and has finished up the docs assessment. Please see the results at https://github.com/cncf/techdocs/blob/main/assessments/0006-gateway-api.md .

/close
