### ISSUE TITLE
Admission Webhook: Who validates the validator?

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/gateway-api#1007]
We should be aiming to test every single validation we have in the webhook, for both happy and unhappy paths at an implementation level as well as at the existing unit test level. Conformance tests are the logical place for these to go.

**Comment by jpeach** [comment]
> Conformance tests are the logical place for these to go.

Not unit tests?

**Comment by youngnick** [comment]
![Both is good](https://c.tenor.com/ZezsFuiFB48AAAAd/both-is-good-both.gif)

We already have unit tests, I was intending to say that, if the conformance tests validate the webhook validations are present, then implementations are free to import the validator code into their own custom webhook, or run our one or whatever. I'll update the description.
