### ISSUE TITLE
Admission Webhook: Security scanning, vulnerability reporting, supply chain security mechanisms

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/gateway-api#1008]
Do we need to do this for beta?

Possibly this might be a good place to try some of the stuff being worked on in upstream, since we use the tooling but aren't really production-ready yet.

NOTE: we will need to incorporate (and perhaps partially, further document) our support policies for a post GA world: we need to say what historical versions we will support and what we will backport fixes to.

/kind cleanup

**Comment by youngnick** [comment]
This is due for a revisit before v0.6.0, at least to see if there's anything available to try out yet.

**Comment by shaneutt** [comment]
@youngnick just checking in on this one?

**Comment by youngnick** [comment]
I still think we should do something like this? Having some supply chain security stuff on our own webhook seems important.

**Comment by robscott** [comment]
Closing this out in favor of the upcoming deprecation and longer term removal of the validating webhook: https://github.com/kubernetes-sigs/gateway-api/issues/2319.
