### ISSUE TITLE
Allow delegation of parts of a HTTP domain name's request space

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/gateway-api#102]
**What would you like to be added**:
As a cluster operator, I want to be able to control domain names, including their TLS information, and delegate control over some part of the domain name's HTTP request space to other teams.

This delegation may be via path matching ("/blog" is controlled by Marketing, "/api" is controlled by the product team), header matching, (mobile clients should go to the Mobile team, the rest should go to the desktop team), or a combination of both. At least one of the types must be specified to differentiate delegations.

Teams that have space delegated to them should not be able to see private TLS information (that is, the TLS key for a domain name).

Delegations may be nested to an arbitrary degree, but each delegation may only divide the space given by its parent further. A delegation must not allow expansion outside its parent's space.

Conflicting delegations must produce an error, which ideally should be at object ingestion. That is, the object should be rejected when an operator (whether they are cluster operation or application developer) attempts to apply it.

**Why is this needed**:

This covers the current use case for Contour's HTTPProxy.

I've tried to be as feature-oriented here as possible, I think this covers most of it.

**Comment by youngnick** [comment]
Contrast this one with #103

**Comment by danehans** [comment]
xref: https://github.com/kubernetes-sigs/service-apis/issues/62

**Comment by jpeach** [comment]
/remove-lifecycle stale
/lifecycle frozen

This use case isn't possible with HTTPRoute today.

**Comment by shaneutt** [comment]
This is covered by #1058, closing as duplicate :+1:
