### ISSUE TITLE
Document Path Redirects and Rewrites (GEP 726)

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1038]
This GEP was implemented but has not been documented yet.

**Comment by youngnick** [comment]
The todo list here:
- [ ] Take the GEP (https://gateway-api.sigs.k8s.io/geps/gep-726/) and write some documentation that explains how to use the feature. This probably needs to be a separate Guide under the guides heading (stored in `/site-src/v1alpha2/guides`).
- [ ] #1124 will mean that there will be slight schema changes to any examples.
