### ISSUE TITLE
Document requirements for a resource to graduate to beta

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1039]
In the related [working doc](https://docs.google.com/document/d/1F3dcs_J8Y6GVlfMGjRtom5ljovnKa_MMIC34GJxUdBs/edit), the following was proposed as a starting point:

* Covered by conformance tests
* Implemented by several implementations
* Users are exercising most of the API surface

**Comment by hbagdi** [comment]
> requirements for a resource to graduate

Meaning graduation to the beta will be in on a resource by resource basis even for types that ship within the API? (not trying to say that it is bad, just new)

**Comment by youngnick** [comment]
Exactly. In the first round of v1beta1 changes, we will be graduating Gateway, GatewayClass, and HTTPRoute to `v1beta1`.
