### ISSUE TITLE
Introduce v1beta1 types for resources graduating to beta

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1041]
As one of the final steps to graduate GatewayClass, Gateway, and HTTPRoute to beta, we need to create v1beta1 type definitions for these resources. These MUST be identical to the corresponding v1alpha2 type definitions.

**Comment by mehabhalodiya** [comment]
@robscott Will, you help me to get started? I am interested to work on this.
I want to learn while contributing. Thanks!

**Comment by robscott** [comment]
Thanks for volunteering to help with this @mehabhalodiya! This will be one of our last steps prior to the v1beta1 (v0.5.0) release. In general, this will involve copying the type definitions for HTTPRoute, Gateway, and GatewayClass from the apis/v1alpha2 dir to a new apis/v1beta1 dir and then running `make generate`. We've never actually done this before, so I'm not 100% sure if anything else will be required, but that should be the starting point.
