### ISSUE TITLE
Change the version mention 

### ISSUE THREAD

**Issue by mehabhalodiya** [kubernetes-sigs/gateway-api#1048]
**What happened**:
Latest supported version [status](https://github.com/kubernetes-sigs/gateway-api#status) is mentioned wrong in the [README.md](https://github.com/kubernetes-sigs/gateway-api#readme).

It doesn't match with the site.
![k8s_signet](https://user-images.githubusercontent.com/73488906/158745909-c8bf7645-05b1-479b-9c93-c7b5277644cf.png)

**What you expected to happen**:
We should correct the version in README.md to avoid misconceptions.

**How to reproduce it (as minimally and precisely as possible)**:
Currently, it is written:
`The latest supported version is v1alpha2 as released by the [v0.4.0 release](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.4.0) of this project.`

I think we should change it to:
`The latest supported version is v1alpha2 as released by the [v0.4.2 release](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.4.2) of this project.`

**Comment by Anubhavdevv** [comment]
Hey @mehabhalodiya i would like to work on this issue

**Comment by Nawaz027** [comment]
All the best @Anubhavdevv

**Comment by Anubhavdevv** [comment]
> All the best @Anubhavdevv 

Thank you 🤠

**Comment by mehabhalodiya** [comment]
Thanks @Anubhavdevv for opening a PR super soon 🙂

**Comment by Anubhavdevv** [comment]
> Thanks @Anubhavdevv for opening a PR super soon 🙂 

Thank you @mehabhalodiya please review it 🤠
