### ISSUE TITLE
'Security Model' page just shows `TemplateNotFound` error

### ISSUE THREAD

**Issue by wjam** [kubernetes-sigs/gateway-api#1053]
**What happened**: Viewing the 'Security Model' page only shows a message about `TemplateNotFound`

**What you expected to happen**: Able to read the content on the Security Model page, which I presume is https://github.com/kubernetes-sigs/gateway-api/blob/master/site-src/concepts/security-model.md

**How to reproduce it (as minimally and precisely as possible)**: Go to https://gateway-api.sigs.k8s.io/concepts/security-model/ and look at the page

**Anything else we need to know?**:

**Comment by robscott** [comment]
Thanks for catching this @wjam! I've filed #1054 to fix the bug.
