### ISSUE TITLE
Include port in listener status

### ISSUE THREAD

**Issue by markmc** [kubernetes-sigs/gateway-api#1060]
We should consider adding the port number to listener status in anticipation of future support for auto-assigning a port when no port is specified.

By adding it in advance of actually supporting auto-assignment, API users can begin to adapt their usage in a way that will continue to work in future.

For example, examples like in [Istio's gateway docs](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/) could be future-proofed to do:

```
$ kubectl wait -n istio-ingress --for=condition=ready gateways.gateway.networking.k8s.io gateway
$ export INGRESS_HOST=$(kubectl get gateways.gateway.networking.k8s.io gateway -n istio-ingress -ojsonpath='{.status.addresses[*].value}')
$ export INGRESS_PORT=$(kubectl get gateways.gateway.networking.k8s.io gateway -n istio-ingress -ojsonpath='{.status.listeners[*].port}')
```

See also #1061, #818, and [Gateway API: Multi Port Approach](https://docs.google.com/document/d/1NN-IDoN-mIxtv6f7JR_G9kK1kKbZHMqQPcUSy6tPDbA)

**Comment by youngnick** [comment]
Strong +1 from me here.

**Comment by robscott** [comment]
I think this is worth exploring, but want to be a bit cautious. The most compelling reason to add port to status would be if we added support for automatic port assignment/allocation. Without that feature, we'd just be replicating a value from spec to status. I think it may be better to wait until we have a clearer picture for what port assignment would look like/if we want to proceed with that feature before we add port to status.

**Comment by shaneutt** [comment]
Hey @kundan2707 :wave: just wanted to check if there was some new context on this one?
