### ISSUE TITLE
Make listener port optional

### ISSUE THREAD

**Issue by markmc** [kubernetes-sigs/gateway-api#1061]
There are multiple cases where it may make sense to not require a gateway owner to specify a listener port:

1. Where a port number is irrelevant or nonsensical - #1052 is an example AIUI
2. Where the port is well-known and can be derived from the listener protocol - e.g. where `protocol==HTTP` default to port 80 if unspecified
3. Where a port should be auto-allocated for this listener - e.g. similar to auto-allocating an ephemeral port if you call `bind()` with the port specified as 0

One proposal is to specify that an unspecified port should be defined to have per-protocol semantics - so e.g. we'd define defaults for HTTP and HTTPS, but TLS, TCP, and UDP would be auto-allocated a random port. Implementation-specific protocols would define their own default behaviors.

Another alternative would be to use `port==0` for auto-allocating a random port, and only have defaults for protocols where one makes sense.

See also #1060, #818, and [Gateway API: Multi Port Approach](https://docs.google.com/document/d/1NN-IDoN-mIxtv6f7JR_G9kK1kKbZHMqQPcUSy6tPDbA)

**Comment by markmc** [comment]
#1066 adds docs for implementors about the possibility of required fields become optional in future:

> Handle fields that have transitioned from required to optional without crashing

**Comment by hbagdi** [comment]
Gateway resource consists of two parts:
1. Network configuration that is closely tied to the underlying infrastructure. Ports, IPs and hostnames are good example of this category.
2. Routing configuration such as TLS, route selectors, etc.

Of these, most/all use-cases consider (2) to be the source of truth and a Gateway should _lead_ and not _follow_.

(1) is more complicated.
In most of our designs up until this point, we have focused on Gateway resource "representing" a network endpoint.
Up until now, we have assumed that such a network endpoint exists or is managed out of band, and the Gateway resource reflects the state of that resource and the API has no semantics around that.

There are two class large classes of use-cases
- Treat networking configuration such as ports in the Gateway as the source of truth. Reconcile the rest of the infrastructure to this. This is similar to throw Service resource works and has been the focus so far.
- Gateway represents the existing state, which is updated based on what exists in the underlying infrastructure. We have not focused much on the use-cases of these classes or waived them off with "another controller could be creating the gateway resource". I've seen some use-cases from proxy vendors, mesh vendors and L4-level use-cases that run into this problem.

I don't propose a solution here. I want to express my understanding and validate it with how others are thinking about it.
cc @shaneutt who has done some thinking around these parts.

cc @robscott @youngnick
