### ISSUE TITLE
docs: intended ReferencePolicyTo implementation unclear for backendRef without optional Kind

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/gateway-api#1092]
**What would you like to be added**:

When the optional `kind` field is not specified on a `BackendReferenceObject`, explicitly describe whether `Service` is assumed to be the default `Kind`, or if it should be handled as a wildcard selector by name across any `Kind`.

**Why this is needed**:

The `kind` field on [`ReferencePolicyTo`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.ReferencePolicyTo) is required, but it may be used to grant permission for a [`BackendObjectReference`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.BackendObjectReference) that does not specify a `kind` field. As part of validation when applying a route, it's unclear if this should require an actual API call to look up potentially matching objects, if a lightweight validation is possible by assuming an unspecified `kind` on a `BackendObjectReference` implies a `Service`, and/or if the route is accepted, if traffic should be prevented from routing to non-`Service` backends.

**Comment by robscott** [comment]
If I'm understanding this correctly, I think this shows a gap in our reference docs. The docs you linked to do not mention that `BackendObjectReference.Kind` has a [default value of `Service`](https://github.com/kubernetes-sigs/gateway-api/blob/ef773194892636ea8ecbb2b294daf771d4dd5009/apis/v1alpha2/object_reference_types.go#L105). I think we should clarify more generally that if/when a controller encounters an empty value on a field with a default value configured, it should consider that input invalid.

**Comment by mikemorris** [comment]
Fixed by #1121
