### ISSUE TITLE
Conformance Tests: HTTPRoute Matching

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1102]
This issue is intended to track conformance test development for HTTPRoute matching. Comment below if you're interested in working on covering any of these areas.

**Core Capabilities:**
- [x] Path prefix matching
- [x] Exact path matching (#1147)
- [x] Header matching (#1134)
- [ ] Combinations of the above

**Extended Capabilities:**
- [x] Method matching (@skriss)
- [x] Query param matching (@skriss)
- [ ] Combinations of the above with core capabilities

**Comment by candita** [comment]
@robscott Interested

**Comment by robscott** [comment]
@candita great, thanks! Any particular tests described in this issue you want to take on? Let me know if you have any questions as you're getting started.

**Comment by skriss** [comment]
I've submitted https://github.com/kubernetes-sigs/gateway-api/pull/1134 for header matching.

**Comment by skriss** [comment]
I can take on tests for query param and method matching (@robscott note that query param should move under "Extended" conformance per https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPQueryParamMatch).

Has a pattern been discussed for separating extended-conformance tests from core conformance ones? Is it intended to use the `SupportedFeatures` field (https://github.com/kubernetes-sigs/gateway-api/blob/master/conformance/conformance_test.go#L51-L53)? If not, I can put some thought into how to structure things.

**Comment by robscott** [comment]
Thanks @skriss! I've moved query param matching into extended. I think right now our best approach is to have any extended feature gated by the "SupportedFeatures" option, but open to other ideas.

**Comment by skriss** [comment]
Circling back here, @robscott you can mark query param matching as done, and I'll try to get to method matching soon.

Would be great if someone else wanted to pick up the combination tests!

**Comment by robscott** [comment]
Updated, thanks @skriss!

**Comment by sunjayBhatia** [comment]
I can work on some tests for combinations of matching capabilities

Also see https://github.com/kubernetes-sigs/gateway-api/pull/1370 for a relevant PR

**Comment by youngnick** [comment]
/remove-lifecycle stale

@skriss, @sunjayBhatia, is there further work outstanding here?

**Comment by skriss** [comment]
> /remove-lifecycle stale
> 
> @skriss, @sunjayBhatia, is there further work outstanding here?

HTTP method matching can be checked off in the list up top. Beyond that, I think some tests of combinations of different match types would still be valuable. I'm happy to work on some of those unless someone else beats me to it.

**Comment by youngnick** [comment]
Great, thanks, I've updated the list.

**Comment by robscott** [comment]
This is mostly done, closing it out in favor of a more focused bug to finish it up: https://github.com/kubernetes-sigs/gateway-api/issues/1962.
