### ISSUE TITLE
Conformance Tests: HTTPRoute Filters

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1103]
This issue is intended to track conformance test development for HTTPRoute filters. Comment below if you're interested in working on covering any of these areas.

**Core Capabilities:**
- [x] Header modifier (@skriss)
  - [x] Set
  - [x] Add
  - [x] Remove
- [x] Request Redirect: (@LiorLieberman)
  - [x] Scheme
  - [x] Port Number

**Experimental Capabilities:**
- [x] Request Redirect:
  - [x] Path
- [x] Request Rewrite: (@LiorLieberman )
  - [x] Host
  - [x] Path

**Extended Capabilities:**
- [x] Request mirroring
- [ ] Combinations of the above with core capabilities

**Comment by skriss** [comment]
I've submitted https://github.com/kubernetes-sigs/gateway-api/pull/1163 for the header modifier set/add/remove cases.

**Comment by sunjayBhatia** [comment]
I think this issue should be augmented (or another created) to add testing for HTTPRoute Filters per-BackendRef as well, since the existing tests only test per-RouteRule

Part of that will include adding a test helper that can conditionally check a response has the correct content, given it was routed to a particular backend

**Comment by robscott** [comment]
@LiorLieberman is working on conformance tests for HTTP Redirects.

**Comment by LiorLieberman** [comment]
@robscott is request conformance for request mirroring still wanted? 

also proposing changes to the description

...

Extended Capabilities:
 Request Redirect: (@LiorLieberman)
   [x] Scheme
   [x] Port Number
   
Experimental  Capabilities:
 Request Redirect:
    [x] Path
 Request Rewrite: (@LiorLieberman )
   [x] host
   [x] Path
   
...

**Comment by robscott** [comment]
Thanks @LiorLieberman! Updated the issue to match. We are still looking for tests covering request mirroring.

**Comment by shaneutt** [comment]
At this point we only have one item left, talked with @robscott he's gonna close this and spin off the last one.

/assign @robscott

**Comment by LiorLieberman** [comment]
What is the one item left? @shaneutt

**Comment by robscott** [comment]
@LiorLieberman added https://github.com/kubernetes-sigs/gateway-api/issues/2037 to track the last part of this (combining HTTPRoute filters together in tests).

Going to close this one out in favor of that more specific one.
