### ISSUE TITLE
Conformance Tests: L7 Gateways

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1104]
This issue is intended to track conformance test development for L7 Gateways. Comment below if you're interested in working on covering any of these areas.

**Core Capabilities:**
- [x] Gateway - Route Binding
  - [x] Successful cross namespace configuration
  - [x] Invalid cross namespace configuration
  - [x] Invalid binding from Route kind not specified in AllowedRoutes.Kinds (@skriss) 
- [x] Hostname matching (@skriss) 
  - [x] Multiple listeners specifying different hostnames and same port, forwarding to different Routes
  - [x] Single listener specifying hostname that intersects with one of several hostnames specified on a Route 
  - [x] Single listener specifying hostname that intersects with none of several hostnames specified on a Route 
- [x] TLS Certificates (Prior art in https://github.com/kubernetes-sigs/ingress-controller-conformance that can be a starting point) - tracked in #1330

**Extended Capabilities:**
- [ ] #2035
  - [ ] Specify 1 address
  - [ ] Specify multiple addresses

**Comment by skriss** [comment]
I'm interested in picking up some of these - can start with the remaining route binding one and the hostname matching ones. @robscott were you thinking that the Gateway manifests for these would go into the individual tests, rather than the "base" manifests, since these aren't likely to be reused across many tests?

**Comment by robscott** [comment]
@skriss that's a great question. I think it will be most straightforward to start with Gateways being defined by the tests directly. We'll need to discuss more broadly though, maybe at the next community meeting. I think some implementations don't support automatically provisioning Gateways yet, so depending on how widespread that is, we may need to move Gateway definitions into base manifests. I'm thinking it should be easy to change where Gateways are defined after the tests are written though.

**Comment by shaneutt** [comment]
At this point the remaining items are broken off as separate issues, so we're good to close this.
