### ISSUE TITLE
Gateway.Spec.Addresses Support Level Likely Inaccurate

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1106]
`Gateway.Spec.Addresses` is [currently listed as having "Core" support](https://github.com/kubernetes-sigs/gateway-api/blob/master/apis/v1alpha2/gateway_types.go#L138). This does not seem like something that some implementations will be able to support. It would be helpful to get some comments here from other implementers to confirm my theory that this is not universally supportable.

**Comment by mehabhalodiya** [comment]
> It would be helpful to get some comments here from other implementers to confirm my theory that this is not universally supportable.

Can you please specify "other implementors" from the [file](https://github.com/kubernetes-sigs/gateway-api/blob/master/apis/v1alpha2/gateway_types.go)?

Maybe I can work on this!

**Comment by youngnick** [comment]
I agree that this should be `Extended` support. Contour only supports setting addresses when the underlying cloud provider does, so it's definitely not all the time.
