### ISSUE TITLE
"good" state for ListenerStatus feels logically inverted, difficult to understand

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/gateway-api#1110]
**What would you like to be added**:

- Add [`ListenerConditionType`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io%2fv1alpha2.ListenerConditionType) `Attached` (or possibly `Accepted` for parity with other objects, ref #1111 ), deprecate `Detached`

**Why this is needed**:

From a quick glance, seeing a `ListenerStatus` with `Detached` and `Conflicted` conditions on a Gateway can be a red herring leading an operator to initially think a `Listener` is not working properly - this may be particularly confusing for new users unfamiliar with checking for the "negative" case of `Detached: {status: false, reason: Attached}`, `Conflicted: {status: false, reason: NoConflicts}` meaning that the Listener is actually in a "good" state.

This potential confusion about whether a Listener is working as expected is slightly exacerbated by the `ListenerStatus` field being a child of [`GatewayStatus`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.GatewayStatus) rather than being a `status` field directly on [`Listener`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.Listener).

I initially considered if `Conflicted` should be changed too, but I think just this change alone could make the status conditions for a Listener feel a bit more intuitve.

**Comment by youngnick** [comment]
Agreed, we should have the same `Attached` condition type across every place we use conditions, and have it mean the same thing.

**Comment by mikemorris** [comment]
[GEP-1364](https://gateway-api.sigs.k8s.io/geps/gep-1364/) has been approved, deprecating `ListenerConditionDetached` and proposing that `ListenerConditionAccepted` be used instead.

This GEP also addresses the confusion with the `Conflicted` status by setting an expectation that positive polarity error status conditions should only be present when the error state exists.
