### ISSUE TITLE
discrepancies between Accepted, Ready, and Detached condition types and reasons

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/gateway-api#1111]
Several different [`Kubernetes meta/v1.Condition`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#condition-v1-meta) types are defined by the spec, and some use differing terminology to communicate apparently similar status.

**What would you like to be added**:

- [ ] Add `Pending` GatewayClassConditionReason, deprecate `Waiting` (for parity with ListenerConditionType)
  - Tracking in https://github.com/kubernetes-sigs/gateway-api/issues/1449
- [x] Possibly add an `Accepted` GatewayConditionType, with `Accepted`, `Invalid` and `Pending` GatewayConditionReason to disambiguate the status of the object being accepted by the Gateway Controller versus being ready to route traffic.
  - [GEP-1364](https://gateway-api.sigs.k8s.io/geps/gep-1364/) proposed replacing the current `GatewayConditionScheduled` with a new `GatewayConditionAccepted`
  - https://github.com/kubernetes-sigs/gateway-api/pull/1447
- [x] Add `Attached` or `Accepted` ListenerConditionType, deprecate `Detached`
  - `Attached` could still be a reasonable choice to clarify that this object isn't submitted to the controller individually, but rather evaluated as part of a Gateway object.
  - If choosing `Accepted`, add `Accepted` ListenerConditionReason, deprecate `Attached`
  - See https://github.com/kubernetes-sigs/gateway-api/issues/1110 for more detail
  -  [GEP-1364](https://gateway-api.sigs.k8s.io/geps/gep-1364/) proposed switching this to `Accepted`
  - https://github.com/kubernetes-sigs/gateway-api/pull/1446
- [ ] ~~Add `InvalidParameters` ListenerConditionReason, prefer over more generic `Invalid` when applicable?~~
- [x] Add `Accepted` RouteConditionReason, deprecate `Admitted` (for parity with GatewayClassConditionType)
  - `Admitted` was only in the v1alpha1 spec, and had already been removed in https://github.com/kubernetes-sigs/gateway-api/pull/839
  -  Documented `Accepted` properly in https://github.com/kubernetes-sigs/gateway-api/pull/1114
- [ ] ~~Possibly add `Ready` RouteConditionType, although this is known to be difficult to implement accurately.~~
  - Tracked in https://github.com/kubernetes-sigs/gateway-api/issues/1156
- [ ] Add `Pending` and `Invalid` or `InvalidParameters` RouteConditionReason, ~~prefer over generic `Refused` when applicable?~~
  - Tracking in https://github.com/kubernetes-sigs/gateway-api/issues/1449

**Why this is needed**:

### "Accepted"
The possible `false` reasons indicate either that the controller is evaluating the GatewayClass still, or that it has been rejected and _likely requires manual intervention to resolve_. A `Ready` condition doesn't feel appropriate here as this isn't a concrete instance.
- `true` reasons
  - "Accepted"
- `false` reasons
  - "InvalidParameters"
  - "Waiting"

### "Ready"
This is pretty clearly intended to communicate different issues than the `Accepted` conditions, judging from the possible `false` values, the latter two of which seem to communicate issues that _could be expected to be transient and eventually resolve on their own_, or to look to a child object for additional detail.
- `true` reasons
  - "Ready"
- `false` reasons
  - “ListenersNotValid”
  - “ListenersNotReady”
  - “AddressNotAssigned”

### "Detached"
The logical inversion issues with this condition are separately described in https://github.com/kubernetes-sigs/gateway-api/issues/1110, but at a high level the possible `true` reasons seem to communicate issues that _could be expected to require manual intervention to resolve_.
- `true` reasons
  - “PortUnavailable”
  - “UnsupportedExtension”
  - “UnsupportedProtocol”
  - “UnsupportedAddress”
- `false` reasons
  - "Attached"

### "Ready"
The possible `false` reasons for this field look quite similar to the `false` reasons for the `Accepted` `GatewayClassConditionType`, but use slightly different terminology. I'm not quite sure how useful this field is beyond being a cue to look to other conditions if the status is `false`.
- `true` reasons
  - "Ready"
- `false` reasons
  - “Invalid”
  - “Pending"

### "Accepted"
The possible `false` reasons for this field are [not currently defined in the v1alpha2 API spec docs](https://github.com/kubernetes-sigs/gateway-api/issues/1109) but were previously [defined in v1alpha1](https://gateway-api.sigs.k8s.io/v1alpha1/references/spec/#networking.x-k8s.io%2fv1alpha1.RouteConditionReason), although don't appear to offer any additional context beyond the status boolean.
- `true` reasons (only documented in v1alpha1)
  - "Admitted"
- `false` reasons (only documented in v1alpha1)
  - "Refused"

(If there's interest in enough of this changing, it could be substantial enough to warrant a GEP.)

**Comment by robscott** [comment]
We need to make sure this is compatible with Route inclusion status proposal

**Comment by mehabhalodiya** [comment]
I would like to work on this, if it's alright 🙂

**Comment by shaneutt** [comment]
@mehabhalodiya from what I've heard in Slack it sounds like you may not be taking this one on because you've got some other things you're working on? If that's the case I was gonna pick this one up, let me know what's up?

**Comment by mehabhalodiya** [comment]
@shaneutt I think that you already have some more context on what needs to be done; so that you can get it done a little quicker as compared to me!

Also @robscott and @youngnick would really like to get it sorted asap.
You can assign this to yourself.
Thank you.

**Comment by shaneutt** [comment]
Turns out the ask here is somewhat large and after reviewing I do think a GEP might be warranted as suggested so that we can ensure consensus about the changes ahead of implementation. I'm not going to be able to work on this one after all as I have significant time constraints and several things competing for my time, so I will be un-assigning myself.

**Comment by carlisia** [comment]
Cross-posting here that I [extracted the case for a "Ready" Route condition into a new issue](https://github.com/kubernetes-sigs/gateway-api/issues/1077#issuecomment-1122043612).

**Comment by nathancoleman** [comment]
Thanks @carlisia ! I think that makes this issue much more manageable

**Comment by youngnick** [comment]
Moving this out of the v0.5.0 milestone so it doesn't block the release. We can add the reasons in a patch release afterward.

**Comment by youngnick** [comment]
I'm attempting to close this one as part of GEP-1364, so I'll take it.

/assign

**Comment by mikemorris** [comment]
[GEP-1364](https://gateway-api.sigs.k8s.io/geps/gep-1364/) helped significantly clarify the expected behavior here, tracking followup work individually in:
- https://github.com/kubernetes-sigs/gateway-api/pull/1446
- https://github.com/kubernetes-sigs/gateway-api/pull/1447
- https://github.com/kubernetes-sigs/gateway-api/issues/1449
- https://github.com/kubernetes-sigs/gateway-api/issues/1156
