### ISSUE TITLE
HTTP Path Matah ： Is it more appropriate to write PathPrefix as Prefix?

### ISSUE THREAD

**Issue by sdjksdajshd** [kubernetes-sigs/gateway-api#1132]
**What happened**:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/42963243/165910671-9e0c70e1-207b-46fb-971f-dae8a58f912e.png">

**What you expected to happen**:

write PathPrefix as Prefix?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by howardjohn** [comment]
PathPrefix is distinguish from 'Prefix' because its not a literal string prefix match. eg `PathPrefix: /foo/bar` does not match `/foo/barextra`, only `/foo/bar/extra`.

**Comment by sdjksdajshd** [comment]
I get it，thanks very much

**Comment by sdjksdajshd** [comment]
My remember question
