### ISSUE TITLE
Add documentation for validating webhook

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1133]
As [suggested](https://github.com/kubernetes-sigs/gateway-api/pull/1066#discussion_r861710156) by @markmc,  it would be helpful to have a docs page that provides information on the webhook. Some questions we should probably answer on that page:

- How do you install it?
- Why is it necessary?
- What does it validate?
- How is it updated?

**Comment by mikemorris** [comment]
This appears to have been fixed in https://github.com/kubernetes-sigs/gateway-api/pull/1066

/close
