### ISSUE TITLE
conformance: refactor listenersMatch and parentsMatch helpers into a single generic function

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/gateway-api#1142]
**What would you like to be added**:

Refactor `listenersMatch` (added in #1081) and `parentsMatch` to be a single generic function, or at least wrappers around a single generic implementation of the core logic.

**Why this is needed**:

The core logic of these two functions is quite similar (searching for all expected items in a slice of actual items, including the unimplemented need to support an arbitrary ordering), and it would be better to have this logic implemented once than risk two similar implementations diverging.

**Comment by FlorentFlament** [comment]
Hi,

It looks like this refactoring could be achieved with the same level of log details by using Reflection. Would that be the way to go ? I'd like to give it a try.

Regards

**Comment by FlorentFlament** [comment]
Hi,

So I've been thinking about the implementation, and found out that the `parentsMatch` and `listenerMatch` functions have a lot of specifics (i.e `v1alpha2.RouteParentStatus` and `v1alpha2.ListenerStatus` are not checked the same way).

I can propose the following approach:

Extracting the test logic of a single elemnent for both type with functions of the following prototype:

```
func oneListenerMatch(eListener, aListener v1alpha2.ListenerStatus) bool
func oneParentMatchClosure(namespaceRequired bool) func(eParent, aParent v1alpha2.RouteParentStatus) bool
```
Note that `oneParentMatchClosure` is a Closure, to allow us building a matcher function with the same prototype as `oneListenerMatch`.

Then we can implement a generic function that iterates on every element of 2 lists passed as arguments with the following prototype:

```
func listMatch(t *testing.T, expected, actual []interface{}, matcher matcherFunction) bool
```

This is the function that can be updated to match elements regardless of their order.  This generic `listMatch` function needs a `matcherFunction` as argument, that will be applied on every element of the lists.

```
type matcherFunction func(interface{}, interface{}) bool
```

Finally, the `parentsMatch` and `listenersMatch` functions would be rewritten like this:

```
func parentsMatch(t *testing.T, expected, actual []v1alpha2.RouteParentStatus, namespaceRequired bool) bool {
	oneParentMatch = oneParentMatchClosure(namespaceRequired)
	return listMatch(t, expected, actual, oneParentMatch)
}

func listenersMatch(t *testing.T, expected, actual []v1alpha2.ListenerStatus) bool {
	return listMatch(t, expected, actual, oneListenerMatch)
}
```

These are my initial thoughts. I'll try to write an actual implementation of it pretty soon.  Any comments are welcome.

Regards
