### ISSUE TITLE
Improvement to the website description of what a Gateway API is and is not

### ISSUE THREAD

**Issue by carlisia** [kubernetes-sigs/gateway-api#1157]
What is the difference between a Gateway API and an API Gateway? 

This is one question that is begging to be answered but is not cleared up by the website content.

I'll add some clarification around that as well as spruce up the existing content.

/assign

**Comment by carlisia** [comment]
Some notes relevant for this:

[Gateway API description | Worklogs](https://carlisia.github.io/carlisia/scrapbook/2022/gw-api-desc)

**Comment by youngnick** [comment]
I definitely think that our existing docs could use some updates, along the lines of what I said in those notes.

**Comment by youngnick** [comment]
/remove-lifecycle stale

@carlisia, are you still able to take this one on? If not, maybe we can write it up for someone else?

**Comment by gyohuangxin** [comment]
@youngnick I'd like to take this if @carlisia are not working on this.

**Comment by youngnick** [comment]
/remove-lifecycle rotten

This one does still need to be done, contributors are welcome here.

/help-wanted

**Comment by shaneutt** [comment]
We would like to see this one make it for GA if possible, help from a contributor would be very much appreciated!

/help

**Comment by david-martin** [comment]
@gyohuangxin @carlisia 
Checking if either of you have progressed anything on Gateway API vs API Gateway description?

I'd really love to have some clarifying words around this, perhaps even how Gateway API differs to API Management (though I don't see that as essential, more of a nice to have).

In terms of where to add this clarification, I'm thinking the Introduction section on the landing page of https://gateway-api.sigs.k8s.io/, near the top in "What is the Gateway API?" would make sense?

Either that, or a separate section on that page to explicitly ask the question "How does Gateway API differ from an API Gateway?"

**Comment by david-martin** [comment]
The original notes linked above give a 404 :( https://carlisia.github.io/carlisia/scrapbook/2022/gw-api-desc

**Comment by gyohuangxin** [comment]
@david-martin I have no progress around this description. So please go ahead to add your words, and I'd love to give my comments  :)

**Comment by david-martin** [comment]
@gyohuangxin when you have time, words in #2191
