### ISSUE TITLE
Wildcard hostname matching behavior is not clearly specified

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1159]
**What would you like to be added**:
As @howardjohn [noted in Slack](https://kubernetes.slack.com/archives/CR0H13KGA/p1652128690078659), our hostname matching behavior is not clearly specified. Other than saying "exact matches must be processed before wildcard matches", we don't really cover how wildcard matches should be implemented. Specifically, which of the following should `*.example.com` match?

1. `a.example.com` 
2. `a.b.example.com` 

We [recently added a conformance test](https://github.com/kubernetes-sigs/gateway-api/pull/1137) that stated that only 1 should match. On further thought, I'm not sure that's what we want. 

Here's my understanding of the default behavior for a variety of different products:

1. nginx defaults to match 1 and 2 [ref](https://nginx.org/en/docs/http/server_names.html#wildcard_names)
2. envoy defaults to match 1 and 2 [ref](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-virtualhost)
3. haproxy can definitely support suffix matching (hdr_end), I'm not sure about the other [ref](https://cbonte.github.io/haproxy-dconv/2.6/configuration.html#7.3.6-req.hdr)
4. GCP can only support suffix matching (not well documented yet)

Given the above, it seems that most underlying implementations treat wildcard host matching as suffix matching as the default, and some may only be able to support that approach. My suggestion would be to adjust the spec and conformance tests to reflect that.

**Why this is needed**:
This is an important gap in our spec today.

**Comment by howardjohn** [comment]
One note in favor of the "1 label" behavior is that TLS verification behaves this way. So if we don't do that, we have inconsistency in certs and routing (which is ok, just inconsistent). I don' have a strong opinion one way or another though; as long as an implementation has regex header matching I think either approach can be implemented in most proxies?

**Comment by skriss** [comment]
xref https://github.com/kubernetes-sigs/gateway-api/issues/654 and https://github.com/kubernetes-sigs/gateway-api/pull/674 which also had discussion on this topic.

**Comment by robscott** [comment]
In general, I think it's safe to describe the two options as "single label matching" and "multi label matching". Each have advantages:

**Single Label Matching:**

* Consistent with Ingress spec
* Consistent with TLS verification

**Multi Label Matching:**

* Consistent with envoy, nginx, and GCP defaults
* More broadly supportable

I'm biased here because GKE can only support the multi label matching approach here, so I would personally prefer that spec. It also seems like it would be more straightforward and performant for other implementations to support suffix matching than implementing regex matches. Want to see what others think though.

**Comment by jpeach** [comment]
Multi label matching won't work with TLS and practically everything is deployed with TLS. Specifying multi label matching just seems likely to encourage broken configurations that are hard to debug.

**Comment by youngnick** [comment]
I *thought* I had specified a single label match previously, so I'd kind of prefer that we keep that.

**Comment by youngnick** [comment]
To summarize what I said at the community meeting:
- Keeping things consistent with Ingress would be preferable
- But this is a core capability, and if some implementations can't implement it, we have a problem.
- I'd rather loosen this and try to find a way for implementations to optionally tighten it than exclude already-working implementations from conformance because of this detail.
