### ISSUE TITLE
Dual Stack support

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/gateway-api#118]
**What would you like to be added**:

Dual Stack support for Gateway

**Why is this needed**:

Right now every change to the current Services, Endpoints, ... APIs is risky, complicated, unpredictable, ... and based on @thockin [feedback](https://github.com/kubernetes/kubernetes/pull/86895#issuecomment-592093115) `Gateway` is one of the best options

**Comment by aojea** [comment]
long history 

https://github.com/kubernetes/kubernetes/pull/86895

short history

> On the topic of "new APIs will save our bacon", EndpointSlice. It already
> handles multi-family cleanly. What if we can enable multi-family for EPSlice
> but leave Endpoints (classic) single-family? Specifically:
> 
> Document 1a - to do a single-to-dual-stack upgrade, the preferred family
> MUST be the same as the historical single-family
> Enforce same-family for various flags
> For any service with ipFamily set, respect that
> Allow ipfamily to be mutable any time ClusterIP is mutable
> For Services without ipFamily set:
> set an annotation of "legacy IP family" or "prefered ip family"
> do NOT set ipFamily
> if needed, allocate a clusterIP of the "legacy" family
> if headless do nothing
> Endpoints (classic) controller will only select endpoints of the "legacy"
> family
> EndpointSlice (modern) controller will select endpoints of both families
> Consumers of endpoints (e.g. kube-proxy) can enable dual-stack by switching
> to EndpointSlice. This includes DNS generating A and AAAA records for
> headless services, ingress controllers, and kube-proxy routing NodePorts, LB
> ingresses, and even external IPs to both-stacks.
> This preserves Endpoints compat, but offers a way forward. This does not offer
> multi-family clusterIPs (see above arguments). That might come as part of Gateway or (if there is enough pressure) we could consider it for Service LATER.

tagging people on the thread
/cc @thockin @khenidak @danwinship @johnbelamaric @smarterclayton

**Comment by aojea** [comment]
/remove-lifecycle stale
we'll get there :)

**Comment by hbagdi** [comment]
/remove-lifecycle rotten
/lifecycle frozen

@aojea Since dual stack is now in mainline, are there any changes that we should be documenting here or having pointers for?

**Comment by aojea** [comment]
> @aojea Since dual stack is now in mainline, are there any changes that we should be documenting here or having pointers for?

I have to admit that I've lost track of this project, but think that the main impact here is the Services have dual-stack IPs, so the field Service.Spec.ClusterIP was pluralised to Service.Spec.ClusterIPs, that is an array.

Happy to talk more about this if necessary

**Comment by hbagdi** [comment]
@robscott We do take into account IPv6 whenever we talk about any address. Is there anything more we need?

**Comment by shaneutt** [comment]
There's nothing in the API that prevents dual stack from working today: anywhere an address can be specified you can use v4 or v6 (and addresses are always lists), so we're going to close this as resolved for the time being. Please comment here and we can re-open this (or open a new issue) if any problems are found in the future.

As an aside: @robscott had suggested in the future we may want to add the ability to specify the kind(s) of IP addresses for better constraints (being able to express that (for example) `Gateway` A is IPv4 only, `Gateway` B is IPv6 only, e.t.c.), if this is something you want please feel free to open a new issue requesting it.
