### ISSUE TITLE
conformance: allow reading BaseManifests from non-embedded local filesystem

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/gateway-api#1180]
**What would you like to be added**:

Update [`getContentsFromPathOrURL`](https://github.com/kubernetes-sigs/gateway-api/blob/d1b86648e2771763d5f782bfd762c33936034fd2/conformance/utils/kubernetes/apply.go#L201-L237) to support reading files from the local filesystem rather than only the [embedded filesystem](https://github.com/kubernetes-sigs/gateway-api/blob/master/conformance/embed.go).

**Why this is needed**:
We're currently working on switching our implementation of Gateway API conformance tests from a local git checkout to re-implementing [conformance_test.go](https://github.com/kubernetes-sigs/gateway-api/blob/master/conformance/conformance_test.go) directly (in order to specify `SupportedFeatures`, which IIUC is a recommended pattern), but we're currently blocked due to our need to make some slight tweaks to the base manifests (lowering the number of replicas to work around resource constraints in CI and adding an annotation to all Deployments), which we have previously been doing with a `kustomize` patch.

Specifying a string path for [`BaseManifests`](https://github.com/kubernetes-sigs/gateway-api/blob/d1b86648e2771763d5f782bfd762c33936034fd2/conformance/utils/suite/suite.go#L71) _is_ currently supported as an option when initializing a `ConformanceTestSuite` struct, but unless the string is a remote path beginning with `https://`, it is hardcoded to [only read from the read-only embedded filesystem](https://github.com/kubernetes-sigs/gateway-api/blob/d1b86648e2771763d5f782bfd762c33936034fd2/conformance/utils/kubernetes/apply.go#L232).

I've managed to read the base manifests from the embedded filesystem, patch them with [`krusty`](https://pkg.go.dev/sigs.k8s.io/kustomize/api/krusty) and write them to a local temp file with [`kyaml/filesys`](https://pkg.go.dev/sigs.k8s.io/kustomize/kyaml/filesys), but would need to add support for reading from the local filesystem to be able to use the patched manifests in this way - is this something we could consider supporting, or is there a different way I should be approaching this problem?

**Comment by youngnick** [comment]
I can't see a reason not to support the local filesystem, subject to the usual input-validation checks to prevent directory traversal.

**Comment by youngnick** [comment]
I can't find any good examples in a quick scan, but even just doing the obvious stuff is an improvement (no more than one consecutive dot allowed in paths and setting a maximum path length to prevent overflows).

Total path length varies depending on OS, but 4096 chars is reasonably common, and probably a good default. Filename length is 255 chars on most Unix-y OSes, so that will do there too.
