### ISSUE TITLE
Blog post for v0.5.0

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#1184]
**What would you like to be added**:

A blog post should be added for our `v0.5.0` release.

**Why this is needed**:

To help spread the word of the APIs progression towards GA.

**Comment by youngnick** [comment]
As mentioned by @candita in the meeting notes, this probably should be cross-posted both to the main Kubernetes blog and to the Gateway API site blog section.

**Comment by shaneutt** [comment]
Now resolved as of https://github.com/kubernetes/website/pull/34968 and https://github.com/kubernetes-sigs/gateway-api/pull/1263
