### ISSUE TITLE
Rename "master" default branch to "main"

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#1195]
**What would you like to be added**:

It seems like we're eventually going to want to rename `master` to `main`. This is a proposal that we do that before `v0.5.0` when we start releasing BETA APIs, because the longer we wait the more trouble the change will be.

**Checklist From [Upstream Rename Documentation](https://www.kubernetes.dev/resources/rename/)**:

- [x] create an issue in your repo to track the branch rename. You can paste this checklist in the issue body.
- [x] If you are not a root approver for the repo, assign a root approver for approval.
- [x] Once the issue has been approved, send a notice to your SIG’s mailing list about the potential branch rename.
- [x] If the repo has netlify configured for it, ask a member of the GitHub Management Team to rename the master branch to main in the netlify site config. It can’t be controlled through the netlify config in the repo.
- [ ] https://github.com/kubernetes/test-infra/pull/26536
- [ ] https://github.com/kubernetes-sigs/gateway-api/pull/1196

**Comment by robscott** [comment]
I'm all for this if anyone has time to take it on - instructions are here: https://www.kubernetes.dev/resources/rename/.

**Comment by shaneutt** [comment]
I'll take care of it.

/assign

**Comment by robscott** [comment]
To more formally state this for the record: I approve this change.

**Comment by bowei** [comment]
Let me know if there is any github super user operation needed as I can make the change directly.

**Comment by shaneutt** [comment]
As per the documentation I have created a PR to account for the name change in this repo:

- https://github.com/kubernetes-sigs/gateway-api/pull/1196

As well as accounting for the name change in `test-infra`:

- https://github.com/kubernetes/test-infra/pull/26536

I would appreciate some extra :eyes: and critical reviews on these to help me find anything I may have missed.

**Comment by shaneutt** [comment]
As per the docs, I updated the mailing list that we intend to do this: https://groups.google.com/g/kubernetes-sig-network/c/WajfaZQqyGo/m/SNXzPAMhAwAJ

**Comment by shaneutt** [comment]
> Let me know if there is any github super user operation needed as I can make the change directly.

Thank you. Are you capable of updating the netlify config, RE: ` If the repo has netlify configured for it, ask a member of the GitHub Management Team to rename the master branch to main in the netlify site config. It can’t be controlled through the netlify config in the repo.`

**Comment by robscott** [comment]
I think @mrbobbytables set up Netlify for us originally, he might be able to help on that side.

**Comment by youngnick** [comment]
I approve this change also, thanks for pushing this forward @shaneutt, it's been on my want-to-do list for ages.

**Comment by shaneutt** [comment]
We're getting some help (right now) from contribex to get the branch renaming and netlify configuration completed, then we should be unblocked.
