### ISSUE TITLE
Move error status code to 500

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/gateway-api#1200]
**What would you like to be added**:

In various places, we've documented that having no endpoints available should variously be 404 or 503. @thockin suggested in the v0.5.0 API Review that we should consider 502 instead.

This issue covers agreeing that's the case, and then implementing that change.

**Why this is needed**:
Need to get breaking behavior changes done before we release v0.5.0.

**Comment by mehabhalodiya** [comment]
@youngnick This needs to be done only in `v1beta1` or in `v1alpha2` also?
I caught 404 in `v1beta1/httproute_types.go`. Not sure, which other files to look at!

**Comment by mehabhalodiya** [comment]
I would like to take up this one.
/assign

**Comment by youngnick** [comment]
In both please, we will keep the v1alpha2 and v1beta1 in sync for this release.

**Comment by youngnick** [comment]
We agreed that:
- If there are no matching routes, a 404 should be generated
- f there are matching routes but no/missing backends/endpoints to route to, a 500 (specifically) should be generated.

@mikemorris is going to write out a list of the different cases, and check we haven't missed anything.
