### ISSUE TITLE
Return ReferencePolicy CRD, deprecated, for v0.5.0

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/gateway-api#1201]
To make migration easier, we should deprecate the v1alpha2 ReferencePolicy resource in v0.5.0, rather than removing it.

This means we'll need to add the types and CRD back, and figure out how to get the deprecation field and warning set on the generated CRD object.  (This will need to use https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#version-deprecation).

ReferencePolicy will then be removed in v0.6.0.

**Comment by shaneutt** [comment]
I'll take care of it.

/assign
