### ISSUE TITLE
ParentReference.Namespace has unnecessary pointer to string.

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes-sigs/gateway-api#1220]
https://github.com/kubernetes-sigs/gateway-api/blob/master/apis/v1beta1/shared_types.go#L48

> "Namespace is the namespace of the referent. When unspecified (or empty string), this refers to the local namespace of the Route."

Given that the zero value in Go for a string type is empty string, there's no need for ParentReference.Namespace to be of type `*string`, rather, `string` would have the same interface with a simpler implementation.

**Comment by shaneutt** [comment]
This is commonly done for reasons of encoding to JSON/YAML. Note the `// +optional` comment above and the `json:"namespace,omitempty"` declaration to the right: making this a pointer causes YAML encoding to omit the field entirely from the final encoding, so the value of this is to avoid having fields with empty strings in YAML, e.g.:

```yaml
kind: Gateway
Namespace: ""
Name: example
```

becomes

```yaml
kind: Gateway
Name: example
```

Besides any aesthetic preferences, this means that our webhook validation can avoid having to accept `""` as a valid namespace name. This has become a common pattern across many Kubernetes repositories so I believe you'll find this prevalent. Let us know if that explanation is helpful and if it's OK to close this issue, or if you have more questions on this topic.

**Comment by briantkennedy** [comment]
@robscott does this mean conformance tests should expect an error if a user provides `namespace: ""` for this field?

**Comment by robscott** [comment]
The [namespace validation included in the CRDs](https://github.com/kubernetes-sigs/gateway-api/blob/master/apis/v1beta1/shared_types.go#L413) should prevent empty string from being a valid input. I think the options are effectively nil or a 1+ character string. We should probably update the docstring to more clearly state that. With all of that said, CRD validation can be bypassed, so handling the empty string case as identical to nil is likely a good idea.

**Comment by briantkennedy** [comment]
So if we want to handle `nil` and `""` as equivalent, why not have a `string` value with `"omitempty"` instead of the `*string` and reduce the number of cases that alias the same thing?

**Comment by briantkennedy** [comment]
Actually, taking a step back from my previous comment, I think our conversation is going something like this:

@briantkennedy : Our docs say nil / "" do the same thing, let's turn two cases into one.
@shaneutt : No, "" shouldn't be allowed as a namespace value, let's not do that.
@robscott : We have to handle "", it should do the same thing for both values.

To me, it sounds like @shaneutt and @robscott / the API docstring are in disagreement.  Do we even have a consensus on whether `namespace: ""` should be allowed for this field?

**Comment by robscott** [comment]
>So if we want to handle nil and "" as equivalent, why not have a string with "omitempty" behavior instead of the *string and reduce the number of cases that alias the same thing?

I'd agree that would work and potentially be cleaner for implementations, but it unfortunately makes our [CRD validation](https://github.com/kubernetes-sigs/gateway-api/blob/9e271efb321fb67708f880d3a83a00c7d4229c8f/apis/v1beta1/shared_types.go#L410-L413) logic/type definitions messier. Essentially right now we've got a shared set of types, like Namespace that have validation centrally defined. If we were to allow an empty string as a valid namespace, we'd need separate types for "OptionalNamespace" and "RequiredNamespace" where the required namespace had a min length of 1. We'd also need to repeat that pattern for all the other types defined in shared_types.go, and I think it would generally just add more confusion. Alternatively we could require the minlength attribute be added in every place the type was used and required, but that seems like it would be _very easy_ to miss in the future and lead to impossible to fix bugs in the API.

**Comment by briantkennedy** [comment]
So, to back up a bit, what's the behavior we want for this field when given empty string?  It sounds like you're both saying the API should treat empty string as an error since the user isn't supposed to express intent for a namespace with name empty string, is that correct?

**Comment by shaneutt** [comment]
> So, to back up a bit, what's the behavior we want for this field when given empty string? It sounds like you're both saying the API should treat empty string as an error since the user isn't supposed to express intent for a namespace with name empty string, is that correct?

Right, this resonates with me.

**Comment by youngnick** [comment]
Yes, I think that it's correct to say that the value shouldn't be an empty string, that is an error. That error won't usually be encountered unless someone bypasses CRD validation, but it needs to be handled without crashing.

Given all that, we get back to the original question: Should this be a pointer? In this case, it doesn't *need* to be, because the difference between the empty string and a nil pointer is not meaningful. However, changing it now is a big breaking change, so we either need to change it before the final v0.5.0 release, or accept that this is how it is forever.

I'm inclined towards the latter, just in case it turns out we need to be able to distinguish between "unset" and "set to empty string".

**Comment by shaneutt** [comment]
Yep that tracks.
