### ISSUE TITLE
Documentation needs to be updated as part of v0.5.0 release

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1229]
I think at a minimum this requires the following changes, these can be combined or split up as needed, comment on whichever ones you can take on:

- [x] _completed by @EmilyShepherd:_ Add v1beta1 examples
  * Copy https://github.com/kubernetes-sigs/gateway-api/tree/master/examples/v1alpha2 into a new v1beta1 directory, ensure all new files use v1beta1 API group
  * Copy https://github.com/kubernetes-sigs/gateway-api/tree/master/hack/invalid-examples/v1alpha2 into a new v1beta1 directory, ensure new files use v1beta1 API group
  * Update any docs (`site-src` dir) that include v1alpha2 examples (example `{% include 'v1alpha2/http-filter.yaml' %}`) to use v1beta1
- [x] _completed by @EmilyShepherd:_ Any GatewayClass, Gateway, or HTTPRoute yaml snippets in `site-src` markdown files should use `v1beta1` instead of `v1alpha2`
- [x] _completed by @EmilyShepherd:_ The `v1alpha2/` prefix in documentation links (and structure) should be removed - bonus points for finding a way to redirect from new to old path
- [x] _completed by @keithmattix:_ Any concepts that are only included in experimental channel need to be clearly documented as that (ReferenceGrant, TCPRoute, TLSRoute, and UDPRoute are all included in this) - [example](https://github.com/kubernetes-sigs/gateway-api/blame/master/site-src/v1alpha2/guides/http-redirect-rewrite.md#L36-L40)
- [ ] As part of release process: Update documentation to explain how to install standard and experimental CRDs.

I may have missed some items here, feel free to add any additional suggestions below.

**Comment by keithmattix** [comment]
I'm willing to help out as well!

**Comment by robscott** [comment]
Awesome, thanks @EmilyShepherd and @keithmattix! Just comment whichever item(s) you want to start with.

**Comment by keithmattix** [comment]
I'll start off with a PR for calling out items in the experimental channel

**Comment by keithmattix** [comment]
FYI @robscott the instructions on the [getting started](https://github.com/kubernetes-sigs/gateway-api/blob/master/site-src/v1alpha2/guides/getting-started.md#install-the-crds) for installing the CRDs also needs to be updated to reflect the new channel structure. I couldn't find another issue tracking that, so I'm commenting here

**Comment by robscott** [comment]
Thanks @keithmattix! Added a bullet to track that. That's one update we try to keep as close to cutting the release as possible.

**Comment by EmilyShepherd** [comment]
I'll start working on switching over examples and references to `v1beta1` (items 1 and 2) :slightly_smiling_face:

**Comment by robscott** [comment]
Closing this out as everything has either been merged or is ready to merge.

**Comment by EmilyShepherd** [comment]
Do you still need a note on the docs RE how to install the experimental channel CRDs?

**Comment by shaneutt** [comment]
If we don't have a note somewhere on this, then I would vote yes we should add this.

**Comment by EmilyShepherd** [comment]
Happy to write something this evening :smile: 

You already have some general documentation about the [release channels](https://gateway-api.sigs.k8s.io/concepts/versioning/#release-channels-eg-experimental-standard) so I'm hoping that this change doesn't actually need to be too complex - I was thinking referencing that and explaining which crd file is needed for each channel would be appropriate.

**Comment by robscott** [comment]
No worries @EmilyShepherd, thanks for all the help with the rest of this!
