### ISSUE TITLE
v0.5.0-rc2 webhook image tag is `latest`

### ISSUE THREAD

**Issue by skriss** [kubernetes-sigs/gateway-api#1261]
**What happened**:
Installed the v0.5.0-rc2 webhook, noticed the image tag is set to `latest`.

**What you expected to happen**:
I expected a versioned image tag, like v0.4.3 had (https://github.com/kubernetes-sigs/gateway-api/blob/v0.4.3/deploy/admission_webhook.yaml#L71)

**How to reproduce it (as minimally and precisely as possible)**:
Install https://github.com/kubernetes-sigs/gateway-api/blob/v0.5.0-rc2/config/webhook/admission_webhook.yaml#L64

**Comment by robscott** [comment]
Thanks for catching this @skriss! We'll make sure this is fixed as part of the v0.5.0 release.
