### ISSUE TITLE
Automated Releases

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#1267]
**What would you like to be added**:

Automated release creation.

**Why this is needed**:

It's nice to have and it might encourage us to release more often.

**Details**:

Ideally we would create a (github?) workflow which automates creating a Github release for us with the following criteria:

1. if using Github actions, has `workflow_dispatch:` property to allow manual triggering with parameters
2. runs any tests needed for the release
3. automatically fills in the CHANGELOG for the release
2. automatically builds and uploads all release artifacts (the release yaml namely)
4. automatically takes SHA256SUM checks of all release artifacts and uploads them to the release
5. automatically creates a github discussion announcing the release
6. saves the release as draft so that a human can review and publish

**TODO**:

- [ ] Before resolving this issue we should make sure to record whatever changes were made as updates to `RELEASE.md`.

**Comment by youngnick** [comment]
One thousand percent agreed, the more we can head towards this goal, the better.

**Comment by akankshakumari393** [comment]
Hey @youngnick @shaneutt. Is this still valid. I would like to contribute to it. Also I would need some technical guidance on it.

**Comment by shaneutt** [comment]
Still valid, feel free to ask in this issue if you need help or run into any specific problems.

**Comment by akankshakumari393** [comment]
>feel free to ask in this issue if you need help or run into any specific problems.
Sure thanks @shaneutt 👍🏻

**Comment by akankshakumari393** [comment]
I would like to understand how were we releasing up until now. Was it a manual process?

**Comment by shaneutt** [comment]
It's been this so far: https://github.com/kubernetes-sigs/gateway-api/blob/main/RELEASE.md#release-steps

**Comment by youngnick** [comment]
Hi @akankshakumari393, before we go too far down the automation route, we have #916 and #627 that are both v0.6.0 release blockers that we could really use help on.

**Comment by akankshakumari393** [comment]
yeah Sure that, I would be happy to help.

**Comment by shaneutt** [comment]
We want this feature, but we consider it low priority until `v1.0.0`/GA is complete and don't believe we will have bandwidth for it until then.

**Comment by shaneutt** [comment]
There haven't been enough pain points to push this forward, so we're going to close it for now. It is always available to re-open if things change.
