### ISSUE TITLE
Add documentation covering conformance tests

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1274]
**What would you like to be added**:
Documentation that covers that provides an overview of our conformance tests as well as how to run them and add new ones.

**Why this is needed**:
Conformance tests are key to the success of this API, ensuring that different implementations provide a consistent experience. Unfortunately today we have no documentation covering conformance tests (unless you count the GEP).

/assign

**Comment by youngnick** [comment]
Definite +1 from me. I'd probably say there's a follow-up once we've done this - to provide a way for implementations to do something to prove what version and tests they're conformant to. Not urgent, but feels like we need some way to reward implementations for doing the work to be, and prove they are, conformant.

**Comment by youngnick** [comment]
Hmm, I think there's still some to do here about how to run, etc? @robscott should we reopen to track that?

**Comment by robscott** [comment]
Good catch, thanks @youngnick!

**Comment by shaneutt** [comment]
I think we're safe to close this once again as we have documentation currently that seems to cover the basics, but we also have #1709 which includes work for extending the conformance documentation to cover setup, configuration and reporting results as well. If I'm wrong and there's something we still need to do that's not covered, please re-open!
