### ISSUE TITLE
GEP: Mesh Service Binding

### ISSUE THREAD

**Issue by keithmattix** [kubernetes-sigs/gateway-api#1294]
**What would you like to be added**:
As the GAMMA initiative seeks to create a model for service [mesh](https://docs.google.com/document/d/1T_DtMQoq2tccLAtJTpo3c0ohjm25vRS35MsestSL9QU/edit#heading=h.fv9zxi8pjsiq) implementations within Gateway API, it is necessary to have a mechanism for [binding](https://docs.google.com/document/d/1T_DtMQoq2tccLAtJTpo3c0ohjm25vRS35MsestSL9QU/edit#heading=h.qerd5nlyuzyt) routes to services

This GEP covers the work to design and implement this mechanism.. 

**Why this is needed**:

As @shaneutt originally suggested, the first step will be implementing a provisional GEP that sets out the terms of what we're doing - the "What" and "Why" of the solution, and then once we're on the same page, we'll talk more about the "How".

Why this is needed:
Without a way to bind routes to services, no further work can continue

**Comment by keithmattix** [comment]
I've drafted a [Google doc](https://docs.google.com/document/d/1_9jFaz3aPQlETMLBSSl2WyQge1ZyJIV2XR52a_9r1rw/edit#) for more fluid discussion of this GEP

**Comment by shaneutt** [comment]
It would appear the permissions on this google doc are restrictive.

**Comment by keithmattix** [comment]
Apologies, the doc should be accessible now!

**Comment by shaneutt** [comment]
Based on recent conversations where we are trying to harden `Service` binding as the main way to do Gateway API for Mesh, this is still an ongoing effort and is not stale.

/remove-lifecycle stale

**Comment by keithmattix** [comment]
I think this will be complete with the release of v1.1

**Comment by youngnick** [comment]
/remove-lifecycle rotten

This is basically finished, but the GEP in the GEP list is listed as GEP-1426, not GEP-1294. We should really fix that, then this can be closed. See https://gateway-api.sigs.k8s.io/geps/gep-1426/ for the details. (May need a redirect from https://gateway-api.sigs.k8s.io/geps/gep-1426/ to gep-1294 once the change is made as well).

**Comment by youngnick** [comment]
This last item was fixed by #3359. Closing.

/close
