### ISSUE TITLE
conformance: support non-amd64 architectures

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#1295]
Similar to https://github.com/kubernetes-sigs/gateway-api/issues/627, we should publish all images used in conformance tests with multi-arch support.

One thing that confused me is @mikemorris seemed to suggest we picked the image we use because it supports arm64: https://github.com/kubernetes/kubernetes/issues/110605#issuecomment-1168908764. However, I do not see the same:

```
$ crane manifest k8s.gcr.io/ingressconformance/echoserver:v0.0.1
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 2026,
      "digest": "sha256:3cb9c24fedce680ad075cdc5d3d4037e306217fa1824344a54a0bd1d65a98654"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 639433,
         "digest": "sha256:5c7fe08dec514a5105d43dfcae1a5a45be002bcd3251dd178ced702aecfb7531"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2317481,
         "digest": "sha256:d6a250117705cac0781f5218e3753ba42a048ebbc49150b39e9a42dce0b189ef"
      }
   ]
}
```

**Comment by howardjohn** [comment]
I think the source is https://github.com/kubernetes-sigs/ingress-controller-conformance/tree/master/images/echoserver - It should be easy to change and I am happy to do it, just not sure how to actually get it published

**Comment by howardjohn** [comment]
/assign @howardjohn 

I'll need help getting it published officially though

**Comment by mikemorris** [comment]
Hmm, interesting that we had found this to work in practice previosuly without explicitly building arm64 images - not quite sure _how_ it was working without digging deeper, but https://github.com/hashicorp/learn-consul-kubernetes/issues/65 was the behavior we found where switching to this image was working on an M1 chip.

**Comment by howardjohn** [comment]
possibly using emulation?

**Comment by jrajahalme** [comment]
For anyone getting here: Multi-arch image is at: gcr.io/k8s-staging-ingressconformance/echoserver:v20221109-7ee2f3e, as used here: https://github.com/kubernetes-sigs/gateway-api/commit/578734fe7c48fa969e1cf4a8097fadd4b66d4ef7.
(changed since to gcr.io/k8s-staging-gateway-api/echo-basic:v20240412-v1.0.0-394-g40c666fd https://github.com/kubernetes-sigs/gateway-api/blame/b9c6f3c3ab4a0bca483eaad85938d279d2479839/conformance/base/manifests.yaml#L142)
