### ISSUE TITLE
conformance: always check `resolvedRefs` condition in `HTTPRoute` conformance tests

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/gateway-api#1314]
**What would you like to be added**:

In the `HTTPRoute` conformance tests, the `RouteConditionResolvedRefs` is checked only in those tests expecting it to have status`false` (e.g., `HTTPRouteInvalidNonExistentBackendRef`, `HTTPRouteInvalidBackendRefUnknownKind`, ...), but it is never checked in those tests who expect the routing to be successful. This leads to never checking the `ResolvedRefs` reason with `ConditionStatus == true`.

**Why this is needed**:

This is needed to ensure that the `RouteConditionResolvedRefs` is always set, no matter if the `ConditionStatus` is `true`, or `false`.

**Comment by shaneutt** [comment]
Sounds good. I've added this to our `v0.6.0` milestone as ideally given the small size we could get this added in time for our next release.

**Comment by shaneutt** [comment]
Talked about this in the sync: not considering this a blocker for v0.6.0
