### ISSUE TITLE
conformance: always check `ResolvedRefs` condition in `Gateway` conformance tests

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/gateway-api#1315]
**What would you like to be added**:

In the `Gateway` conformance tests, the `ListenerConditionResolvedRefs` is checked only in those tests expecting it to have status`false` (e.g., `GatewaySecretMissingReferenceGrant`, `GatewaySecretInvalidReferenceGrant`, ...), but it is never checked in those tests who expect the routing to be successful. This leads to never checking the `ResolvedRefs` reason with `ConditionStatus == true`.

**Why this is needed**:

This is needed to ensure that the `ListenerConditionResolvedRefs` is always set, no matter if the `ConditionStatus` is `true`, or `false`.

**Comment by nathancoleman** [comment]
There was some relevant discussion between myself, @skriss and @robscott in https://github.com/kubernetes-sigs/gateway-api/pull/1158#discussion_r869537633. The spec doesn't specifically call for this to be set to `true` for a healthy state, so this might be a good venue to decide what we want to do.

**Comment by mlavacca** [comment]
@youngnick @shaneutt Reading from the GEP #1383 that has recently merged, I see that has been decided to always enforce the Gateway conditions, even when true. Do you think I can pick this one and start implementing it?

**Comment by shaneutt** [comment]
I would say yes, but I'll defer to @youngnick since he has more context on this than I.

**Comment by mlavacca** [comment]
ping @youngnick

**Comment by youngnick** [comment]
Ah, sorry about this one, missed it. Yes please @mlavacca, please start working on this one.

**Comment by robscott** [comment]
@mlavacca are you still interested in working on this?

**Comment by mlavacca** [comment]
I'm afraid I don't have time to pick this one atm 😞

**Comment by levikobi** [comment]
Hi, can I help with this one?

**Comment by mlavacca** [comment]
> Hi, can I help with this one?

Hi @levikobi, it'd be great if you want to pick this one 👍

**Comment by levikobi** [comment]
> Hi @levikobi, it'd be great if you want to pick this one 👍

sure mate

**Comment by shaneutt** [comment]
Sounds good,

/assign @levikobi 

Let us know if you need any help or run into any trouble! :vulcan_salute:
