### ISSUE TITLE
Print out existing conditions on conformance test failure

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes-sigs/gateway-api#1317]
**What would you like to be added**:

Conformance tests validate conditions which are set on Gateway, HTTPRoute, etc.  On test failure, the test prints out that the wanted condition was not found, but it does not print out the conditions which were present.  Please add functionality to print out the conditions which were present when the test failed.

**Why this is needed**:

This will help improve the experience of debugging conformance test failures.

**Comment by mikemorris** [comment]
I think this has been resolved with the changes in #1363 and #1367, thanks @abhijit-dev82!

/close
