### ISSUE TITLE
GEP: Service Mesh in Gateway API

### ISSUE THREAD

**Issue by keithmattix** [kubernetes-sigs/gateway-api#1324]
**What would you like to be added**:
Due to the overlap in surface area between the Gateway API's routing primitives and many service mesh implementations, it would be generally beneficial to the Kubernetes community for the Gateway API to provide/support patterns and/or new resources for service mesh functionality. 

**Why this is needed**:
While attempting to scope out #1291 and #1294, it became apparent that more higher level context was needed to first answer the "what" question. Both of those issues are intrinsically tied to implementation details, so it is useful to first have a GEP that describes what service mesh interoperability in Gateway API is trying to accomplish.

**Comment by keithmattix** [comment]
/kind gep

Provisional GEP text can be found [here](https://docs.google.com/document/d/1IzItdX22fHfXCP6Zch6pC8hEImMNJ6MCPqGNW1aaDr8/edit?usp=sharing)

**Comment by robscott** [comment]
Let's leave this open until the GEP reaches a more complete state, probably "implemented".

**Comment by keithmattix** [comment]
/remove-lifecycle stale
/lifecycle frozen

This will stick around until something is implementable

**Comment by mikemorris** [comment]
I think this should be able to be closed soon with https://github.com/kubernetes-sigs/gateway-api/pull/2873 moving GAMMA to Standard for Gateway API v1.1

**Comment by youngnick** [comment]
Yes, given that this GEP is now a Memorandum, I think it makes sense to close this out.
