### ISSUE TITLE
Clarify Gateway and GatewayClass

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/gateway-api#135]
The relationship between `Gateway` and `GatewayClass` is critical to the Service API, and yet this relationship was the most confusing part of the API to myself and a few others. Here are some of our observations:

* A [Gateway resource has a 1:1 relationship with the lifecycle of the infrastructure](https://kubernetes-sigs.github.io/service-apis/concepts/#gateway_1) -- when a Gateway resource is created, a new load balancer is provisioned
* A GatewayClass represents a common configuration for provisioned load balancers

And perhaps the most important piece of information of all:

> The Service API v2 assumes the control planes for provisioning and configuring load balancers are one and the same and the `GatewayClass` connects to that control plane.

### Single Control Plane for Provisioning and Configuring Load Balancers

For example, the following load balancer solutions work well with the Service API v2:

* AWS ELB
* NSX-T
* AVI

Each one of the above examples use a single control plane for both provisioning and configuring load balancers. Here is a diagram that illustrates this relationship using NSX-T as an example:

![image](https://user-images.githubusercontent.com/101085/78851478-7cff5e80-79df-11ea-85c9-23b4782a8d37.png)

### Control Plane per Load Balancer

However, with load balancers that do not have a singular control plane, this model can be problematic. For example, the following illustration highlights the challenges faced when using a load balancer like HAProxy, which does not have a dedicated control plane for creating/configuring load balancers:

![gateway_and_gateway_class_without_single_lb_control_plane](https://user-images.githubusercontent.com/101085/78851585-c354bd80-79df-11ea-8021-e96ff0d445ef.png)

Without a centralized control plane for provisioning and configuring load balancers, the `GatewayClass` resource connects to the control plane there is -- the load balancer itself. This means there is a 1:1 relationship between the `Gateway` resource, the `GatewayClass` resource, and the load balancer platform.

### Workaround

Our solution is to introduce a flag/configuration property for the `GatewayClass` called something like:

* `Precreated`
* `DoNotCreate`
* `InfraOff`
* `NoNoNo`

This option would indicate that the controller for the `GatewayClass` should not provision new LB infrastructure for a `Gateway`, but use the load balancer for which the `GatewayClass` is already configured. This makes since when the load balancer itself is its own control plane and you want to limit the number of physical load balancers provisioned.

**Comment by jpeach** [comment]
I don't think I understand the problem here. In the HAproxy diagram, that looks exactly how I would expect this to work. You have 2 classes that are backed by the same controller but have different (semantic) configurations.

The centralized control plane is the `vmware.com/haproxy` controller, that presumably has some innate knowledge of the available proxies.

**Comment by akutz** [comment]
Because ideally your class points to a control plane that can provision a load balancer. The Gateway resource represents the instance, the GatewayClass the factory. In the HAProxy case the Gateway and GateywayClass *both* have a one-to-one relationship with the LB/control plane. That is not the intent, as I understand it, of this model.

**Comment by jpeach** [comment]
Yeh the terminology is not great, but a Gateway doesn't have to be a physical (or virtual thing). It can be something more like a virtual host. 

> Because ideally your class points to a control plane that can provision a load balancer. 

Ideally, but it is not required.

**Comment by akutz** [comment]
> Yeh the terminology is not great, but a Gateway doesn't have to be a physical (or virtual thing). It can be something more like a virtual host.
> 
> > Because ideally your class points to a control plane that can provision a load balancer.
> 
> Ideally, but it is not required.

I did not mean to imply it has to be physical. An HAProxy VM or a MetalLB instance isn’t physical. Still virtual, but they’re their own control plane.

And not required? The docs state without room for misinterpretation that there’s a 1:2 relationship between the Gateway and LB.

If the LB is it’s own control plane, it creates a 1:1 relationship between the Class and LB as well.

It kind of seems you’re agreeing with my original premise but not necessarily what I am trying to communicate re: the control plane. Whether the LB is physical or virtual has no bearing on the matter.

**Comment by jpeach** [comment]
> > Yeh the terminology is not great, but a Gateway doesn't have to be a physical (or virtual thing). It can be something more like a virtual host.
> > > Because ideally your class points to a control plane that can provision a load balancer.
> > 
> > 
> > Ideally, but it is not required.
> 
> I did not mean to imply it has to be physical. An HAProxy VM or a MetalLB instance isn’t physical. Still virtual, but they’re their own control plane.

The proxy itself is the data plane. The process that configures the proxy would be the control plane. 

> And not required? The docs state without room for misinterpretation that there’s a 1:1 relationship between the Gateway and LB.

https://kubernetes-sigs.github.io/service-apis/concepts/#gateway

Also https://kubernetes-sigs.github.io/service-apis/concepts/#deployment-models

> > Depending on the GatewayClass, the creation of the Gateway could do any of the following actions:
> > 
> > * Use cloud APIs to create an LB instance.
> > * Spawn a new instance of a software LB (in this or another cluster).
> > * Add a configuration stanza to an already instantiated LB to handle the new routes.
> > * Program the SDN to implement the configuration.

So there's a ton of wiggle room here for you to do what makes sense for your deployment. "Adding a configuration stanza" sounds a lot like what you would do in this situation.

It definitely looks like we need to make a pass over that document and clarify, and make it not contradict itself.

**Comment by akutz** [comment]
It sounds like a clarification is need for the word “load balancer.” Please see my comments on #130.
