### ISSUE TITLE
Update hack/verify-examples-kind.sh to work better with releases

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1366]
**What would you like to be added**:
Something that allows us to:

1. Run tests using the latest webhook image that has been built (latest commit, not latest release)
2. Still pass `hack/verify-codegen.sh`
3. Have a simple release process that allows us to at least temporarily set a fixed image version in our webhook deployment for our generated YAML attached to the release + the config/webhook YAML found at the release tag.

**Why this is needed**:
At one point we added the following to the script to ensure that our deployed YAML would use the latest image while our manifests on the main branch would not:

```
# Temporary workaround for release
sed -i 's/v0.5.0/latest/g' config/webhook/admission_webhook.yaml
```

This had the unfortunate affect of making a change that would cause our hack/verify-codegen.sh script to fail. https://github.com/kubernetes-sigs/gateway-api/pull/1348#discussion_r956890842 resolved that issue, but it all feels like a bit of a hack. We need a more resilient solution here.

**Comment by akankshakumari393** [comment]
Is this issue still open? @shaneutt I would like to work on it.

**Comment by akankshakumari393** [comment]
Hey @robscott please assign it to someone else, as i may not be able give time to it.
