### ISSUE TITLE
Improve `ExpectedResponse` used in conformance tests

### ISSUE THREAD

**Issue by aryan9600** [kubernetes-sigs/gateway-api#1384]
**What would you like to be added**:
A new type `Response` should be added containing the following fields (non-exhaustive):
```golang
// This struct represents a HTTPResponse returned from a backend.
type Response struct {
	StatusCode    int
	Headers       map[string]string
	AbsentHeaders []string
}
```
The `ExpectedResponse` struct should be modified to have field of the type `Response` replacing the current field `StatusCode`.

**Why this is needed**:
The `ExpectedResponse` contains a lot of information other than about _just_ the expected HTTP response, like the expected modified request, etc. It'd be nice to have a clear level of separation between the info specific to the other functionality of Gateway API and info related to the actual HTTP response.

**Comment by mikemorris** [comment]
Adding this in place of the existing `StatusCode` field make sense to me.

Linking the existing `ExpectedResponse` struct for comparison https://github.com/kubernetes-sigs/gateway-api/blob/a7a465ababc8b7c2cd9eaa1ab769496704fee92a/conformance/utils/http/http.go#L30-L47
