### ISSUE TITLE
Gateway Finalizer

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api#1386]
**What would you like to be added**:
A Gateway finalizer similar to the GatewayClass finalizer.

**Why this is needed**:
The [GatewayClass finalizer](https://github.com/kubernetes-sigs/gateway-api/blob/v0.5.0/apis/v1beta1/gatewayclass_types.go#L64-L67) ensures that a GatewayClass is not deleted when Gateways are attached. A Gateway finalizer should be specified to ensure Gateways are not deleted when HTTPRoutes are attached.

**Comment by tokers** [comment]
> **What would you like to be added**: A Gateway finalizer similar to the GatewayClass finalizer.
> 
> **Why this is needed**: The [GatewayClass finalizer](https://github.com/kubernetes-sigs/gateway-api/blob/v0.5.0/apis/v1beta1/gatewayclass_types.go#L64-L67) ensures that a GatewayClass is not deleted when Gateways are attached. A Gateway finalizer should be specified to ensure Gateways are not deleted when HTTPRoutes are attached.

Also for TLSRoute, TCPRoute, and UDPRoute?

**Comment by howardjohn** [comment]
IMO we shouldn't do this.

1. Core k8s types do not (PDB and deployment for example). The one I know that does, Namespace, is a unique case.
2. Generally finalizer is for the controller to cleanup. But the controller cannot delete the HTTPRoute - the user must. However, the user *also* cannot delete them since there is a persona split between gateway admin and app admin
3. Finalizer generally provide a poor UX, IMO

**Comment by danehans** [comment]
> Generally finalizer is for the controller to cleanup. But the controller cannot delete the HTTPRoute - the user must.

This is not the case for `GatewayClassFinalizerGatewaysExist`.

> However, the user also cannot delete them since there is a persona split between gateway admin and app admin

The persona split is not a requirement of Gateway API, e.g. a user can be responsible for managing the infra and app routing. Even in a split persona use case, I can see value in a Gateway finalizer to avoid an infra admin user from deleting Gateways with routes that were attached by app dev users.

**Comment by howardjohn** [comment]
> This is not the case for GatewayClassFinalizerGatewaysExist.

FWIW I don't think this should exist either :slightly_smiling_face: 

> The persona split is not a requirement of Gateway API

I don't think there is anything stopping an implementation from adding a finalizer if they want to, right? If you specifically want one (maybe you don't have persona split or don't care), you can always add one today?

**Comment by youngnick** [comment]
After thinking about this for a bit, I agree with @howardjohn to some extent - I don't think that the relationship implied by parentRef is strong enough for it to include a finalizer.

The only action on a Gateway being removed should probably be to remove the associated status references as the Route falls out of scope. We could maybe use a small spec update to include that.
