### ISSUE TITLE
Add flags for `SupportedFeature` and `ExemptFeature` in conformance tests

### ISSUE THREAD

**Issue by aryan9600** [kubernetes-sigs/gateway-api#1391]
**What would you like to be added**:
A flag for configuring `SupportedFeature` and another for `ExemptFeature` in the conformance test suite.

**Why this is needed**:
This would let implementations choose which features they want to include in their conformance test runs, depending on which features are supported/unsupported by them.

**Comment by gyohuangxin** [comment]
I will work on this. /assign

**Comment by gyohuangxin** [comment]
@aryan9600 I created a PR to add these flags, please feel free to review and leave comments.
