### ISSUE TITLE
Add make rule for running goimports

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes-sigs/gateway-api#1398]
**What happened**:

Running `make fmt` does not address linter formatting concerns.

**What you expected to happen**:

There should be a `make fmt` or `make goimports` rule that brings files to a state where `hack/verify-golint.sh` will pass.

**How to reproduce it (as minimally and precisely as possible)**:

Alter line spacing on imports then run `make fmt; make verify`.

**Comment by akankshakumari393** [comment]
Hey @briantkennedy, I couldn't reproduce the issue, I added line spaces on imports in the file `cmd/admission/main.go` like this 
```
import (
	"context"
	"crypto/tls"
	"errors"

	"flag"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"sync"

	"syscall"
```

then after running `make verify`  `hack/verify-golint.sh` script passed.
Could you please add more details on what is missing here.

**Comment by shaneutt** [comment]
@akankshakumari393 it's been a while since we heard back from you on this one, are you still interested in this one? Do you need any help moving it forward?

**Comment by akankshakumari393** [comment]
I might not be able to work on the issue, feel free to reassign it.👍

**Comment by shaneutt** [comment]
Ok thanks for the heads up!
