### ISSUE TITLE
Conflict namespace resource when using kustomize

### ISSUE THREAD

**Issue by oo00spy00oo** [kubernetes-sigs/gateway-api#1399]
**What happened**:

```
Error: accumulating resources: accumulation err='accumulating resources from 'kubernetes-gateway-api': '/workspace/bizzi-fluxcd/infrastructure/bizzi-dev/kubernetes-gateway-api' must resolve to a file': recursed accumulation of path '/workspace/bizzi-fluxcd/infrastructure/bizzi-dev/kubernetes-gateway-api': accumulating resources: accumulation err='accumulating resources from 'https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.5.0/standard-install.yaml': may not add resource with an already registered id: Namespace.v1.[noGrp]/gateway-system.[noNs]': evalsymlink failure on '/tmp/kustomize-1628085893/releases/download/v0.5.0/standard-install.yaml' : lstat /tmp/kustomize-1628085893/releases: no such file or directory
```

**What you expected to happen**:

Build with `kustomize` via command:

```bash
kustomize build
```

**How to reproduce it (as minimally and precisely as possible)**:

`kustomizaton.yaml`
```yaml
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.5.0/standard-install.yaml  
```

**Anything else we need to know?**:

There are 2 `kind: Namespace` with `name: gateway-system` in `standard-install.yaml`

Remove conflict namespace resource
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-system
---
```

**Comment by gyohuangxin** [comment]
This bug has been fixed by https://github.com/kubernetes-sigs/gateway-api/issues/1374, are you using the latest code?

**Comment by McLayer** [comment]
I think for non-contributors latest code = latest released code :)

**Comment by gyohuangxin** [comment]
@McLayer Yes, it's a good reminder. @robscott This fix was merged and cherry-picked to [release-0.5](https://github.com/kubernetes-sigs/gateway-api/pull/1387), but we haven't updated it on release page.

**Comment by youngnick** [comment]
Yes, the fix for this will be included in the v0.5.1 patch release.

**Comment by gyohuangxin** [comment]
@youngnick Great, thanks!

**Comment by gyohuangxin** [comment]
@oo00spy00oo https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.5.1 was released, it fixed this issue.

**Comment by oo00spy00oo** [comment]
> @oo00spy00oo https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.5.1 was released, it fixed this issue.

It worked, thanks!
