### ISSUE TITLE
ReferencePolicies yaml not present in config/crd/experimental

### ISSUE THREAD

**Issue by gnossen** [kubernetes-sigs/gateway-api#1422]
**What happened**:

```
$ kubectl apply -k "github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=main"
error: rawResources failed to read Resources: Load from path gateway.networking.k8s.io_referencepolicies.yaml failed: evalsymlink failure on '/tmp/kustomize-993690429/config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml' : lstat /tmp/kustomize-993690429/config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml: no such file or directory
```

**What you expected to happen**:

Successful installation.

**Anything else we should know**:
It looks like the reference to the file is [here](https://github.com/kubernetes-sigs/gateway-api/blob/6a8aa636b4bf39c9961b59fbd3d925ed7effb2a7/config/crd/experimental/kustomization.yaml#L6). By deleting this line, I can successfully install the experimental CRDs.

**Comment by robscott** [comment]
Thanks for reporting this @gnossen! @howardjohn fixed this with #1424
