### ISSUE TITLE
Webhook: Publish metric that tracks the number of errors encountered

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1425]
**What would you like to be added**:
A metric published by the webhook that tracks the number of errors encountered. It may be useful to have a metric that tracks responses by the following three outcomes:

1. 20x - Success
2. 40x - Failed Validation
3. 50x - Internal Error

**Why this is needed**:
When deploying this webhook as a cluster operator or infrastructure provider it would be helpful to detect any potential issues with this webhook.

Note: This issue requires some more thorough design before attempting to implement it. Please add any suggestions for how this could be implemented in comments on this issue.

**Comment by shaneutt** [comment]
We want this feature, but we consider it low priority until `v1.0.0`/GA is complete and don't believe we will have bandwidth for it until then.

**Comment by shaneutt** [comment]
With the deprecation of the webhook, this is no longer needed.
