### ISSUE TITLE
website: render Approved GEPs in numerical order instead of alphabetical

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/gateway-api#1428]
**What would you like to be added**:

Approved GEPs should be rendered in reverse chronological order in the website navigation menu (roughly, sorting by PR number instead of date is likely preferable). This may require adding additional metadata to existing GEP files.

**Why this is needed**:

Currently, Approved GEPs are rendered in alphabetical order, which can be particularly confusing now that we've reached four-digit GEPs.

<img width="248" alt="Screen Shot 2022-10-03 at 5 35 02 PM" src="https://user-images.githubusercontent.com/1149913/193689419-0b045775-48f1-4ef6-a927-0846113581e3.png">

/kind documentation

**Comment by robscott** [comment]
For reference, this is the line that generates this: https://github.com/kubernetes-sigs/gateway-api/blob/main/.golangci.yml#L42.
