### ISSUE TITLE
Improve the Gateway `ResolvedRefs` condition conformance tests

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/gateway-api#1437]
**What would you like to be added**:

#1419 improved the Gateway `ResolvedRefs` condition documentation by specifying in which cases the reason `InvalidCertificateRef` must be used:

https://github.com/kubernetes-sigs/gateway-api/blob/38a295bb0ad65b1b8cfc3610dad89754259f6623/apis/v1beta1/gateway_types.go#L748-L759

To ensure full compliance with this specification, the conformance tests related to the gateway `ResolvedRefs` condition should be improved to ensure that all the following cases are tested:

* the object referenced by the TLS configuration does not exist (already tested [here](https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/gateway-secret-missing-referenced-secret.go))
* the object referenced by the TLS configuration is invalid because of:
  * unsupported group (to be tested)
  * unsupported kind (to be tested)
  * the data within the resource is malformed (to be tested)

**Why this is needed**:

When all the above conditions are tested, all the reasons that can lead the Gateway condition `ResolvedRefs` to be false can be considered thoroughly tested.

**Comment by robscott** [comment]
@mlavacca are you still able to work on this?
