### ISSUE TITLE
webhook: validate certificateRefs when `tls` is set and `mode` is Terminate

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/gateway-api#1441]
**What would you like to be added**:

The `TLSModeType` documentation states: https://github.com/kubernetes-sigs/gateway-api/blob/006a257d4dfd6bf3bea938def6e20e7ddf256df2/apis/v1beta1/gateway_types.go#L290-L305

In particular, when the `TLSConfig` is set, and the `TLSModeType` is **terminate**, the `certificateRefs` field must always be set and contain at least one reference to an object.
To ensure this condition, the Gateway validation should be improved to ensure that such a condition is always verified.

**Why this is needed**:

When the `TLSModeType` is set to terminate, there is always the need for a valid certificate to terminate the TLS connection.

**Comment by gyohuangxin** [comment]
I'd like to implement it.
/assign
