### ISSUE TITLE
Promote ReferenceGrant to Beta

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1448]
**What would you like to be added**:
Based on discussion in recent community meetings, we believe that ReferenceGrant has met the required [graduation criteria](https://gateway-api.sigs.k8s.io/concepts/versioning/#graduation-criteria) to graduate to beta. This will require updating the types to match what we've done for GatewayClass, Gateway, and HTTPRoute, with one exception: The storage version will need to stick to v1alpha2 in this initial release.

**Comment by nathancoleman** [comment]
@robscott I can take this one

**Comment by robscott** [comment]
Thanks!

/assign @nathancoleman

**Comment by nathancoleman** [comment]
@robscott is the plan to move `ReferenceGrant` into the standard channel as well?

**Comment by robscott** [comment]
@nathancoleman yep, resources that have graduated to beta should also be part of the standard channel.
