### ISSUE TITLE
Enhance HTTPRoute Status Conditions

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api#1450]
**What would you like to be added**:
Improve HTTPRoute status conditions to better reflect instances where a route is accepted but differ from spec. For example, a user creates a route that has duplicate header matches. In this instance, the `Accepted=true` condition is surfaced since the ResolvedRefs condition type does not apply.

**Why this is needed**:
To provide better visibility into routes that were accepted but differ from spec.

cc: @youngnick

**Comment by danehans** [comment]
xref: https://github.com/envoyproxy/gateway/pull/495

**Comment by mikemorris** [comment]
I'm not quite sure I understand the ask here - this seems to imply encoding a way to express behavior that violates the spec within a specified status condition?

This feels like something that should be handled through conformance tests, setting an implementation-specific status condition, or suggesting changes to the Gateway API spec if it's misaligned with implementations in practice.
