### ISSUE TITLE
Conformance tests for TLS Passthrough 

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#1452]
**What would you like to be added**:
Conformance tests that define rules within the TLS Route API to enable TLS Passthrough between the client and the backend

**Why this is needed**:
To validate that the implementation supports the [TLSRoute API](https://gateway-api.sigs.k8s.io/concepts/api-overview/?h=tlsroute#tlsroute)

**Comment by candita** [comment]
@shaneutt  I'll get this started.

**Comment by candita** [comment]
See https://github.com/kubernetes-sigs/gateway-api/issues/1579 for a comprehensive list of tests that we can prioritize.

**Comment by shaneutt** [comment]
Sounds good, since #1579 seems to cover the purpose of this issue but has a long list of the individual tests to create, I'll close this as a duplicate. @arkodg if you feel that there's any context this issue has that _isn't_ properly captured by #1579 let me know.
