### ISSUE TITLE
https://gateway-api.sigs.k8s.io/references/spec renders code snippets improperly

### ISSUE THREAD

**Issue by pmalek** [kubernetes-sigs/gateway-api#1458]
It seems that the tooling responsible for generating the source for https://gateway-api.sigs.k8s.io/references/spec is not doing it properly for code snippets (e.g. yaml manifests)

Taking a look at https://github.com/kubernetes-sigs/gateway-api/blob/ff862f153f1c3c014ddf84a1194bc44982d027e2/site-src/api-types/httproute.md#matches the manifest looks correct

<img width="481" alt="image" src="https://user-images.githubusercontent.com/739996/195800822-8f99c964-e2e1-4522-abc2-17ef258e8b3a.png">

Although what's rendered at https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPRouteRule doesn't look right

<img width="919" alt="image" src="https://user-images.githubusercontent.com/739996/195800914-eb720383-0538-4c4e-8e6b-10091a1ffaf7.png">

Note the squashed list items.

Not sure how feasible it is to address this.

**Comment by robscott** [comment]
Thanks for filing this @pmalek! Hopefully someone can find a solution to this that also passes linting. If not, we may just need to find an alternative to inline YAML snippets. We ran into similar problems in https://github.com/kubernetes-sigs/gateway-api/pull/1416.

**Comment by shaneutt** [comment]
Hi @kundan2707 👋 

Wanted to check in on this one: are you still planning on doing this, and do you need any assistance from us? If not that's totally fine just let us know and we can unassign you 🖖

**Comment by kundan2707** [comment]
@shaneutt  can you help me to get path or any document related to tooling which is responsible for generation of this document?

**Comment by shaneutt** [comment]
What I usually do when I need to update the site is make my changes (e.g. in `site-src/`) and then make a _draft_ PR, so that netlify can build it for me and provide a demo URL I can test my changes at.

**Comment by kundan2707** [comment]
@shaneutt  thanks 
I will make change and push draft PR soon.

**Comment by robscott** [comment]
Closing this in favor #2555.
