### ISSUE TITLE
Define how Policy Attachment might be applied to GAMMA resources

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/gateway-api#1482]
**What would you like to be added**:

[GEP-1426](https://github.com/kubernetes-sigs/gateway-api/pull/1426) does not cover how Policy Attachment might be applied to mesh resources for GAMMA.

**Why this is needed**:

Many service meshes have a significant scope of functionality which could possibly be expressed through the Policy Attachment pattern, potentially configurable by cluster operators, security administrators or application developers at various degrees of granularity (mesh-wide, per-namespace, per-service) including rate limits, timeouts, AuthZ and more.

**Comment by youngnick** [comment]
I think that the `defaults` and `overrides` functionality of Policy Attachment resources would be very useful for things that have various degress of granularity (like mesh, namespace, and service), since that way you can make the most of the pseudo-inheritance they provide.

**Comment by youngnick** [comment]
Hmm, this is definitely still relevant, just needs to continue being worked on. I probably won't get to this for a bit though, so releasing it.

**Comment by mikemorris** [comment]
I expect this will be covered with the revisions and split out of "inherited" policy attachment in https://github.com/kubernetes-sigs/gateway-api/issues/2649, and shouldn't necessarily require anything specific for GAMMA, okay to close this issue if you agree @youngnick

**Comment by youngnick** [comment]
Hmm, yes, let's close this one out.

/close
