### ISSUE TITLE
Define if or how TCPRoute might be used for GAMMA configuration

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/gateway-api#1483]
**What would you like to be added**:

[GEP-1426](https://github.com/kubernetes-sigs/gateway-api/pull/1426) focuses exclusively on how to configure Layer 7 routing rules between services in a mesh using `HTTPRoute`. We should specify if or how `TCPRoute` should also be supported for Layer 4 routing in GAMMA.

**Why this is needed**:

Clarity is needed on whether it should be possible to use `TCPRoute` for GAMMA routing configuration (e.g. to weight traffic between different backends, but only at L4), what should happen if both an `HTTPRoute` and `TCPRoute` would attempt to target the same service as a `parentRef`, and if `TCPRoute` should be a preferred UX for some use cases or mesh implementations (e.g. if L7 traffic management is not supported).

**Comment by howardjohn** [comment]
Fixed by https://github.com/kubernetes-sigs/gateway-api/pull/1492 - don't believe github UI, this merged

**Comment by shaneutt** [comment]
Sounds like we can close this then, if that's not the case please feel free to re-open. :vulcan_salute:
