### ISSUE TITLE
Define if or how "headless" Services and StatefulSets might be supported for HTTPRoute in GAMMA

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/gateway-api#1484]
**What would you like to be added**:

Specify if or how `HTTPRoute` as configured for GAMMA should allow directing traffic to a `StatefulSet` through a "headless" Service.

**Why this is needed**:

[GEP-1426](https://github.com/kubernetes-sigs/gateway-api/pull/1426) has removed any mention of "headless" `Service` and `StatefulSet` to minimize scope and complexity.

From @howardjohn:
> Targetting headless service is not un-ambiguous either btw. Its possible to implement, but you can have 2 headless services for 1 pod, and its impossible to distinguish them based on IP ( since there is no VIP ). If we want to allow this, lets clearly document the behavior.
>
> In Istio I think we just pick the oldest or something. its pretty rare to have this scenario
>
> https://github.com/kubernetes-sigs/gateway-api/pull/1426/files#r992453893

Furthermore, there was some substantial confusion about the mention of this behavior described in the docs:

> [Headless Services](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) without selectors SHOULD NOT be supported as a `backendRef` due to the possibility of matching `Services` with `type: ExternalName`.

**Comment by keithmattix** [comment]
My gut feeling thinking through this is that the `Service` should be the thing that's bound, even if it's headless. Implementations should maintain existing kubernetes behavior (including statefulset subdomaining), and in the edge case John laid out (where 2 headless services point to the same pod), the behavior should explicitly be undefined.

**Comment by dprotaso** [comment]
Generally I've seen headless services used to work around k8s load balancing. ie. use GRPC client-side load balancing https://www.bytefold.com/load-balancing-a-grpc-service-on-k8s

I'm only aware of Istio Mesh doing properly loadbalancing when the K8s service is not headless - as long as the Service port name is labelled `grpc` (which sorta feeds into the need for https://github.com/kubernetes-sigs/gateway-api/discussions/1244)

**Comment by keithmattix** [comment]
@mikemorris may have to close the issue, but we're effectively deferring to the existing language in the GEP which says that headless services are not supported with parentRef due to the fact that they have no "frontend" role (i.e. no ClusterIP)
