### ISSUE TITLE
Define how conformance levels and release channels should be applied to GAMMA

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/gateway-api#1488]
**What would you like to be added**:

Define how conformance levels (core, extended, implementation-specific) and release channels (standard, experimental) should be applied to GAMMA.

**Why this is needed**:

It may be useful to somehow segment GAMMA support, as some N/S Gateway API implementations are very unlikely to implement mesh functionality.

**Comment by mikemorris** [comment]
There has been some discussion on this topic in the past few [GAMMA meetings](https://docs.google.com/document/d/1s5hQU0CB9ehjFukRmRHQ41f1FA8GX5_1Rv6nHW6NWAA/edit#), and is on the agenda for further discussion at the next [main Gateway API meeting on 1/23/2023](https://docs.google.com/document/d/1eg-YjOHaQ7UD28htdNxBR3zufebozXKyI28cl2E11tU/edit#heading=h.8exjqcg0ukpq).

Ideas include introducing a "conformance profile" or separate suite to segment GAMMA tests without introducing new channels or levels, as well as potentially split L4/L7 conformance given some N/S implementations may not support both.

There is interest in building machine-readable advertisement of feature support, possibly through `GatewayClass`, or potentially something more broadly applicable (from which other projects might benefit too) like a "capabilities" API.

**Comment by keithmattix** [comment]
Consensus was that conformance tests aren't required until promotion to beta, so we have time to decide. Gateway API is looking into creating a way to split off a GAMMA profile of separate conformance tests for mesh implementations

**Comment by keithmattix** [comment]
Does #1686 cover enough of this issue for the Implementable 0.70 milestone?
