### ISSUE TITLE
GEP 820 - Is it HTTPRouteMatch.ExtensionRef or HTTPRouteFilter.ExtensionRef 

### ISSUE THREAD

**Issue by Amila-Rukshan** [kubernetes-sigs/gateway-api#1523]
This [GEP 820](https://gateway-api.sigs.k8s.io/geps/gep-820/) says:
```
Drop extension points within Route match block
```
but as I checked the reference docs  [HTTPRouteFilter](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPRouteFilter) is the object that support `ExtensionRef`.

Should it be corrected to HTTPRouteFilter.ExtensionRef or have I understood something wrong?

**Comment by youngnick** [comment]
Ah, this GEP is marked as `Standard`, which means it has been implemented and the extension points have already been removed. So the work is done.

**Comment by robscott** [comment]
Sorry for any confusion here, since this work has already been completed, I'm going to close this out.
