### ISSUE TITLE
Conformance: allow opting out of subtests

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#1525]
Currently, we have some logic like this:

```go
			for _, ct := range tests.ConformanceTests {
				t.Run(ct.ShortName, func(t *testing.T) {
					if reason, f := skippedTests[ct.ShortName]; f {
						t.Skip(reason)
					}
					ct.Run(t, csuite)
				})
			}
```

To execute the conformance tests from our own Go runner. The issue is this is not very granular as the conformance has subtests in plenty of places.

It would be nice to be able to be more specific so we could opt out of something like `GatewayInvalidTLSConfiguration/Nonexistent_secret_referenced_as_CertificateRef_in_a_Gateway_listener` instead of just `GatewayInvalidTLSConfiguration/`

**Comment by robscott** [comment]
Based on discussion in chat, it seems like at least Istio, Consul, and GKE have used an approach like this. I'd be open to some kind of built in way to do this instead of everyone inventing their own.

**Comment by mlavacca** [comment]
In the Kong ingress controller, we used a similar approach too. I'd like to pick this one and propose a built-in solution to opt-out entire test suites (`GatewayInvalidTLSConfiguration `) or only specific test cases (`GatewayInvalidTLSConfiguration/Nonexistent_secret_referenced_as_CertificateRef_in_a_Gateway_listener`).

/assign

**Comment by dprotaso** [comment]
FWIW: Go 1.20 will have a `go test` flag `-skip`  https://github.com/golang/go/issues/41583

**Comment by howardjohn** [comment]
I would prefer to not use `-skip` personally since we want it in code not in our test runner, but we could make do if needed.

**Comment by youngnick** [comment]
I think that having a standard mechanism for skipping tests is good, but that skipping Core tests should eventually mark you as not conformant. Otherwise we could have implementations skip all the tests but still "pass" conformance. Obviously this requires us to have a more structured conformance process than the current honor system though.
