### ISSUE TITLE
Conformance: GatewaySecretReferenceGrantSpecific is overly restrictive

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#1536]
This checks that SupportedKinds is exactly `[HTTPRoute]`. This is somewhat a requirement of `listenersMatch`, which requires tests which don't care about the full status (the test has nothing to do with SupportKinds) to specify everything, and do an exact match.

Specifically, this broke us when we implemented GRPCRoute, as we added that as a supported kind

cc @gnossen

**Comment by shaneutt** [comment]
Marked this as `release-blocker` as we need to get this fixed _before_ v0.7.0 to avoid breaking people's stuff.

**Comment by arkodg** [comment]
should be fixed in v0.6.1 with https://github.com/kubernetes-sigs/gateway-api/pull/1692 and https://github.com/kubernetes-sigs/gateway-api/pull/1707

**Comment by shaneutt** [comment]
Good call @arkodg, thanks!
