### ISSUE TITLE
conformance: Update conformance tests to check for correct `attachedRoutes` value

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/gateway-api#1543]
**What would you like to be added**:
Currently, we mandate behavior for `attachedRoutes` in Listener status, but don't check for it in conformance tests. We should do that.

**Why this is needed**:
Conformance tests should test all mandated behaviors.

Todo list:
- [ ] Add a helper to check that a given Gateway Listener has a given value for `attachedRoutes`
- [ ] Update existing tests to check `attachedRoutes` - this one is a fair amount of work, I think,

/area conformance
/help-wanted

**Comment by youngnick** [comment]
/good-first-issue
for folks looking to get to know the conformance tests.

**Comment by nickgreenspan** [comment]
I can try taking this. I'm a new contributor but I've read through a lot of the gateway-API documentation.

**Comment by nickgreenspan** [comment]
When I try building the code (before making any changes of my own), I get the following failed test:
Test FAILED: hack/../hack/verify-codegen.sh
Uncommitted changes in generated sources:
 M apis/v1alpha2/grpcroute_types.go
 M apis/v1alpha2/validation/gateway.go
 M apis/v1beta1/httproute_types.go
 M apis/v1beta1/shared_types.go
 M apis/v1beta1/validation/gateway.go
 M config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
 M config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
 M config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
 M config/crd/standard/gateway.networking.k8s.io_httproutes.yaml

Should I do something about this?

**Comment by gyohuangxin** [comment]
@nickgreenspan Can you show the method/command you built the code?

**Comment by youngnick** [comment]
The verify-codegen script takes the APIs in `apis/` and generates the YAML files from it - it shouldn't be changing those files that are listed in there. Are you sure you ran it with a freshly-pulled repo? (I've done this a few times myself).

**Comment by nickgreenspan** [comment]
I just ran "make" from the gateway-api directory. I reran after reverting to the last [commit]([d7f71d6](https://github.com/kubernetes-sigs/gateway-api/commit/d7f71d6b7df7e929ae299948973a693980afc183)), and it seems like something during the build is modifying the above files. Maybe "go fmt ./..." which is run during hack/update-codegen.sh?

**Comment by youngnick** [comment]
ah, are you using the correct Go version? `go fmt` has had some changes between versions lately...

**Comment by nickgreenspan** [comment]
Gotcha, that seems like it might be it.

**Comment by nickgreenspan** [comment]
Unfortunately I've recently become really busy with school work (will continue for the next 2-3 weeks) so it might make sense to take me off this issue for now so someone else can make progress.

**Comment by shaneutt** [comment]
No worries, if nobody else picks it up by the time you come back and you want it again feel free. Thanks for letting us know! :vulcan_salute:

**Comment by ChaningHwang** [comment]
Hi! I am a new contributor who is looking for my first issue to work on. And I went through the documentation. Can I try to take this one?

**Comment by shaneutt** [comment]
Sounds great, thanks @ChaningHwang! Please check in with us in `#sig-network-gateway-api` on [Kubernetes Slack](https://kubernetes.slack.com) if you need help.

**Comment by shaneutt** [comment]
@ChaningHwang how are things going? Can we provide any assistance?

**Comment by ChaningHwang** [comment]
> 

I am trying to add more tests to cover cases when attachedRoutes should be 1 or more. But I am not able to pass the following tests on local with the istio implementation.
GatewaySecretReferenceGrantAllInNamespace
GatewaySecretReferenceGrantSpecific

**Comment by shaneutt** [comment]
Sounds like the `ReferenceGrant` CRD is not installed. Can you provide more detail about how you're setting up and running the test suite?

**Comment by ChaningHwang** [comment]
> Sounds like the `ReferenceGrant` CRD is not installed. Can you provide more detail about how you're setting up and running the test suite?

I used this command to run the test:
go test -v ./conformance --gateway-class istio --run TestConformance/GatewaySecretReferenceGrantAllInNamespace
And I kubectl apply the standard and experimental channel following here: https://gateway-api.sigs.k8s.io/v1alpha2/guides/
And on local, the version of referencegrants.gateway.networking.k8s.io is v1alpha2. 
Did I miss anything?

**Comment by shaneutt** [comment]
You'll want to be using https://gateway-api.sigs.k8s.io/guides/ rather than the `v1alpha2` link, but even then I'm just realizing those links are out of date! As a temporary workaround, please replace `v0.5.1` with `v0.6.1` in the relevant links to install the more up-to-date versions of the CRDs which includes the `v1beta1` version of `ReferenceGrant`. I'll get the guides updated, thanks for identifying this problem :vulcan_salute:

**Comment by ChaningHwang** [comment]
> You'll want to be using https://gateway-api.sigs.k8s.io/guides/ rather than the `v1alpha2` link, but even then I'm just realizing those links are out of date! As a temporary workaround, please replace `v0.5.1` with `v0.6.1` in the relevant links to install the more up-to-date versions of the CRDs which includes the `v1beta1` version of `ReferenceGrant`. I'll get the guides updated, thanks for identifying this problem 🖖

Thanks for your information! I updated the crd on local and saw a lot of this instead:
helpers.go:197: expected observedGeneration to be updated for all conditions, only 2/3 were updated. stale conditions are: Accepted
And waited for a while, the test failed with timeout. Do you have any insight into it?

**Comment by shaneutt** [comment]
This seems to indicate that the implementation does not update the `Accepted` condition for every generation of the object. The implementation should be updating the `Accepted` condition for each new version of the object to verify that the controller has seen the update and that state remains valid for that version.

**Comment by ChaningHwang** [comment]
> This seems to indicate that the implementation does not update the `Accepted` condition for every generation of the object. The implementation should be updating the `Accepted` condition for each new version of the object to verify that the controller has seen the update and that state remains valid for that version.

Thanks for your information! I changed to use istio-1.17.0 implementaion and the test got passed. I am working on adding tests to cover attachedRoutes to be 1 or more cases.
