### ISSUE TITLE
Job post-gateway-api-push-images started failing on 09-11

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/gateway-api#1545]
**What happened**:

![image](https://user-images.githubusercontent.com/6450081/202408336-f851995a-724d-45cc-8b57-18af2815cdb7.png)

https://testgrid.k8s.io/sig-network-gateway-api#post-gateway-api-push-images

```
hack/build-and-push.sh
unknown flag: --build-arg
See 'docker --help'.
Usage:  docker [OPTIONS] COMMAND
```

There were several changes in this area https://github.com/kubernetes-sigs/gateway-api/commit/7a1324159a500c08596f5458e936f3bb65ef8592

**Comment by aojea** [comment]
@wilsonwu you restored those flags recently https://github.com/kubernetes-sigs/gateway-api/commit/b48859c48d9e9a99d4e8aefebaca46257c90fae9

**Comment by wilsonwu** [comment]
> @wilsonwu you restored those flags recently [b48859c](https://github.com/kubernetes-sigs/gateway-api/commit/b48859c48d9e9a99d4e8aefebaca46257c90fae9)

#1542 try to fix in this PR.

**Comment by wilsonwu** [comment]
After #1542 PR merged, still has problem, need help @shaneutt 
```
gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211118-2f2d816b90
hack/build-and-push.sh
unknown shorthand flag: 't' in -t
See 'docker --help'.
Usage:  docker [OPTIONS] COMMAND
A self-sufficient runtime for containers
```

I tried this docker container can support buildx command.

**Comment by Xunzhuo** [comment]
I can help on this if you are willing to : ) @wilsonwu

**Comment by wilsonwu** [comment]
> I can help on this if you are willing to : ) @wilsonwu

Yes please, I checked that the gcb-docker-gcloud image could support buildx: https://github.com/kubernetes/test-infra/tree/master/images/gcb-docker-gcloud.

And it works in my local env, please help to fix it.

**Comment by Xunzhuo** [comment]
Can you share how you test this image locally @wilsonwu ?

**Comment by wilsonwu** [comment]
> Can you share how you test this image locally @wilsonwu ?

I just tested the make command and script in my local env(not in container), and also checked the job image could support docker buildx command.

BTW: I am tring to use dind to test the script but not success now, still tring...

**Comment by Xunzhuo** [comment]
Yep, I tested the gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211118-2f2d816b90, and yes, docker buildx is supported.

https://github.com/kubernetes-sigs/gateway-api/pull/1549 added verify and log for docker buildx, I think this can provide more context on the docker buildx issue.

**Comment by Xunzhuo** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-gateway-api-push-images/1593583940357066752
Looks like we can not find docker buildx in our CI workflows.

**Comment by Xunzhuo** [comment]
This is weird, some options I think:
1. Try to upgrade the gcb-docker-gcloud image to the latest.
2. Try to change the build image.

I will take some time later this day to look into this issue.

**Comment by shaneutt** [comment]
Sounds good, thanks for the help @Xunzhuo!

**Comment by wilsonwu** [comment]
I suggest to change a build image.

**Comment by wilsonwu** [comment]
> I suggest to change a build image.
> 
> And I am looking for a good build image from popular repos.

I found the istio build tools image is good as build image: gcr.io/istio-testing/build-tools

**Comment by robscott** [comment]
#1552 didn't work. Looks like we should try to use something like what ingress-nginx is doing: https://github.com/kubernetes/ingress-nginx/blob/main/hack/init-buildx.sh.

**Comment by Xunzhuo** [comment]
Nope, something is different now, at least, docker supports docker buildx now.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/48784001/202994617-9675ed4a-cad6-44d9-aa53-6c98356f998b.png">

**Comment by Xunzhuo** [comment]
We passed image verify now, before #1552:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/48784001/202994900-72906d33-8d4a-42ce-bfd5-430b08e79d11.png">

For now, I think we just need some setups for muli-arch buildx context : )

cc @robscott @wilsonwu

**Comment by wilsonwu** [comment]
Good job, I added: `docker buildx create --use`, I think it can be solved.
