### ISSUE TITLE
"Stable" channel instead of "Standard" channel in the doc

### ISSUE THREAD

**Issue by plgingembre** [kubernetes-sigs/gateway-api#1567]
Just reporting a minor documentation bug. 

**What happened**: The release channels diagram in the Concepts > Versioning page (https://gateway-api.sigs.k8s.io/concepts/versioning/#release-channels-eg-experimental-standard) shows the inner circle labeled with "Stable" channel.

**What you expected to happen**: "Stable" should be replaced with "Standard" as it seems to be the naming convention (Standard, Experimental). I checked the rest of the page, there's no mention of "Stable" anywhere else in this page.

**Comment by youngnick** [comment]
Yes, that's correct, we are _planning_ to have a stable channel later when things move to GA.
