### ISSUE TITLE
Member request from Wilson Wu

### ISSUE THREAD

**Issue by wilsonwu** [kubernetes-sigs/gateway-api#1574]
**What would you like to be added**:
I'd like to add me as sigs member.
I have some PRs and review works like below:
#1462 #1542 #1522 #1545 #1553  

**Why this is needed**:
I want to do more contributions on the kubernetes world.

Thank you!

**Comment by Xunzhuo** [comment]
You should create an issue in https://github.com/kubernetes/org.
And you need two sponsors for your request I think.

**Comment by wilsonwu** [comment]
> You should create an issue in https://github.com/kubernetes/org. And you need two sponsors for your request I think.

Got it, thank you!

**Comment by wilsonwu** [comment]
@Xunzhuo BTW, do you mind being one of my sponsors?

**Comment by wilsonwu** [comment]
@Xunzhuo Be confident!

**Comment by robscott** [comment]
Hey @wilsonwu, thanks for the interest in becoming a member! The process is described here: https://github.com/kubernetes/community/blob/master/community-membership.md#member.

Here are the requirements for sponsors:
>Sponsored by 2 reviewers. Note the following requirements for sponsors:
>* Sponsors must have close interactions with the prospective member - e.g. code/design/proposal review, coordinating on issues, etc.
>* Sponsors must be reviewers or approvers in at least one OWNERS file within one of the [Kubernetes GitHub organizations](https://github.com/kubernetes/community/blob/master/github-management#actively-used-github-organizations)*.
>* Sponsors must be from multiple member companies to demonstrate integration across community.

I'd recommend reaching out to potential sponsors directly on Slack to ask for support.

**Comment by wilsonwu** [comment]
Thanks for the process @robscott I will submit request later.
