### ISSUE TITLE
Update conformance test to assert observedGeneration is bumped

### ISSUE THREAD

**Issue by dprotaso** [kubernetes-sigs/gateway-api#1584]
As a follow up to https://github.com/kubernetes-sigs/gateway-api/issues/1364 we should update conformance tests to assert that each condition's `observeredGeneration` is incremented to match the resource's `metadata.generation`

This is important because as updates occur to a resource's `spec` block (which increments `metadata.generation`) it implies the conditions are stale until the controller acknowledges them.

Also the language in the GEP is a bit confusing

> observedGeneration is an optional field that sets what the metadata.generation field was when the controller last saw a resource. Note that this is optional in the struct, but is required for Gateway API conditions. This will be enforced in the conformance tests in the future.

I would probably just state that `observedGeneration` is required to be set by gateway implementations and ignore mentioning that there's an `+optional` marker

**Comment by youngnick** [comment]
Yeah, reading it back, that is confusing, thanks. I'll do a small PR to update that. But agreed that we should check observedGeneration matches correctly as well.
