### ISSUE TITLE
grpc-web support using GRPCRoute

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#1637]
**What would you like to be added**:
Clarification/support for [grpc-web](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) traffic using the [GRPCRoute](https://gateway-api.sigs.k8s.io/api-types/grpcroute/) API

**Why this is needed**:
Support incoming grpc-web traffic to be route to a gRPC based backend.

Related issues: https://github.com/kubernetes-sigs/gateway-api/pull/1004#issuecomment-1032846167
https://github.com/envoyproxy/gateway/issues/879

**Comment by gnossen** [comment]
I think this would be a great feature for GRPCRoute. It was one of the ideas we had for a second pass at the resource, along with:

- REST transcoding
- simplification of reflection passthrough
- protobuf-based routing

For the moment, however, I've been putting my efforts into getting the initial scope of HTTP/2 + protobuf support made official. If someone else is willing to help out though, this would be a really great feature.

**Comment by brianehlert** [comment]
My only comment is that this is historically exclusive to Envoy.

**Comment by HummingMind** [comment]
Is this still not planned? :(
