### ISSUE TITLE
Add ability to enable all Supported Feature Conformance tests

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#1638]
**What would you like to be added**:
A way to enable all core and extended conformance tests without explictly specifying [each supported feature suite name ](https://github.com/kubernetes-sigs/gateway-api/blob/d950009b34786a2fda3f5e8837c2de31b54b483d/conformance/utils/suite/suite.go#L34)

**Why this is needed**:
To be able to run the complete and latest set of conformance tests in the implementation repo (e.g. in [envoy-gateway](https://github.com/envoyproxy/gateway/blob/8dd60b1a3aaa8a93504aae0efd4d50315a43bd96/test/conformance/conformance_test.go#L56)) w/o having to manually track which new suite was added to the gateway-api repo

Relates to https://kubernetes.slack.com/archives/CR0H13KGA/p1668094311024819

**Comment by robscott** [comment]
This makes sense to me, open to any PRs.

**Comment by arkodg** [comment]
@shaneutt can this be added to the v0.6.1 milestone ?

**Comment by shaneutt** [comment]
Yeah let's see if we can get this in there, I'll check back in with @robscott :+1:
