### ISSUE TITLE
The client is missing Apply() functions, making use alongside other client-go packages difficult

### ISSUE THREAD

**Issue by therealmitchconnors** [kubernetes-sigs/gateway-api#1639]
Since K8s 1.22, client-go has supported server-side-apply through functions like Apply(), ApplyStatus(), etc.  Because the gateway api client library lacks these functions, it must be called in non-idiomatic ways, increasing friction for those who intend to automatically control gateways.

**Comment by nikola-jokic** [comment]
Can I take this one :relaxed: ?

**Comment by howardjohn** [comment]
Just FYI this is going to have a real world negative impact on all users: https://github.com/kubernetes/kubernetes/issues/101384

**Comment by dprotaso** [comment]
Could you maintain the server-side apply client in a separate package - so it's opt-in?

**Comment by Sajiyah-Salat** [comment]
Hello, I want to work on this issue. But I cant see the whole picture. A more detailed description and some resource links would be helpful. Thank you.

**Comment by ashutosh887** [comment]
I would like to work on this @shaneutt @therealmitchconnors

**Comment by shaneutt** [comment]
Sounds good @ashutosh887, but since I've noticed that you've taken some other issues on in the last couple days: please note that this one could take some significant time, let us know if you get stuck or need any help along the way! :vulcan_salute: 

/assign @ashutosh887

**Comment by ashutosh887** [comment]
I'll try to work on it @shaneutt 
Sure I'll let you know if I face any difficulty

**Comment by shaneutt** [comment]
@ashutosh887 do you still have time for this? Anything we can do to help support you?

**Comment by therealmitchconnors** [comment]
@shaneutt what needs to happen to move this forward?  It was disappointing to see it removed from the GA tracker.  SSA is the standard that K8s seems to be trying to get everyone to move to, but lack of support in critical libraries makes doing the right thing very difficult...

**Comment by dprotaso** [comment]
@howardjohn are the concerns in your [comment](https://github.com/kubernetes-sigs/gateway-api/issues/1639#issuecomment-1382166741) still relevant?

**Comment by Bharadwajshivam28** [comment]
Hey @shaneutt I can take on this issue but I need some more details like steps to get started

**Comment by dprotaso** [comment]
hey @Bharadwajshivam28 there's already a PR out of for this - https://github.com/kubernetes-sigs/gateway-api/pull/2537

Forgot to link it back to the issue.

Secondly, keep an eye on who's assigned to the issue cause if there's already someone assigned you don't want two people creating duplicate work.
