### ISSUE TITLE
Update implementer's guide with info about what resources impls need to watch

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/gateway-api#1650]
From some discussion about the GatewayClass observed generation bump conformance test (https://kubernetes.slack.com/archives/CR0H13KGA/p1673599220709819), amongst others, it seems that an update to the implementation guidelines page detailing the expectations Gateway API has for implementations would be useful.

I'm thinking of rules like:
- Implementations must be able to pick up _any_ GatewayClass with their `controllerName` set, and update its status. (They are free to only pick one Accepted GatewayClass, but they have to watch all of them. You need to specify the GatewayClasses to watch using the controllerName, _not_ by specifying a GatewayClass name directly, for example.)
- Implementations don't have to support all Route types, but for those they do, they need to update the status of any that have a `parentRef` pointing to an in-scope Gateway. (Here, "in-scope Gateway" means a Gateway that has a `spec.gatewayClassName` field referencing a GatewayClass that has a `spec.controllerName` field that matches the one the implentation is configured with. This sort of definition should also be included in the implementations guidelines page).

I'll take this, but wanted to make everyone aware of what I'm doing.

/assign

/area documentation

**Comment by youngnick** [comment]
Oh, I just found another thing to include in my notes: Tips for if you want to autogenerate HTTPRoute entries, for example, from a Swagger definition - https://github.com/kubernetes-sigs/gateway-api/issues/1485#issuecomment-1312873193 was the trigger for that one.

**Comment by shaneutt** [comment]
Still want this ultimately, but it doesn't need to block the GA release.

**Comment by youngnick** [comment]
At some point, we've actually folded these changes into the [Implementer's Guide](https://gateway-api.sigs.k8s.io/guides/implementers/). Closing.
