### ISSUE TITLE
Cross-namespace `parentRef` reason for routes accepted condition 

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/gateway-api#1670]
**What would you like to be added**:

A new `RouteConditionReason` should be added to state that the route is not accepted because a cross-namespace reference is not granted by a `ReferenceGrant`.

We already have a specular reason for the `ResolvedRefs` condition:
https://github.com/kubernetes-sigs/gateway-api/blob/7d408be7fc5389002858712fd7e7c0f14260274c/apis/v1beta1/shared_types.go#L276-L280

That should be set in such a case, jointly with a failed `accepted` condition, but no reason for the `accepted` condition is suitable to express it.

**Why this is needed**:

As of now, the *route `Accepted` condition can fail with the following reasons :
- `NotAllowedByListeners`
- `NoMatchingListenerHostname`
- `NoMatchingParent`
- `UnsupportedValue`

When a route references a gateway (through a `ParentRef`) in another namespace, and no `ReferenceGrant` allows such a reference, there is no suitable reason to use  for the `Accepted` condition to state it as failed.

**Comment by Sajiyah-Salat** [comment]
This is somewhat confusing for me as a beginner. Can you please break it down or provide me some resources to get started  in this. Thank you.

**Comment by mlavacca** [comment]
> This is somewhat confusing for me as a beginner. Can you please break it down or provide me some resources to get started in this. Thank you.

This issue is about adding a new reason to the set of already existing reasons for the `accepted` condition of the *route:
https://github.com/kubernetes-sigs/gateway-api/blob/7d408be7fc5389002858712fd7e7c0f14260274c/apis/v1beta1/shared_types.go#L205-L252
 This reason should be used to express that the Route has not been accepted because it has a `ParentRef` that references a Gateway in another namespace, but no ReferenceGrant allows such a reference.

Therefore, simply adding the new reason to the API and providing the documentation is the scope of the issue. Such a reason will likely be used in the conformance tests in subsequent PRs.

**Comment by Sajiyah-Salat** [comment]
https://github.com/kubernetes-sigs/gateway-api/blob/7d408be7fc5389002858712fd7e7c0f14260274c/apis/v1beta1/shared_types.go#L212

In this block there are only three condititons while @mlavacca  says that there are four reasons and the extra reason is "NoMatchingParent"

https://github.com/kubernetes-sigs/gateway-api/blob/7d408be7fc5389002858712fd7e7c0f14260274c/apis/v1beta1/shared_types.go#L280
Here in place of RefNoPermitted I should change it to accepted. and make changes in docs as well accordingly. right?

**Comment by mlavacca** [comment]
@Sajiyah-Salat The documentation related to the `Accepted` condition has been recently updated. Here is the updated one:

https://github.com/kubernetes-sigs/gateway-api/blob/5bc87cf04e28205d886476a5353315eaba5df659/apis/v1beta1/shared_types.go#L205-L221

As you can see, four different reasons can make the `Accepted` condition fail. The issue is about adding a fifth condition, similar to the `RefNotPermitted` one (which is related to the `ResolvedRefs` condition), that aims at stating that the route has not been accepted because a `ParentRef` references a `Gateway` in another namespace, but no `ReferenceGrant` allows such a reference.

**Comment by Sajiyah-Salat** [comment]
https://github.com/kubernetes-sigs/gateway-api/pull/1672 
Please review this pr and help me in adding a code line as I just added a comment now just to demonstrate what I have understood.Thank you.

**Comment by Sajiyah-Salat** [comment]
Hello please close this pr.

**Comment by mlavacca** [comment]
> Hello please close this issue.

👍 For the future, to make a merging PR automatically close the fixing issue, you need to write "Fixes #<issue_number>" in the PR description.

**Comment by mlavacca** [comment]
Closing as fixed by #1672

**Comment by mlavacca** [comment]
Closing as fixed by #1672

**Comment by shaneutt** [comment]
Re-opened briefly to properly link the PR, closing again.
