### ISSUE TITLE
conformance: create a testing plan for mesh implementations

### ISSUE THREAD

**Issue by keithmattix** [kubernetes-sigs/gateway-api#1686]
Before GAMMA is released, there needs to be, at the very least, a plan for conformance testing implementations. The level of detail for this deliverable should be something akin to [this](https://docs.google.com/document/d/11mK-Xxug4GYFrhXmt6KdS5ApB2gAM3mf28HHbvMwqHs/edit#heading=h.6tmk2axi2aet) testing plan doc for sig-multicluster.

**Comment by michaelbeaumont** [comment]
I'd be happy to work on the testing plane

**Comment by keithmattix** [comment]
Current draft can be found here: https://docs.google.com/document/d/1a-MY0rBwlXGSNM4V5U0it5uLxVOpi8gTbCBipKQVn9k/edit#heading=h.pw0d9uhzxq9k

**Comment by shaneutt** [comment]
@michaelbeaumont should we get that reformatted into GEP format soon? doesn't seem like any of it is all that controversial, but it's a bit hard for outsiders to find nested here in a google doc? :thinking:

**Comment by keithmattix** [comment]
Closed by #1813

**Comment by robscott** [comment]
Leaving this open until this GEP either graduates to standard or is removed from the API.

/kind gep
/reopen

**Comment by shaneutt** [comment]
Where are we at with this one, @michaelbeaumont ?

**Comment by mikemorris** [comment]
I believe the testing plan documented in https://github.com/kubernetes-sigs/gateway-api/pull/1813 was mostly? implemented in https://github.com/kubernetes-sigs/gateway-api/pull/1878, this GEP should probably be moved to Standard alongside the rest of GAMMA in https://github.com/kubernetes-sigs/gateway-api/pull/2873

**Comment by youngnick** [comment]
I was just reading the testing plan today (finally started working on Cilium's implementation of GAMMA), and we don't have everything covered yet. I think if we want to close this one out, we need a tracking issue for any remaining gaps.

**Comment by mikemorris** [comment]
/remove-lifecycle rotten

Still some outstanding work here to identify remaining conformance gaps per https://github.com/kubernetes-sigs/gateway-api/issues/1686#issuecomment-2106902042.

Refs #3566

**Comment by LiorLieberman** [comment]
and #3581

**Comment by mikemorris** [comment]
/remove-lifecycle stale

Not stale - not sure if remaining work actually needs a GEP, but @LiorLieberman is driving progress on closing mesh conformance gaps during the 1.4 release cycle.

**Comment by shaneutt** [comment]
Code freeze for `v1.4.0` is tomorrow, checking in: what remains?
