### ISSUE TITLE
Some conformance tests fail when implementation supports GRPCRoute

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#1691]
**What happened**:

Below tests

* https://github.com/kubernetes-sigs/gateway-api/blob/8694ac9531ffb96b6d99b7aae5e8beba2dccc0ad/conformance/tests/gateway-secret-invalid-reference-grant.go#L45

* https://github.com/kubernetes-sigs/gateway-api/blob/8694ac9531ffb96b6d99b7aae5e8beba2dccc0ad/conformance/tests/gateway-secret-reference-grant-specific.go#L45

* https://github.com/kubernetes-sigs/gateway-api/blob/8694ac9531ffb96b6d99b7aae5e8beba2dccc0ad/conformance/tests/gateway-invalid-tls-certificateref.go#L41

* https://github.com/kubernetes-sigs/gateway-api/blob/8694ac9531ffb96b6d99b7aae5e8beba2dccc0ad/conformance/tests/gateway-secret-reference-grant-all-in-namespace.go#L45

cross check the expected and actual ListenerStatus https://github.com/kubernetes-sigs/gateway-api/blob/8694ac9531ffb96b6d99b7aae5e8beba2dccc0ad/conformance/utils/kubernetes/helpers.go#L629
including the `SupportedKinds` field.

These tests have the `SupportedKinds` field set to `HTTPRoute` which fails for implementations which set the `SupportedKinds` field to `HTTPRoute` and `GRPCRoute`

**What you expected to happen**:
Tests shouldnt fail when implementations support `GRPCRoute` and highlight it using the `SupportedKinds` field.

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/envoyproxy/gateway/pull/805

**Anything else we need to know?**:
An option is to skip checking the `SupportedKinds` field when checking ListenerStatus

**Comment by shaneutt** [comment]
`v0.6.1` is expected to release next Tuesday, since we already have a PR up for this would definitely like to get this in there if we can.
