### ISSUE TITLE
`Programmed`  in the print column does not display

### ISSUE THREAD

**Issue by nak3** [kubernetes-sigs/gateway-api#1711]
**What happened**:

* https://github.com/kubernetes-sigs/gateway-api/pull/1602 introduced the `Programmed` for the print column, but it does not work as:

```
$ kubectl  get gateways.gateway.networking.k8s.io  -n istio-system
NAME                    CLASS   ADDRESS                                                PROGRAMMED   AGE
knative-gateway         istio   istio-ingressgateway.istio-system.svc.cluster.local                 143m
```

**What you expected to happen**:

* `PROGRAMMED` is trying to display the status of `status.listeners.attachedRoutes[*].conditions.programmed` but I wonder it is not possible.

**How to reproduce it (as minimally and precisely as possible)**:

* Just deploy Gateway API.

**Test env**
  * GATEWAY_API_VERSION="v0.6.0"
  * Istio 1.18-alpha.c197f978388c1d049584140df1944ca7d2f349e0

**Anything else we need to know?**:

* The root cause seems that level of `Programmed` is wrong.
* The current CRD has `.status.conditions[?(@.type=="Programmed")].status` but the `Programmed` field is under `status.listeners.attachedRoutes[*].conditions`.

<details>
<summary>out of gateway yaml with status to check for time saving </summary>

```
$ kubectl  get gateways.gateway.networking.k8s.io  -n istio-system  knative-gateway -o yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.networking.k8s.io/v1beta1","kind":"Gateway","metadata":{"annotations":{},"name":"knative-gateway","namespace":"istio-system"},"spec":{"addresses":[{"type":"Hostname","value":"istio-ingressgateway"}],"gatewayClassName":"istio","listeners":[{"allowedRoutes":{"namespaces":{"from":"All"}},"name":"default","port":80,"protocol":"HTTP"}]}}
  creationTimestamp: "2023-02-08T04:20:24Z"
  generation: 3
  name: knative-gateway
  namespace: istio-system
  resourceVersion: "34759"
  uid: ce45475c-448b-4b4e-b49d-7968fb5a10e1
spec:
  addresses:
  - type: Hostname
    value: istio-ingressgateway
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: default
    port: 80
    protocol: HTTP
status:
  addresses:
  - type: Hostname
    value: istio-ingressgateway.istio-system.svc.cluster.local
  conditions:
  - lastTransitionTime: "2023-02-08T06:40:08Z"
    message: Resources available
    observedGeneration: 3
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2023-02-08T06:40:08Z"
    message: Gateway valid, assigned to service(s) istio-ingressgateway.istio-system.svc.cluster.local:80
    observedGeneration: 3
    reason: ListenersValid
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-02-08T06:40:08Z"
    message: Resources available
    observedGeneration: 3
    reason: ResourcesAvailable
    status: "True"
    type: Scheduled
  listeners:
  - attachedRoutes: 1
    conditions:
    - lastTransitionTime: "2023-02-08T06:40:08Z"
      message: No errors found
      observedGeneration: 3
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2023-02-08T06:40:08Z"
      message: No errors found
      observedGeneration: 3
      reason: NoConflicts
      status: "False"
      type: Conflicted
    - lastTransitionTime: "2023-02-08T06:40:08Z"
      message: No errors found
      observedGeneration: 3
      reason: Attached
      status: "False"
      type: Detached
    - lastTransitionTime: "2023-02-08T06:40:08Z"
      message: No errors found
      observedGeneration: 3
      reason: Programmed
      status: "True"
      type: Programmed
    - lastTransitionTime: "2023-02-08T06:40:08Z"
      message: No errors found
      observedGeneration: 3
      reason: Ready
      status: "True"
      type: Ready
    - lastTransitionTime: "2023-02-08T06:40:08Z"
      message: No errors found
      observedGeneration: 3
      reason: ResolvedRefs
      status: "True"
      type: ResolvedRefs
    name: default
    supportedKinds:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
```

</details>

**Comment by skriss** [comment]
@nak3 `Programmed` is a new condition for Gateway a/o v0.6.0 -- see https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.GatewayConditionType and https://gateway-api.sigs.k8s.io/geps/gep-1364 for more background. Perhaps it's possible that the version of Istio you're using isn't populating this new Condition type yet?

**Comment by nak3** [comment]
Thank you! Yes, you are correct. Istio seems not implement the status yet.
Then, I thought `Programmed` should have the default status rather than empty - and it started the PR https://github.com/kubernetes-sigs/gateway-api/pull/1701 :sweat_smile: 

I'm closing here.

**Comment by nak3** [comment]
Oh, you are correct. It seems no conformance tests. Opened https://github.com/kubernetes-sigs/gateway-api/issues/1722

**Comment by howardjohn** [comment]
Istio does implement it under `status.listeners.attachedRoutes[*].conditions` as mentioned, are we actually supposed to put it under .status.conditions[?(@.type=="Programmed")].status as well?

**Comment by robscott** [comment]
>are we actually supposed to put it under .status.conditions[?(@.type=="Programmed")].status as well?

Yes, this is a condition that we expect to be set on Gateways and Listeners, clearly our conformance tests have a pretty big gap since they're missing this. Thanks to @nak3 for filing issues to track this!
