### ISSUE TITLE
Incorrect default port value check in HTTPRouteRedirectPath test

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#1721]
**What happened**:

Seeing `HTTPRouteRedirectPath` fail in Envoy Gateway. This test was added as part of https://github.com/kubernetes-sigs/gateway-api/pull/1611 which did the following
* always checked for the `Port` value in the redirect Location URL
* if the expected redirect port was unset in the test input, it would derive this value from the input request URL

The issue with this logic is that implementations are basing the data plane redirect logic solely on the values set in the RedirectFilter API https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPRequestRedirectFilter. 
Envoy Gateway computes the redirected Host based on the `hostname` and `port` defined in the API. If the `port` section is unspecified, it cannot make any assumptions and leaves it empty.  So this fails the test when the  API only defines the redirect [hostname](https://github.com/kubernetes-sigs/gateway-api/blob/e36b374652a6bcc56af5f9fa405c00e7bc478cc7/conformance/tests/httproute-redirect-path.yaml#L59) but passes successfully when the [redirect hostname and port](https://github.com/kubernetes-sigs/gateway-api/blob/e36b374652a6bcc56af5f9fa405c00e7bc478cc7/conformance/tests/httproute-redirect-port.yaml#L44) are specified

Here are the test error logs
```
=== CONT  TestGatewayAPIConformance/HTTPRouteRedirectPath/4_request_to_'/full-path-and-host'_should_receive_a_302
    http.go:186: Response expectation failed for request: {{http   127.0.0.1:80 /full-path-and-host  false false   }  HTTP GET map[X-Echo-Set-Header:[]] true [] [] }  not ready yet: expected redirected port to be 80, got  (after 28.075232404s)
    
Sending Request:
< GET /full-path-and-host HTTP/1.1
< Host: 127.0.0.1:80
< User-Agent: Go-http-client/1.1
< X-Echo-Set-Header: 
< Accept-Encoding: gzip
< 
< 

Received Response:
< HTTP/1.1 302 Found
< Date: Thu, 09 Feb 2023 03:51:28 GMT
< Location: http://example.org/replacement-full
< Server: envoy
< Content-Length: 0
< 
```    

Downstream GH Issue : https://github.com/envoyproxy/gateway/issues/993

**Comment by arkodg** [comment]
also applies to `HTTPRouteRedirectHostAndStatus` and `HTTPRouteRedirectScheme` which add `hostname` in redirect filter API

**Comment by arkodg** [comment]
Nvm I think it's working as expected,  here's the line from the spec -  `When empty, port (if specified) of the request is used.`

**Comment by muyuan0** [comment]
According to the https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRequestRedirectFilter

> In all cases, when the protocol is http and the port is port 80, then the port must be omitted. Similarly, when the protocol is https and the port is port 443, then the port must also be omitted.

We should still leave the port empty if it is the well-known one, which is the case of this issue.

Maybe we can reopen this issue and update https://github.com/kubernetes-sigs/gateway-api/blob/653565d4c28bc4728a833709273f5c5911511863/conformance/utils/http/http.go#L291-L304?

**Comment by arkodg** [comment]
hey @muyuan0 https://github.com/kubernetes-sigs/gateway-api/issues/1805 has been raised to track the changes needed to conformance tests to address the newer clarifications to the API
