### ISSUE TITLE
Configure Timeouts in Gateway API

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#1741]
Here are some timeouts that would be benefit users 

HTTP
* Request Timeout
  * Envoy - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-timeout
  * NGINX - https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_send_timeout

* Idle Timeout
  * NGINX - 
  * Envoy - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-httpprotocoloptions-idle-timeout
  
TCP
* Connect Timeout
  * NGINX - https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_connect_timeout
  * Envoy - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-connect-timeout

* Keep Alive
  * Upstream
    * NGINX - https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive_requests
    * Envoy - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#config-core-v3-tcpkeepalive
  * Downstream
    * NGINX - TODO
    * Envoy - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/socket_option.proto#config-core-v3-socketoption

Relates to https://github.com/kubernetes-sigs/gateway-api/discussions/1715

**Comment by Xunzhuo** [comment]
This is definitely needed, thanks for raising it! 
I would like to assign to work on this after finishing some assigned issues of mine.

**Comment by youngnick** [comment]
I think that this one will probably be addressed by #1742, sorry @Xunzhuo, should have linked it earlier.

**Comment by Xunzhuo** [comment]
That is fine @youngnick, happy to see it is already started, I will help review everything in GWAPI, ping me if you forks need more reviews : )

**Comment by shaneutt** [comment]
I linked this over in #1742 as reference material (@arkodg's layout of known timeouts, thanks Arko!) but since we now have a duplicate and #1742 already has a merged PR with a GEP referring to 1742, I'm going to close this one as a duplicate as it seems we can simply continue work there. Let me know if we need to re-open this however, if I've missed something! :vulcan_salute:
