### ISSUE TITLE
Add support for Load Balancing Policy

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#1778]
**What would you like to be added**:
The ability for the user to specify the load balancing policy/algorithms used when load balancing requests from the gateway to the upstream / backend.

**Why this is needed**:
To improve performance/throughput in production.

Examples in Data Plane
* Envoy - https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers
* NGINX - https://nginx.org/en/docs/http/load_balancing.html

Examples in Control Plane
* Contour - https://projectcontour.io/docs/v1.10.0/config/request-routing/#load-balancing-strategy
* Istio - https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings

**Comment by shaneutt** [comment]
For posterity, this has been brought up a few times. Here's some of the prior art:

#1074 #992 #912 

Historically we have landed on policy attachment being the suggested method to handle this, however I'm personally OK with seeing where this goes. @youngnick and @robscott should weigh in.

**Comment by arkodg** [comment]
thanks @shaneutt for surfacing all the prior issues ! would ideally like to see this as a native noun rather than a policy  attachment

**Comment by shaneutt** [comment]
I'm with you that this would be good. To make it happen we're going to need someone who's dedicated to championing it, teasing out all the issues and pushing it forward as a GEP. I think getting this right across multiple implementations is going to be a little tricky.

**Comment by arkodg** [comment]
thanks, I see how this feature can be related to the Backend Properties proposal outlined in https://github.com/kubernetes-sigs/gateway-api/pull/1333/files .

From an API perspective, the `HTTPBackendRef` https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPBackendRef could be a good place to introduce the notion of a backend filter/property to support a load balancing policy.

**Comment by shaneutt** [comment]
We don't consider this a blocker for `v1.0.0`/GA because we have every expectation that it can be done post-GA. We do want this feature, and if any community member is interested in taking it on please do.

/help

**Comment by shaneutt** [comment]
We want this feature, but we consider it low priority until `v1.0.0`/GA is complete and don't believe we will have bandwidth for it until then.
