### ISSUE TITLE
Initial conformance tests for UDPRoute

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#1792]
**What would you like to be added**:

Initial conformance tests for `UDPRoute` need to be added.

**Why this is needed**:

In order to mature `UDPRoute` to beta and eventually GA, we'll need conformance tests and implementations [reporting](#1709) their usage of them.

**Comment by cnvergence** [comment]
I have added the initial UDPRoute test in https://github.com/kubernetes-sigs/gateway-api/pull/2661, having it tested in two implementations currently: Envoy Gateway and Kong Ingress Controller.
Would like to continue the work on adding more scenarios and verifying the support on more implementations.
