### ISSUE TITLE
Port Redirect Semantics for HTTP and HTTPS Are Confusing

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1806]
**What happened**:
It's not clear to me if the following portion of the spec is targeted at implementers or users. I initially [commented on the PR](https://github.com/kubernetes-sigs/gateway-api/pull/1740#pullrequestreview-1335290763), but creating an issue so we don't lose track of it.
https://github.com/kubernetes-sigs/gateway-api/blob/227de0756d763b320cb4dcfa16a668867e326554/apis/v1beta1/httproute_types.go#L905-L908

**What you expected to happen**:
Ideally the spec would also clarify the following:

* Are users, implementers, or both supposed to leave Port unspecified in the Redirect Filter?
* What protocol are we looking at to determine HTTP or HTTPS? Is this a runtime decision or is it something we determine by looking at either the Listener protocol or the Redirect filter protocol?

**Comment by youngnick** [comment]
Okay, fair.

I guess it should be something like 
```
When empty, the Gateway Listener port is used.
In all cases, when implementations are generating a redirect `Location` header,
a Location header that will use HTTP (whether that is determined via the Listener protocol
or the Scheme field) _and_ use port 80 must not include the port number in the `Location` header.
Similarly, when an implementation renders a `Location` header that uses HTTPS
(regardless of how the protocol is determined) _and_ uses port 443,
it must not include the port number in the `Location` header.
```

**Comment by spencerhance** [comment]
I'm happy to make this update

**Comment by shaneutt** [comment]
Thank you @spencerhance!

/assign @spencerhance 

Let us know if you run into any trouble and need any help from us!
