### ISSUE TITLE
Clarify GatewayClass Support Requirements

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1822]
**What would you like to be added**:
We need to clearly state that implementations MUST populate status on all GatewayClasses in a cluster that specify their controller name. This does not necessary require implementations to implement the config specified by arbitrary GatewayClasses, just to at least communicate the status via GatewayClass.

**Why this is needed**:
This was initially surfaced in https://github.com/kubernetes-sigs/gateway-api/pull/1781. We need to clarify our expected behavior here in the API Spec before adding a required conformance test.

**Comment by youngnick** [comment]
I have been intending to address this as part of #1650, but that's been getting beaten out by other stuff for a while now. I'll see if I can bump it up.
