### ISSUE TITLE
Consistent status reasons

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#1832]
GatewayConditionReady is extended. It has a set of reasons:
	// * "ListenersNotValid"
	// * "ListenersNotReady"
	// * "AddressNotAssigned"

ListenerConditionProgrammed is core, but it only has a few reasons:
	// * "Invalid"
	// * "Pending"

Given these represent almost the same thing, it seems like these should be the same set, or GatewayConditionReady should be a superset 

similar concern on Listener status

**Comment by robscott** [comment]
Good catch, agree that these should all be present for both conditions.

/help

**Comment by howardjohn** [comment]
Also I think the spec is pretty clear but while I am here to double check... if I cannot say "traffic is ready to flow immediately" I should just not set Ready at all, right? And only use Programmed?

**Comment by arkodg** [comment]
> Also I think the spec is pretty clear but while I am here to double check... if I cannot say "traffic is ready to flow immediately" I should just not set Ready at all, right? And only use Programmed?

+1 to this, helps users understand the difference between CP programmed and DP ready
cc @dprotaso

**Comment by howardjohn** [comment]
So my interpretation means:

* Accepted: I got far enough to start sending *some* data to the data plane
* Programmed: I got far enough to start send *all* the data to the data plane
* Ready (optional): I sent *all* the data to the data plane *and* it fully processed it and is ready to go

**Comment by robscott** [comment]
>Also I think the spec is pretty clear but while I am here to double check... if I cannot say "traffic is ready to flow immediately" I should just not set Ready at all, right? And only use Programmed?

Yep, the requirements for setting ready have become pretty strict:

https://github.com/kubernetes-sigs/gateway-api/blob/1c4ae619312754c52e1ff130439caed87132dc54/apis/v1beta1/gateway_types.go#L609-L611

If there were some kind of delay after which you could guarantee readiness that may also be a good reason to set "Ready", but not sure if that's a good idea.

**Comment by robscott** [comment]
@gauravkghildiyal has volunteered to work on this one

**Comment by arkodg** [comment]
would be good to add conformance tests to make sure if Route reports status as `Ready`, all requests through it must succeed

**Comment by robscott** [comment]
@arkodg completely agree, mind creating an issue to track that?

**Comment by gauravkghildiyal** [comment]
@howardjohn The issue says that "**Listener**ConditionProgrammed" should be subset of "**Gateway**ConditionReady". 

Is that perhaps a typo and you meant to say **Gateway**ConditionProgrammed" should be subset of "**Gateway**ConditionReady"?

(I'm new to this and hence cannot confidently differentiate a typo from an actual ask)

**Comment by youngnick** [comment]
@howardjohn I agree that Programmed should have a `NotAccepted` Reason, which says "Can't be Programmed because it wasn't Accepted".

**Comment by howardjohn** [comment]
> The issue says that "**Listener**ConditionProgrammed" should be subset of "**Gateway**ConditionReady".

That was a typo, good catch

**Comment by dprotaso** [comment]
Would we consider `GatewayConditionReady` a top-level terminal condition? 

Meaning
- it requires all the child conditions (Accepted, Programmed) to be True before it can be True
- If any of the child conditions are `False` then it should be `False`?

Also it would be good for implementations to hint that they don't support `GatewayConditionReady`  by setting the `Status` to `Unknown` and some hard coded `Reason` - ie. `NotSupported`

**Comment by howardjohn** [comment]
+1 to Unknown and NotSupported

**Comment by youngnick** [comment]
+1 to `Unknown` and `NotSupported` being _available_.

But I don't think they should be _required_. The absence of a Condition means that it should be read as `Unknown` anyway, so it shouldn't be _necessary_ for implementations to add it if they don't want to support it.

**Comment by gauravkghildiyal** [comment]
Alright, collating all the information here, does the following look agreeable? (Adding all related condition/reasons here for a holistic view)

(Also, lets take this step by step and tackle the issue https://github.com/kubernetes-sigs/gateway-api/issues/1877 regarding "removing GatewayConditionReady completely" as a separate item)

<table>
    <tr>
        <th>Resource</th>
        <th>Condition name</th>
        <th>Value</th>
        <th>Reason</th>
        <th>Comment</th>
    </tr>
    <tr>
        <td rowspan="15">Gateway condition</td>
        <td rowspan="5">Accepted</td>
        <td>TRUE</td>
        <td>Accepted</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>NotReconciled</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>NoResources</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>ListenersNotValid</td>
        <td>Moved from Ready. <br />This should be set when one of the Listnerers has Accepted=False</td>
    </tr>
    <tr>
        <td>UNKNOWN</td>
        <td>Pending</td>
        <td></td>
    </tr>
    <tr>
        <td rowspan="5">Programmed</td>
        <td>TRUE</td>
        <td>Programmed</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>Invalid</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>NotAccepted</td>
        <td>Newly Added. <br />Question: Is there another reason to set (Programmed, FALSE, Invalid) besides Accepted=False? If not, then this might be redundant</td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>Pending</td>
        <td></td>
    </tr>
    <tr>
        <td>UNKNOWN</td>
        <td>Pending</td>
        <td></td>
    </tr>
    <tr>
        <td rowspan="5">Ready (Extended)</td>
        <td>TRUE</td>
        <td>Ready</td>
        <td></td>
    </tr>
    <tr>
        <td><del>FALSE</del></td>
        <td><del>ListenersNotValid</del></td>
        <td>Deleted/Deprecated<br />Moving this to Accepted since it represents that some listener is &quot;syntactically or semantically&quot; invaid.</td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>ListenersNotReady</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>AddressNotAssigned</td>
        <td></td>
    </tr>
    <tr>
        <td>UNKNOWN</td>
        <td>ConditionNotSupported</td>
        <td>Newly added. <br />Ready condition already has Extended support, meaning that it is not necessary for implementations to explicitly set Ready to Unknown with this reason</td>
    </tr>
    <tr>
        <td rowspan="14">Listener Condition</td>
        <td rowspan="5">Accepted</td>
        <td>TRUE</td>
        <td>Accepted</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>PortUnavailable</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>UnsupportedProtocol</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>UnsupportedAddress</td>
        <td></td>
    </tr>
    <tr>
        <td>UNKNOWN</td>
        <td>Pending</td>
        <td></td>
    </tr>
    <tr>
        <td rowspan="5">Programmed</td>
        <td>TRUE</td>
        <td>Programmed</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>Invalid</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>NotAccepted</td>
        <td>Newly Added. <br />Question: Is there another reason to set (Programmed, FALSE, Invalid) besides Accepted=False? If not, then this might be redundant</td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>Pending</td>
        <td></td>
    </tr>
    <tr>
        <td>UNKNOWN</td>
        <td>Pending</td>
        <td></td>
    </tr>
    <tr>
        <td rowspan="4">Ready (Extended)</td>
        <td>TRUE</td>
        <td>Ready</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>Invalid</td>
        <td></td>
    </tr>
    <tr>
        <td>FALSE</td>
        <td>Pending</td>
        <td></td>
    </tr>
    <tr>
        <td>UNKNOWN</td>
        <td>Pending</td>
        <td></td>
    </tr>
</table>

**Comment by youngnick** [comment]
Wow @gauravkghildiyal, thanks for that table, that's excellent.

Here's _my_ answers to your questions, but I'm interested to hear if I'm the outlier here:
- For Gateway `ListenersNotValid`, if we're having _one_ Listener being not accepted mean the _entire Gateway_ is not accepted, that means that we can't do partial Gateway validity. I'd prefer `ListenersNotValid` to be a reason that's allowable with _either_ `Accepted` as `true` or `false` - in either case, that Reason means that one or more listeners are invalid, but if `Accepted` is `true`, that means _at least one_ Listener _is_ valid. `Accepted` being `false` means that there are _no_ valid Listeners. This is analogous to how Route partial validity works as well.
- I agree that `NotAccepted` seems like a _better_ description for the same state as `Invalid` at first glance, but I think we should leave `Invalid` in there until we're sure there are no other use cases for it. We should enforce `NotAccepted` for both Listener and Gateway Programmed Conditions though, I think that it should probably always be added.

**Comment by howardjohn** [comment]
Here is how I view things:

GatewayAccepted: "The _Gateway_ is accepted by the controller"
Conditions:
* Accepted: All Good
* ListenersNotValid: one or more listeners are invalid. **Accepted can still be True if at least some configuration was programmed**
* Pending: Still waiting to be reconciled.
Removed: NoResources

GatewayProgrammed: "The _Gateway_ is ready to go, (but maybe not immediately; eventual consistency allowed). This only applies to the entire GW; a new listener would not make this flip to False for example"
Conditions:
* Programmed: All good
* Invalid: Gateway was no accepted, so we cannot be programmed of course
* AddressNotAssigned (added): Could not allocate addresses
* NoResources (added): Could not allocate non-address resources

GatewayReady: removed

---

ListenerAccepted: "The listener is accepted and valid"
Conditions:
* Accepted: all good
* PortUnavailable
* UnsupportedProtocol
Removed: UnsupportedAddress (listener does not have an Address... this is handled by AddressNotAssigned in Gateway)

ListenerResolvedRefs: "all references resolved
No changes

ListenerProgrammed: "The _Listener_ is ready to go, (but maybe not immediately; eventual consistency allowed)"
Conditions:
* Programmed: All god
* Invalid: set when Accepted=False
* Pending: waiting

ListenerReady: removed

---

Overall changes:
* Remove Ready from Listener and Gateway
* Remove UnsupportedAddress from ListenerAccepted
* Add AddressNotAssigned and NoResources to Programmed
* Remove NoResources from Accepted
