### ISSUE TITLE
conformance: new test checking a standard condition on a Route that cannot route due to lacking `ReferenceGrant`

### ISSUE THREAD

**Issue by pmalek** [kubernetes-sigs/gateway-api#1838]
**What would you like to be added**:

When an `HTTPRoute` (or route in general but only HTTPRoute is supported now, right?) lacks a `ReferenceGrant` in order to route traffic to designated `backendRef`s the status condition(s) should reflect that in a standard way. 

For instance: a condition with `type: ResolvedRefs`, `reason: RefNotPermitted` and `status` set to `"False"`.

**Why this is needed**:

To standardize route's statuses when rejected due to missing `ReferenceGrant`.

https://gateway-api.sigs.k8s.io/api-types/referencegrant/ doesn't mention this. On purpose?

**Comment by robscott** [comment]
Unless I'm misunderstanding this issue, I think this may already be covered here: https://github.com/kubernetes-sigs/gateway-api/blob/d5d4e6f810ada055690351dc2d643926f13872c9/conformance/tests/httproute-partially-invalid-via-reference-grant.go#L47-L56

We could probably improve documentation stating that this is a requirement, but I think this is already covered in terms of conformance tests.

**Comment by pmalek** [comment]
🤦 Don't know how I've missed that.

One potential improvement for this though (which is coming from our implementation's lessons learnt) is that this might get extended to check that this `RouteConditionResolvedRefs` condition with `RouteReasonRefNotPermitted` reason is correctly set after an existing `ReferenceGrant` gets deleted.

As for the documentation itself: yes, I'd find some mention of this useful (and perhaps I wouldn't have created this in first place :) )

**Comment by shaneutt** [comment]
I think that improvement sounds good. As for the documentation, seems like we could put that on the the relevant conditions?

**Comment by pmalek** [comment]
Created #1853 to address the conformance test aspect of this issue.

If I read this right, the route without a relevant ReferenceGrant should return a 503 right? That's what #1853 is trying to enforce as of now. If that's not the case feel free to correct me.
