### ISSUE TITLE
Clarify Conformance Expectations for Gateway Ports and Listeners

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1842]
**What would you like to be added**:
As described in https://github.com/kubernetes-sigs/gateway-api/pull/1827#issuecomment-1474273702, it would be helpful to describe what we expect from implementations in terms of supported combinations of ports, protocols, and listeners. It seems like the minimum bar is that L7 implementations can handle one HTTP listener on 80 and one HTTPS listener on 443. 

What is less clear is what happens beyond that:

1) Is support for additional ports considered "Extended" conformance?
2) Is support for multiple listeners on the same port considered "Extended" as well?
3) What about non-standard combinations like "HTTPS" on 80 or "HTTP" on 443?

**Why this is needed**:
There's some variation among implementations in terms of what's supported today, it would be good to ensure expectations are clearly stated for conformance.

**Comment by dprotaso** [comment]
> Is support for additional ports considered "Extended" conformance?

It would be nice if this was "Core" and didn't require unique manual configuration of each implementation to support.

> Is support for multiple listeners on the same port considered "Extended" as well?

A use case here is how easy it is to manage multiple certificates on a gateway. Adding multiple listeners with the same port but different `certificateRefs` could be a valid option.

An alternative that scales better in K8s clusters would be  https://github.com/kubernetes-sigs/gateway-api/issues/1713

> What about non-standard combinations like "HTTPS" on 80 or "HTTP" on 443?

Is there a list of standard combinations?

**Comment by dprotaso** [comment]
I created a PR that includes a conformance tests for dynamic listener ports

**Comment by dprotaso** [comment]
> Is support for multiple listeners on the same port considered "Extended" as well?

Note: the TLS examples on the website here show multiple listeners using the same port
https://gateway-api.sigs.k8s.io/guides/tls/#wildcard-tls-listeners

**Comment by robscott** [comment]
>sharing a Port and Protocol is okay if the TLS details are distinct. I don't know if this is the common view however.

@youngnick To clarify, are you including "Hostname" in the general category of "TLS Details"? So far we've said that the combination of "Hostname", "Protocol", and "Port" must be unique for each listener. I think that would cover your use case if I'm understanding it correctly.

**Comment by dprotaso** [comment]
FYI with #2065 merging we now have

https://github.com/kubernetes-sigs/gateway-api/blob/7c7c0b3158f1ff1d8679ad463edc97dc23df5080/apis/v1beta1/gateway_types.go#L72-L79

**Comment by robscott** [comment]
I think we can close this now that #2065 has merged. Feel free to reopen if I missed anything.
