### ISSUE TITLE
Docs: Frequently Asked Questions have become stale

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1862]
**What happened**:
The https://gateway-api.sigs.k8s.io/faq/ page has grown stale and in some cases conflicts with other more recently updated portions of our documentation.

**What you expected to happen**:

The following questions should all likely have less detailed answers on this page and instead link out to more frequently updated sections:

* **Q: What are the differences between Ingress and Gateway API?**
  Should include a link to https://gateway-api.sigs.k8s.io/guides/migrating-from-ingress/
* **Q: How can I expose custom capabilities through Gateway API?**
  Should be shortened significantly and include a link to https://gateway-api.sigs.k8s.io/references/policy-attachment/
* **Q: How should I think about alpha API versions?**
  Should include a link to https://gateway-api.sigs.k8s.io/concepts/versioning/
* **Q: Which Kubernetes versions are supported?**
  Should remove specific versions and instead link to https://gateway-api.sigs.k8s.io/concepts/versioning/#supported-versions

**Comment by spencerhance** [comment]
I can make this change
