### ISSUE TITLE
GEP: Provide a standard way to configure per-Gateway Infrastructure

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#1867]
**What would you like to be added**: a standard way to configure per-Gateway Infrastructure

**Why this is needed**: Currently this is only configurable on a Cluster scoped resource, which has a variety of issues

GEP: https://github.com/kubernetes-sigs/gateway-api/pull/1868

**Comment by keithmattix** [comment]
- Survey implementations to ensure we have enough (3+) and/or encourage more implementations to support this feature.
- Write documentation
- Updates to GEP, docs, and API types to bump status to standard.

**Comment by keithmattix** [comment]
Implementations: Istio, Envoy Gateway,? Is anyone aware of more?

**Comment by youngnick** [comment]
Cilium also supports labels and annotations in infrastructure.

**Comment by keithmattix** [comment]
I think the only tasks left before this gets closed out is to bump some API types

**Comment by youngnick** [comment]
Yes, we will need to remove the experimental tags from the `infrastructure` field and the child `labels` and `annotations` fields, and check that we document the required feature name in those fields. Those actions will move this field to GA in 1.2.
