### ISSUE TITLE
Remove GatewayConditionReady

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#1877]
Related to https://github.com/kubernetes-sigs/gateway-api/issues/1832 but split out to be more clear

`GatewayConditionReady` 

> 	// Ready is an optional Condition that has Extended support. When it's set,
> 	// the condition indicates whether the Gateway has been completely configured
> 	// and traffic is ready to flow through the data plane immediately.

It was changed in https://gateway-api.sigs.k8s.io/geps/gep-1364/#ready, when we added a new Programmed condition and moved Ready to extended.

`GatewayConditionProgrammed` is a weaker form of `Ready`, indicating we have configured the data plane, but it may be eventually consistent.

The problem, IMO, is it is not useful to know a _Gateway_ is Ready. Gateway's do not provide functionality on their own; they are an attachment point for functionality (Route).

The typical use case for Ready is something like knative, where we `kubectl wait --for=ready` and then start sending traffic. But that cannot be used here, because all we know is the "Gateway" is ready - its not even clear what this means without routes.

We cannot change the spec to mean "Gateway and all attached routes are ready", as there is no way to verify this is up-to-date due to the cross-object references (typically this is solved via observedGeneration, but that applies only to single route).

As a result, I propose we remove the Ready condition entirely.

Alternative: we instead move Ready to a route condition

cc @youngnick @dprotaso @frankbu

**Comment by dprotaso** [comment]
> . Gateway's do not provide functionality on their own

the top level `Ready` could be a summation of all the `ListenerStatus` - `Ready`

> Alternative: we instead move Ready to a route condition

+100 I think HTTPRoute should have a `Ready` condition.

**Comment by howardjohn** [comment]
> the top level Ready could be a summation of all the ListenerStatus - Ready

So:

Programmed = the Gateway itself is valid
Ready = the Gateway and all Listeners are valid

?

**Comment by youngnick** [comment]
I agree that if `Ready` exists at the Gateway top-level, it should be a summary that says "everything on this Gateway is correct, configured, and routable".

All the Route objects also having `Ready` seems like a good idea, although I still think that actually _populating_ `Ready` correctly is much more difficult than it seems (at least for Envoy dataplanes).

**Comment by dprotaso** [comment]
> Programmed = the Gateway itself is valid
> Ready = the Gateway and all Listeners are valid

I would expect Gateway/Ready to become true after all the Listeners/Ready become true. 'valid' in my mind here would imply `Accepted=True` on admission. Unless you meant something different.

> Ready is also impossible for most implementations to implement, so it will often be missing

Curious - are you able to support ListenerReady ?

> Ready is not useful at a Gateway, only at a Route

Given that we can add listeners dynamically I think having a top-level `Ready` being a summation would be a great UX. Like you pointed out users could - `kubectl wait --for=ready`


> This leads to a very confusing user experience where folks 

Don't forgot controllers programming the API. I think `Ready` can also be used a signal for terminal failures that happen after `Programmed=True`. ie. there might some some validation that can only occur when realizing the config changes really late (ie. waiting on an LB IP address)

I do agree that having Ready on the Route provides more value. I'll drive that.

 Few questions
- Looking at the godoc/api types I don't see a `Programmed` condition on Route - is that omitted for a reason?
- If xRoute/Ready isn't supported for Knative any signal of progress would provide value 
  - ie. I would look for the Listener/Gateway to be Ready prior to falling back onto probing
     - (related) should we have a ListenerReady condition on HTTPRoute?

**Comment by howardjohn** [comment]
> Don't forgot controllers programming the API. I think Ready can also be used a signal for terminal failures that happen after Programmed=True. ie. there might some some validation that can only occur when realizing the config changes really late (ie. waiting on an LB IP address)

That seems like something that should be reported in Programmed=True?

(I am literally currently implementing exactly that in Istio, so please tell me if I shouldn't :slightly_smiling_face: )

**Comment by keithmattix** [comment]
I generally agree with @howardjohn here from a UX perspective. In Kubernetes world `Ready` is an assurance that nothing is wrong and I can reasonably expect to use the resource in question. The concept of a `Ready` condition being extended invites a lot of questions as users are wondering why their implementations aren't "ready"

**Comment by rainest** [comment]
The phrasing in the OP/current docs:

> Ready is an optional Condition that has Extended support. When it's set, the condition indicates whether the Gateway has been completely configured and traffic is ready to flow through the data plane immediately.

seems wrong, but I think there's a meaningful distinction.

I would expect `Programmed` to mean that a controller has seen a Gateway, recognizes it as something it should manage, and created something (e.g. a Deployment or something running outside kubelets, like an AWS ALB managed via a cloud provider). That's the eventually consistent stage where the controller has created something that'll hopefully reach a state where the controller can start pushing route configuration.

`Programmed` may fail if the controller sees a Gateway that it _cannot_ satisfy for some reason, e.g. if your implementation only supports HTTP proxying and you don't support plain TCP proxying, you'd fail `Programmed` for a Gateway that requests a TCP listener.

`Ready` then means the thing the controller configured reached a state where the controller can start pushing routes. If you created a Deployment, and it has no ready replicas, your controller presumably _can't_ push routes.

**Comment by howardjohn** [comment]
> Programmed may fail if the controller sees a Gateway that it cannot satisfy for some reason, e.g. if your implementation only supports HTTP proxying and you don't support plain TCP proxying, you'd fail Programmed for a Gateway that requests a TCP listener.

That sounds more like Accepted:

```
	// This condition is true when the controller managing the Gateway is
	// syntactically and semantically valid enough to produce some configuration
	// in the underlying data plane. This does not indicate whether or not the
	// configuration has been propagated to the data plane.
```

IMO we should actually remove Programmed, but make Ready drop the problematic _"immediately"_. I think the wording is a bit vague but with context from the original discussion that "immediate" was intended to be a very important word that explicitly meant that there was 100% certainty that all the config was actuated (no eventual consistency). I agree with your definition of Ready.

**Comment by howardjohn** [comment]
I opened https://github.com/kubernetes-sigs/gateway-api/pull/1886 to make this a bit more concrete and since there seemed to be directional agreement on this.

**Comment by youngnick** [comment]
What we found is that the expectation that people have about `Ready` is that it means "Ready, _right now_" - that's what we've tried to make clear with the language we're using.

`Programmed` is what we settled on as "as close as we can get to Ready without the guarantee". What you're thinking of as `Programmed` is more like `Accepted`. `Programmed` is referring to the _data plane_, not the _control plane_ - the data plane has been programmed with the config, and it will be ready soon.

**Comment by shaneutt** [comment]
After thinking this over last night and reading over https://github.com/kubernetes-sigs/gateway-api/pull/1886 I believe I understand the impetus for change, but my biggest question here is whether this is only bubbling up because of confusion with older CRDs which still have `Ready` in the short view (and in newer controllers, now never get populated)?

It's a little difficult for me to see how `Ready` is becoming a problem because if you don't implement it, and don't try to, it should be somewhat _invisible_ to end users no?
