### ISSUE TITLE
Clarify ListenerConditionAccepted specification

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes-sigs/gateway-api#1896]
**What would you like to be added**:

Clarify the spec for the condition.l

**Why this is needed**:

I'm somewhat confused as to what this is instructing implementer to do.  This matches the condition on the gateway, but the spec indicates that it should only be set if the controller is unable to configure the listener which seems odd to have a (type=Accepted, status=True, reason=Accepted) combination.

https://github.com/kubernetes-sigs/gateway-api/blob/bdbd3644ee7f2f478f73049314df0a1f02b3275f/apis/v1beta1/gateway_types.go#L730

**Comment by youngnick** [comment]
Thanks for this @briantkennedy. This description is a holdover from when this Condition was called `Scheduled`, before we standardized on `Accepted` across the API.

It should probably say something more like:
```go
	// This condition indicates that the listener is syntactically and
        // semantically valid, and that all features used in the listener's spec
        // are supported.
	//
        // In general, a Listener will be marked as Accepted when the supplied
        // configuration will generate at least some data plane configuration.
        //
        // For example, a Listener with an unsupported protocol will never generate
        // any data plane config, and so will have Accepted set to `false.`
        // Conversely, a Listener that does not have any Routes will be able to generate
        // data plane config, and so will have Accepted set to `true`.
```

I'll mark this as help wanted because it seems like a straightforward fix.

/help-wanted
