### ISSUE TITLE
conformance: tests should run in a stable order

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#1904]
**What happened**:

Run tests, see
```
    --- FAIL: TestGatewayConformance/HTTPRouteRedirectHostAndStatus (1.02s)
        --- PASS: TestGatewayConformance/HTTPRouteRedirectHostAndStatus/1_request_to_'/status-code-301'_should_receive_a_301 (0.01s)
        --- FAIL: TestGatewayConformance/HTTPRouteRedirectHostAndStatus/0_request_to_'/hostname-redirect'_should_receive_a_302 (30.00s)
        --- FAIL: TestGatewayConformance/HTTPRouteRedirectHostAndStatus/2_request_to_'/host-and-status'_should_receive_a_301 (30.00s)
```

**What you expected to happen**:

Tests run in stable order (0->1->2)

**How to reproduce it (as minimally and precisely as possible)**:

run any test with multiple subtest

**Anything else we need to know?**:

This is caused by go random map iteration order.

Its helpful for consistency in debugging to run in a stable order. Not a huge deal though

**Comment by shaneutt** [comment]
I was also thinking about this recently, this sounds reasonable to me. Not a high priority in the face of getting `v1.0.0` out the door perhaps, but if someone has the time and feels strongly about knocking it out please feel free:

/help

It's not quite a `good-first-issue` (because it requires a conformant or near-conformant implementation ready to test with) but I expect this wont take much code if someone is looking for something on the lighter side.

**Comment by dprotaso** [comment]
The subtest was explicitly marked as parallel - it seems the ordering here isn't an issue 

https://github.com/kubernetes-sigs/gateway-api/blob/26ce3a32c8c7b27a918961cf208df07dbda08e25/conformance/tests/httproute-redirect-host-and-status.go#L89

Note: this would conflict with https://github.com/kubernetes-sigs/gateway-api/issues/1898


Generally I would assume if a test needs a stable order for subtests it shouldn't call `t.Parallel()`

**Comment by howardjohn** [comment]
Ah... Misunderstood.

I think 1898 is about parent tests in parallel though, not subtests, but definitely related.

**Comment by gauravkghildiyal** [comment]
Not looking into this at the moment. Up for grabs if anyone wants to take a look in the mean time.

/unassign
/help

**Comment by aojea** [comment]
I do not think that test should run in stable order as that can lead to "bad habits" or to make assumption on the tests, each test should be hermetic and not depend on other tests, running randomly helps to avoid this

**Comment by shaneutt** [comment]
While grooming we saw that this one was open for a long period of time without anyone with a strong use case to champion it. We're going to close this as we don't expect anyone's ready to drive it forward, but if you still want this feature and have a strong use case we will be happy to reconsider this and re-open.
