### ISSUE TITLE
Spec unclear for scheme redirects in HTTPRoute

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#1909]
**What happened**:
As feedback in https://github.com/kubernetes-sigs/gateway-api/pull/1908, @howardjohn pointed out that it's currently unclear how scheme and port interact in the redirect filter. Two examples below:

1. If an incoming request is to http://example.com (on port 80), and the redirect simply requests "HTTPS" scheme without specifying port, what should the implementation do?

A) https://example.com
B) https://example.com:80

2. Similarly if an incoming request is to http://example.com:80, and the redirect simply requests "HTTPS" scheme without specifying port, what should the implementation do?

A) https://example.com
B) https://example.com:80

3. Finally, if an incoming request is to http://example.com:8080, and the redirect simply requests "HTTPS" scheme without specifying port, what should the implementation do?

A) https://example.com
B) https://example.com:8080

**What you expected to happen**:
The spec should tell implementations how to treat these scenarios.

**Comment by gauravkghildiyal** [comment]
I've already been involved with this so lets take it all the way.

/assign

**Comment by gauravkghildiyal** [comment]
I've put my thoughts in [this](https://docs.google.com/document/d/1fx8kuWh2bmBge9IRGn7NlhGqTP0Kj21Cz5RZyUW6428) doc. Will try to bring this up in some Gateway API meeting -- if time permits :)
