### ISSUE TITLE
The `AttachedRoutes` field does not reflect the expected route status

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/gateway-api#1913]
### Problem statement

The Gateway `AttachedRoutes` field states:

https://github.com/kubernetes-sigs/gateway-api/blob/26ce3a32c8c7b27a918961cf208df07dbda08e25/apis/v1beta1/gateway_types.go#L677-L679

But the *Route `Attached` condition does not exist (the `Detached` condition with reason `Attached` was used in the past, and it is now deprecated). The `Accepted` condition is meant to be used that a route can be considered accepted by (attached to) a Gateway.

### Proposed solution

We could rename the `AttachedRoutes` field of the Gateway status to `AcceptedRoutes` to reflect the route status condition to check in order to increment (or decrement) the number of routes considered accepted.

**Comment by robscott** [comment]
Unfortunately renaming a field would require a new API version and likely also a conversion webhook, both things we're trying to avoid. I think the concept of "AttachedRoutes" still makes sense, we probably just want to update the spec to say that it represents the "number of Accepted Routes that are attached to this Listener".

**Comment by shaneutt** [comment]
Because changing the API would be such a massive undertaking at this point let's go with Rob's suggestion and improve the documentation:

/triage accepted

We should probably do this prior to GA to help avoid confusion sooner rather than later:

/priority important-longterm
/milestone v1.0.0
/help
