### ISSUE TITLE
Conformance test HTTPRouteRedirectHostAndStatus has an unusual test case

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes-sigs/gateway-api#1928]
**What happened**:

The test `HTTPRouteRedirectHostAndStatus` configures a redirect filter with only the [status code](https://github.com/kubernetes-sigs/gateway-api/blob/c27cdfc7c63f6f6f80e51a520b6bade7cf813acb/conformance/tests/httproute-redirect-host-and-status.yaml#L25).  According to the [spec](https://github.com/kubernetes-sigs/gateway-api/blob/c27cdfc7c63f6f6f80e51a520b6bade7cf813acb/apis/v1beta1/httproute_types.go#L852), any fields omitted will be identical to the request, so this is instructing the controller to configure the LB to return 301 to the requested URL.  Most browsers / clients will eventually error out when given such a response, and this is typically something that should be avoided.

**What you expected to happen**:

It's possible people might want to do this for unconventional reasons, but it seems like such a configuration would be mostly broken, so I'd expect the controller to return an error in the event redirect is configured to the request URL.

**Comment by shaneutt** [comment]
Seems agreeable:

/triage accepted

Let's get this sorted out prior to GA:

/priority important-longterm
/milestone v1.0.0
/help

**Comment by shaneutt** [comment]
@briantkennedy meaning that you want to add a real redirect from one scheme or host to another, rather then the currently problematic loop so that the _test_ is more valid even if we don't add the spec change and validation yet?

**Comment by shaneutt** [comment]
@briantkennedy meaning that you want to add a real redirect from one scheme or host to another, rather then the currently problematic loop so that the _test_ is more valid even if we don't add the spec change and validation yet? If so, yes that sounds reasonable.

**Comment by briantkennedy** [comment]
@shaneutt Yes, that's what I'd like to do, rather than only the status code, test the combination of (status, hostname) and (status, scheme).
