### ISSUE TITLE
Allow setting TLS mode when using networking.gke.io/certmap

### ISSUE THREAD

**Issue by nicon89** [kubernetes-sigs/gateway-api#1932]
**What would you like to be added**:
Allow setting TLS mode when using networking.gke.io/certmap.
I know I can configure it in tls section, but it fails with error:
```
Warning  SYNC    100s                   sc-gateway-controller  failed to translate Gateway "kube-system/xyz-dev": Error GWCER105: Listener "https" is invalid, err: TLS configuration not allowed when CertificateMap "gcp-xyz-com" is attached to the Gateway.
```
**Why this is needed**:
To allow passthrough of SSL certificate from the Kubernetes service, while still using GCloud managed wilcard certificates.

**Comment by howardjohn** [comment]
This repo is for the general API. This looks like an issue with GKEs implementation which would be better suited elsewhere

/close

cc @robscott

**Comment by shaneutt** [comment]
In case it is helpful: here is a reference to another GKE specific issue where @robscott (who works on the GKE implementation of Gateway API at Google) directed the user to the gke-gateway-feedback at google.com email address: https://github.com/kubernetes-sigs/gateway-api/issues/1222#issuecomment-1163638153
