### ISSUE TITLE
Allow `host:port` in `HTTPRouteSpec.hostnames`

### ISSUE THREAD

**Issue by tommie** [kubernetes-sigs/gateway-api#1936]
**What happened**: The [`HTTPRouteSpec.hostnames`](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteSpec) does not allow HTTP authority that includes a port number suffix.

**What you expected to happen**: Either

1. The [`Hostname` validation pattern](https://github.com/kubernetes-sigs/gateway-api/blob/b751bbdce6245c24556ac8ee13b6de0797515bb8/apis/v1beta1/shared_types.go#L381) allows full authority,
2. the `HTTPRouteSpec.hostnames` is changed to a separate `HTTPAuthority` string with an updated validation pattern, or
3. it is clarified that HTTPRoutes are matched against the hostname only, ignoring the port.

**Edit:** Since there is interaction between `Listener.hostname` and these hostnames, that needs to be expanded on in solutions 1-2.

**Anything else we need to know?**: The `HTTPRouteSpec.hostnames` field is of type `[]Hostname`, which is specified to only use a simple domain name. However, in [HTTP/1](https://www.rfc-editor.org/rfc/rfc7230#section-5.4), the `Host` header optionally includes the port. In [HTTP/2](https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2), the `:authority` pseudo-header carries the same syntax, but disambiguating the name. I.e.both use authority from [RFC 3986, sec 3.2](https://www.rfc-editor.org/rfc/rfc3986#section-3.2), without userinfo

Based on https://github.com/envoyproxy/gateway/pull/1311#issuecomment-1509429314.

**Comment by howardjohn** [comment]
Prefer (3) personally (ignore port)

**Comment by robscott** [comment]
+1 to @howardjohn on this one.

/help
