### ISSUE TITLE
Ambiguity in whether ReferenceGrant is required for same namespace references

### ISSUE THREAD

**Issue by NickMRamirez** [kubernetes-sigs/gateway-api#1944]
**What would you like to be added**:

The requirement for when a `ReferenceGrant` is needed for `HTTPRoute`, `TLSRoute`, `TCPRoute`, `UDPRoute` is ambiguous. Although it is clear that cross-namespace references require a ReferenceGrant, it is less clear whether it is required for *same-namespace* references.

For example, the description of `TCPRoute` states (emphasis mine):

> BackendRef defines how a Route should forward a request to a Kubernetes resource. Note that **when a namespace is specified**, a ReferenceGrant object is required in the referent namespace to allow that namespace's owner to accept the reference.

This indicates that the mere presence of a `namespace` field in the `BackendRef` would require a ReferenceGrant, even if that namespace is the same in both the `parentRef` and `backendRef`.

Meanwhile, in that same `TCPRoute` definition, the `namespace` field has this note (emphasis mine):

> Note that **when a different namespace is specified**, a ReferenceGrant object with ReferenceGrantTo.Kind=Service is required in the referent namespace to allow that namespace's owner to accept the reference.

This indicates that a ReferenceGrant is required only when the namespaces are different.

The intent of ReferenceGrant seems to be for cross-namespace references only, though. The `ReferenceGrant` definition has this note:

> ReferenceGrant identifies kinds of resources **in other namespaces** that are trusted to reference the specified kinds of resources in the same namespace as the policy...All **cross-namespace references** in Gateway API (with the exception of cross-namespace Gateway-route attachment) require a ReferenceGrant.

Should the notes that say *when a namespace is specified* be changed to say *when a namespace different from the namespace of the referenced resource is specified* to clarify this for same-namespace occurrences?

**Why this is needed**:

For implementors, if the specification avoids ambiguity, they are able to create implementations that behave in ways users expect. As-is, an implementor could require a `ReferenceGrant` even when both namespaces are the same (for example, both Gateway and Route are in the *default* namespace).

**Comment by shaneutt** [comment]
Talked about this one on the community meeting today:

Ultimately, for Gateway API it's colloquially understood that a `ReferenceGrant` is _not needed for same-namespace_ so we should get the documentation to reflect that:

/kind documentation
/priority backlog
/help

Do note that there are efforts to potentially move `ReferenceGrant` in tree as part of efforts in SIG Auth, so it's possible for that version of `ReferenceGrant` there might be situations where you would actually have same-namespace grants, but that's neither here nor there for the moment.

**Comment by youngnick** [comment]
Catching up on this one - I think we never really thought of this because the defined behavior is "no namespace specified == same namespace". I agree that we should carve out an exception that if you _do_ specify a namespace, and it's the same one, then a ReferenceGrant is _not_ required (since you can achieve the same thing by not specifying a namespace).

**Comment by NickMRamirez** [comment]
Thank you @shaneutt and @youngnick for clarifying this!
