### ISSUE TITLE
Conformance RoundTripper should allow for custom dialer

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes-sigs/gateway-api#1945]
**What would you like to be added**:

A way to inject a custom dialer into the conformance round tripper.

**Why this is needed**:

The existing round tripper requires the user to use the built in Go `http.Client` which directly dials endpoints from the test process.  Adding a custom dialer will allow communicating with the load balancer via a tunneled TCP connection which is useful if the load balancer is behind a firewall or not routable from the test process.

**Comment by shaneutt** [comment]
This seems reasonable to add:

/triage accepted

Though we would consider this a low priority in general:

/priority backlog

If it's blocking you however we would definitely welcome PRs to get people unstuck:

/help

**Comment by briantkennedy** [comment]
@robscott can we reopen this?  We need to fix up the change just slightly since we want to add a `DialContext` function as a member of the conformance RoundTripper instead of putting a `http.RoundTripper` on the request.
