### ISSUE TITLE
Add validation for `Gateway.Spec.Addresses`

### ISSUE THREAD

**Issue by shawnh2** [kubernetes-sigs/gateway-api#1960]
**What would you like to be added**:

In current validation server, it does not have validations for `Gateway.Spec.Addresses` . 

**Why this is needed**:

It's odd that this field does not have any validations, though we can do this in downstream implementations, still feels more logical to do it here.

refer to: https://github.com/envoyproxy/gateway/pull/1322#discussion_r1174349868

**Comment by gyohuangxin** [comment]
@shawnh2 Thanks for the issue. I agree that we could add some validation for  `Gateway.Spec.Addresses`, but can you explain more about what your implementation want to validate then we can come to an agreement between implementations?

**Comment by arkodg** [comment]
+1 to @shawnh2's suggestion

**Comment by shaneutt** [comment]
We would like to try and have this for GA, so we've added it to the board. It doesn't need to block it, but if we get time or someone feels very strongly they want to do this one please do!

/help

**Comment by shawnh2** [comment]
I’d like to give it a try, assign please

**Comment by shaneutt** [comment]
Thanks! Let us know if you run into any trouble or need help :vulcan_salute:
