### ISSUE TITLE
add test for gateway.go

### ISSUE THREAD

**Issue by khareyash05** [kubernetes-sigs/gateway-api#1961]
**What would you like to be added**:
I would like to add tests for `pkg/client/listers/apis/v1beta1/gateway.go`

**Why this is needed**:
Adding unit testing would enhance user experience with the API

**Comment by robscott** [comment]
@khareyash05 The code in `/pkg/client` is actually generated so we probably can't/shouldn't test it. Feel free to reopen if I'm missing anything though.
