### ISSUE TITLE
Gateway API to support Egress Traffic

### ISSUE THREAD

**Issue by quangnguyen101** [kubernetes-sigs/gateway-api#1968]
- Issue: [#1856](https://github.com/kubernetes-sigs/gateway-api/issues/1856)
- Status: Provisional|Implementable|Experimental|Standard|Deferred|Rejected|Withdrawn|Replaced

# TLDR
Egress traffic is any traffic that originates inside a Kubernetes cluster that is bound for a resource outside of the cluster. Egress Traffic in Kubernetes is a common use case for Service Providers to provision outbound traffic that requires a Gateway resource to provide Source Network Address Translation (SNAT) capabilities.  

We propose a Gateway API Route allowing us to describe the path for an application to reach an endpoint outside of the cluster.  The egress path is protocol agnostic and the Gateway can be connected to multiple external networks.

# Goals

- Provide a standardize configuration for provisioning egress for any protocol through a single Gateway.
- Egress Gateways can be connected to different external networks.
- Provision for using SNAT to allow for identification of cloud-native network functions (CNFs) via engineered IP assignments for security purposes.
- Allow CNFs to be addressed by their external IPs regardless of whether they are being access from within the cluster or from outside the cluster.

# Non-Goals
Security functionality should be kept outside this "route". We can have these be referenced as appropriate.

IP address management for SNATing will not duplicate non-trivial IPAM (IP address management) capabilities, only simple capability will be provided here.

Potential future use cases such as:

- Provision for using SNAT to allow for IPv4 to IPv6 translation on the way out of the cluster.
- Allow CNFs using peering protocols like Diameter to function by allowing connections to originate in either direction.
- Allow attaching policies (specifics to come later).

# Introduction
There are a number of scenarios where it is very useful to control and direct access to multiple external network domains.  This is explained, in some detail for Telco use cases in the linked document, below, but it is also true for other scenarios – for example, any time you have an isolated network (vlan, vrf, etc.) that should be accessed by certain apps on not others.  An example might be a front-end server that is exposed to the Internet versus a back-end database that is isolated.

Telco use cases: https://docs.google.com/document/d/13xAF_pqH2bV8x4MfXWde47esCdVwow1-nig6iy_rafA/edit

When there are multiple external networks involved, there needs to be a model for how to control access to the different networks.  The suggested model in this GEP is to allow the Infrastructure Provider to define what networks are available for a Gateway Class.  Each Gateway instantiated would then connect to a single one of the networks, with those Gateways allowing routes to/from defined K8S namespaces.  This allows the Cluster Operator to control who accesses each of the external networks.  In the model, the application developers need only to request routes to/from the right Gateways.

```
Diagram: EgressRoute to POD

                                                  -------------------
Infrastructure Provider   ------->                |  Gateway Class  | <-- Configure: Available Networks
                                                  -------------------
                                                           |
                                                  ------------------
Cluster Operator          ------->                |     Gateway    | <-- Select: Single Network
                                                  ------------------
                                                   /            \
Application Developer     ------->                /          ------------------
                                                 /           |   EgressRoute  | 
                                                /            ------------------
                                        ------------------                 \
                                        |   HTTPROUTE    |            ------------------
                                        ------------------            |       POD      |            
                                                /                     ------------------
                                    ------------------
                                    |   SERVICE      |            
                                    ------------------
                                       
```

Beyond connecting to multiple external network domains, it is very important in many scenarios (specifically including Telco) to be able to identify individual applications egressing a cluster, based on the source IP.  In scenarios where firewalls and access control lists (ACLs) are in use, it is standard to control access based on source/destination IP addresses.  For those firewall policies to be meaningful, it is vital for application traffic to be individually identifiable, based on source IP.  Because of this, controlling the source IP (SNAT) on egressing traffic is a key use case.

# API
(... details, can point to PR with changes)

# Alternatives
(List other design alternatives and why we did not go in that direction)

# References
(Add any additional document links. Again, we should try to avoid too much content not in version control to avoid broken links)

**Comment by shaneutt** [comment]
Thanks @quangnguyen101 for taking the time to submit a GEP, however GEPs are meant to be submitted as PRs and added/updated to files in the repository, for instance:

https://github.com/kubernetes-sigs/gateway-api/blob/main/geps/gep-1323.md

The PR process is then used for review. Please create a PR where you submit these contents as the following file:

https://github.com/kubernetes-sigs/gateway-api/blob/main/geps/gep-1856.md

And let us know if you need any help or have any trouble!

**Comment by shaneutt** [comment]
No worries! If you get stuck at all let us know how we can help, we're also available in `#sig-network-gateway-api` on [Kubernetes Slack](https://kubernetes.slack.com)!

**Comment by marco-a-itl** [comment]
Sorry, has the discussion about this API improvement continued somewhere else ?
Or there is really no intention at all to support Egress traffic ?

**Comment by shaneutt** [comment]
> Sorry, has the discussion about this API improvement continued somewhere else ?

I haven't seen it come up in a while.

> is really no intention at all to support Egress traffic ?

It's not a never, it's a "someone has to champion this to move it forward". At least lately we haven't had anyone pushing it forward. Check out the [project management section of the CONTRIBUTING.md](https://github.com/kubernetes-sigs/gateway-api/blob/main/CONTRIBUTING.md#project-management) for some guidance on how features get prioritized, and how old issues like this one can in theory be revived.
