### ISSUE TITLE
Request for information/support on http2 transport enablement in conformance test

### ISSUE THREAD

**Issue by pramodrj07** [kubernetes-sigs/gateway-api#1982]
**What would you like to be added**:
Need support for http2 in conformance test specifically the "roundtripper" package

**Why this is needed**:
To overcome limitation of just using http1 in the conformance test as the upstream backend host might just support only http2
https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/utils/roundtripper/roundtripper.go#L111

**Additional Details **:
From the initial investigation, it looks like we cannot pass the custom HTTP client into the default round tripper implementation. If there is an alternate way to achieve this, I would like to be redirected there.

**Comment by gauravkghildiyal** [comment]
Will passing in an [http2.Transport](https://github.com/kubernetes-sigs/gateway-api/blob/6efcfdf8aff7aa7c3ed8deb956e5b93eed779234/conformance/utils/roundtripper/roundtripper.go#L119) through the `CustomDialer` in a `Request` be sufficient for your use case?

https://github.com/kubernetes-sigs/gateway-api/blob/6efcfdf8aff7aa7c3ed8deb956e5b93eed779234/conformance/utils/roundtripper/roundtripper.go#L41-L52

**Comment by ibilalkayy** [comment]
Checkout this [PR](https://github.com/kubernetes-sigs/gateway-api/pull/1983) that I just sent

**Comment by shaneutt** [comment]
This sounds good.

/triage accepted

It would be nice to have this for GA, but it doesn't appear to _need_ to block it so we'll leave it off the `v1.0.0` milestone.
