### ISSUE TITLE
Method matching importance in matching priorities

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/gateway-api#1993]
**What would you like to be added**:

When there are multiple HTTPRoute rules matching, the documentation [states](
https://github.com/kubernetes-sigs/gateway-api/blob/a56f84f6bffdb527c6796ed15c04440afd5a1ed6/apis/v1beta1/httproute_types.go#L154-L164):

```go
	// Proxy or Load Balancer routing configuration generated from HTTPRoutes
	// MUST prioritize matches based on the following criteria, continuing on
	// ties. Across all rules specified on applicable Routes, precedence must be
	// given to the match with the largest number of:
	//
	// * Characters in a matching "Exact" path match
	// * Characters in a matching "Prefix" path match
	// * Header matches.
	// * Query param matches.
	//
	// Note: The precedence of RegularExpression path matches are implementation-specific.
```

In this section, there is no mention of the method matching, that should be taken into account. A fifth line containing method matching could be added after the first four related to matching types.

**Comment by sunjayBhatia** [comment]
I would like to bump the priority for 0.7.x for this since we've added a test that covers it without an explicit mention in the spec, see https://github.com/kubernetes-sigs/gateway-api/pull/1984/files#r1200873543

**Comment by sunjayBhatia** [comment]
Another approach would be to comment out the test that is not covered by the spec and add a TODO until the next minor release
