### ISSUE TITLE
Add support for configurable HTTP redirects

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#200]
**What would you like to be added**:

On a per route basis, a user can configure HTTP redirects 301/302 (may be 307/308 too?) and the location of where to redirect to. It could be simply a redirect to HTTPS, in which case, redirect with the Location header matching the URL of the request being processed or it could be a redirect to a different location. The second part can get tricky because that can invovle path munging (we could consider that to be an extended/custom API).

**Why is this needed**:

This is a common requirement and most controllers already support this using annotations.

**Comment by jpeach** [comment]
@hbagdi One idea I had for this was a special syntax for route selectors (e.g. .wellknown namespace names). That can work for simple http->https cases, but probably doesn't scale for arbitrary redirects.
