### ISSUE TITLE
Restrict routing for /.well-known/acme-challenge and other sensitive URLs

### ISSUE THREAD

**Issue by costinm** [kubernetes-sigs/gateway-api#2018]
Cross namespace routing allows a 'shared gateway' to designate a set of namespaces allowed to attach routes for a specific hostname. The expectation is that the owner of the domain runs an isolated gateway, where the domain certificate access may be controlled and isolated from the workloads and their namespace owners. 

The spec doesn't define any restrictions on which paths a namespace may define a route for - and some paths are 
sensitive as they allow escalations - in particular acme-challenge path allows a namespace owner to get a signer certificate
for the domain, eliminating any benefits that a managed and isolated gateway attempts to provide. 

There are few options to tighten things up:
- spec listing a set of URLs that should not be delegated cross namespace
- define an RBAC-like policy that restricts what URL prefixes are allowed for different namespaces. 

I would suggest starting with the first - I don't think there are many legitimate use cases for a cross-namespace route to 
get ACME certificates outside of the namespace where the gateway is defined. 

An RBAC-like policy - or the actual K8S RBAC using "nonResourceURLs" to identify URLs in roles and binding it to the default SA in a namespace - would be a nice extension but I expect to take a lot of bikeshedding and only get advanced users adoption - so doing both would be better. 

In addition to acme-challenge, other .well-known domains are sensitive and used in OIDC and new protocols to prove
domain ownership. Restricting the entire /.well-known/ to same namespace may be an option.

**Comment by dprotaso** [comment]
> The expectation is that the owner of the domain runs an isolated gateway, 

I don't think this reflects the HTTP-01 use case very well.  Knative intends to have a shared gateway and have many subdomains that have certificates issued via HTTP-01 challenges.

So in theory we'll have few gateways in some system namespaces but many routes pointing to them. So I would expect our control plane to author paths for `/.well-known/` for routes in the user's namespace.

**Comment by costinm** [comment]
Yes, knative and all cases where ACME is used for getting certificates will work - the Secret and certificate are in the same namespace with the Gateway. 

The problem is that evie-namespace can also create a route for .well-known and get a certificate for the domain - then use it to MITM traffic for the entire site ( by intercepting traffic from external users and serving the cert it just got). 
The proposal is to prevent cross-namespace route delegation for such URLs.

I don't think TCP/TLS routes have this problem - unless they are used on port 443 or 80 ( I don't think ACME challenge for example works over other ports ). The use case of a TCP server not on port 80/443 and delegated to multiple namespaces is not very common.

**Comment by costinm** [comment]
CertManager creates HttpRoutes ( or VirtualServices) dynamically - and removes them after they're done. So having an existing route doesn't help.

**Comment by howardjohn** [comment]
TLSRoute on 443 is probably not so weird for passthrough. But I think HTTP challenge is always port 80, good point. Although ALPN challenge may be a concern still

**Comment by dprotaso** [comment]
> Yes, knative and all cases where ACME is used for getting certificates will work - the Secret and certificate are in the same namespace with the Gateway.

I was pointing out that the Gateway is in a separate namespace than the secret and cert
