### ISSUE TITLE
GAMMA members want to make GAMMA more visible on the Gateway API website

### ISSUE THREAD

**Issue by kflynn** [kubernetes-sigs/gateway-api#2057]
Given real implementations and the upcoming marking of GAMMA as implementable, we should arrange for GAMMA to appear more visibly on the Gateway API website, to make it easier for people looking for GAMMA information to find it.

**Comment by robscott** [comment]
Completely agree that we should have more GAMMA documentation throughout the website. Whether that's more integrated documentation or a dedicated GAMMA section, or some combination of both, contributions would be very welcome.

/triage accepted

**Comment by pierDipi** [comment]
@robscott @kflynn in the meantime, is there any other place you'd recommend looking at?

**Comment by kflynn** [comment]
I think this has long since been tackled. 🙂 

/close
