### ISSUE TITLE
Improve `AttachedRoutes` conformance test

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/gateway-api#2058]
**What would you like to be added**:

At the moment, the [test cases](https://github.com/kubernetes-sigs/gateway-api/blob/4738c6c6e981d4a0e38c8c6120dc0198e4128351/conformance/tests/gateway-with-attached-routes.go) related to the `AttachedRoutes` are structured as follows:
- the first one has one `Gateway` with one listener and one `HTTPRoute` referring to it as a parent. The test verifies that the `status.listeners[0].AttachedRoutes` field gets the value 1 assigned.
- the second one has one `Gateway` with one listener and two `HTTPRoute`s referring to it as a parent. The test verifies that the `status.listeners[0].AttachedRoutes` field gets the value 2 assigned.

Alongside the above test cases, we should verify that a `gateway` with many listeners has the corresponding `AttachedRoutes` field assigned only if the Routes can really attach to them.

Example:
- create a `Gateway` with two listeners using two different protocols: HTTP and UDP
- create an `HTTPRoute`
- only the HTTP listener should have the `AttachedRoutes` field to 1, the UDP listener value should be 0.

**Comment by levikobi** [comment]
Can I help with this one?

**Comment by shaneutt** [comment]
@levikobi we would love to have you help out, and appreciate the offer!

Do you have an implementation in mind that you're already contributing to which runs the conformance test suite?

**Comment by levikobi** [comment]
Thanks @shaneutt 
I can use [envoy-gateway](https://gateway.envoyproxy.io/v0.4.0/) if that's ok. I'm not a contributor though.

**Comment by mlavacca** [comment]
Hi @levikobi! We'd definitely appreciate your contribution! You can use whichever Gateway implementation you prefer, envoy is 👍!

**Comment by shaneutt** [comment]
Sounds good, let us know if you need any support (by posting comments here, or checking in `#sig-network-gateway-api` on slack)!

/assign @levikobi
