### ISSUE TITLE
Conformance: TCPRoute with TLS mode Terminate

### ISSUE THREAD

**Issue by tanujd11** [kubernetes-sigs/gateway-api#2060]
**What would you like to be added**:
Add conformance test for scenario to use kind TCPRoute for Protocol TLS and mode Terminate. Precisely the following [case](https://gateway-api.sigs.k8s.io/guides/tls/#:~:text=TLSRoute-,TLS,TCPRoute,-HTTPS).

**Comment by shaneutt** [comment]
Relates to #1794
