### ISSUE TITLE
Back-off pulling image "registry.k8s.io/gateway-api/admission-server:v0.7.1"

### ISSUE THREAD

**Issue by duanhongyi** [kubernetes-sigs/gateway-api#2086]
```
crictl pull registry.k8s.io/gateway-api/admission-server:v0.7.1
```

![1685927407392](https://github.com/kubernetes-sigs/gateway-api/assets/548686/e4112b08-64e2-4206-a147-9e13f445a6c4)

**Comment by gyohuangxin** [comment]
@duanhongyi Thanks for the issue, it's a known issue and will be fixed after this PR is merged: https://github.com/kubernetes/k8s.io/pull/5352

**Comment by sunjayBhatia** [comment]
this should be resolved now!

**Comment by shaneutt** [comment]
This should be resolved now, please let us know if there's still a problem and we'll re-open. :+1:
