### ISSUE TITLE
New SectionNames field for RouteParentStatus

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2093]
**What would you like to be added**:
RouteParentStatus could benefit from a `SectionNames` field to clarify which "Sections" of a parent the Route had been attached to. 

**Why this is needed**:
This would be most useful when a ParentRef targets an entire Gateway but is only attached to a subset of the listeners in that Gateway due to port, protocol, hostname, or other restrictions. 

_Note: This issue is meant to start a discussion, it does not mean that this idea is ready to work on yet._

**Comment by youngnick** [comment]
/remove-lifecycle rotten

I agree we should still do this.

**Comment by youngnick** [comment]
/remove-lifecycle rotten

Still could use doing.
