### ISSUE TITLE
Conformance tests require a listener on port 8080

### ISSUE THREAD

**Issue by pleshakov** [kubernetes-sigs/gateway-api#2094]
**What happened**:

The Gateway spec states https://github.com/kubernetes-sigs/gateway-api/blob/c2d863bb06f63b069be58d6ae9dc79f22365f809/apis/v1beta1/gateway_types.go#L72-L77

However, one of the base conformance Gateways includes a listener on port 8080 -- https://github.com/kubernetes-sigs/gateway-api/blob/c2d863bb06f63b069be58d6ae9dc79f22365f809/conformance/base/manifests.yaml#L40

Since base Gateways always get deployed as part of running the conformance tests, that Gateway with port 8080 listener becomes a blocker for running conformance tests for implementations that do not support port 8080.

**What you expected to happen**:

Conformance tests only use ports 80 and 443 in base manifests.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by sunjayBhatia** [comment]
also note this test: https://github.com/kubernetes-sigs/gateway-api/blob/c2d863bb06f63b069be58d6ae9dc79f22365f809/conformance/tests/gateway-observed-generation-bump.go#L67-L74

(requires support for multiple ports for a single protocol at the moment, which Contour will support soon but does not now)

**Comment by xtineskim** [comment]
i'd like to help w/ this!
