### ISSUE TITLE
Gateway listener's AllowedRoutes are not validated by the admission controller.

### ISSUE THREAD

**Issue by sjberman** [kubernetes-sigs/gateway-api#2099]
**What happened**:

Without error, I'm able to define a Gateway listener with `AllowedRoutes.Namespaces.From` set to `Selector` and not set the `AllowedRoutes.Namespaces.Selector` field.

**What you expected to happen**:

Per the [API specification](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.RouteNamespaces), defining the above configuration should not be allowed. The admission controller should reject this configuration.

**Comment by shaneutt** [comment]
Sounds like something worth fixing

/triage accepted

Ideally we should be able to get around to this before `v1.0.0`, however it doesn't appear as a hard blocker.

/milestone v1.0.0
/priority important-longterm

**Comment by shaneutt** [comment]
The admission webhook is now deprecated and will rotate out of support, so it seems like we can consider this one a wont do. If anyone disagrees, or really wants to work on this please feel free to re-open.
