### ISSUE TITLE
HttpRouteFilters Docs and webhook do not match. 

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes-sigs/gateway-api#2109]
**What happened**:
HttpRouteFilters Docs and webhook do not match. 

The docs/api field description say: 
https://github.com/kubernetes-sigs/gateway-api/blob/f2cd9bb92b4ff392416c40d6148ff7f76b30e649/apis/v1beta1/httproute_types.go#L204-L205

And it seems that the webhook does not allow multiple features from the same type (unless it is `HTTPRouteFilterExtensionRef`)
https://github.com/kubernetes-sigs/gateway-api/blob/f2cd9bb92b4ff392416c40d6148ff7f76b30e649/apis/v1beta1/validation/httproute.go#L137-L142

**What you expected to happen**:

Expected both to match. 

Would vote for changing the webhook to allow and clarify in the docs that repeatable is implementation-specific.

cc: @howardjohn

**Comment by howardjohn** [comment]
Note we have gotten a few requests for multiple mirrors in Istio: https://github.com/istio/istio/issues/13330. This isn't in our API today, but could be exposed via multiple Mirror filters
