### ISSUE TITLE
Request to add Cipher suites in the roundtripper

### ISSUE THREAD

**Issue by pramodrj07** [kubernetes-sigs/gateway-api#2129]
**What would you like to be added**:
*need to way to relay back cipher suites as part of roundtripper*

**Why this is needed**:
*This is required as different implementation of gateway-api can support different Ciphers. For example, the set of Cipher suites supported by two different version envoy might be different and we need to make sure the conformance tests has the capability to relay back the Cipher suites(atleast suite code) to the caller.*

**Comment by howardjohn** [comment]
The mesh test echo tool, which is already used for some tests, supports this already. https://github.com/istio/istio/blob/9b625fdeae8e9a6176cab53371d2845022c615ae/pkg/test/echo/server/forwarder/tls.go#L83.

There has been some discussion of using this for all tools

**Comment by shaneutt** [comment]
General idea sounds ok, but still needs a bit more information/discussion.

Doesn't seem like this is needed for GA.
