### ISSUE TITLE
bug: multiple header value matching semantics

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#213]
HTTP headers can have multiple values for the same key.  
Clarify what should be the route matching behavior for headers with multiple values to avoid surprises for the end user when they switch from one implementation to other.

A good example for this is matching based on `X-forwarded-for` header.

Questions to be answered:
- Should a single match for value among a set of values be considered a positive match?
- Should it be required to list out all values in case of multiple headers for a valid match? Is ordering important in this case?

**Comment by hbagdi** [comment]
Some questions I've:
- Is this something that is even used? Do users define routing based on such rules?
- If the answer to the above is rarely, does it make sense to keep the matching behavior as undefined in this case and we leave up to the implementation? It would be pretty hard (or impossible) to define a behavior that is consistent across implementations.

**Comment by hbagdi** [comment]
This seems like an edge case that would rarely happen in practice.
@bowei @robscott Have you run into this in your experience?
If not, I propose we move this back into the backlog and come back to this when someone actually reports that they are running into this case.

**Comment by robscott** [comment]
@hbagdi I think the [current spec](https://github.com/kubernetes-sigs/gateway-api/blob/master/apis/v1alpha2/httproute_types.go#L434) is fairly clear here:

> Multiple match values are ANDed together

It would be possible for multiple RegEx or ImplementationSpecific matches + a single Exact match to all match a single value. In the event that one match does not match the value, the result of the AND would be false. Do you think we need to clarify anything more here?

**Comment by jpeach** [comment]
> @hbagdi I think the [current spec](https://github.com/kubernetes-sigs/gateway-api/blob/master/apis/v1alpha2/httproute_types.go#L434) is fairly clear here:
> 
> > Multiple match values are ANDed together

Then for a muti-valued header, a single match entry matches a single value, and you give multiple matches if you want more:
```yaml
match:
  headers:
  - name: Forwarded
    value: Foo
  - name: Forwarded
    value: Bar
```

**Comment by robscott** [comment]
@jpeach I think the config you listed would not match any requests. On the other hand, this would match requests with a `Forwarded` header value of `Foo` or `Bar`

```yaml
matches:
- headers:
  - name: Forwarded
    value: Foo
- headers:
  - name: Forwarded
    value: Bar
```

**Comment by jpeach** [comment]
IIUC this issue is about headers that can have multiple values, so my example would match when the header contains bit of these values, right?

**Comment by robscott** [comment]
My interpretation is that each individual header match in a `headers` section needs to be true for the match as a whole to be considered true. In your example, it would be impossible for `Foo` and `Bar` to be either a prefix, regex, or exact match of the same header.

This is making it clear that there's too much ambiguity in the spec though, it sounds like we're interpreting this differently.

**Comment by jpeach** [comment]
> My interpretation is that each individual header match in a `headers` section needs to be true for the match as a whole to be considered true. In your example, it would be impossible for `Foo` and `Bar` to be either a prefix, regex, or exact match of the same header.

It would be possible if the header has multiple values:
```
HTTP/1.1 GET https://foo.example.com/something
Forwarded: Foo
Forwarded: Bar
Forwarded: Baz
```

Or are you saying that in this case, it's not possible to match against the `Forwarded` header at all?

**Comment by howardjohn** [comment]
Do we have prior art on how this behaves in other places? I think at least
Envoy's API is a similar shape - I couldn't tell from the docs how it
handles this though.

**Comment by robscott** [comment]
Good point, it looks like Envoy has been updated to concat multiple header values into a comma separated list before matching: https://github.com/envoyproxy/envoy/issues/13751. That's the behavior I'd been assuming here, but I'd need to do some more digging to see how widespread that actually is.

**Comment by jpeach** [comment]
> Good point, it looks like Envoy has been updated to concat multiple header values into a comma separated list before matching: [envoyproxy/envoy#13751](https://github.com/envoyproxy/envoy/issues/13751). That's the behavior I'd been assuming here, but I'd need to do some more digging to see how widespread that actually is.

> > requires gymnastics with regular expressions etc. to do a multi-value match

:grimacing:

**Comment by bowei** [comment]
Repeated headers are a single header comma combined. There is no such thing as treating them as individual headers. Check the RFC.

**Comment by jpeach** [comment]
> Repeated headers are a single header comma combined. There is no such thing as treating them as individual headers. Check the RFC.

Is this the relevant part? https://www.rfc-editor.org/rfc/rfc7230.html#section-3.2.2

>   A sender MUST NOT generate multiple header fields with the same field
>   name in a message unless either the entire field value for that
>   header field is defined as a comma-separated list [i.e., #(values)]
>   or the header field is a well-known exception (as noted below).
>
>   A recipient MAY combine multiple header fields with the same field
>   name into one "field-name: field-value" pair, without changing the
>   semantics of the message, by appending each subsequent field value to
>   the combined field value in order, separated by a comma.  The order
>   in which header fields with the same field name are received is
>   therefore significant to the interpretation of the combined field
>   value; a proxy MUST NOT change the order of these field values when
>   forwarding a message.
>
>      Note: In practice, the "Set-Cookie" header field ([RFC6265]) often
>      appears multiple times in a response message and does not use the
>      list syntax, violating the above requirements on multiple header
>      fields with the same name.  Since it cannot be combined into a
>      single field-value, recipients ought to handle "Set-Cookie" as a
>      special case while processing header fields.  (See Appendix A.2.3
>      of [Kri2001] for details.)

So you must not generate multiple header fields with the same key **unless the entire field value is a list**, in which case you can. And cookies are an exception.
