### ISSUE TITLE
Update TargetREf in Policy GEP

### ISSUE THREAD

**Issue by candita** [kubernetes-sigs/gateway-api#2147]
Discussion generated from GEP-1897 points out that TargetRef could use some updates.  
1. All policy resources must include TargetRef with the fields specified here: https://github.com/kubernetes-sigs/gateway-api/blob/a33a934af9ec6997b34fd9b00d2ecd13d143e48b/apis/v1alpha2/policy_types.go#L24-L41
2. Policy resources _may_ also choose to include `SectionName` and/or `Port` in TargetRef following the same mechanics of `ParentRef`

Then we can provide additional `TargetRef` types that extend the base `TargetRef` with the different possible combinations of these fields. That feels like it could be handled in a separate smaller update to the policy GEP.

_Originally posted by @robscott in https://github.com/kubernetes-sigs/gateway-api/pull/2113#discussion_r1239035806_

**Comment by arkodg** [comment]
happy to pick this one up, @robscott does that warrant a discussion first, or can I start with a GEP ?

**Comment by youngnick** [comment]
I think that #2128 needs to merge before we make any more Policy changes. After that, yes, this should update GEP-713.

**Comment by shaneutt** [comment]
> I think that https://github.com/kubernetes-sigs/gateway-api/pull/2128 needs to merge before we make any more Policy changes. After that, yes, this should update GEP-713.

+1, let's get #2128 done and then update the existing doc.

**Comment by arkodg** [comment]
looks like @zhaohuabing is driving this, thanks !
