### ISSUE TITLE
Conformance: Add `FoucsTests` option for conformance test suite

### ISSUE THREAD

**Issue by shawnh2** [kubernetes-sigs/gateway-api#2151]
**What would you like to be added**:
Add a new field called `FoucsTests` in `ConformanceTestSuite` Options:
https://github.com/kubernetes-sigs/gateway-api/blob/a5ede12430c31639349ae6c00666890591f72a40/conformance/utils/suite/suite.go#L57

**Why this is needed**:
When I working with my GW implementation, I kind need the ability to only foucs on serval failed conformance test, to debug or retest them. For now, the GW-API conformance test suit only provide `SkipTests`, so I am hoping we can add `FocusTests` as well, for debugging purpose.
https://github.com/kubernetes-sigs/gateway-api/blob/a5ede12430c31639349ae6c00666890591f72a40/conformance/utils/suite/suite.go#L78

**Comment by arkodg** [comment]
@shawnh2 you should be able to run individual tests directly using `go test`, more in https://gateway-api.sigs.k8s.io/concepts/conformance/?h=confor#suite-level-options, can you try this out ?

**Comment by shawnh2** [comment]
thanks @arkodg , that works.
