### ISSUE TITLE
Conformance report API version and channel

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/gateway-api#2197]
**What would you like to be added**:

The conformance profiles [GEP](https://github.com/kubernetes-sigs/gateway-api/blob/main/geps/gep-1709.md#gateway-api-version-and-channel) clearly states that an automatic mechanism to detect and set the `GatewayAPIVersion` in use when running the experimental conformance suite needs to be implemented.
The mechanism described therein needs to be added to the conformance profiles machinery.

**Why this is needed**:

This is needed to automatically detect the current Gateway API version and channel in use without relying on the user manual settings.

**Comment by shaneutt** [comment]
Nice to have for `v1.0.0` if we have the time, but not a `release-blocker`. Probably should be a blocker for moving beyond `Experimental` status.

**Comment by mlavacca** [comment]
Closing as superseded by https://github.com/kubernetes-sigs/gateway-api/issues/2738
