### ISSUE TITLE
Logo for the Gateway API

### ISSUE THREAD

**Issue by MarcoSteinke** [kubernetes-sigs/gateway-api#2202]
Hello,
I am the maintainer of the website https://servicemesh.es/ and just replaced the Service-Mesh-Interface from the implementations with the Gateway API. I used an unofficial logo which you can see in the bottom of the screen.

Is there any concern for you by using this logo, or do you have any other logo I could use for the listing?

Best wishes,
Marco

![image](https://github.com/kubernetes-sigs/gateway-api/assets/49523050/a1385d70-1b89-4ba7-889d-49ab800e07e0)

**Comment by MarcoSteinke** [comment]
Feel free to create a Pull Request on the website for the suggestion of a new logo, or another description of the Gateway API. 

Or make a suggestion in this issue and I will change the content accordingly.

**Comment by robscott** [comment]
Hey @MarcoSteinke, sorry it's taken so long to respond here! We have wanted to develop a logo for quite some time but just haven't had the skills or time. Your logo is definitely a good start, we were just hoping to have something a bit more unique.

@thockin came up with the idea of combining some basic black hole line art with a Kubernetes logo and came up with this icon:
![gateway-api-icon](https://github.com/kubernetes-sigs/gateway-api/assets/419322/05bbed16-284d-42d0-8cd9-f40ce38d5bf1)


I've also experimented with adding some text to it, but fair warning it does not render well if you've got dark mode enabled on GitHub:

![gateway-api](https://github.com/kubernetes-sigs/gateway-api/assets/419322/2204545d-4e49-45c0-a79b-cfc079d81d34)
![gateway-api-tall](https://github.com/kubernetes-sigs/gateway-api/assets/419322/5d608733-fea2-460e-a0d1-3b1e89e778f8)

Feedback and ideas are very welcome and appreciated here.

**Comment by youngnick** [comment]
I think we should use the Kubernetes font for any text, but this looks good to me.

**Comment by robscott** [comment]
> I think we should use the Kubernetes font for any text, but this looks good to me.

I just used the Ubuntu font which I believe is actually what Kubernetes uses per https://github.com/kubernetes/kubernetes/pull/23071#issue-141382998.

**Comment by youngnick** [comment]
Ah, this is because this is an SVG and I don't have the "ubuntu" font installed! Maybe render to PNG instead?

**Comment by robscott** [comment]
Good call, hopefully these are better

![gateway-api-tall](https://github.com/kubernetes-sigs/gateway-api/assets/419322/d9314695-7df3-4fe0-9d86-a0ac9f0793da)
![gateway-api-wide](https://github.com/kubernetes-sigs/gateway-api/assets/419322/4713f957-2b87-409a-aaeb-d545a7569621)

**Comment by youngnick** [comment]
I installed the font and now they look the same, so yes, nice one. 😄

**Comment by robscott** [comment]
Talked about this with @shaneutt and @youngnick, and we decided to leave this open until the end of September so anyone can submit potential logos for Gateway API. We'll plan to make a final decision on a logo in early October.

**Comment by MarcoSteinke** [comment]
Hey, thank you for continuing this thread. I could not answer yet, because I am in vacation, but I am really thankful for this nice logo. I will insert it into servicemesh.es as soon as I return to my desk.

**Comment by robscott** [comment]
A few more options, inspired by a sketch by @plgingembre and designed by @lmscott8. All are not particularly precise at this point and could be cleaned up if there was interest in going further with any of these. Since there are a lot of options here, it would help to narrow down the list by reacting to this comment with emoji(s) for the options you like best.

**Option A (👀):**
![Gateway API Logo - E](https://github.com/kubernetes-sigs/gateway-api/assets/419322/d44c5a35-b474-4b38-a442-21b383f1b23a)

**Option B (🎉):**
![Gateway API Logo - B](https://github.com/kubernetes-sigs/gateway-api/assets/419322/13e0fc41-cc32-4578-bcf8-7afbc0c4a5b5)

**Option C (❤️):**
![Gateway API Logo - C](https://github.com/kubernetes-sigs/gateway-api/assets/419322/ef8300da-9ed9-4f04-af06-c9a22a032b93)

**Option D (🚀):**
![Gateway API Logo - D](https://github.com/kubernetes-sigs/gateway-api/assets/419322/a3ac4292-b15a-4241-b2ca-5ea6551786a1)

**Comment by thockin** [comment]
Of these, I like A (all arrows down) but the center-ring from B.

**Comment by youngnick** [comment]
I also like all arrows down - I was worried that having the center ring made this logo not distinguishable enough to the regular Kubernetes logo.

**Comment by thockin** [comment]
That's half the fun

**Comment by dprotaso** [comment]
I would do a squint test - from a distance see if you can distinguish this logo from the k8s one 

I think the above designs can be tweaked a bit
![Untitled](https://github.com/kubernetes-sigs/gateway-api/assets/18562/1585ff75-fc6d-4157-a9eb-915f82035a50)

**Comment by quangnguyen101** [comment]
Team B 🎉 ...without the center circle it looks like a peace sign...which is not a bad thing either.

**Comment by dprotaso** [comment]
@shaneutt here's that kitchen sink concept

![Untitled](https://github.com/kubernetes-sigs/gateway-api/assets/18562/edfbc6e9-a789-4ac4-9ac6-7904c47cf778)

**Comment by shaneutt** [comment]
:point_up: this has my vote.

**Comment by thockin** [comment]
![th1](https://github.com/kubernetes-sigs/gateway-api/assets/5595220/5b177267-a1c8-47c4-a950-84e469e32a8d)

or get silly (view it without a white BG)

![th2](https://github.com/kubernetes-sigs/gateway-api/assets/5595220/f66044c7-dccc-4ba7-933d-57047185e684)

**Comment by robscott** [comment]
I've taken the most popular options here and created a poll that will allow everyone to vote. For your vote to be counted, it needs to be in by 11:59PM Pacific Time on Sunday, October 8.

https://forms.gle/3Qp8tdVJ5c4999jT9

**Comment by youngnick** [comment]
The vote happened, and we chose the following option:

![image](https://github.com/kubernetes-sigs/gateway-api/assets/9346599/a7d9e776-830d-4259-9898-97015d5e7799)

This image has been included in the website, we have some merch, and so on.

Closing this issue, thanks to everyone for all the work and feedback.
