### ISSUE TITLE
Conformance: Routability features not included in "all features" set

### ISSUE THREAD

**Issue by sunjayBhatia** [kubernetes-sigs/gateway-api#2204]
Noticed while running v0.8.0 conformance tests, it looks like none of the routability features from this list were added to the "all features" set: https://github.com/kubernetes-sigs/gateway-api/pull/2171/files#diff-f42c32db470693cfe1bf5989b0c4b73928ae7b0598404059d44938e88472161e

Is this just an oversight or intended?

**Comment by robscott** [comment]
Thanks for catching this @sunjayBhatia! I think this is an oversight.

/triage accepted

**Comment by sunjayBhatia** [comment]
I'm finding a lot of issues in the routability tests once actually enabling them to be run, I will include the fixes in the same PR
