### ISSUE TITLE
Conformance test for multiple mirror filters within the same rule

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes-sigs/gateway-api#2210]
**What would you like to be added**:
Conformance test for multiple mirror backends

**Why this is needed**:
https://github.com/kubernetes-sigs/gateway-api/pull/2199 enables support for multiple HTTPRouteFilterRequestMirror filters in the same HTTP Rule.

We should add SupportFeature and conformance test for it.

Support level would be `implementation-specific`.

**Comment by robscott** [comment]
>Support level would be implementation-specific.

I think support level here would actually be extended since we'd expect behavior to be consistent across the implementations that support mirroring to more than one backend.

**Comment by shaneutt** [comment]
This is a feature we already support, so we definitely need this.

/triage accepted

We should get this done for GA.

/milestone v1.0.0
/label release-blocker

**Comment by levikobi** [comment]
I would like to take this if nobody is working on it

**Comment by shaneutt** [comment]
Nobody is, thank you we really appreciate the help getting GA done :bow: 

/assign @levikobi 

Let us know if you get stuck or need help, we're hoping to have this and all other release blockers complete within the next 4-6 weeks.
