### ISSUE TITLE
UnsupportedRoutability and UnsupportedAddress inconsistencies

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#2229]
Minor API nitpicks

UnsupportedRoutability: `This reason is used with "Programmed" and "Accepted" conditions`

UnsupportedAddress: `This reason is used with the "Accepted" condition when the Gateway`

These feel very similar. If one applies to both, I would expect the other?

Also, UnsupportedRoutability is missing from the list of "Possible reasons for this condition to be False are:..." on both condition docs

/assign @dprotaso

**Comment by dprotaso** [comment]
> These feel very similar. If one applies to both, I would expect the other?

I think you're right and maybe we should drop the Reason for `Programmed`

But a few questions:

1. When creating a Gateway - if the address is unsupported and `Accepted` is set to `UnsupportedAddress` - is there a "Programmed" condition?
2. If a Gateway (Programmed=True,Accepted=True) is updated with an invalid address - I assume `Accepted` is set to `UnsupportedAddress` - what happens to the existing `Programmed` condition? 

@robscott do you have thoughts on this? 

> Also, UnsupportedRoutability is missing from the list of "Possible reasons for this condition to be False are:..." on both condition docs

Let me add that

**Comment by dprotaso** [comment]
@howardjohn you might want to close this issue out given the rework required on the GEP
