### ISSUE TITLE
Define what conformance means for L4 LoadBalancers

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/gateway-api#223]
There has always been the goal of using Gateway to fill the role that is currently filled by Services of type LoadBalancer (i.e. a single-purpose layer 4 proxy that sends traffic to a Service). As we decide what spec conformance means, we should ensure that a Gateway that just provides this level of functionality is conformant (i.e. it can omit TLS, HTTP and so on).

**Comment by hbagdi** [comment]
xref #764

**Comment by shaneutt** [comment]
Despite this issue being quite old, we the maintainers are still pretty convinced that we want to have this functionality in a future release. We are marking this `help wanted` as we're looking for contributors with strong use cases to help champion and drive this forward.

**Comment by shaneutt** [comment]
At this point the definition of conformance for L4 is starting to be defined by [GEP 1709](https://gateway-api.sigs.k8s.io/geps/gep-1709/) as part of the #1709 project. The work itself to add the conformance tests is now https://github.com/kubernetes-sigs/gateway-api/issues/1792 and https://github.com/kubernetes-sigs/gateway-api/issues/1794. I believe this covers the original intention of this issue so I'm going to mark it as duplicate but please do re-open it or ping us if you feel there's still something we've missed.
