### ISSUE TITLE
Conformance Profiles: summaries for profiles without content

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#2235]
**What happened**:

In the last couple of PRs to document some conformance profile reports (#2192 , #2232) I noticed that the "summary" field is often empty for reports.

**What you expected to happen**:

At best, the tooling automates a human readable summary that clearly summarizes the results of the test.

At minimum, let's just not emit empty string fields when the field isn't being set.

**Comment by mlavacca** [comment]
You mentioned #2191 in the issue description which does not seem relevant, probably a copy-paste error :)
