### ISSUE TITLE
Allow specifying NodePort for the Listener ports

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/gateway-api#2321]
**What would you like to be added**:
I would like to be able to specify the node port to be used for each Listener port at the Gateway NodePort Svc.

**Why this is needed**:
We are working in a cluster where LoadBalancer svc is not available. We can only use NodePort. It will be much ever ux if the NodePort for a Listener port can be specified in the Gateway object. This will make things more predictable and usable.

**Comment by arkodg** [comment]
another related aspect if retrieving the `nodePort` to `listenerPort` mapping via the Status. The status today is defined at the Gateway level and not the Listener level making this not possible today
https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.GatewayStatusAddress

**Comment by Cajga** [comment]
Is there any other way defined in the Gateway API to "request" NodePort from the Gateway API implementation?

We use Istio in which using NodePort is possible but only thanks to an "implementation specific" annotation.
