### ISSUE TITLE
GatewaySpec Listener CEL block empty Hostname if similar Listeners also present

### ISSUE THREAD

**Issue by rainest** [kubernetes-sigs/gateway-api#2369]
**What happened**:

0.8.0 does not allow a Gateway with two same Port, same Protocol Listeners where one Listener has Hostname set and the other does not. This violates [a CEL rule](https://github.com/kubernetes-sigs/gateway-api/blob/v0.8.0/apis/v1beta1/gateway_types.go#L131) that ensures Listeners have a unique Port/Protocol/Hostname combination.

**What you expected to happen**:

The Gateway passes validation. Per [the above spec comment](https://github.com/kubernetes-sigs/gateway-api/blob/v0.8.0/apis/v1beta1/gateway_types.go#L105-L107):

> one Listener within a group may omit Hostname, in which case this Listener matches when no other Listener matches.

**How to reproduce it (as minimally and precisely as possible)**:

With 0.8.0 installed:

```
$ echo "apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway                                                             
metadata:    
  name: prod-web
spec:           
  gatewayClassName: acme-lb
  listeners:               
  - protocol: HTTP
    port: 80      
    name: http
  - protocol: HTTP
    port: 80      
    name: httphostname
    hostname: http.example" | kubectl create -f -
The Gateway "prod-web" is invalid: spec.listeners: Invalid value: "array": Combination of port, protocol and hostname must be unique for each listener
```

**Anything else we need to know?**:

It looks like

```
(has(l1.hostname) && has(l2.hostname) ? l1.hostname == l2.hostname : true
```
requires a set value to compare if Hostname is equal.

Setting Hostname to `""` or `"*"` does not work around this, as these values violate Hostname's `'^(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'` validation regex.

**Comment by robscott** [comment]
In my opinion this example _should_ be invalid. The spec currently states that the combination of Hostname, Protocol, and Port must be unique:

https://github.com/kubernetes-sigs/gateway-api/blob/c21d0e46019bff1515cad5e80af3d6a48638f255/apis/v1beta1/gateway_types.go#L72-L73

Unfortunately the webhook validation did allow this to happen:

https://github.com/kubernetes-sigs/gateway-api/blob/ab03a594e7db13b8d2579929b204d8d10990fd2b/apis/v1beta1/validation/gateway.go#L145-L165

For completeness, here's the corresponding CEL validation:

https://github.com/kubernetes-sigs/gateway-api/blob/c21d0e46019bff1515cad5e80af3d6a48638f255/apis/v1beta1/gateway_types.go#L131

To me, this is/was a bug in validation. I recognize that if a bug exists long enough, it becomes a feature. I'm not sure if we've already crossed that line here. Would be interested in what others think.

/cc @shaneutt @youngnick

**Comment by robscott** [comment]
This feels conceptually similar to ParentRefs where we're also saying that for ParentRefs to be distinct, either SectionName or Port needs to be set to non-empty + distinct values, x-ref https://github.com/kubernetes-sigs/gateway-api/pull/2350. To avoid confusion here, I think we should do what we can to make sure the definitions of distinct here are as consistent as possible.

**Comment by rainest** [comment]
Considering this invalid would severely limit the ability to use a catch-all wildcard hostname, since you couldn't use it in combination with any other Listeners on the same Port+Protocol. I don't think we'd want that, and the prose indicates that we do want the 0.7 behavior--it's "one Listener within a group [port and protocol combination] may omit Hostname" rather than "a Listener may omit Hostname and match any Hostname if it is the only Listener in the group)".

We could require an explicit non-nil value for the catch-all (either `"*"` or `""`), but it'd be a breaking change (the webhook [used the same regex validation](https://github.com/kubernetes-sigs/gateway-api/blob/v0.7.1/apis/v1beta1/validation/gateway.go#L48-L49) previously, and the spec said to omit it).

IMO empty is fine so long as we can check it and confirm that there are no two Listeners both using it on the same Protocol+Port. Rather, for Hostname alone, the list `["foo.example", "*.example", nil]` has no duplicates, but `["foo.example", "*.example", nil, nil]` does.

Testing that in CEL may be another story, but I assume you can somehow work in a failure condition for `!has(l1.hostname) && !has(l2.hostname)` (from brief testing, you cannot directly compare `l1.hostname == l2.hostname` if one is nil).

**Comment by frankbu** [comment]
This seems like a valid configuration to me. The missing hostname is unique, it essentially behaves like `hostname: *`, right? So `http.example` will match the second listener, everything else will go to the first. It seems no different than if the first listener had `hostname: *.example`, which would be considered a valid unique hostname combination.

**Comment by robscott** [comment]
Yep, I think you're all right. I missed @rainest's reference to the spec in the original issue that very much settles this:

https://github.com/kubernetes-sigs/gateway-api/blob/d031c1641465e16abcc0f29abb5d97ed9db2943a/apis/v1beta1/gateway_types.go#L105-L107

Sorry for the noise here, this is indeed a bug in the CEL validation and we should fix it ASAP.

/triage accepted
/help

**Comment by frankbu** [comment]
I'm no CEL expert, but it seems that the rule just needs to remove the has() part, so it will just check for duplicate hostnames, nil or not.
```
 // +kubebuilder:validation:XValidation:message="Combination of port, protocol and hostname must be unique for each listener",rule="self.all(l1, self.exists_one(l2, l1.port == l2.port && l1.protocol == l2.protocol && l1.hostname == l2.hostname))"
```
