### ISSUE TITLE
Conformance: Add coverage for AttachedRoutes, ensuring count is accurate regardless of Listener or Route validity

### ISSUE THREAD

**Issue by sunjayBhatia** [kubernetes-sigs/gateway-api#2402]
**What would you like to be added**:

Following on from https://github.com/kubernetes-sigs/gateway-api/pull/2396 we should add conformance that covers the exact semantics defined in the API for implementations when setting the Gateway Listener status `AttachedRoutes` count field.

Namely:
- `AttachedRoutes` should be set on Listeners that are valid or invalid
- The count of `AttachedRoutes` should include Routes that are valid or invalid

**Why this is needed**:

The spec now defines the `AttachedRoutes` field to document the number of Route resources that are successfully related to a Gateway, regardless of the validity of either side of the relationship.

**Comment by shaneutt** [comment]
We're going to try to get this into `v1.0.0`, but we don't consider it a _blocker_ for that release.

If someone has some extra time and wants to work on this one, it would be appreciated.

/help
