### ISSUE TITLE
Automate labels for GEP PRs

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#2431]
**What would you like to be added**:

PRs automation which identifies GEP changes and labels them as:

`kind/gep`
`do-not-merge/hold`

**Why this is needed**:

Generally we try to put `do-not-merge/hold` on GEP PRs manually such as to allow more time for the community, and most or all maintainers to explicitly check them out before they merge.

Automatically tagging this way will help make it easier to search for GEP changes, and then also help make sure people can add approvals/lgtms without actually it merging through before more complete consensus is built.

**Comment by cnvergence** [comment]
I would be interested in helping with that

**Comment by shaneutt** [comment]
Ok, thank you!

/assign @cnvergence 
/remove-label help-wanted

Let us know if you have questions or run into any trouble.

**Comment by cnvergence** [comment]
@shaneutt I have opened the PR to add `kind/gep` label first: https://github.com/kubernetes/test-infra/pull/31112
For adding a `do-not-merge/hold` label, I don't see any prow plugin available for this, so probably it will be needed to create one or extend the existing one, wdyt?

**Comment by shaneutt** [comment]
Yep sounds reasonable, thank you for your efforts on this!

**Comment by youngnick** [comment]
/remove-lifecycle rotten

@shaneutt, what do you think, should we look into auto-adding hold or just keep doing it manually and close this out?

For me, I think that now we have `kind/gep` available, manual hold is not too big a deal.

**Comment by shaneutt** [comment]
Yep, we can close this out now.
