### ISSUE TITLE
Unable to match on HTTP pseudo headers that start with : (colon)

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#2455]
**What happened**:

tried to match on a http pseudo header in my HTTPRoute
```
- matches:
    - headers:
      - name: ":scheme"
        value: "http"
```

Got this error 
```
the Kubernetes API server reported that "envoy-gateway-system/httpbin-test-http-3b88a86a" failed to fully initialize or become live: HTTPRoute.gateway.networking.k8s.io "httpbin-test-http-3b88a86a" is invalid: spec.rules[0].matches[0].headers[0].name: Invalid value: ":scheme": spec.rules[0].matches[0].headers[0].name in body should match '^[A-Za-z0-9!#$%&'*+\-.^_\x60|~]+$'
```

**What you expected to happen**:

The HTTPRoute would get accepted and I would be able to add a redirect filter which redirects to https only when
the current request is http, else you end up also getting a redirect for https

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Pseudo headers defined in https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.1

**Comment by arkodg** [comment]
curious why http2 pseudo headers are not supported https://github.com/kubernetes-sigs/gateway-api/blob/9deb057afb6a5796b5101bfbec1988844b6a8c80/apis/v1beta1/httproute_types.go#L433

**Comment by robscott** [comment]
Sorry we missed this one @arkodg! This was in an effort to avoid having multiple ways to express the same thing. Take the example of the `:method` header used in the spec - we already have a method matcher. How would we handle the situation when both were specified?

This is at least theoretically a solvable problem, but it would be helpful to clarify if this is really about having a way to match the scheme of a request or a way to match any arbitrary pseudo header.

**Comment by arkodg** [comment]
thanks for sharing the history !, specific ask here is to provide a way to match `scheme`, should I update the issue title or create a new one ?

**Comment by dprotaso** [comment]
I think a use case for matching on scheme (that works with HTTP1 & 2) would be to help avoid redirect loops 

see here: https://github.com/kubernetes-sigs/gateway-api/issues/1185#issuecomment-1962181068

**Comment by robscott** [comment]
yep, SGTM. I think this is a pretty big gap in the API. A new issue is probably the best way to cover this, but I think it probably justifies a mini-GEP.

**Comment by dprotaso** [comment]
Made a new issue: https://github.com/kubernetes-sigs/gateway-api/issues/2809
