### ISSUE TITLE
Update documentation once v1.0 is released

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2457]
This issue will contain a list of all changes we need to make once v1.0 has been released:

- [x] Replace "upcoming v1.0 release" per https://github.com/kubernetes-sigs/gateway-api/pull/2446#discussion_r1344859308.
- [ ] Update Gateway, GatewayClass, and HTTPRoute examples to use "v1" instead of "v1beta1" (most are in examples directory, but some incomplete examples are embedded directly in site-src markdown)
- [x] Update getting started guide to use v1.0 instead of v0.8.1 (https://gateway-api.sigs.k8s.io/guides/)
- [x] Update readme to use v1.0 instead of v0.8.1

**Comment by sftim** [comment]
Would also be nice to make https://gateway-api.sigs.k8s.io/ visually match https://k8s.io/docs/ more closely.

Want changes to  https://k8s.io/docs/ to make that easier? **It's OK to ask.**

**Comment by robscott** [comment]
> Would also be nice to make https://gateway-api.sigs.k8s.io/ visually match https://k8s.io/docs/ more closely.

That would be great! Any tips for how we can do that?

**Comment by robscott** [comment]
Created https://github.com/kubernetes-sigs/gateway-api/issues/2718 to cover last remaining open item here. Closing this one out.
