### ISSUE TITLE
BackendTLSPolicy: Add CEL Tests

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2473]
**What would you like to be added**:
Tests to ensure the CEL validation added in #2448 is working as expected.

**Why this is needed**:
All other CEL validations have corresponding go tests in https://github.com/kubernetes-sigs/gateway-api/tree/main/pkg/test/cel. Without it, it's awfully hard to ensure that the CEL we've written covers all the inputs we want to allow or prevent.

**Comment by Ygnas** [comment]
I'm going to look into it, as I believe iI have hit a problem with the rules
