### ISSUE TITLE
Tighten requirements for optional BackendRefs

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#2485]
**What would you like to be added**:
A way to warn the user that they have not specified any `backendRefs` within their HTTP Route rule helping them debug their config issues.

**Why this is needed**:

The `backendRefs` field within a [HTTPRoute Rule](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPRouteRule) is optional. This probably makes sense when a `RequestRedirect` filter is attached to the rule, but for most cases at least a single `backendRef` is required

Relates to https://kubernetes.slack.com/archives/CR0H13KGA/p1697227923325639

**Comment by kflynn** [comment]
Gut response: start with very tight validation and just have CEL refuse to allow `empty backendRefs` unless `RequestRedirect` is specified. I’m having a hard time coming up with a case where an extension or policy attachment should be able to supply backendRefs when there aren’t any — we can always relax the requirement if we find use cases later.

**Comment by danehans** [comment]
> start with very tight validation and just have CEL

IMHO Before starting with implementing in CEL, the HTTPRouteRule spec should be updated to include these details. For example:

```go
type HTTPRouteRule struct {
...
	// BackendRefs must be unset when the rule contains a RequestRedirect filter.
        // Otherwise, BackendRefs is a required field that...
	//
	// Support for weight: Core
	//
	// +optional
	// +kubebuilder:validation:MaxItems=16
	BackendRefs []HTTPBackendRef `json:"backendRefs,omitempty"`
...
}

**Comment by robscott** [comment]
Thanks @danehans! Agree that updating the spec here is a good starting point. One nit - I think we need to allow BackendRefs to be empty when an "ExtensionRef" filter is set. 

Adding CEL validation is going to be tough here since we're trying to provide backwards compatibility. With that said, I think we might be able to justify adding validation that lets existing empty/unspecified backendRefs through. For example:

```
!has(self.backendRefs) || size(self.backendRefs) == 0 ? size(oldSelf.backendRefs) == 0 || !self.filters.exists_one(f, f.type == "RequestRedirect" || f.type == "ExtensionRef") : true
```

**Comment by kflynn** [comment]
@robscott, do you have a use case in mind for an `ExtensionRef` filter with no `BackendRefs`?

**Comment by robscott** [comment]
> @robscott, do you have a use case in mind for an `ExtensionRef` filter with no `BackendRefs`?

Don't have a specific use case in mind, but also the very nature of `ExtensionRef` means that we basically can't rule anything out. Maybe an ExtensionRef could be used for more advanced redirect configuration for example.
