### ISSUE TITLE
Add a new API Types Page

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2499]
**What would you like to be added**:
It would be great to have a new API Types overview page at https://gateway-api.sigs.k8s.io/api-types/ for Gateway API that had a similar structure to https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ and linked out to each of our individual API Type docs. This page could then be linked from kubernetes.io docs. To accomplish this we'd need to add a new index page to `site-src/api-types`.

**Why this is needed**:
This would enable better integration with kubernetes.io documentation, as suggested by @sftim in Slack: https://kubernetes.slack.com/archives/CR0H13KGA/p1697817925108689.

**Comment by sftim** [comment]
No need to copy the structure of https://kubernetes.io/docs/reference/kubernetes-api/ too closely - that layout there is a work in progress.
