### ISSUE TITLE
spec.rules[0].matches: Too many

### ISSUE THREAD

**Issue by Rez0k** [kubernetes-sigs/gateway-api#2501]
Hi,

I am getting the following error:
```
The HTTPRoute "###" is invalid: spec.rules[0].matches: Too many: 20: must have at most 8 items
```

I need all 20 routes, why is there a limit and how can I bypass this limitation if possible?

if I can't bypass this limitation what is the workaround? creating multiple http routes objects?

I read this https://github.com/kubernetes-sigs/gateway-api/issues/1485 issue but I coudn't understand wheater or not you are going to increase / delete this limitation in the future.

**Comment by youngnick** [comment]
There is a size limit because there is a limit to the size of any one Kubernetes object, so we need to ensure that we don't hit that.

Also, we do prefer that people create multiple, smaller HTTPRoute objects, and this is designed to have people do that.

It's _possible_ we might increase this limit at some point, but unlikely, because of the reasons above.

If you post your HTTPRoute (or at least a redacted version), maybe someone can assist with splitting it up.

**Comment by Rez0k** [comment]
> There is a size limit because there is a limit to the size of any one Kubernetes object, so we need to ensure that we don't hit that.
> 
> Also, we do prefer that people create multiple, smaller HTTPRoute objects, and this is designed to have people do that.
> 
> It's _possible_ we might increase this limit at some point, but unlikely, because of the reasons above.
> 
> If you post your HTTPRoute (or at least a redacted version), maybe someone can assist with splitting it up.

I understand but I still believes the limit should be more than 8, thanks

**Comment by devopsmash** [comment]
Hi @youngnick ,
Got this error too, you need to understand that in some places the developers has legacy routes that hard to be changed.

It will be great if you can add the ability to configure the limit with environment variable or some other ways, so each user will be responsible for his configuration.

**Comment by robscott** [comment]
Unfortunately increasing the max size of an individual list has significant knock-on effects as @youngnick mentioned. To highlight consider the following:

**16 max HTTPRoute rules:**
https://github.com/kubernetes-sigs/gateway-api/blob/ee42a6d5d81283d9f41a85627b93e4492b876638/apis/v1/httproute_types.go#L119

**8 max HTTPRouteRule matches:**
https://github.com/kubernetes-sigs/gateway-api/blob/ee42a6d5d81283d9f41a85627b93e4492b876638/apis/v1/httproute_types.go#L192

**16 max HTTPRouteMatch header matches:**
https://github.com/kubernetes-sigs/gateway-api/blob/ee42a6d5d81283d9f41a85627b93e4492b876638/apis/v1/httproute_types.go#L605

**16 max HTTPRouteMatch query param matches:**
https://github.com/kubernetes-sigs/gateway-api/blob/ee42a6d5d81283d9f41a85627b93e4492b876638/apis/v1/httproute_types.go#L617

That means that each rule can specify 8 matches, and each match can specify 16 header matches and 16 query param matches 🤯. If you consider that we allow 16 rules within a route, you can see that this can quickly result in untenable resource size. I think the only reasonable way to make significant increases here would be if Kubernetes API machinery allowed us to make the max size conditional - ie this can only be larger than x if there is only 1 total route rule.

In the meantime, it should be entirely possible to split different matches into different route rules to get around this limitation.

**Comment by youngnick** [comment]
As I said to @Rez0k, I'd be happy to take a look at sample HTTPRoutes and suggest ways that I think it would be better to break them up - I have an outstanding TODO to write some documentation around best practices here, but I need more real-world data to make it useful.

**Comment by Rez0k** [comment]
> As I said to @Rez0k, I'd be happy to take a look at sample HTTPRoutes and suggest ways that I think it would be better to break them up - I have an outstanding TODO to write some documentation around best practices here, but I need more real-world data to make it useful.

Thanks, I decoupled my 20 paths into groups of 8 in each match array, all in the same httproue single object, and it seems to work fine.
the helm template wasn't fun, though 😇

**Comment by srinathrangaramanujam** [comment]
I understand the technical implication. is it possible to document this behaviour?

**Comment by youngnick** [comment]
Hmm, the behavior is already documented in the validations, but I'm not sure how we should document this aside from that. I think that may need a fresh issue, would you mind opening one?

**Comment by srinathrangaramanujam** [comment]
@youngnick  sure let me raise a new one. We could add these rules into the API spec for the [HttpRoutes](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRoute)

**Comment by 804e** [comment]
> > As I said to @Rez0k, I'd be happy to take a look at sample HTTPRoutes and suggest ways that I think it would be better to break them up - I have an outstanding TODO to write some documentation around best practices here, but I need more real-world data to make it useful.
> 
> Thanks, I decoupled my 20 paths into groups of 8 in each match array, all in the same httproue single object, and it seems to work fine. the helm template wasn't fun, though 😇

hi, @Rez0k Can you give an example yaml file?

**Comment by 804e** [comment]
Increasing this property value can expands the limit, it also in file https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml, 9768 line
https://github.com/kubernetes-sigs/gateway-api/blob/45c7d4ff434f744b5bf55ed81dfd059d78cd33f3/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml#L2723C1-L2724C1

**Comment by youngnick** [comment]
@804e, the limit has been chosen to limit the combinatorial complexity and resulting size of the object. We've had a few discussions before, but have not found a compelling enough reason to increase the limit yet. If you would like to open a fresh issue outlining your reasons, please feel free to do so.
