### ISSUE TITLE
Add v1.0 conformance profile of Envoy Gateway

### ISSUE THREAD

**Issue by Xunzhuo** [kubernetes-sigs/gateway-api#2557]
**What would you like to be added**:

Add v1.0 conformance profile of Envoy Gateway

/assign

**Comment by shaneutt** [comment]
We don't usually open issues for adding these reports for individual implementations, as we don't track individual implementation progress in this repository. Not a big deal, but there's no reason to track this as an issue, we can just track the accompanying PR.
