### ISSUE TITLE
Docs could use clarity regarding nested support levels

### ISSUE THREAD

**Issue by gcs278** [kubernetes-sigs/gateway-api#2620]
**What happened**:
Pardon me if I'm missing something, but it seems like the docs could use clarity regarding nested support levels. The main scenario that is causing confusion for me: **An extended struct with a core field.**

I've done a bit of searching, and it seems like there's a general [consensus](https://github.com/kubernetes-sigs/gateway-api/pull/1004#discussion_r841285288) that support levels are relative (not absolute) to it's parent object/field.

The documentation speaks to a particular situation where the parent has a dynamic support level depending on the object within which it is utilized: https://github.com/kubernetes-sigs/gateway-api/blob/efe23a0d6ad8816ec5246a8ea7004cc2c6c469f9/site-src/concepts/conformance.md?plain=1#L49-L55

However, I'm struggling with the sentence: `Fields within this struct may express separate Core and Extended support levels, but those levels must not be interpreted as exceeding the support level of the parent struct they are embedded in.`

Is this saying:
- At all times (even in relative terms), Core fields with Extended structs as parents should be interpreted not as Core but rather as Extended.
- Or is this trying to clarify that fields are indeed relative to their parent?

**What you expected to happen**:

Either clarity regarding nested support levels, or an explanation that I'm misinterpreting the docs that already provide enough clarity and closing of this issue.

**How to reproduce it (as minimally and precisely as possible)**:

1. Be me
2. Read the [overlapping-support-levels docs](https://gateway-api.sigs.k8s.io/concepts/conformance/#overlapping-support-levels)
3. Slightly confused

**Anything else we need to know?**:

Related issue: https://github.com/kubernetes-sigs/gateway-api/issues/655

Real Life Example of nested Core Support in Extended Struct:
- [`GRPCRoute`](https://github.com/kubernetes-sigs/gateway-api/blob/8113fe09efb72999af7bcc0f7c8c62b6305e4809/apis/v1alpha2/grpcroute_types.go#L38) struct is Extended, but has [`spec.hostnames`](https://github.com/kubernetes-sigs/gateway-api/blob/8113fe09efb72999af7bcc0f7c8c62b6305e4809/apis/v1alpha2/grpcroute_types.go#L138) as Core

**Bonus questions:**
- Is it valid to have a Core struct with all Extended fields?
- Can you have a required (via CRD validation) Extended field?

Thanks.

**Comment by shaneutt** [comment]
I think it's probably reasonably intuitive to think if something under extended is labeld "core", it means you have to implement it IF you implement the extended feature.

At a language, and technical level however using "core" for this seems to dilute the meaning of "core".

At minimum it would at least be good to document this further so it's nice and clear if we decide this is how we intend to do this. At best it might be good to come up with different language to differentiate "required sub-feature of extended features".
