### ISSUE TITLE
Conformance test `HTTPRouteInvalidParentRefSectionNameNotMatchingPort` included in `core` instead of `extended`

### ISSUE THREAD

**Issue by ciarams87** [kubernetes-sigs/gateway-api#2625]
**What happened**:
[This PR](https://github.com/kubernetes-sigs/gateway-api/pull/2582) introduced a new conformance test to ensure that when both Port and SectionName are specified in a HTTPRoute ParentRef, the name and port of the selected listener must match both specified values.

The issue is that this test was added to the `core` suite, but `ParentRef.Port` has [extended support, not core](https://github.com/kubernetes-sigs/gateway-api/blob/1b14708b143e837fd94be97698ecbe0e6a4e058d/apis/v1/shared_types.go#L150).

**What you expected to happen**:
Tests for features that are extended support should be part of the extended test suite.

**How to reproduce it (as minimally and precisely as possible)**:
Run the conformance test suite against an implementation without `ParentRef.Port` support. See https://github.com/nginxinc/nginx-gateway-fabric/actions/runs/7041855950/job/19165071974 for an example.

**Anything else we need to know?**:

**Comment by ciarams87** [comment]
Oh, I missed this PR - thanks @shaneutt and @mlavacca !

**Comment by shaneutt** [comment]
Yep, sorry for the confusion just a bit of bad timing!

/assign @mlavacca 

However if you are looking for more opportunities to contribute to Gateway API and need some support in that, let us know! We're very happy to try and provide that support and we're very active on `#sig-network-gateway-api` in [Kubernetes Slack](https://kubernetes.slack.com)!
