### ISSUE TITLE
GEP-713: no way to target specific kind of namespace

### ISSUE THREAD

**Issue by spacewander** [kubernetes-sigs/gateway-api#2664]
**What would you like to be added**:

An extra field in TargetRef to distinguish the kind of namespace.

**Why this is needed**:

Different kinds of Namespace are listed in the hierarchy picture of GEP-713 (https://github.com/kubernetes-sigs/gateway-api/blob/main/geps/images/713-hierarchy.png). For example, there is "Gateway Namespace" above "Gateway", and "Route Namespace" below "Gateway". However, it is not clear how to target a specific namespace. If we simply specify the `Kind` in `TargetRef` to `Namespace`, there is no way to specify whether it is a "Gateway Namespace" or "Route Namespace", which have different behaviors.

Therefore, an extra field might be needed to distinguish them.

**Comment by spacewander** [comment]
Or we can use the SectionName field to do this.

**Comment by youngnick** [comment]
To target a specific namespace, it's expected that a single Policy will use `kind: Namespace` plus the `name` field. We've specifically designed `targetRef` to _not_ be able to reference multiple targets. Policy Attachment is complicated enough already.

**Comment by spacewander** [comment]
I see. Thanks for your reply!
