### ISSUE TITLE
gateway-api-addmission-server v1.0.0 doenst know "gateway" and "gatewayclass"

### ISSUE THREAD

**Issue by xEBIx** [kubernetes-sigs/gateway-api#2673]
**What happened**:
I installed "standard_install.yaml" from the kubernetes documentation which wants to install the pod version 0.5.0, which doesnt work because the cluster is running on arm CPUs. After i found out about that, i looked it up and found this repo and installed release 1.0.0 of standard-install.yaml and webhook-install.yaml. Seemed to work, but the helm chart of traefik kept failing. After some hours of searching a solution i came back to this and saw this log line in the admission-server log: 
I1212 18:23:39.735946       1 main.go:92] admission webhook server started and listening on :8443
E1212 18:39:03.921563       1 server.go:101] failed to process request: unknown resource 'gateways'

After some fideling around again, i downgraded the container to v0.8.1 by editing the webhook-install.yaml v1.0.0 image source line. 
Now the traefik helm chart works...

After some time I only tried to install a gateway, just to safe some time which will get lost when using the hole helm chart. 
But when I tried to, there was a second log line which said the same, despite gatewayclass instead of gateway. 

**What you expected to happen**:
Installing the webhook-install.yaml and the admission-server does not output that log. 

**How to reproduce it (as minimally and precisely as possible)**:
I dont know about possible circumstances, but I suppose install the v1.0.0 webhook and try to install traefik with the experimental gateway-api function active.

**Anything else we need to know?**:
Cluster is version 1.28 currently.

**Comment by xEBIx** [comment]
Yes, traefik is trying to use v1alpha2, that is true. It makes sense very well, what you say.  

Thanks

**Comment by Xunzhuo** [comment]
Similar to https://github.com/kubernetes-sigs/gateway-api/issues/2674#issuecomment-1867197041 ? Can we close this now ?

**Comment by robscott** [comment]
Thanks for catching this @Xunzhuo! Yes, this was covered by #2674 which has now been fixed. Closing this one out.
