### ISSUE TITLE
Webhook manifest incorrectly limited to v1alpha2 and v1beta1 API versions

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2674]
**What happened**:
As initially reported in #2673, the API resources and versions that the webhook is watching are outdated:

https://github.com/kubernetes-sigs/gateway-api/blob/05536370b28e6d827b7b5e15ee527a2d79331642/config/webhook/admission_webhook.yaml#L9-L12

**What you expected to happen**:
These should be aligned directly with the versions specified in the corresponding code: https://github.com/kubernetes-sigs/gateway-api/blob/05536370b28e6d827b7b5e15ee527a2d79331642/pkg/admission/server.go#L48-L97

**Comment by Xunzhuo** [comment]
Should we close this since https://github.com/kubernetes-sigs/gateway-api/pull/2595 ?

**Comment by robscott** [comment]
Fixed by @2702

**Comment by chris-mirek-holidu** [comment]
> Fixed by @2702

I think you meant to tag the issue, not me.
