### ISSUE TITLE
The User Guide lacks information for beginners

### ISSUE THREAD

**Issue by NoZomIBK** [kubernetes-sigs/gateway-api#2697]
The Guides require knowledge about the gateway api resources without explaining it.
For example the [Simple Gateway](https://gateway-api.sigs.k8s.io/guides/simple-gateway/) guide assumes a gateway class `acme-lb`. There is no explaination what a gateway class is, what it does, why i need it and how it is created. 

As a beginner I want a getting started guide which I can work through from the beginning and have a proper understanding at the end. It falls a bit into the second todo in #558 about having the guides create a real deployment instead of just theoretical steps. Having a guide actually creating something on a testsystem without assuming anything (apart maybe from basic kubernetes stuff, but even that could be done shortly in the first step), would benefit beginners and speed up their understanding of how the parts work with each other

**Comment by robscott** [comment]
Completely agree, thanks for raising this issue @NoZomIBK! I'd recently had similar thoughts when reviewing #2699, it be really great to have a standardized/placeholder GatewayClass we used everywhere so it was clear that it needed to be replaced. A better option would be to find a way to allow users to enter their own values when reading the docs (similar to [what GKE does](https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-gateways)), but I'm not sure how to make that work with our current system for docs. In either case, any improvements would be very welcome here.

/help

**Comment by sawsa307** [comment]
I would like to work on this.

/assign
