### ISSUE TITLE
Update Remaining Gateway, GatewayClass, and HTTPRoute examples to v1

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2718]
**What would you like to be added**:
Update the remaining Gateway, GatewayClass, and HTTPRoute examples from v1beta1 to v1.

**Why this is needed**:
Before the v1.0 release we left examples that were used in documentation with v1beta1. Now that we've release v1.0, we should update any remaining Gateway, GatewayClass, and HTTPRoute examples to use `apiVersion: gateway.networking.k8s.io/v1`.

**Comment by pradeepnnv** [comment]
I would like to work on this issue.

**Comment by robscott** [comment]
Thanks @pradeepnnv!

/assign @pradeepnnv
