### ISSUE TITLE
BackendTLSPolicy wellKnownCACerts field "System" value should not be core

### ISSUE THREAD

**Issue by sunjayBhatia** [kubernetes-sigs/gateway-api#2726]
We're working on implementing BackendTLSPolicy in Contour and are a little confused about the `wellKnownCACerts` field.

It is marked as `Support: Core for “System”` in the spec but in the [GEP](https://gateway-api.sigs.k8s.io/geps/gep-1897/#api) the usage of system certificates is documented as implementation-specific: `The use and definition of system certificates is implementation-dependent, and the intent is that these certificates are obtained from the underlying operating system.`

It looks like the spec was updated here: https://github.com/kubernetes-sigs/gateway-api/pull/2448#discussion_r1342170962

While I don't disagree that implementations would not be able to support some form of fetching system certs to use, I would still argue the support for this field should still be implementation-specific.

If a field is marked core I would expect a conformance test to exist for it eventually and that all implementations should to be able to pass a test verifying the behavior it introduces, regardless of how exactly they make it work. I'm not sure how a conformance test for this would work against all implementations.
- Would this mean that we assert that a TLS connection to a backend app is verified on the Gateway implementation end of the connection with a specific root CA cert from the system?
- What happens if say the test expects a server certificate to be verified but an implementation has a newer/older version of an OS package providing the root certs?
- If an implementation decides to explicitly use a container image with no filesystem/minimal OS packages, how would this work?

This seems like this test is going to start mandating a specific runtime environment for implementations, which I don't think is desirable.

**Comment by howardjohn** [comment]
Regardless of the specific field, this seems to be making the assertion that if we cannot write a very good conformance test for the API, it cannot be core. I am a bit worried about this approach; IMO we should be building an API that meets our users needs, and conformance tests are a **best effort** way to codify an implementation is meeting those. Having a good API and no/limited conformance is better than a bad API with perfect conformance.


> What happens if say the test expects a server certificate to be verified but an implementation has a newer/older version of an OS package providing the root certs?

IMO the Core part is a concept of "System", not that each impl has the exact same set. Its fine to have variations on what is considered "System".

> If an implementation decides to explicitly use a container image with no filesystem/minimal OS packages, how would this work?

I don't think they should do this. Almost every minimal OS/container i have seen includes system certificates since it breaks a lot if they are not included.

That being said, with my above stance I suppose technically an impl could say "System" is a null set...

**Comment by sunjayBhatia** [comment]
> this seems to be making the assertion that if we cannot write a very good conformance test for the API, it cannot be core

It looks like we've documented this explicitly here: https://gateway-api.sigs.k8s.io/concepts/conformance/#2-support-levels

```
Core features will be portable and we expect that there is a reasonable roadmap for ALL implementations towards support of APIs in this category.
```

```
Behavior and feature in the Core and Extended set will be defined and validated via behavior-driven conformance tests. Implementation-specific features will not be covered by conformance tests.
```

I don't think a field being marked as implementation-specific reduces the user value/ability to address user need, it just means we don't expect all implementations to enable the specified behavior in a uniform way so users should not expect an identical experience.

**Comment by sunjayBhatia** [comment]
From the community meeting:
- agreement that this will (at the very least initially) be moved to implementation-specific
- update the documentation of the relationship between the `caCertRefs ` and `wellknownCACerts` fields
  - one of the two options must be specified
  - if `wellknownCACerts` is specified but not supported, Policy is rejected and status is set appropriately

/assign
