### ISSUE TITLE
Improve conformance reports structure

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/gateway-api#2740]
**What would you like to be added**:

https://github.com/kubernetes-sigs/gateway-api/pull/2391 proposed a new way of organizing conformance reports belonging to multiple organizations and provide a README.md file for each of them; such a README.md file should provide a brief description of the project, a table of content, and instructions on how to reproduce the claimed results.
To achieve the above, the related [GEP paragraph](https://github.com/kubernetes-sigs/gateway-api/blob/main/geps/gep-1709/index.md#reports-submission) needs to be implemented.

/area conformance

**Comment by robscott** [comment]
@mlavacca are you intending to move to that for only v1.1+ reports or should we do some kind of backfill?

**Comment by mlavacca** [comment]
> @mlavacca are you intending to move to that for only v1.1+ reports or should we do some kind of backfill?

I am very open to suggestions. I do not think we should organize all the reports this way; maybe we can leave the pre-graduation reports as they are and start applying this structure from 1.0. What do you think?

**Comment by shaneutt** [comment]
> maybe we can leave the pre-graduation reports as they are and start applying this structure from 1.0. What do you think?

That's going to happen naturally anyway, unless you intend to modify git history.

If the ask is "we don't require the new reporting structure until `v1.1` lands" I don't really see any problem with that, we just update all current ones slightly before release.

**Comment by youngnick** [comment]
I think if we're going to cut things over, we should cut them over and make the changes. I did a similar thing with the GEP shuffle, and, while it was a big PR, it makes it much easier for everyone.

Trying to keep track of two different options is very complicated - I think that putting extra effort into only having one way to do things is worth it.

**Comment by shaneutt** [comment]
Given how things are going to land timing wise, I have my suspicions that it's all gonna come down naturally at one time anyhow (e.g. we're aiming to get these last few conformance profiles bits done before Kubecon Paris, which is also when we want to release v1.1).
