### ISSUE TITLE
Conformance feat: Is it possible to add response.body to CapturedResponse?

### ISSUE THREAD

**Issue by ShyunnY** [kubernetes-sigs/gateway-api#2757]
**What would you like to be added**:

I hope to add `response.body` in `CapturedResponse`, which will allow us to get more information when writing e2e tests. As I can see, the `body` field is retained in the code, but it is not set in `CapturedResponse`

**Why this is needed**:

When I wrote the e2e test related to backend weight, I found that just getting the response metadata did not allow me to clearly know where the traffic went? Therefore, I could not determine the correctness of the weight configuration, I could not use other information of the response Determine the true destination of the traffic.

**Comment by youngnick** [comment]
I changed the title to make it clearer that this is a conformance feature.
