### ISSUE TITLE
Bump the k8s.io group with 5 updates

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#2769]
**What happened**:

Dependabot failed to provide a good patch in https://github.com/kubernetes-sigs/gateway-api/pull/2764

**What you expected to happen**:

This needs manual correction.

**Anything else we need to know?**:

A few times in the past we've made fixing dependency into an issue. This might seem a little overkill, as we could probably just as easily do the fix in the dependabot PR, however as a project we have a really hard time providing `good first issues` and we know the community is always hungry for ways to contribute so we occasionally set these aside as a really easy way to get some commits into the project for those who are looking for a way. So we'll leave this available for anyone who wants a quick and easy way to contribute.

**Comment by jongwooo** [comment]
Can I work on this issue?

**Comment by shaneutt** [comment]
Yes, and thank you!

/assign @jongwooo 

Let us know if you run into any trouble.

**Comment by jongwooo** [comment]
It appears that #2762 and #2763 are similar issues to #2764.
