### ISSUE TITLE
Gateway API CRDs not working with Traefik, when Gateway functionality activated in traefik

### ISSUE THREAD

**Issue by xEBIx** [kubernetes-sigs/gateway-api#2771]
I am using the experimental-install.yaml of Version 1.0.0, or the standard-install.yaml, issue will be the same. 
This seems the same issue, I already filed, but with the CRDs rather than the admission-server.

**What happened**:
If I try to install Traefik by Helm now, with the Gateway options active (kubernetesGateway / enabled: true) I get this Error:
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "traefik-gateway" namespace: "traefik" from "": no matches for kind "Gateway" in version "gateway.networking.k8s.io/v1alpha2"
ensure CRDs are installed first, resource mapping not found for name: "traefik" namespace: "" from "": no matches for kind "GatewayClass" in version "gateway.networking.k8s.io/v1alpha2"
ensure CRDs are installed first]

**What you expected to happen**:
Traefik installs just fine. 

**How to reproduce it (as minimally and precisely as possible)**:
Install the Gateway CRDs v1.0.0, and try to install Traefik with kubernetesGateway / enabled: true in the values.yaml. 

**Anything else we need to know?**:
When I use the CRD files from Traefik (https://doc.traefik.io/traefik/reference/dynamic-configuration/kubernetes-gateway/#definitions) it will work, but they replace the whole CRD. But this is breaking cert-manager, and possible kubectl. As I have issues, with the ACME request returning 404 rather than 200, so the gateway rerouting is not working. And it will be mixed up than, because Traefik only delivers 3 CRDs, "gatewayclasses.gateway.networking.k8s.io","gateways.gateway.networking.k8s.io" and "httproutes.gateway.networking.k8s.io".
Maybe we can have both Versions, v1 and v1alpha2 in the CRD? Traefik doesnt seem to update to the new gateway CRD version soon. 
And then I have to replace the CRDs again, becuase the cert-manager drops this error, as they obviously use v1:
"propagation check failed" err="the server could not find the requested resource (post httproutes.gateway.networking.k8s.io)" logger="cert-manager.challenges" resource_name="example-issuer-account-key-1-2005002160-3865645027" resource_namespace="whoami" resource_kind="Challenge" resource_version="v1" dnsName="whoami.elite-penner.de" type="HTTP-01"
Which makes it impossible to get it running, because now, traefik cant read the gateway anymore:
W0214 15:38:40.493250       1 reflector.go:424] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: failed to list *v1alpha2.Gateway: the server could not find the requested resource (get gateways.gateway.networking.k8s.io)
E0214 15:38:40.497621       1 reflector.go:140] k8s.io/client-go@v0.26.3/tools/cache/reflector.go:169: Failed to watch *v1alpha2.Gateway: failed to list *v1alpha2.Gateway: the server could not find the requested resource (get gateways.gateway.networking.k8s.io)

**Comment by youngnick** [comment]
Thanks for logging this issue @xEBIx, but this one needs to be fixed by the Traefik team - their Helm chart needs to be updated to use the `v1` objects instead of the `v1alpha2` objects.

I suggest opening an issue there.
