### ISSUE TITLE
Add HAProxy Kubernetes Ingress Controller to Gateway API Implementation page

### ISSUE THREAD

**Issue by NickMRamirez** [kubernetes-sigs/gateway-api#2779]
**What would you like to be added**:

On https://gateway-api.sigs.k8s.io/implementations/, I'd like to add the following implementation:

> ### HAProxy Kubernetes Ingress Controller
>
> HAProxy Kubernetes Ingress Controller is an open-source project maintained by HAProxy Technologies that provides fast and efficient traffic management, routing, and observability for Kubernetes. It has built-in support for the Gateway API since version 1.10. The same deployment of the ingress controller will allow you to use both the Ingress API and Gateway API. See the [documentation](https://www.haproxy.com/documentation/kubernetes-ingress/gateway-api/enable-gateway-api/) for more details. In the [GitHub repository](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/gateway-api.md), you will also find additional information about supported API resources.

**Why this is needed**:

To provide Gateway API implementation information for those looking in the K8s docs.

Relevant source file: https://github.com/kubernetes-sigs/gateway-api/blob/main/site-src/implementations.md

**Comment by robscott** [comment]
This is great to see, thanks for filing this @NickMRamirez! Feel free to make a PR to add HAProxy to the implementations list.
