### ISSUE TITLE
Implement `gwctl describe namespaces`

### ISSUE THREAD

**Issue by gauravkghildiyal** [kubernetes-sigs/gateway-api#2795]
We ideally want to have something like this as the output for `gwctl describe namespace my-namespace`

```
Name: my-namespace
Labels: 
- key1: value1
- key2: value2
Annotations: 
- key1: value1
- key2: value2
Status: Active
DirectlyAttachedPolicies:
  TYPE                   NAME
  ----                   ----
  TimeoutPolicy.foo.com  demo-timeout-policy-on-namespace
  RetryOnPolicy.baz.com  demo-retry-policy-1
```

If it makes things easy, to start with, you can ignore the `Label`, `Annotation` and `Status` fields and do that in a follow up PR (once you are somewhat comfortable with the codebase). FYI: Adding those fields involves [adding a Namespace resource](https://github.com/kubernetes-sigs/gateway-api/blob/faca85dee9c521d05ba2de537326fd7eb05808bf/gwctl/pkg/resourcediscovery/nodes.go#L250-L262) (instead of the just the name) to the Namespace node, and then populating it within the [discoverNamespaces](https://github.com/kubernetes-sigs/gateway-api/blob/faca85dee9c521d05ba2de537326fd7eb05808bf/gwctl/pkg/resourcediscovery/discoverer.go#L228-L241)

**Comment by gauravkghildiyal** [comment]
@Devaansh-Kumar -- Please use "/assign" to assign this to yourself. Do reach out if you get stuck somewhere

**Comment by Devaansh-Kumar** [comment]
@gauravkghildiyal I have some confusions regarding how to phrase the command. 
1. Ideally we want to use the command in the following way: `gwctl describe namespace my-namespace`. If the user types just `gwctl describe namespace` should be describe all the namespaces available or just return an error asking to specify a namespace? And what should the behavior be if `-n` flag is used? According me having `-n` flag does not make sense.
2. For just the namespace name and DirectlyAttachedPolicies, should I create a function like `DiscoverResourcesForNamespace` in `discover.go`?

**Comment by gauravkghildiyal** [comment]
@Devaansh-Kumar Those are valid questions.
1. Yes you are right, for `gwctl describe namespace`, we will describe all namespaces. I think what will help you here is that we're trying to match the behaviour of `kubectl`. Similar to `kubectl`, `-n` flag is redundant for namespaces.
2. Yes you are on the right track.

**Comment by Devaansh-Kumar** [comment]
@gauravkghildiyal I have figured out how to fetch the namespace details from the API server. I created a function called `fetchNamespace` in `discover.go` for that.
```golang
func fetchNamespace(ctx context.Context, k8sClients *common.K8sClients, filter Filter) ([]unstructured.Unstructured, error) {
	gvr := schema.GroupVersionResource{
		Group:    "",
		Version:  "v1",
		Resource: "namespaces",
	}

	if filter.Name != "" {
		// Use Get call
		namespace, err := k8sClients.DC.Resource(gvr).Get(ctx, filter.Name, metav1.GetOptions{})
		if err != nil {
			return []unstructured.Unstructured{}, err
		}
		return []unstructured.Unstructured{*namespace}, nil
	}

	// Use List call.
	listOptions := metav1.ListOptions{
		LabelSelector: labels.SelectorFromSet(filter.Labels).String(),
	}
	var namespacesList *unstructured.UnstructuredList
	namespacesList, err := k8sClients.DC.Resource(gvr).Namespace(filter.Namespace).List(ctx, listOptions)
	if err != nil {
		return nil, err
	}

	return namespacesList.Items, nil
}
```

I call this function in `DiscoverResourcesForNamespace` function. But I cannot understand how to populate `resourceModel`
This is a sample code that I wrote for `DiscoverResourcesForNamespace` function.
```golang
func (d Discoverer) DiscoverResourcesForNamespace(filter Filter) (*ResourceModel, error) {
	ctx := context.Background()
	resourceModel := &ResourceModel{}

	namespaces, err := fetchNamespace(ctx, d.K8sClients, filter)
	if err != nil {
		return resourceModel, err
	}
	resourceModel.addNamespace(namespaces...) // This is where i am facing issue

	d.discoverNamespaces(ctx, resourceModel)
	d.discoverPolicies(ctx, resourceModel)

	// resourceModel.calculateEffectivePolicies()

	return resourceModel, nil
}
```

**Comment by gauravkghildiyal** [comment]
You don't need to use unstructured for namespaces -- simply use the `k8sClients.Client` to fetch a concrete `corev1.Namespace` typed resource.

In other words:
1. Fetch all namespaces
2. Wrap them in their respective nodes (inside `addNamespace`)
