### ISSUE TITLE
GEP-1748: Use ServiceExport instead of ServiceImport as parentRef

### ISSUE THREAD

**Issue by costinm** [kubernetes-sigs/gateway-api#2831]
One of the main improvements in Gateway API is separating the 'frontend' and 'backend' roles. 
ServiceImport fits very well as a 'backend' - as used in the examples in GEP 1748.

However in 'mesh' use cases it may be more intuitive and clear to have the ServiceExport as a parent. 

An additional benefit:  ServiceExport is created by a user ( usually with RBAC permissions) and represent the intent to have a service available in all clusters. ServiceImport is usually created by an automation tool / MCS implementation. For a user to create a proper config with helm or kubeconfig they would need to wait for the ServiceImport to show up ( or attempt to create one directly). 

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by howardjohn** [comment]
What if I have 

Cluster A: ServiceExport foo
Cluster B: wants to route to 'foo.clusterset.local'

Cluster B only has a ServiceImport, no ServiceExport to refer to?

> For a user to create a proper config with helm or kubeconfig they would need to wait for the ServiceImport 

They can point to it in the route at any point, it just won't be valid until its propogated so seems ok?

**Comment by costinm** [comment]
If ClusterB wants to route to foo.clusterset.local - but cluster A defines the ServiceExport - then ClusterB won't be able to do that, and that's working exactly as intended. 

The routes and all policies should stay in Cluster A - just like we don't allow other namespaces to define routes.

Of course we may use grants and other mechanisms to relax this - but fundamentally a cluster should be an even stronger boundary than a namespace. 

Breaking the cluster boundaries is IMO a far larger and more dangerous issue - in particular when clusters are in different (cloud vendor) projects and have different admin. The mesh admin ( or fleet admin ) may even designate
'config clusters' where ServiceExports are allowed - we can discuss what would be the equivalent to the cross-namespace 
grant.

Regarding 'point to a missing ServiceImport' - it may work if validators don't block it, but it's still not a very intuitive UX.
For everything else we are dealing with resources created by the user - ServiceImport is an internal auto-generated config AFAIK. We do have a similar problem when using 'backendRef', so maybe it's not a huge issue.

But as general design and long term alignment with the concept of separating 'frontend' and 'backend' roles - I think
making this distinction is pretty useful. If we now think continuing to mix frontend/backend is the right approach - perhaps we should revisit a lot of other things. My understanding was that most people in the community believe Service mixing them is a problem and one of the main improvements in Gateway is separating them and providing controls around frontend->backend delegation.

**Comment by costinm** [comment]
To be more clear: as a user, in ClusterA I express the intent for 'foo' to be exported by creating a ServiceExport. As a result, in ClusterB we'll eventually have a ServiceImport. It is not intuitive or secure for ClusterB to define routes attached to the ServiceImport - it is not the owner of the service, just a consumer. 

And in ClusterA it is not intuitive to define routes on the created ServiceImport either - when the user already creates a ServiceExport resource and that is the intent of sharing a service.

**Comment by howardjohn** [comment]
What if I have:

Cluster A: ServiceExport `foo`
ClusterB: ServiceImport `foo` (automatic), want to create a Route for `foo`.

I wouldn't expect them to create a cross-cluster resource reference here. Also, ServiceImport is a thing with an IP address (in status), so it kind of represents the frontend... ServiceExport does not afaik?

> The routes and all policies should stay in Cluster A - just like we don't allow other namespaces to define routes.

For producer routes yes, but there are also consumer overrides.

**Comment by costinm** [comment]
> What if I have:
> 
> Cluster A: ServiceExport `foo`
> ClusterB: ServiceImport `foo` (automatic), want to create a Route for `foo`.
> 
> I wouldn't expect them to create a cross-cluster resource reference here. Also, ServiceImport is a thing with an IP address (in status), so it kind of represents the frontend... ServiceExport does not afaik?

There is no cross cluster reference. You want a route - you create a ServiceExport, if you gave the permissions. I think it is allowed to have multiple ServiceExport, one per cluster.

Not aware of a requirement to have an IP address - if ServiceExport does have a status I'm sure we can provide feedback to add it.

What is important is that as a user you _can_ create SE and route - no need to wait for a SI to be created ( with a name that is not deterministic)



> 
> > The routes and all policies should stay in Cluster A - just like we don't allow other namespaces to define routes.
> 
> For producer routes yes, but there are also consumer overrides.


Consumer overrides are a complicated thing from security perspective. I think even for Service they are problematic - not to mention egress in general.

That doesn't change the fact that SE is a better target than ServiceImport - both would have same characteristics for consumer overrides.

**Comment by mikemorris** [comment]
I think ServiceExport as parentRef could make sense for defining _producer_ routes, whereas ServiceImport makes more sense for defining _consumer_ routes. Importantly, the enforcement of each set should happen within the boundary where it is created, both to avoid any cross-cluster visibility issues, and also because some implementations may funnel cross-cluster traffic through an edge gateway and apply routing rules there (similar to Istio Ambient waypoints).

ServiceExport does have a [status](https://github.com/kubernetes-sigs/mcs-api/blob/master/pkg/apis/v1alpha1/serviceexport.go) field already.

Refs [GEP-1748](https://gateway-api.sigs.k8s.io/geps/gep-1748/#mesh-serviceimport-as-parent), cc @robscott

**Comment by robscott** [comment]
+1, ServiceExport as a target for producer routes or policies sounds very reasonable to me in the context of mesh. 

When it comes to Gateways, we assume that the Gateway, Route, and ServiceImport are all in the same cluster, and thus targeting the ServiceImport with Routes and Policies seems like the most correct interpretation since you're effectively a consumer in that scenario and not particularly concerned about the producer side.

**Comment by costinm** [comment]
For the record - IMO ServiceImport as 'consumer route'  or policies would only make sense if the API had such a thing - like in the Istio case, where most policies are client-oriented. Fortunately the Gateway API is primarily producer oriented - i.e. the  owner of a Gateway/Service defines routes and policies. 

Having a cluster define routes via ServiceImport for something running outside the cluster is pretty dangerous and confusing.

Egress policies are an interesting problem that is not very well covered in Gateway API - and the only case where it would make sense to have consumer policies  - but it probably doesn't have to be, since Egress Gateways are less common and follow some ancient and well established protocols ( for CONNECT and HTTP_PROXY). 

I no longer thing ServiceExport should be used as parentRef - there is no need, each cluster should operate independently and define routes and policies with the existing API without extra complications. An (internal) Gateway will have a Service associated - and if there is a standard ServiceExport, the gateway will be visible in the mesh with the clusterset.local  FQDN. Implementations can 'optimize away' the Gateway and create other paths if they can provide equivalent semantics - or use regular gateways. 

So in practice both ServiceExport and ServiceImport are better left for L4 semantics, as they are currently defined - with
Gateway and HttpRoutes used in each cluster in isolation (to reduce blast radius) and eventual consistency. 

As we have seen in ambient, attaching Routes to Services is also not necessary if we use the 'waypoint' abstraction
( which is also a gateway)
