### ISSUE TITLE
Documentation and examples needed for HTTP Request Mirroring

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2833]
**What would you like to be added**:
Although we have [conformance test coverage](https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/httproute-request-mirror.yaml) for request mirroring, we don't have any corresponding documentation. This would fit well as a guide, similar to the existing [redirect one](https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/). 

**Why this is needed**:
This is an important feature of the API and it's currently completely missing from our documentation.

**Comment by sawsa307** [comment]
/assign

I would like to work on this one.
