### ISSUE TITLE
gateway api CRD apply failed on kubernetes 1.17.1

### ISSUE THREAD

**Issue by haifzhu** [kubernetes-sigs/gateway-api#2838]
**What happened**:
on kubernetes with version 1.17.1,  gateway api CRD apply version, follow errors are printed:
error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.controllerName): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.versions[1].schema.openAPIV3Schema.properties.spec.properties.controllerName): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps, ValidationError(CustomResourceDefinition.status): missing required field "storedVersions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionStatus]; if you choose to ignore these errors, turn validation off with --validate=false

**What you expected to happen**:
on kubernetes with version 1.17.1,  gateway api CRD apply should be success.

**How to reproduce it (as minimally and precisely as possible)**:
on kubernetes with version 1.17.1, kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml

**Anything else we need to know?**:
no

**Comment by sunjayBhatia** [comment]
See the supported versions section of the website: https://gateway-api.sigs.k8s.io/concepts/versioning/#supported-versions

k8s 1.17.x is not in the supported versions for Gateway API release v1.0.0

**Comment by robscott** [comment]
+1 to what @sunjayBhatia said, Gateway API only guarantees support for the most recent 5 Kubernetes minor versions. We often try to provide more than that, but in this case the move to CEL was such a huge UX improvement that we upgraded as soon as we could support 5 versions with it.
