### ISSUE TITLE
Allow redirecting to IP address

### ISSUE THREAD

**Issue by eternalphane** [kubernetes-sigs/gateway-api#2867]
**What would you like to be added**:
Allow to configure IP address in `hostname` field of `HTTPRequestRedirectFilter`

**Why this is needed**:
Gateway API should conform with HTTP spec which allows redirection to both IP address and domain name URLs.

**Comment by costinm** [comment]
Do you mean to allow validation of 'hostname' to accept an IPv4 and IPv6 address, as it would be expressed in the Host: header ? If yes - it seems reasonable and consistent with the HTTP and URL specs. 

But not sure what it would do for https:// redirection - I don't think IP certs are issued or common.

**Comment by eternalphane** [comment]
> Do you mean to allow validation of 'hostname' to accept an IPv4 and IPv6 address, as it would be expressed in the Host: header

Yes :)

> But not sure what it would do for https:// redirection

I don't think redirection will handle the SSL certificate, nor do GEP-726 mention anything about it.
