### ISSUE TITLE
Support wide output format for get commands (`-o wide`)

### ISSUE THREAD

**Issue by gauravkghildiyal** [kubernetes-sigs/gateway-api#2889]
Refer https://gateway-api.sigs.k8s.io/geps/gep-2722/ for details

**Comment by jongwooo** [comment]
I'll work on this once #2866 is completed.

**Comment by gauravkghildiyal** [comment]
Hi @jongwooo! Thanks for your contributions so far. Are you still interested in getting this one through?

**Comment by jongwooo** [comment]
Hi @gauravkghildiyal, Sorry for the late response. I am currently in the midst of a job search, which will restrict my time to work on this until early June. If anyone is interested in picking this up in the meantime, I'd be happy to hand it off. Otherwise, I'll be sure to tackle it in early June.

**Comment by gauravkghildiyal** [comment]
No worries @jongwooo. Thanks again for all your contributions. Best of luck with the job search! Just FYI, Gateway API release v1.1 includes your name as one of the contributors: https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.1.0

(I'll make this bug unassigned for the time being)
