### ISSUE TITLE
Add conformance test for GRPCRouteFilterRequestHeaderModifier

### ISSUE THREAD

**Issue by pleshakov** [kubernetes-sigs/gateway-api#2900]
**What would you like to be added**:
A conformance test for https://github.com/kubernetes-sigs/gateway-api/blob/729d38f9bf17ff72d17f0148452416551296f67c/apis/v1alpha2/grpcroute_types.go#L436

**Why this is needed**:

Increase conformance feature coverage of GRPCRoute

**Comment by yashvardhan-kukreja** [comment]
Hi @pleshakov I would love to contribute this.

**Comment by yashvardhan-kukreja** [comment]
@pleshakov IIUC, isn't this test already achieving what this issue expects? - https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/httproute-request-header-modifier.go

**Comment by pleshakov** [comment]
Hi @yashvardhan-kukreja 

> Hi @pleshakov I would love to contribute this.

that's great! I'd recommend to wait until any of the maintainers replied that this issue makes sense or ask this question in the gateway api slack channel https://gateway-api.sigs.k8s.io/contributing/#communications , to double check this work is needed.

> @pleshakov IIUC, isn't this test already achieving what this issue expects? - https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/httproute-request-header-modifier.go

that tests works for HTTPRoutes. However, there is no such test for GRPCRoutes.

I'd also double check with @gnossen  who authored first GRPC conformance tests https://github.com/kubernetes-sigs/gateway-api/pull/2745

**Comment by yashvardhan-kukreja** [comment]
> that tests works for HTTPRoutes. However, there is no such test for GRPCRoutes.

Gotcha, that makes sense :)

**Comment by sjberman** [comment]
@yashvardhan-kukreja have you been working on this?
