### ISSUE TITLE
Move the injection point of the fakeClock

### ISSUE THREAD

**Issue by jongwooo** [kubernetes-sigs/gateway-api#2928]
Currently, gwctl injects `fakeClock` into each `Printer` struct as a dependency to avoid being affected by the "current time". However, in the future, we should change the injection point of `fakeClock` if we want to perform larger tests.

For example, suppose we write a test for the `get` command, in which case we should inject the `realClock` into the code above `NewGetCommand`. Currently, the `realClock` is initialized and injected inside the `NewGetCommand`, which leads to the issue of affected by the "current time" again in larger tests.

https://github.com/kubernetes-sigs/gateway-api/blob/437eff1ce670ee5e30805f10a938373a07817162/gwctl/cmd/get.go#L82

 Therefore, I think we should place the `realClock` at the entry point(e.g. `cmd/root.go`) and pass it as an argument.

CC. @gauravkghildiyal

**Comment by gauravkghildiyal** [comment]
Archiving this. Let's address this in the new repo (setup in progress) https://github.com/kubernetes-sigs/gwctl
