### ISSUE TITLE
Support YAML output format in get commands (-o yaml)

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [kubernetes-sigs/gateway-api#2932]
**What would you like to be added**:
Support for returning YAML outputs from `gwctl get` analogous to how `kubectl get .... -o yaml` works

**Why this is needed**:
Needed in favor of the progress of this [GEP](https://deploy-preview-2723--kubernetes-sigs-gateway-api.netlify.app/geps/gep-2722/)

More details here - #2761

**Comment by yashvardhan-kukreja** [comment]
My preferred approach to this would be to implement #2931 first in a "generic" enough way so that this issue can cleanly integrated on top of it further.

**Comment by yashvardhan-kukreja** [comment]
Covering this in the PR #2940 as well

**Comment by gauravkghildiyal** [comment]
This has been completed as mentioned in https://github.com/kubernetes-sigs/gateway-api/issues/2932#issuecomment-2044136736

/close
