### ISSUE TITLE
Conformance Tests for FrontendTLSValidation

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#2977]
Add conformance tests once 1 or 2 implementations support this field

API: https://github.com/kubernetes-sigs/gateway-api/blob/69b526683f13aabff4edce0d44b20b7edc09c283/apis/v1/gateway_types.go#L437

GEP: https://gateway-api.sigs.k8s.io/geps/gep-91/

_Originally posted by @arkodg in https://github.com/kubernetes-sigs/gateway-api/issues/91#issuecomment-2054968285_

**Comment by howardjohn** [comment]
I would encourage tests before implementations. Otherwise people will wait until there are tests (or maybe I'm just lazy...)
