### ISSUE TITLE
BackendTLSPolicy does not show up in generated API Spec

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#3016]
**What happened**:
BackendTLSPolicy is currently absent from https://gateway-api.sigs.k8s.io/reference/spec.

**What you expected to happen**:
BackendTLSPolicy to be included with all our other APIs.

**How to reproduce it (as minimally and precisely as possible)**:
Visit https://gateway-api.sigs.k8s.io/reference/spec.

**Anything else we need to know?**:
It's worth noting that references to BackendTLSPolicy types are still linked, they just don't go anywhere:
<img width="502" alt="Screenshot 2024-04-23 at 4 52 09 PM" src="https://github.com/kubernetes-sigs/gateway-api/assets/419322/e9806364-f415-4e6a-9747-cbe2e4d82997">

My best guess is that the docs generator we're using is just confused by the transition to v1alpha3 while all other API types are in different versions. Maybe something used in the [logic to combine API packages](https://github.com/ahmetb/gen-crd-api-reference-docs/blob/master/main.go#L250) is messed up?

I've been meaning to move to https://github.com/elastic/crd-ref-docs, this may be another reason to try that out if we can't find an easy fix with our existing docs generation.

**Comment by candita** [comment]
@robscott do you want to include all the version directories on that page?  In the template we only include two: https://github.com/kubernetes-sigs/gateway-api/blob/main/hack/api-docs/pkg.tpl#L40-L49

**Comment by robscott** [comment]
@candita good point! Maybe that's the only change we'd need? So far we've included all versions on a single page which I think is probably simplest, but happy to take a different approach if that's better.

**Comment by candita** [comment]
We could revert to https://github.com/kubernetes-sigs/gateway-api/blob/b1f655e6e88690b47447643066c550884e2f81ab/hack/api-docs/pkg.tpl, which iterates over the packages, and that would fix one problem.

**Comment by robscott** [comment]
> We could revert to https://github.com/kubernetes-sigs/gateway-api/blob/b1f655e6e88690b47447643066c550884e2f81ab/hack/api-docs/pkg.tpl, which iterates over the packages, and that would fix one problem.

I'm not sure why we made that change to begin with, but reverting to the earlier version SGTM.

**Comment by candita** [comment]
Fixed by #3202 
/close
