### ISSUE TITLE
conformance: Revisit HTTPRouteHTTPSListener test 404 case

### ISSUE THREAD

**Issue by sunjayBhatia** [kubernetes-sigs/gateway-api#3044]
**What happened**:

While validating v1.1.0-rc1 with Contour, running into this test failing: https://github.com/kubernetes-sigs/gateway-api/pull/2824

The request to unknown-example.com never succeeds to get an HTTP response (the test expects a 404), since there is no Listener/certificate configured that will allow the gateway to terminate the TLS connection

**What you expected to happen**:

Should we expect this test request to return a 404 or should we instead expect a TLS connection error since there is no explicit configuration for a Listener TLS certificate that matches the request?

**How to reproduce it (as minimally and precisely as possible)**:

Run the conformance tests for v1.1.0-rc1 against Contour, using the branch in this PR: https://github.com/projectcontour/contour/pull/6398

**Anything else we need to know?**:

We can likely work around this with fallback certificate configured in contour

I did approve the original PR that added that test but overlooked the 404 case for the request with the unknown hostname since it was added later in the PR's lifecycle, I think we might want to revisit this before releasing v1.1.0

**Comment by robscott** [comment]
Thanks for catching this @sunjayBhatia! @dprotaso is out, but if you or anyone has time to remove this specific test case before RC2 tomorrow, I think it would be good to pull it out for the time being and revisit after v1.1.

**Comment by sunjayBhatia** [comment]
https://github.com/kubernetes-sigs/gateway-api/pull/3045 PR to remove the questionable case for now

**Comment by sunjayBhatia** [comment]
rethinking my own thinking here: https://github.com/kubernetes-sigs/gateway-api/pull/3045#issuecomment-2089329137

this might just be fine and something we need to fix in contour

**Comment by sunjayBhatia** [comment]
I'm going to close this for now since I think this is probably correct actually, sorry for the confusion
