### ISSUE TITLE
Follow up tasks for conformance reporting

### ISSUE THREAD

**Issue by xtineskim** [kubernetes-sigs/gateway-api#3050]
These are some follow up tasks noted after the merging of #2874 

**What would you like to be added**:
From reviewers (thank you all for the suggestions!):
- [a list of shortened feature names](https://github.com/kubernetes-sigs/gateway-api/pull/2874#discussion_r1566528605)
- a way to show [past versions conformance reports](https://github.com/kubernetes-sigs/gateway-api/pull/2874#discussion_r1583818520)

There are also some things I noticed that might be helpful:
- having a basic conformance yaml in the repo as well. We wouldn't have to have thrown the [list of features](https://github.com/kubernetes-sigs/gateway-api/blob/6fc4f832bd49ac1a844d760413a8b8bf0bcd3fbb/hack/mkdocs-generate-conformance.py#L49) (i have a feeling we might forget to add to that list down the road), and listing out the core conformance tests as well maybe? Might be helpful down the line when more `supportedFeatures` are added, and more xRoutes are reported
-  have a better way to show `partial` support, and a different symbol to show skippedTests.

**Comment by youngnick** [comment]
One hundred percent agreed on trying to do something else with the list of features - ideally we would read this out of the Go source files for the test suite, but I think that may require porting the generation script to Go, sadly.

Also agreed on everything else.

**Comment by xtineskim** [comment]
also the format of <MESH | GATEWAY>-<HTTP | GRPC | TLS>  in the reports have to be changed (for v1.1.0)
https://github.com/kubernetes-sigs/gateway-api/pull/3019
