### ISSUE TITLE
Investigate HTTPFilter extensions

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#306]
Context https://github.com/kubernetes-sigs/service-apis/pull/276#discussion_r485925638

Filters like Mirror or Headers are not too hard to find ways implementations may extend, such as percentage of mirroring, or "set" header instead of add, etc. Currently there is no way to extend these short of defining a completely new custom filter.

**Comment by hbagdi** [comment]
> Currently there is no way to extend these short of defining a completely new custom filter.

This is intentional. The filters inside the core/extended API will always be a common denominator of all implementations that are implementing this API. Overtime, I expect that more and more implementations will add in features such as the one you have described. As this convergence happens, we can promote more fields into the core filters as well.

A new custom filter should not be hard to implement, especially if you do plan to advantage of filters API.

/cc @robscott

**Comment by hbagdi** [comment]
/remove-lifecycle stale

ping @howardjohn @robscott

**Comment by bowei** [comment]
@howardjohn do you want to freeze this bug to keep it from becoming stale as the general ask is still relevant -- or we can close this and have the issue naturally pop up again, but in a more specific context? Right now the ask is quite general so it's harder to make progress on the issue.

**Comment by hbagdi** [comment]
I think we need to keep the core filters as clearly defined, narrow and targeted to get traction and conformance from implementations. As soon as we add anything a bit more complicated, the number of implementations diverging in at least one detail will increase. Is defining a new implementation-specific acceptable for these cases and then come back to convergence in future?

**Comment by shaneutt** [comment]
While grooming we saw that this one was open for a long period of time without anyone with a strong use case to champion it. We do expect that at some point downstreams may implement their own custom filters and we would invite you to present such implementations here to be considered for adding upstream. For the time being however, we're going to close this as we don't expect anyone's ready to drive it forward. If you still want this feature and have a strong use case we will be happy to reconsider this and re-open.
