### ISSUE TITLE
conformance should require use of EndpointSlices rather than Endpoints

### ISSUE THREAD

**Issue by danwinship** [kubernetes-sigs/gateway-api#3069]
**What would you like to be added**:
A test that if a Gateway is backed by a Service that has _only_ EndpointSlices, and not Endpoints, that it works. (Along with associated documentation updates.)

**Why this is needed**:
The Endpoints API is basically deprecated, and new service features that require per-endpoint support are only being added to EndpointSlice. In particular, a Gateway implementation that is based on Endpoints cannot possibly support dual-stack, terminating endpoints, topology, etc. (Not to mention "services with more than 1000 endpoints".)

https://github.com/kubernetes/kubernetes/issues/124777 discusses adding helper functions to make this easier for people.

/cc @robscott

**Comment by sunjayBhatia** [comment]
I think this might be covered by one of the cases in this test: https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/httproute-service-types.go

**Comment by robscott** [comment]
Yep fortunately @dprotaso added this test for us recently (as @sunjayBhatia linked above). In today's sig-network meeting I was actually meaning that some implementations may struggle to pass this test though, so a helper function could be very welcome.

**Comment by danwinship** [comment]
ah, ok, feel free to close this then if it's not tracking anything useful

**Comment by robscott** [comment]
Closing this out, thanks for double checking that we had test coverage here!
