### ISSUE TITLE
Expose grpc conformance client as an interface in the conformance suite

### ISSUE THREAD

**Issue by snehachhabria** [kubernetes-sigs/gateway-api#3093]
**What would you like to be added**:

Would like to make the `conformance/utils/grpc` client:  
https://github.com/kubernetes-sigs/gateway-api/blob/cd6379d6b39010a2979eb68cc5e77c72c3787b75/conformance/utils/grpc/grpc.go#L139 an interface and expose it in the `ConformanceOptions`: https://github.com/kubernetes-sigs/gateway-api/blob/cd6379d6b39010a2979eb68cc5e77c72c3787b75/conformance/utils/suite/suite.go#L127 similar to the `RoundTripper`: https://github.com/kubernetes-sigs/gateway-api/blob/cd6379d6b39010a2979eb68cc5e77c72c3787b75/conformance/utils/roundtripper/roundtripper.go#L46 

**Why this is needed**:
This would make it the GRPCRoute tests consistent with the HTTPRoute tests in the conformance suite. This in turn would benefit our implementation (Application Gateway for Containers) to run the conformance suite in environments where the IP address is not directly reachable.

**Comment by robscott** [comment]
Sounds very reasonable to me, thanks for the suggestion @snehachhabria! Open to any contributions to make this happen.

/help

**Comment by yeedove** [comment]
@robscott  Can I pick this up?

**Comment by snehachhabria** [comment]
> Sounds very reasonable to me, thanks for the suggestion @snehachhabria! Open to any contributions to make this happen.
> 
> /help

thanks @robscott, I can pick it up right away as it would help unblock us

**Comment by snehachhabria** [comment]
I was able to put out a PR that was reviewed and merged

**Comment by robscott** [comment]
Thanks @snehachhabria!
