### ISSUE TITLE
Getting UnsupportedValue for RegularExpression type in HTTPRouteHeaderMatch

### ISSUE THREAD

**Issue by Danielkiss9** [kubernetes-sigs/gateway-api#3096]
**What happened**:
 I'm trying to apply the following HTTPRoute, that according to the [documentation](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HeaderMatchType) and the CRD's should work:
 
![image](https://github.com/kubernetes-sigs/gateway-api/assets/72993169/14ea28c6-11e5-4299-84c7-4823561ec26c)
        
And when describing the httproute i'm seeing:
`      Message:               All rules are invalid: spec.rules[0].matches[0].headers[0].type: Unsupported value: "RegularExpression": supported values: "Exact"      Observed Generation:   1
      Reason:                UnsupportedValue`
      
      
**What you expected to happen**:
Everything to work fine, and my HTTPRoute to be applied and resolved.

**How to reproduce it (as minimally and precisely as possible)**:
Try to apply a HTTPRoute that catches a header withthe type RegularExpression.

**Anything else we need to know?**:
I'm using the NGINX Fabric Gateway controller, and tried both the standard install and both the experimental, both are not working.

Thanks!

**Comment by pleshakov** [comment]
Hi @Danielkiss9 

NGINX Fabric Gateway (NGF) doesn't support Regex matching for headers . List of supported fields of HTTPRoute -- https://docs.nginx.com/nginx-gateway-fabric/overview/gateway-api-compatibility/#httproute Related discussion https://github.com/nginxinc/nginx-gateway-fabric/discussions/1676

Please note that https://github.com/kubernetes-sigs/gateway-api repo is about Gateway API, not individual implementations like NGF.  For NGF specific questions, I recommend reaching out to the NGF maintainers https://github.com/nginxinc/nginx-gateway-fabric?tab=readme-ov-file#contacts

**Comment by Danielkiss9** [comment]
Thank you very much @pleshakov.
This was my mistake as i thought the HTTPRoute is individually maintained by the gateway API and not NGINX. 
I'll be closing this issue :)
