### ISSUE TITLE
gwctl flag behaviour

### ISSUE THREAD

**Issue by xtineskim** [kubernetes-sigs/gateway-api#3133]
**What happened**:
- When using the `gwctl`, the `-A` (all namespaces) flag experience could be improved. 

**What you expected to happen**:
When running `gwctl get gateways -A`, the namespace isn't printed out, it'd be a nice to have
```
NAME    CLASS   ADDRESSES       PORTS  PROGRAMMED  AGE
cilium  cilium  172.18.255.200  80     True        4d
cilium  cilium  172.18.255.201  80     True        4d
```
- In the README.md, the first example of usage is `gwctl get policies -A`. The all-namespace flag doesn't work for policies

**How to reproduce it (as minimally and precisely as possible)**:
Run the above cmds

**Anything else we need to know?**:
n/a

**Comment by gauravkghildiyal** [comment]
I believe this can be closed given the PR was merged! Thanks for contributing.

/close
