### ISSUE TITLE
Make gwctl work with Policies having multiple targetRefs

### ISSUE THREAD

**Issue by gauravkghildiyal** [kubernetes-sigs/gateway-api#3196]
As per recent updates to the Policy related GEPs in https://github.com/kubernetes-sigs/gateway-api/discussions/2927#discussioncomment-8991869, Policies are now allowed to target multiple resources i.e. `targetRefs` (which previously was limited to a single `targetRef`).

Make gwctl work with this new pattern. Common places that need to be updated include:
- Displaying/handling multiple resources appropriately when using `gwctl get policies`
- Code changes required within https://github.com/kubernetes-sigs/gateway-api/blob/28e408013bd1084ca731e1a4559e38234d235182/gwctl/pkg/policymanager/manager.go#L277-L303

/area gwctl
/kind feature

**Comment by deszhou** [comment]
Can I assign it to myself? I want to try it

**Comment by gauravkghildiyal** [comment]
Hi @deszhou, sure go ahead, though there's a few minor open questions here which may need to be ironed out. Like for example what exactly would the following output:

```
gwctl get policies

gwctl describe policies
```

Would be nice if you can give a sample of what you have in mind before diving deep

**Comment by deszhou** [comment]
> 你好@deszhou当然可以，不过这里还有一些小问题需要解决。例如，以下输出到底是什么：
> 
> ```
> gwctl get policies
> 
> gwctl describe policies
> ```
> 
> 如果你能在深入探讨之前给出一个示例，那就太好了

```
gwctl get policies -A
```
- Indented Format:
```
NAME                          KIND                       TARGET NAME           TARGET KIND     POLICY TYPE  AGE
health-check-gateway          HealthCheckPolicy.foo.com  foo-gateway           Gateway         Inherited    20d
                                                         foo-gatewayclass      GatewayClass    Inherited    20d                
timeout-policy-gatewayclass   TimeoutPolicy.bar.com      foo-gatewayclass      Gatewayclass    Direct       5m
timeout-policy-httproute      TimeoutPolicy.bar.com      foo-httproute         HTTPRoute       Direct       13m
```
- Comma-Separated Format:
```
NAME                          KIND                       TARGET REFS                                            POLICY TYPE  AGE
health-check-gateway          HealthCheckPolicy.foo.com  foo-gateway (Gateway),foo-gatewayclass (GatewayClass)  Inherited    20d
timeout-policy-gatewayclass   TimeoutPolicy.bar.com      foo-gatewayclass (Gatewayclass)                        Direct       5m
timeout-policy-httproute      TimeoutPolicy.bar.com      foo-httproute (HTTPRoute)                              Direct       13m
```


```
gwctl describe policies health-check-gateway
```
```
Name: health-check-gateway
Group: foo.com
Kind: HealthCheckPolicy
Inherited: "true"
Spec:
  ...
  targetRefs:
	 - group: gateway.networking.k8s.io
	   kind: Gateway
	   name: foo-gateway
	 - group: gateway.networking.k8s.io
	   kind: GatewayClass
	   name: foo-gatewayclass 
```
Which of these two output formats do you think is better for `gwctl get policies`, or do you have any suggestions for improving the output format?

**Comment by deszhou** [comment]
> Hi @deszhou, sure go ahead, though there's a few minor open questions here which may need to be ironed out. Like for example what exactly would the following output:
> 
> ```
> gwctl get policies
> 
> gwctl describe policies
> ```
> 
> Would be nice if you can give a sample of what you have in mind before diving deep


```
gwctl get policies -A
```
- Indented Format:
```
NAME                          KIND                       TARGET NAME           TARGET KIND     POLICY TYPE  AGE
health-check-gateway          HealthCheckPolicy.foo.com  foo-gateway           Gateway         Inherited    20d
                                                         foo-gatewayclass      GatewayClass    Inherited    20d                
timeout-policy-gatewayclass   TimeoutPolicy.bar.com      foo-gatewayclass      Gatewayclass    Direct       5m
timeout-policy-httproute      TimeoutPolicy.bar.com      foo-httproute         HTTPRoute       Direct       13m
```
- Comma-Separated Format:
```
NAME                          KIND                       TARGET REFS                                            POLICY TYPE  AGE
health-check-gateway          HealthCheckPolicy.foo.com  foo-gateway (Gateway),foo-gatewayclass (GatewayClass)  Inherited    20d
timeout-policy-gatewayclass   TimeoutPolicy.bar.com      foo-gatewayclass (Gatewayclass)                        Direct       5m
timeout-policy-httproute      TimeoutPolicy.bar.com      foo-httproute (HTTPRoute)                              Direct       13m
```


```
gwctl describe policies health-check-gateway
```
```
Name: health-check-gateway
Group: foo.com
Kind: HealthCheckPolicy
Inherited: "true"
Spec:
  ...
  targetRefs:
     - group: gateway.networking.k8s.io
        kind: Gateway
        name: foo-gateway
     - group: gateway.networking.k8s.io
        kind: GatewayClass
	name: foo-gatewayclass 
```
Which of these two output formats do you think is better for `gwctl get policies`, or do you have any suggestions for improving the output format?

**Comment by gauravkghildiyal** [comment]
Let's choose the "comma-separated one" which is consistent with others. Let's just display 2 targets and then +n more pattern.

Though the other one also seems good but we can revisit this later.

**Comment by shaneutt** [comment]
@gauravkghildiyal we should transfer this over to the gwctl repository as well.

**Comment by gauravkghildiyal** [comment]
Moved to https://github.com/kubernetes-sigs/gwctl/issues/1

/close
