### ISSUE TITLE
Inconsistent Default Reason for GatewayClass Status Condition `Accepted`

### ISSUE THREAD

**Issue by snorwin** [kubernetes-sigs/gateway-api#3225]
**What happened**:
According to the [API reference](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.GatewayClassConditionReason), `Pending` is the default Reason for the status condition `Accepted` of a new GatewayClass. However, in the actual code, the default reason is inconsistently set to two different values:
- https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1/gatewayclass_types.go#L63
```
	// +kubebuilder:default={conditions: {{type: "Accepted", status: "Unknown", message: "Waiting for controller", reason: "Waiting", lastTransitionTime: "1970-01-01T00:00:00Z"}}}
```
- https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1/gatewayclass_types.go#L260
```
	// +kubebuilder:default={{type: "Accepted", status: "Unknown", message: "Waiting for controller", reason: "Pending", lastTransitionTime: "1970-01-01T00:00:00Z"}}
```
During the creation of a resource, the status is typically absent. As a result, the reason for the status condition `Accepted` is still set to the deprecated value `Waiting`.

**What you expected to happen**:
Regardless of how a GatewayClass is created, the reason for the status condition `Accepted` should always be set to `Pending`.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the following manifest and verify its status:
```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: foo
spec:
  controllerName: foo.com/bar
```

**Anything else we need to know?**:
N/A

**Comment by youngnick** [comment]
Thanks for this @snorwin, agreed, the reasons should be the same there.

So this just needs a PR to change the `Reason` field in the two lines mentioned above to the same value (`Pending`).

/help-wanted
