### ISSUE TITLE
Make gwctl available for install via kubectl krew

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#3270]
**What would you like to be added**:

[Krew] is a plugin manager for `kubectl` which is governed by us here in `kubernetes-sigs` and is growing in popularity. The purpose of this issue is to request that we host ourselves [among the supported plugins][sup].

[Krew]:https://github.com/kubernetes-sigs/krew/
[sup]:https://krew.sigs.k8s.io/plugins/

**Why this is needed**:

This is a tiny UX thing we can do to make using (and maybe to some degree, finding) Gateway API tools easier for end-users deploying with Gateway API.

**Comment by shramanpaul** [comment]
Hey @shaneutt  I would like to work on this issue, as i have some experience with kubectl and Krew earlier, and it would be great to get assigned and start with this good first issue

**Comment by shaneutt** [comment]
Sounds great, thank you!

/assign @shramanpaul 

If you run into any trouble, have questions or need support just let us know here.

/cc @gauravkghildiyal  who has been the primary developer of `gwctl`

**Comment by shaneutt** [comment]
Checking in?

**Comment by shramanpaul** [comment]
Thanks for checking in! I'm currently working on the issue. If any questions or issues arise, I'll reach out here. I expect to provide an update soon.
