### ISSUE TITLE
Error returns after running `gwctl get policies -A` on the latest branch.

### ISSUE THREAD

**Issue by jgao1025** [kubernetes-sigs/gateway-api#3273]
**What happened**:
I followed [gwctl readme file](https://github.com/kubernetes-sigs/gateway-api/blob/main/gwctl/README.md), and it says I can list all the policies in the cluster. The command is `gwctl get policies -A`.  However, I get "failed to execute command: unknown shorthand flag: 'A' in -A" error on my local machine. I am not sure if this is because maybe I didn't add any policy on my cluster?

**What you expected to happen**:
It needs to say either there is no policy we can find for you or list the policies they found in my cluster.

**How to reproduce it (as minimally and precisely as possible)**:
1. On Mac M1 laptop.
2. clone the latest repo, and build the gwctl.
3. follow Dev guide to create crd and install one API implementation.
4. run `gwctl get policies -A`

**Anything else we need to know?**:

The list of the command I tried:

```bash
 gwctl % gwctl get policies -A
Error: unknown shorthand flag: 'A' in -A
Usage:
  gwctl get policies [flags]

Aliases:
  policies, policy

Flags:
      --for string      Filter results to only those related to the specified resource. Format: TYPE[/NAMESPACE]/NAME. Not specifying a NAMESPACE assumes the 'default' value. Examples: gateway/ns2/foo-gateway, httproute/bar-httproute, service/ns1/my-svc
  -h, --help            help for policies
  -o, --output string   Output format. Must be one of (yaml, json)

Global Flags:
      --kubeconfig string   path to kubeconfig file (default is the KUBECONFIG environment variable and if it isn't set, falls back to $HOME/.kube/config)
  -v, --v int               number for the log level verbosity (defaults to 0)

failed to execute command: unknown shorthand flag: 'A' in -A
 gwctl % gwctl get policies -n default
Error: unknown shorthand flag: 'n' in -n
Usage:
  gwctl get policies [flags]

Aliases:
  policies, policy

Flags:
      --for string      Filter results to only those related to the specified resource. Format: TYPE[/NAMESPACE]/NAME. Not specifying a NAMESPACE assumes the 'default' value. Examples: gateway/ns2/foo-gateway, httproute/bar-httproute, service/ns1/my-svc
  -h, --help            help for policies
  -o, --output string   Output format. Must be one of (yaml, json)

Global Flags:
      --kubeconfig string   path to kubeconfig file (default is the KUBECONFIG environment variable and if it isn't set, falls back to $HOME/.kube/config)
  -v, --v int               number for the log level verbosity (defaults to 0)

failed to execute command: unknown shorthand flag: 'n' in -n
 gwctl % gwctl get policies           
NAME  KIND  TARGET NAME  TARGET KIND  POLICY TYPE  AGE
 gwctl % kubectl get pod
NAME                      READY   STATUS    RESTARTS   AGE
coffee-56b44d4c55-4m76b   1/1     Running   0          24h
tea-596697966f-v7ljs      1/1     Running   0          24h
 gwctl % git log                      
commit d6e29e30272126964bf9b09f6b4688f3768ba657 (HEAD -> main, origin/main, origin/HEAD)
Author: Shane Utt <shaneutt@linux.com>
Date:   Thu Aug 15 02:21:17 2024 -0400

    docs: add issue and PR bumping section to CONTRIBUTING.md (#3264)
    
    * docs: add issue and PR bumping section to CONTRIBUTING.md
    
    * Update CONTRIBUTING.md

```

**Comment by shaneutt** [comment]
@gauravkghildiyal we should transfer this one to the new gwctl repository as soon as it's ready :bookmark:

**Comment by gauravkghildiyal** [comment]
Hi @jgao1025! Thanks for reporting the issue.

Yes I think this was a UX issue with `gwctl get policies` always running in `-A` (all-namespaces) mode, and hence not supporting that flag (for redundancy). I checked and think this should now be fixed in the version available at https://github.com/kubernetes-sigs/gwctl.

Please feel free to open an issue at https://github.com/kubernetes-sigs/gwctl is still experience this issue, or encounter any other ones.
