### ISSUE TITLE
Allow dot (.) in GatewayClass.Spec.Controller

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#330]
**What would you like to be added**:

The controller implementing the GatewayClass might have different behavior based on the version of controller.
Having a `.` character could be helpful here.

Background for the conversation: https://github.com/kubernetes-sigs/service-apis/pull/327#discussion_r488200741

**Comment by robscott** [comment]
@hbagdi I think this issue needs a bit of clarification on 2 points:

1. Our validation does not currently prevent this from happening.
2. The [upstream Ingress validation](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L131) and spec for this field require this to be a "domain-prefixed path". That means that "gateway.example.com/v1" would be valid but "gateway.example.com/v1.1" would not be. Importantly a "." can be valid, depending on its position.

**Comment by jpeach** [comment]
> 2\. The [upstream Ingress validation](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L131) and spec for this field require this to be a "domain-prefixed path". That means that "gateway.example.com/v1" would be valid but "gateway.example.com/v1.1" would not be. Importantly a "." can be valid, depending on its position.

Looking at `httpPathRegexp`, I think the second example would be valid. I agree that if we want to do any validation of this, its a good idea to be consistent with ingress class.

**Comment by robscott** [comment]
Thanks for catching that @jpeach! You're completely right. It looks like we could probably use an update to the Gateway.Spec.Controller docs to clarify this.
