### ISSUE TITLE
API Spec Should Provide Source and/or Description of RegEx Validation

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#3306]
**What would you like to be added**:
Ideally the API spec should have more information about RegEx validation, for example where it came from or what it's based on. This should be visible in go type definitions but hidden from the generated CRD.

**Why this is needed**:
We rely heavily on RegEx validation and it can be difficult to ensure that our validation is well aligned with the relevant RFC or k8s concept. A simple reference or description of how we landed at a specific RegEx would be very helpful for future readers. Since we already have custom CRD gen, it would be relatively simple to build something like this to enable the concept:

https://github.com/kubernetes-sigs/gateway-api/blob/b4bff75934590ceb1dc3a85a6fac495d980165c2/pkg/generator/main.go#L209-L210

**Comment by LiorLieberman** [comment]
For #3304 the regex is taken from the RFC ([link](https://datatracker.ietf.org/doc/html/rfc3986#appendix-B)) but has been  slightly modified to enforce a full URI and not relative.

**Comment by LiorLieberman** [comment]
@Devaansh-Kumar are you interested in taking this?

**Comment by LiorLieberman** [comment]
@robscott my understanding of this request is that we want to add a note for where we took the regex from, but we dont want this in the CRD. I believe we can generalize this to more than just a regex but all comments we want to add on the go struct but not on the CRD. Just making sure we are on the same page?

**Comment by robscott** [comment]
> @robscott my understanding of this request is that we want to add a note for where we took the regex from, but we dont want this in the CRD. I believe we can generalize this to more than just a regex but all comments we want to add on the go struct but not on the CRD. Just making sure we are on the same page?

Yep, I don't think we want to overuse this pattern and have comments for anything, but agree that the overall pattern can/should be generalized any time we want to have comments like this.
