### ISSUE TITLE
How to make nginx annotations compatible with envoy contour

### ISSUE THREAD

**Issue by JayaBharathiSG** [kubernetes-sigs/gateway-api#3326]
Our current nginx config looks like this with tls client authentication

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-orchestrator
  namespace: "test"
  annotations:
    # Enable client certificate authentication
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    # Create the secret containing the trusted ca certificates
    nginx.ingress.kubernetes.io/auth-tls-secret: "test/ingressca"
    # Specify the verification depth in the client certificates chain
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "2"
    # Specify an error page to be redirected to verification errors
    #nginx.ingress.kubernetes.io/auth-tls-error-page: "http://www.mysite.com/error-cert.html"
    # Specify if certificates are passed to upstream server
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    # By default the controller redirects (308) to HTTPS if TLS is enabled for that ingress.
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/client-max-body-size: "10m"
spec:
  tls:
    - hosts:
      - "test-app.dev.lab"
      secretName: ingresstls
  rules:
    - host: "test-app.dev.lab"
      http:
        paths:
          - path: /testprod
            pathType: Prefix
            backend:
              service:
                name: backend-orchestrator
                port:
                  number: 8080

How to make this compatible with contour ingress controller?

**Comment by youngnick** [comment]
Sorry @JayaBharathiSG, this repo is for creation of the Gateway API itself - I'd suggest opening this issue at https://github.com/projectcontour/contour/issues/new/choose instead.
