### ISSUE TITLE
support protobuf

### ISSUE THREAD

**Issue by qicz** [kubernetes-sigs/gateway-api#3346]
**What would you like to be added**:

**Why this is needed**:
client-go read resource will get better performance

**Comment by howardjohn** [comment]
I don't think the api-server supports reading CRDs as protobuf

**Comment by qicz** [comment]
xref: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2138 @howardjohn

**Comment by howardjohn** [comment]
yeah that works for core types not crd

**Comment by qicz** [comment]
just support core types by `protobuf`

```
Not all API resource types support Protobuf; specifically, Protobuf isn't available for resources that are defined as [CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/) or are served via the [aggregation layer](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/). 
```

`Controller-runtime`  based clients already use `protobuf` for types.  https://github.com/kubernetes-sigs/controller-runtime/pull/1149

using informer support core types and crd.
