### ISSUE TITLE
Conformance reports unavailable on the website for v1.1 and v1.2

### ISSUE THREAD

**Issue by arkodg** [kubernetes-sigs/gateway-api#3395]
**What would you like to be added**:

* https://gateway-api.sigs.k8s.io/implementations/v1.1/ does not show any conformance reports although the data exists https://github.com/kubernetes-sigs/gateway-api/tree/main/conformance/reports/v1.1.0 . The [link for v1.0](https://gateway-api.sigs.k8s.io/implementations/v1.0/) works fine

* v1.2 was recently released, so a section for this release should also be available on the website. Cilium has already uploaded a conformance report https://github.com/kubernetes-sigs/gateway-api/tree/main/conformance/reports/v1.2.0

**Why this is needed**:

**Comment by xtineskim** [comment]
ooh ill take a look @arkodg !
