### ISSUE TITLE
Validate examples against CRD schema

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#346]
Currently our examples fall out of date pretty quickly. We should validate these against the CRD schema. As a side effect, this will allow us to see awkward validation logic in the PR.

I could not find any tools to do this (aside from a real cluster). I tried to write one: https://github.com/istio/istio/blob/df7c20c2a261fa08dd93c9e09e65dd973a30c454/pkg/config/crd/validator.go#L66 and got really close but am stuck on one issue: https://kubernetes.slack.com/archives/C0EG7JC6T/p1600914427006300?thread_ts=1600454679.014900&cid=C0EG7JC6T

**Comment by hbagdi** [comment]
@howardjohn Just following up, were you able to make any progress towards this?

**Comment by howardjohn** [comment]
No, I am stuck on this by https://github.com/kubernetes/kubernetes/issues/95407

**Comment by howardjohn** [comment]
/reopen

I finally got a local CRD validator working 100%. I tested it against all our examples and it fails on all the invalid ones and success on all valid ones. If we are interested I can send a PR to use it.

Either we can maintain the tool in tree here or can import from my repo once I push it there, either one works for me...

**Comment by hbagdi** [comment]
@robscott @youngnick This is exactly what I was referring to when I was saying we should have a common validation package that all implementations can run before processing any objects.

**Comment by hbagdi** [comment]
@howardjohn It makes a lot of sense to have a shared package for this. Would love to hear thoughts from others.

**Comment by youngnick** [comment]
I commented on #926, but in short, I agree.

**Comment by robscott** [comment]
Agree that we should work on a common validation package that merges the logic @howardjohn has for CRD validation + our existing webhook validation code.

**Comment by robscott** [comment]
This was fixed by https://github.com/kubernetes-sigs/gateway-api/pull/428
