### ISSUE TITLE
HTTPRequestMirrorFilter needs webhook validation

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#349]
We need to be able to ensure that only one filter is set at a time in this type.

**Comment by cmluciano** [comment]
@robscott Can you expand on this a little bit more? I've decided to start with this first but I'm not sure that I understand what we are validating for. Is it possible to do something like 

```
HTTPRouteFilter{
  RequestMirror {
    ServiceName
    BackendRef
    Port
  },
  RequestMirror {
    ServiceName
    BackendRef
    Port
} 
```

**Comment by hbagdi** [comment]
> that only one filter is set at a time in this type.

Should we start with limiting one filter per type for all filters and then open it up if required?


> @robscott Can you expand on this a little bit more? I've decided to start with this first but I'm not sure that I understand what we are validating for. Is it possible to do something like

@cmluciano The case in your comment should error out and be rejected by the validating webhook.
