### ISSUE TITLE
Gateway API CRD apply validation fails on K3D 5.7.4

### ISSUE THREAD

**Issue by CodingFlow** [kubernetes-sigs/gateway-api#3527]
**What happened**:

On k3d version 5.7.4 cluster on my local machine, tried to apply CRD with:

```
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml
```

Returns validation error:

> ```error: error validating "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.1/standard-install.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.controllerName): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps, ValidationError(CustomResourceDefinition.spec.versions[1].schema.openAPIV3Schema.properties.spec.properties.controllerName): unknown field "x-kubernetes-validations" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps]; if you choose to ignore these errors, turn validation off with --validate=false```

**What you expected to happen**:

CRD to be applied successfully.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install k3d 5.7.4
2. Create k3d cluster
3. Apply CRD version 1.2.1 with CLI command

**Anything else we need to know?**:

No.

**Comment by howardjohn** [comment]
What version of kubernetes? k3d is not a kubernetes version, its a tool to manage manage different versions of k8s -- we need the k8s/k3s version, not the k3d.

**Comment by CodingFlow** [comment]
> What version of kubernetes? k3d is not a kubernetes version, its a tool to manage manage different versions of k8s -- we need the k8s/k3s version, not the k3d.

Running `k3d version` says k3s version is v1.21.7-k3s1

**Comment by CodingFlow** [comment]
I switched k3s to version v1.31.4-k3s1 and the CRDs are applied successfully. 🎉 My bad for assuming the latest version of k3d comes with a recent version of k3s. Thanks for pointing me in the right direction @howardjohn !
