### ISSUE TITLE
Add success reasons for conditions

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/gateway-api#370]
**What would you like to be added**:

Add predefined reason constants to be used when a condition is in the default (successful) state.

**Why is this needed**:

The `metav1.Condition` field "Reason" is required. Since Conditions should always be present in status, even when they are expressing a successful state, this requires the controller to ender something in "Reason". We should provide constants for that.

**Comment by jpeach** [comment]
Per WG discussion, we can ship v1alpha1 without this

**Comment by robscott** [comment]
I think this was fixed by https://github.com/kubernetes-sigs/gateway-api/pull/729, feel free to reopen if I missed anything.
