### ISSUE TITLE
BackendTLSConfig defaulting and system ca certificates

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#401]
Currently CertificateAuthorityRef is optional and can refer to an object like secret.

The spec does not define what happens when this is not set - is this essentially `-k`/`InsecureSkipVerify` or is it defaulting to using the system ca certificates?

If the former - how can we specify to use the system ca certificates? This is an extremely common use case which seems wrong to force users to either copy them into a Secret or to have each implementation create some custom resource for this case.

**Comment by hbagdi** [comment]
This is a very good question.
Most implementations are capable of performing verification based on system ca certs.
The default in implementations vary, some do `-k/InsecureSkipVerify` and some don't.

Is this something that belongs to GatewayClass's ParameterRef?

cc @bowei @danehans @jpeach @robscott

**Comment by jpeach** [comment]
My initial thought is that the validation type should be explicit, but that system CA configuration belongs in the gateway class config.

**Comment by MadhavJivrajani** [comment]
/remove-kind design
/kind feature
`kind/design` is migrated to `kind/feature`, see https://github.com/kubernetes/community/issues/6144 for more details

**Comment by shaneutt** [comment]
Despite this issue being quite old, we the maintainers are still pretty convinced that we want to have this functionality in a future release. We are marking this `help wanted` as we're looking for contributors with strong use cases to help champion and drive this forward.

**Comment by shaneutt** [comment]
While grooming we saw that this one was open for a long period of time without anyone with a strong use case to champion it. We're going to close this as we don't expect anyone's ready to drive it forward, but if you still want this feature and have a strong use case we will be happy to reconsider this and re-open.
