### ISSUE TITLE
Define Semantics for Extended Protocol Types

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api#433]
**What would you like to be added**:
The Gateway API defines "Core" and "Implementation-specific" protocol types but does not address "Extended" protocols. Should "Extended" protocols contain a prefix, i.e. `extended/GRPC" to denote that implementations are not required to support this protocol type?

xref: https://github.com/kubernetes-sigs/service-apis/pull/398

**Comment by hbagdi** [comment]
Considering we document everything "Extended" within our API, should we add in documentation that says that Extended protocol must be defined within this package?
We could define an extended protocol as well. How about GRPC?

**Comment by youngnick** [comment]
So, we currently have no Extended support protocol types, but this issue serves to record that it's fine for implementations to bring Custom support protocol types upstream to us, and we'll consider moving them to Extended support.

This will be subject to the usual Extended support rules:
- the exact value will be specified
- there has to be conformance tests that validate how it works, if an implementation chooses to implement it.

I'll close this for now, please feel free to comment if you want to reopen.
