### ISSUE TITLE
Develop a plan for repository and docs structure post v1alpha1

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#447]
Although we're currently very focused on a v1alpha1 release, we also need to figure out how we'll update our project structure after the API release. We need to answer the following questions:

- How can we ensure that all new work targets v1alpha2 by default?
- Should we create branches for each API release?
- How can we structure the docs to cover multiple API versions?

**Comment by hbagdi** [comment]
Removing this from v1alpha1 milestone because this is intended for post v1alpha1.

**Comment by robscott** [comment]
One thing that we’ll need to figure out pretty quickly - what do we want to do with changes that come in now that v1alpha1 is launched?

As I see it, we have 2 main options:
1. Create a v1alpha2 API directory and branch immediately, make the majority of changes excluding bug fixes there.
2. Continue to iterate on v1alpha1, release new minor versions of service-apis with updates to v1alpha1. We would avoid a new API version if/until we wanted to make breaking changes.

/cc @bowei @danehans @hbagdi @jpeach

**Comment by robscott** [comment]
I'm personally leaning towards option 1 since I think it could be confusing to have lots of variations to the v1alpha1 API.

**Comment by hbagdi** [comment]
+1 to option 1. It will be much more easy to maintain and ship changes that way.
One concern I have is too many versions. CRD versions are kind of heavy weight and having a lot of them can easily confuse users and maintainers alike.
