### ISSUE TITLE
Provide Alternatives for Managing TLS Assets Through Secrets

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api#455]
**What would you like to be added**:
Currently, a controller that implements Service APIs needs the ability to watch secrets from all namespaces when an HTTPRoute is configured with a CertificateRef. Alternatives should be considered to reduce the need for a controller to have this level of RBAC privileges.

**Alternative Considerations:**
- Designate a single namespace used for secrets. Now different teams have access to each other's secrets.
- Store TLS assets in `HTTPRoute` as strings. Now `HTTPRoute` needs to be managed like a secret.
- Require secrets to be annotated. Even though the controller has RBAC to watch secrets, it can use a predicate to reduce access to only annotated secrets.
- Admission webhook? Scale concerns.

xref: https://github.com/kubernetes-sigs/service-apis/issues/103

**Comment by robscott** [comment]
A couple more options discussed today:

- Run multiple instances of the controller that each have access to secrets in only the subset of namespaces that are relevant.
- Provision Gateways and TLS config in namespaces that are otherwise isolated. Secrets in those namespaces can be limited to TLS certificates. Gateways can then target Routes in specific namespaces and controllers would not need access to secrets in those namespaces.

**Comment by hbagdi** [comment]
/remove-lifecycle stale
/lifecycle frozen

It seems to me that we should have documentation around this for the implementers. We can't really do much at the API level, can we?

**Comment by youngnick** [comment]
I agree, this seems like something that an implementation can handle itself, probably with one of the methods mentioned above, like providing a list of valid namespaces for secrets or something. In that case, seems like the implementation should put a condition on the object to say that the secret couldn't be found (it's pretty much the same case as "the secret doesn't exist).

Contour has a slightly similar idea, `TLSCertificateDelegation`, where we allow you to refer to a secret in a namespace other than the one the object resides in, if there is a special binding object that allows that. Now that I think about it more, this is kind of like an RBAC binding that allows Secrets to be referred to from outside namespaces. Happy to talk more about this at a meeting sometime.

**Comment by stevesloka** [comment]
//cc @dprotaso

**Comment by jpeach** [comment]
> I agree, this seems like something that an implementation can handle itself, probably with one of the methods mentioned above, like providing a list of valid namespaces for secrets or something. In that case, seems like the implementation should put a condition on the object to say that the secret couldn't be found (it's pretty much the same case as "the secret doesn't exist).

Yup I agree with this. Once implementations are implementing new approaches, then it makes more sense to dscuss what can be folded back into the API. The TLS options field can be used in the interim.

**Comment by shaneutt** [comment]
`ReferenceGrant` gets us something close to what appeared to be the original intention here, as it allows cross-namespace certificate references. For now we're going to close this as we don't expect anyone's ready to drive it forward, but if you still want this feature and have a strong use case we will be happy to reconsider this and re-open.
