### ISSUE TITLE
Investigate alternative doc generation

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#489]
**What would you like to be added**:

Study and investigate docs site generator used by upstream Kubernetes and related project. 

**Why is this needed**:

Existing docs tooling (mkdocs) is not meeting our needs. Specifically, we need our docs to be version aware. A long term goal for the project is to integrate docs to upstream, and hence it makes sense to align with upstream early on.

**Comment by hbagdi** [comment]
I looked into https://github.com/kubernetes/website. Hugo is powerful but also more complicated that mkdocs.
We can move over to Hugo but I don't see any benefit imminently, especially since we don't have any major problems other than the search functionality.
I'd like to punt on this one if that seems okay with everyone else.
/unassign

**Comment by youngnick** [comment]
Sounds fair to me, I agree that updating to Hugo at some point will help later, but now is probably not the time.

**Comment by robscott** [comment]
The move to Netlify probably helps makes this less necessary, but it also gives us a lot more flexibility in terms of what tooling we could use here.

**Comment by robscott** [comment]
I think now that we've moved to Netlify our docs story is not that bad. Although there's still room for improvement, I'm not sure that we have to leave this issue open.

**Comment by youngnick** [comment]
I think that it's true that we'll need versioned docs at some point, but also true that that point is a ways away. So closing this seems fine.

**Comment by hbagdi** [comment]
Closing this for now, let's revisit when this becomes necessary again.
/close
