### ISSUE TITLE
Add support for selecting a specific in-cluster proxy instance as implementer of Gateway

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#491]
**What would you like to be added**:

A field like `selector` on Gateway that specifies what <thing> will have the gateway configuration applied to it.

For an in cluster proxy, this would be the pods that are actually implementing the Gateway. For out of cluster implementations, there may be similar selection mechanisms, although this is probably more domain specific.

The selector could be either a direct reference, like:
```
selector:
  kind: Deployment (or Service?)
  name: my-nginx
```

or label selector:
```
selector:
  app: my-nginx
```

**Existing implementations**:

Istio allows running multiple gateway deployments. A similar `selector` label selector is used to bind a Gateway object to a gateway pod: https://istio.io/latest/docs/reference/config/networking/gateway/#Gateway

Ambassador does this by assigning each instance an ID and referencing that in all objects: https://www.getambassador.io/docs/latest/topics/running/running/#ambassador_id

I think Kong does this by each deployment having an ingress class associated: https://discuss.konghq.com/t/managing-multiple-kong-instances-creation-of-the-kong-resources-on-its-respective-database/3475, as does nginx: https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/

**Alternatives**:

Alternatively, we could control this by GatewayClass. However, this means that deploying a gateway implementation is a privileged task, as they need access to a cluster wide resource.

In our use case, its common for users to have many deployments handling gateway traffic, deployed and managed completely by application teams/namespaces. It would be great to not require these to each create a dedicate GatewayClass

**Comment by hbagdi** [comment]
This is a very interesting problem.

Up until now, the maintainers have taken the stance that Service APIs doesn't dictate anything about the underlying implementation. This works even for in-cluster proxies to a certain extent: I had imagined a workflow where an in-cluster proxy is told which GatewayClass and which Gateway it is supposed to target. With that bit of information, the implementation can configure itself as necessary and also add in the correct Status in the Gateway resource. Essentially, this is the inverse case, where the "selector" is on the implementation and not on the Gateway.

I'm still digesting what is being proposed here but meanwhile would love to hear more thoughts from @robscott @danehans @jpeach @youngnick @Miciah.

**Comment by jpeach** [comment]
I thought that this was exactly the kind of problem that GatewayClass was intended to address?

There was a previous discussion (probably in a issue IIRC) about deploying a gateway stack in a single namespace as an unprivileged operation and consensus was not in favor of that. Maybe #136 captures some of that, but I don't think it's the full discussion.

**Comment by howardjohn** [comment]
My primary concern is when we start moving from the happy-case of "one big load balancer for the cluster" to things like gRPC, service mesh, etc which will potentially have many different instances. The original issue was perhaps not the right solution to this problem, but I am not convinced GatewayClass is either due to its cluster scoping

**Comment by maplain** [comment]
When the GatewayClass controller is a cluster-scoped resource, meaning the proxy is either outside of the cluster or a cluster-scoped resource, this is less of a problem.

However, when the in-cluster proxies are used in namespace scope, they're forced to access Cluster scoped GatewayClass with the current model, which might not be ideal.

**Comment by jpeach** [comment]
Just to clarify this for myself. The scenario is that you have some pods running some un-configured proxy. You also have a one or more Gateway object. The controller needs to figure out which pods to configure with which Gateways.

This seems close to what @bowei always phrased as "scheduling Gateways" onto the available capacity. The controller needs to figure out which sets of Gateways the same proxy can compatibly be configured with and maybe make some choices around rescheduling for performance or operational reasons.

Probably (at least) 3 approaches:
* gateways select their proxy instances
* proxy instances select their gateways
* the controller figures it all out dynamically somehow

My instinct here  is that it's probably a bit early to encode a specific approach into the API. Maybe implementations can get by with annotations?

**Comment by shaneutt** [comment]
While grooming we saw that this one was open for a long period of time without anyone with a strong use case to champion it. We're going to close this as we don't expect anyone's ready to drive it forward, but if you still want this feature and have a strong use case we will be happy to reconsider this and re-open.
