### ISSUE TITLE
Insecure Connection Policy

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api#51]
**What would you like to be added**:
The ability to enforce how insecure (http) connections are handled for a `xRoute`:

`InsecureConnections: “Redirect”`: Redirects http > https connections for an `xRoute`.
`InsecureConnections: “None”`: Refuse http connections for an `xRoute`.
`InsecureConnections: “Allow”`: Allows insecure connections for an `xRoute`.

**Why is this needed**:
As a cluster operator, I need the ability to enforce how insecure (i.e. http) connections are handled for an `xRoute` bound to a Gateway. For example, I have hostname "foo.example.com" hosted by service-apis that routes to a backend http `Service`. The `Gateway` exposes a secure and insecure listener. I want to ensure any attempt for "http://foo.example.com" is either allowed, disallowed or redirected to "https://foo.example.com".

**Comment by danehans** [comment]
pr xref: https://github.com/kubernetes-sigs/service-apis/pull/35

**Comment by hbagdi** [comment]
> Otherwise, should this functionality be added to gateway ListenerTLS?

This seems like a route level property since each application or route will want to control it.

I do see value in having a Gateway-level property where one configures redirects for every request.
But, it would be hard to use in practice. For instance, HTTP challenge in the ACME protocol for automated-certificate is always HTTP based.

**Comment by stevesloka** [comment]
In Contour, we've implemented this by having the 301 redirect from http->https if a cert is defined on the route. Then if someone needs to remove the redirect, we have a field to allow the route path to serve insecure. 

What's nice about this is by default most folks probably want the 301 redirect if they have a cert applied, but don't need more configuration.

**Comment by hbagdi** [comment]
#713 covers this in some sense.
Safe to close?
/cc @robscott @jpeach @youngnick

**Comment by robscott** [comment]
Agree with that, feel free to reopen if there's a better more portable way to handle this.

/close
