### ISSUE TITLE
Add API Tests

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api#520]
**What would you like to be added**:
API tests.

**Why is this needed**:
The current tests only ensure the CRDs and examples can be installed to a cluster. Tests are needed that compare the current and expected values of API types. For example, many API fields are being defaulted but no tests exist to ensure the defaults are being properly set.

/cc @robscott @hbagdi 

xref: https://github.com/kubernetes-sigs/service-apis/issues/517

**Comment by jpeach** [comment]
xref #691

**Comment by jpeach** [comment]
Duplicate of #20
