### ISSUE TITLE
Inconsistent Persona Naming

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api#521]
The persona naming scheme is inconsistent across documentation.

[Intro Page](https://kubernetes-sigs.github.io/service-apis/):
- Platform Provider
- Platform Operator
- Service Operator

[Concepts Page](https://kubernetes-sigs.github.io/service-apis/api-overview/):
- Infrastructure Provider
- Cluster Operator
- Application Developer

@robscott and I prefer the concepts page naming scheme. Thoughts?

/assign @mark-church 
/cc @hbagdi

**Comment by hbagdi** [comment]
I think we have usually discussed the API with the naming in Concepts doc. 
I personally prefer the naming in Concepts doc as well.

**Comment by mark-church** [comment]
Yeah makes sense, I like the ones from the concepts doc as well. I can go ahead and change it later this week.

**Comment by hbagdi** [comment]
Great, thanks!
I'll assign this to you for now.
/assign @mark-church

**Comment by hbagdi** [comment]
Hey @mark-church, do you still have the bandwidth to take this on?

**Comment by mark-church** [comment]
Yup, fixed it with https://github.com/kubernetes-sigs/gateway-api/pull/551
