### ISSUE TITLE
Inconsistency in ParametersRef Documentation

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/gateway-api#524]
**What happened**:
I'm trying to implement Service APIs and I'm confused on what resources can be used for `gatewayclass.spec.parametersRef`.

**What you expected to happen**:
That either cluster-scoped or namespace-scoped resources are allowed. The namespace **must** be known by the implementation when using a namespace-scoped resource.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Comment by danehans** [comment]
xref: https://kubernetes.slack.com/archives/CR0H13KGA/p1609808722309100

**Comment by danehans** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/97396

**Comment by robscott** [comment]
Following up on this, @danehans and I are planning on working on a KEP for the 1.21 release cycle that would add an optional namespace reference to IngressClass ParametersRef. Initial feedback on sig-network community call was promising. Assuming that KEP is approved, I think it will make sense to move forward here as well.

**Comment by hbagdi** [comment]
xref https://github.com/kubernetes-sigs/service-apis/pull/543
