### ISSUE TITLE
The schedule of next intermediate release

### ISSUE THREAD

**Issue by nak3** [kubernetes-sigs/gateway-api#535]
**What would you like to be added**:

It would be great if we could know about the schedule of intermediate releases from docs or somewhere.

**Why is this needed**:

For Knative Serving, [this change](https://github.com/kubernetes-sigs/service-apis/commit/8a8b4e7a4ced75f999fdfef7a393563e16c38a89) is one of the important requirements.
But each Ingress (I am testing Istio now) implements v1alpha1 with v0.1.0 branch and so they do not contain the change yet.

Then, as per [release doc](https://kubernetes-sigs.github.io/service-apis/releases/#versioning), it mentioned about intermediate releases:

> As the API evolves, we will make intermediate releases that improve upon an existing API version. These releases will be fully backwards compatible and will be limited to either bug fixes or additions to the API.

But it is not clear when the intermediate release happens. It would be great if we could know the schedule.

**Comment by hbagdi** [comment]
`v1alpha2` is a bit away.
We can consider releasing v0.2.0 since there is need with whatever all the progress we have made.

@robscott @bowei @danehans Thoughts?

**Comment by robscott** [comment]
I agree completely. I know closer to the end of 2020 we'd discussed the possibility of an 0.2.0 release sometime in January. Although that's unlikely to happen, I think it would make sense to release something soon. There are plenty of people working on implementations of this API and it would be helpful to provide a more recent version of the API to pin to. I'll bring this up at our community meeting tomorrow and see what kind of feedback we get as far as a timeline here.

**Comment by robscott** [comment]
We discussed this at our community meeting earlier today. We're going to try to get a v0.2.0 release out in the first half of February.

**Comment by bowei** [comment]
Rob -- do we want to use the project board and gather the PRs/issues that we want to get done in the next two weeks?

**Comment by robscott** [comment]
Quick update, it looks like we're a bit behind schedule for "first half of February" but should still get 0.2.0 out this month. We're trying to bundle this with the rename to gateway-api - most of the pieces seem to be in place for that, but not sure how long it will take for all the changes to get merged in and applied across various repos. We've created https://github.com/kubernetes-sigs/service-apis/milestone/3 to track this release.

**Comment by nak3** [comment]
Thank you! Now I found https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.2.0 was released. Closing this issue.
