### ISSUE TITLE
Change repo name?

### ISSUE THREAD

**Issue by bowei** [kubernetes-sigs/gateway-api#536]
Should we change the name of the repo to align with the primary resource names (gateway-apis?)

**Comment by mark-church** [comment]
Could we not pluralize it though? When it's plural everybody tends to call it something different (service api vs service apis). It would be a bit more concrete if it was just gateway-api.

**Comment by SantoDE** [comment]
I am so much in favour of `gateway-api` then :)

**Comment by hbagdi** [comment]
@bowei Before we get into renaming, I think we should understand why the current name was chosen in the first place. What was the motivation and goal then?

**Comment by bowei** [comment]
I chose the name because it has to do with an API that was an iteration on Kubernetes services.

At that point in time, we didn't really have any of the resource names, so I didn't really want to make up a name.

**Comment by robscott** [comment]
Although the plural APIs name feels more accurate, I think the singular Gateway API name would likely be easier to work with. Name changes are always painful, but I think the transition from Service to Gateway probably makes sense here. Certainly will be easier to change the project name now than at any point in the future. With that said I'm sure it will be a non-trivial amount of work.

**Comment by robscott** [comment]
Of course this would be a terrible change if we weren't 100% sold on the Gateway name. I think our [votes on resource naming](https://docs.google.com/spreadsheets/d/18hlubHDfZ73oi17CmqmdL-fQOJiwrXLOFcbIU2RaTh0/edit#gid=779515090) in the fall were pretty conclusive though.
<img width="710" alt="Screen Shot 2021-01-26 at 10 44 02 AM" src="https://user-images.githubusercontent.com/419322/105889936-9485f300-5fc3-11eb-863e-fb5808719803.png">

**Comment by danehans** [comment]
@bowei what is the impetus for the name change? Renaming to `Gateway API` implies a single API. I'm in favor of keeping the name unless the current name does not follow a standardized k8s repo naming schema.

**Comment by danehans** [comment]
@bowei will send an email to the sig-network mailer to obtain feedback on the rename. This issue will be readdressed during the 2/3 service apis community meeting.

**Comment by robscott** [comment]
Thread in sig-network mailing list: https://groups.google.com/g/kubernetes-sig-network/c/5Rkg_juNDGc. Also added to agenda for sig-network meeting on Feb 4.
