### ISSUE TITLE
Old URL is 404

### ISSUE THREAD

**Issue by craigbox** [kubernetes-sigs/gateway-api#556]
There are a lot of links to https://kubernetes-sigs.github.io/service-apis/.  Could you make them 301 to /gateway-apis/ now you've renamed?

**Comment by hbagdi** [comment]
Fair ask.
To do this, we would need to create a `kubernetes-sigs/service-apis` repo and then initialize that with a webpage that essentially does the redirect.
The things that would break in that case is:
- https://github.com/kubernetes-sigs/service-apis currently redirects to this repo (github feature)
- kubectl kustomize "github.com/kubernetes-sigs/service-apis/config/crd?ref=v0.1.0" currently works fine, again thanks to Github's auto-redirect feature for renamed repositories.

These two along-with all other redirections would break. I'm not sure what is the right trade-off here.

Thoughts @robscott @bowei @danehans @jpeach @mark-church?

There was a brief discussion of removing reliance on Github.io DNS and instead use a domain name. We have gateway-api.io and gateway-api.org to use for this project. We can also use a `*.sigs.k8s.io` domain (not sure how to go about doing it).

**Comment by robscott** [comment]
Yeah I think you're right, we really don't have great options here other than to make things better going forward :(. I wish GitHub auto-redirects extended to pages. I asked @mrbobbytables about what our options here are and it sounds like our best option is to setup a custom `gateway-api.sigs.k8s.io` domain that will give us more control over redirects in the future. 

As a side note, that would also enable us to switch to Netlify which would give us live previews + likely remove the need for us to manually compile all our docs HTML. I'm going to work on setting up a domain soon and hopefully we'll be in a better position going forward. Sorry for the 404s here!

**Comment by hbagdi** [comment]
> that would also enable us to switch to Netlify

I didn't know we had that option in kube projects. Netlify is very good with such things. Looking forward and let me know if I can help.

**Comment by mrbobbytables** [comment]
@hbagdi It's the preferred option :)

 It's honestly pretty hard to find this stuff as its scattered across a bunch of repos/teams + GitHub search is not super great 😬 We've recently put a list of a bunch of the different services available to project members/repos here to try and list them out in one place: https://k8s.dev/services

**Comment by robscott** [comment]
I've started this process with https://github.com/kubernetes-sigs/gateway-api/pull/559. Does not help the 404 issue but gives us a lot more control going forward.

**Comment by robscott** [comment]
So it looks like we have 2 options here and neither are great:

1. Leave as is
This allows us to maintain the existing redirects from github.com/kubernetes-sigs/service-apis to gateway-api, including the URLs we've recommended using for installing the CRDs.

2. Create a new service-apis and add configuration that will redirect gh-pages to gateway-api
This allows us to redirect from kubernetes-sigs.github.io/service-apis to gateway-api but would break the GitHub redirects for other links. We could add links in the readme for users browsing to our repository, but if anyone was trying to install CRDs using the service-apis URLs, it would break. There would also be a period of time after k8s GitHub admins had created the site but before we had pushed anything to it where everything would be broken.

I think given the extra overhead involved in 2 it is not worthwhile. I wish we'd moved to Netlify earlier in this process so this would not be an issue. Unfortunately we're rather stuck here. I'm going to close this issue, but feel free to reopen if there's anything more we can do here. Although I sure hope we're not going to rename this project again, we'll be better equipped to handle docs updates in the future.

/close
