### ISSUE TITLE
Docs Improvements

### ISSUE THREAD

**Issue by mark-church** [kubernetes-sigs/gateway-api#558]
I wanted to list out some general docs improvements that would improve the site, for others to contribute, and also to keep track for myself. If anybody else has docs improvements that they would find valuable, feel free to pile on this issue and we can keep a running tracker.

- [ ] Make user guide Service names consistent (and consistent within concept docs too). There is foo-v1, foo-v2, foo, foo-canary, etc. Ideally, a small set of Deployment and Service resources should be able to be used to run every single one of the user guides so making the example names converge to only a few would allow this to happen.
- [ ] This needs discussion, but we should decide whether we want to specify an actual application Deployment within the Gateway docs so we can include end-to-end examples that contain real output from an app. I personally think this would be a good move because it would allow the user guides to have concrete steps in them rather than being theoretical examples as they are now. In a [previous version](https://github.com/GoogleCloudPlatform/gke-networking-recipes/tree/master/gateway#traffic-splitting) of the user guide I used [whereami](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/master/whereami) but I'm happy to use any app that highlights the user guides we have.
- [ ] The [multi-ns user guide](https://kubernetes-sigs.github.io/gateway-api/multiple-ns/) should be reformatted into a similar style as the other guide
- [ ] The [TLS in HTTPRoute user guide](https://kubernetes-sigs.github.io/gateway-api/tls/) has some good conceptual content that is maybe better suited for [Gateway concepts](https://kubernetes-sigs.github.io/gateway-api/gateway/). Perhaps we should move some of that content there and slim down this TLS example to a smaller and self-contained guide.
- [ ] A TLSRoute user guide and also TLSRoute API Types page.
- [x] Addition of a "Gateway API implementations" page (or maybe add this content to [getting started](https://kubernetes-sigs.github.io/gateway-api/getting-started/) ) that lists out the current and planned implementations for Gateway. Ideally a user can go to an implementations page which shows how to install or enable that Gateway Controller and corresponding GatewayClasses in a K8s cluster. Then the user can deploy a reference Gateway from one of these GatewayClasses and continue with any of the standard user-guides, which should all theoretically function if that GatewayClass and controller is compliant.
- [ ] Gateway and Route ownership patterns need to be documented. There are several design patterns that make sense:
    - Single-tenant Gateways - Gateway and Route in same Namespace / Gateway and Route deployed by same owner
    - Shared Gateways - Gateways shared by Routes which are owned by different users (across Namespaces and also within the same Namespace)
    - Controlling hostname ownership - This is related to the route merging and conflicts, but a very common question is how to control which route-owners can own which hostnames. This can be done by specifying multiple listeners for the same port with different hostnames. Each of these listeners is bound to a different set of Routes, effectively giving those Routes exclusive ownership over the hostname. Since this is a design pattern, this capability is not really obvious to users and so it should be documented.
- [ ] We probably need some more conceptual content and examples for the [Gateway concepts](https://kubernetes-sigs.github.io/gateway-api/gateway/) page.
- [ ] Route merging and conflicts are only described in the API specification reference. This should have a section in the concept (or HTTPRoute) portion of the docs.

Happy to take edits or additions to this list. I just wanted to record what's on the top of my head before I forget :)

kind/docs

**Comment by robscott** [comment]
This is a great list, thanks for putting it together! I completely agree with more real end to end examples. I still remember how helpful that classic guestbook example was for me when I was getting started with Kubernetes. Providing examples that are similarly useful will make this API much easier to get started with.

**Comment by shaneutt** [comment]
As per today's sync I'll take on this one:

>  Make user guide Service names consistent (and consistent within concept docs too). There is foo-v1, foo-v2, foo, foo-canary, etc. Ideally, a small set of Deployment and Service resources should be able to be used to run every single one of the user guides so making the example names converge to only a few would allow this to happen.

And from there I'll just keep plugging away at other ones.

**Comment by mateiidavid** [comment]
I'd like to improve the TLS section a bit, if that's okay. 
i.e
> The TLS user guide has some good conceptual content that is maybe better suited for Gateway concepts. Perhaps we should move some of that content there and slim down this TLS example to a smaller and self-contained guide.

**Comment by shaneutt** [comment]
@robscott @mark-church what do you think about us breaking down the checkboxes into several smaller issues? Maybe since there are so many smaller things to tackle logistically we could put together a documentation milestone or something to organize them?

Just thinking out loud as I feel like we could break this one down a bit, let me know your thoughts :thinking:

**Comment by navendu-pottekkat** [comment]
@mark-church @robscott Was there any effort made to build an example application?

**Comment by robscott** [comment]
@navendu-pottekkat I'm not sure, what would that look like?

**Comment by navendu-pottekkat** [comment]
I was referring to these two points (first two) made in the issue description:

> Make user guide Service names consistent (and consistent within concept docs too). There is foo-v1, foo-v2, foo, foo-canary, etc. Ideally, a small set of Deployment and Service resources should be able to be used to run every single one of the user guides so making the example names converge to only a few would allow this to happen.
>
> This needs discussion, but we should decide whether we want to specify an actual application Deployment within the Gateway docs so we can include end-to-end examples that contain real output from an app. I personally think this would be a good move because it would allow the user guides to have concrete steps in them rather than being theoretical examples as they are now. In a [previous version](https://github.com/GoogleCloudPlatform/gke-networking-recipes/tree/master/gateway?rgh-link-date=2021-02-17T02%3A52%3A20Z#traffic-splitting) of the user guide I used [whereami](https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/tree/master/whereami?rgh-link-date=2021-02-17T02%3A52%3A20Z) but I'm happy to use any app that highlights the user guides we have.

So, this example application would be able to demonstrate the features provided through the Gateway API. And the goal for creating such an application would be to use it in examples so that readers can actually see an e2e example and test it out themselves using their choice of a Gateway API implementation.

I was looking for such applications for our own project when I came across this issue. We were considering building such an application if there were no existing examples.

So, if there are any existing works, discussions, or ideas, we would be happy to contribute and build on it. Otherwise, if creating a sample application is still a goal, we can maybe help take initiative and work on a proposal for the application.

**Comment by shaneutt** [comment]
@navendu-pottekkat I'm not sure if it's exactly what you're looking for but we're currently working on https://github.com/kong/blixt (which is being donated to Kubernetes SIGs, see https://github.com/kubernetes/org/issues/3875) as a _layer 4_ implementation of Gateway API meant for CI testing and reference purposes. I wouldn't say it's in the right shape _today_ to be used as a reference yet but we have several people who have joined in to collaborate on it and we expect it should be migrated to https://github.com/kubernetes-sigs soon. If you're interested we'd love to have you join us! We have a Gateway API meeting called `[SIG Network] Gateway API Code Jam` on fridays (it's on the [Kubernetes SIGs calendar](https://github.com/kubernetes/community/blob/master/sig-network/README.md)) where this has been the main topic of conversation for several weeks.

**Comment by shaneutt** [comment]
If someone takes this one on, the best next step would be to verify that the bullet point items are still relevant to current documentation and break the remaining individual bullet point items out into separate issues.

**Comment by shaneutt** [comment]
This has grown quite old, and at this point it would appear to make more sense to rely on new reports of problems with the documentation than to try and organize this existing one forward. That said, "closed" does not mean "dead", it mainly means not prioritized: if there's reason to re-open this please let us know the context, and if you're interested in helping to move it forward.
