### ISSUE TITLE
Machine parseable tokens for indicating field support state

### ISSUE THREAD

**Issue by bowei** [kubernetes-sigs/gateway-api#56]
**What would you like to be added**:

This comes from suggestion from @danehans:

For features and structs that can be clearly delineated with a support expectation (base = 100% support, extended = if supported, must be portable, custom = implementation extension), we have a machine parse able label:

```
// +serviceapis:resource:core
// +serviceapis:resource:extended
// +serviceapis:resource:custom
```

This makes it easier create tooling for generating docs later.

**Why is this needed**:

We are already putting `Support: base` in the code comments. This will just formalize the string used.
As this is part of the comments and not consumed for now, the cost for support is quite low.

**Comment by bowei** [comment]
I'm going to send a PR to do the string changes, seems like people are (silently) ok with this.

**Comment by hbagdi** [comment]
This was discussed in office hours on May 13. This is already supported but it turns out it is not documented in the concepts doc.

/assign @bowei

**Comment by jpeach** [comment]
/remove-lifecycle rotten
/lifecycle frozen

this is still a good idea

**Comment by shaneutt** [comment]
While grooming we saw that this one was open for about 2 years without anyone with a strong use case to champion it. We're going to close this as we don't expect anyone's ready to drive it forward, but if you still want this feature and have a strong use case we will be happy to reconsider this and re-open.
