### ISSUE TITLE
Add categories to CRDs

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#589]
**What would you like to be added**:
Add something like:
```
    categories:
    - gateway-api
```

or similar to the CRD spec

**Why is this needed**:
This allows people to do `kubectl get gateway-api` and get all associated types, instead of needing to do `kubectl get gwc,gc,httproute,...`

**Comment by robscott** [comment]
Good idea, I had no idea this was a thing.

/assign
