### ISSUE TITLE
Handling Route status when multiple controllers are involved

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#591]
Consider a route that selects many different gateways from many different controllers. This may cause issues in writing the route status.

At first glance, you could have each controller only update info about gateways they own. However, this makes it hard to handle removal of Gateways. For example, if I see existing status of `gateways: [a, b, c, d]`, and now I see the route matches gateways `a` and `b` owned by my controller, I cannot tell if `c` and `d` are gateways controlled by another controller, or if they are gateways that _used_ to be controlled by my controller but have since been removed.

**Comment by robscott** [comment]
This is a good catch! What would help with this? Maybe we need a class field in `GatewayReference`?

**Comment by howardjohn** [comment]
@robscott I think that would reduce but not eliminate the problem. A controller can handle many classes, they could remove one of the classes and we end up with a dangling reference still?

One option would be a `controller` reference but that feels ugly

**Comment by robscott** [comment]
Yeah, controller name feels like the safest way to avoid dangling references. It doesn't feel quite as natural as using something like GatewayClass, but it might be our best option here.

**Comment by stevesloka** [comment]
I agree controllerName could work. This could also happen if the selector on the Gateway is changed, leaving a set of resources that were once selected but now are not and need the status removed from them.

**Comment by hbagdi** [comment]
Since Rob already has a PR out for this.
/assign @robscott
