### ISSUE TITLE
Document best practices for third party applications bundling routes (ie helm)

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#599]
Its common for Helm charts or other application deployments to bundle an Ingress to expose the application. With gateway-api, it may be less straightforward. I think it would be helpful to define best practices for this.

I would imagine this means:
* Bundle xRoutes, but not Gateways
* Have some configuration to control the gateway selections. We should define the API we recommend for this in terms of what is configurable and how
* Likely some other things - we may need to let the area develop more to know what the best practices are

**Comment by hbagdi** [comment]
> Bundle xRoutes, but not Gateways

> Have some configuration to control the gateway selections. We should define the API we recommend for this in terms of what is configurable and how

As of today, this is still moving but I think letting the end user of the Helm chart have control over the lables of the xRoute resource of the application as well as `spec.gateways` should be sufficient.

**Comment by shaneutt** [comment]
While grooming we saw that this one was open for a long period of time without anyone with a strong use case to champion it. We're going to close this as we don't expect anyone's ready to drive it forward, but if you still want this feature and have a strong use case we will be happy to reconsider this and re-open.
