### ISSUE TITLE
Traefik Implementation Link is Broken

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#602]
In the implementations docs, our Traefik link currently targets https://doc.traefik.io/traefik/routing/providers/kubernetes-gateway/. It looks like that link no longer works. Maybe https://doc.traefik.io/traefik/master/routing/providers/kubernetes-gateway/ and/or https://traefik.io/blog/getting-started-with-traefik-and-the-new-kubernetes-gateway-api/ would be better to link to. Not sure if this is a problem with our docs or something that accidentally changed on Traefik side.

/kind documentation
cc @santode

**Comment by SantoDE** [comment]
I'll take a look tomorrow and if needed do a PR to fix

**Comment by SantoDE** [comment]
We had an issue on Thursday with our docs, which was related. The issue since then is fixed and we don't need to make changes :)
