### ISSUE TITLE
Kubernetes.io Blog Post for Gateway API

### ISSUE THREAD

**Issue by mark-church** [kubernetes-sigs/gateway-api#604]
I'm putting together a blog post for the Kubernetes.io public site that is an introduction for Gateway API. Since this is a community effort, I'd like to have the primary contributor(s) from each [contributing company](https://gateway-api.sigs.k8s.io/implementations/) be listed as authors. The goal is to get this published prior to Kubecon on May 4th to generate some awareness of Gateway API going into the conference.

[This](https://docs.google.com/document/d/1jJqRf7lRQzw_cg15eIllpz2PV1m6kkZDKw5Mj8fa8gQ/edit?usp=sharing) is the draft blog post. I've already listed some folks as authors that have been actively involved for some time. For other companies I'm not sure who is the best person but I'll let them decide: @bowei @robscott @hbagdi @danehans @stevesloka @SantoDE @yuval-k

cc @mrbobbytables

**Comment by hbagdi** [comment]
Happy to do this. Thanks for the effort Mark!

**Comment by mark-church** [comment]
@stevesloka, @robscott thought it might be a bit simpler if we just showed one author per contributing company. Feel free to edit the doc for whether it should be you or @youngnick :)

**Comment by mark-church** [comment]
@yuval-k lmk who is the best person to list as the author from Solo. Thanks!

**Comment by stevesloka** [comment]
@mark-church I updated, can use @youngnick for this one. Let's write another later on with implementation stories or something. =)

**Comment by SantoDE** [comment]
Obviously LGTM to me. Great post. Thanks @mark-church :)

**Comment by danehans** [comment]
Other than a few nits, LGTM. Thanks @mark-church for leading the effort.

**Comment by hbagdi** [comment]
The blog was published: https://kubernetes.io/blog/2021/04/22/evolving-kubernetes-networking-with-the-gateway-api/

/close
