### ISSUE TITLE
speed up hack/verify-golint.sh for developer environment

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#607]
**What happened**:
./hack/verify-golint.sh is super slow because golangci-lint takes a while to generate intermediate representation. The intermediate representation is not being cached to disk.

**What you expected to happen**:

./hack/verify-golint.sh to run fast and provide a good developer experience 

**How to reproduce it (as minimally and precisely as possible)**:
 
**Anything else we need to know?**:

**Comment by hbagdi** [comment]
I tried fixing this with a time boxed 15 minutes but couldn't get it to work due to file permissions.
The solution here would be to mount a volume (or reuse existing one) from host to container and then set GOLANGCI_LINT_CACHE (https://golangci-lint.run/usage/configuration/#cache) appropriately.

**Comment by youngnick** [comment]
I had a crack at this, and saw a 35 second improvement, from 80sec to 45sec.

I'll make a PR, but in short, I gitignored a cache directory, then mounted it into the container, and set the `GOLANGCI_LINT_CACHE` dir.
