### ISSUE TITLE
Clarify how Gateways and Routes should interact with TLS

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#612]
This is a followup to the great conversation in [Slack](https://kubernetes.slack.com/archives/CR0H13KGA/p1618300603046300). I think we reached a good consensus there, we just need to document it.

/assign @hbagdi

**Comment by SantoDE** [comment]
@hbagdi we can try to help working on that (or do a draft you can review) if that helps :)

**Comment by jbdoumenjou** [comment]
We are focused on the [downstream](https://gateway-api.sigs.k8s.io/guides/tls/#downstream-tls) connection (between the Client and the Gateway).

Concerning the HTTP protocol, the TLS is defacto terminated and so `HTTPRoute` will manage both HTTPS and HTTP Gateway Protocol types.

Concerning the TCP protocol, the TLS could be terminated or not (passthrough mode). The `TLSRoute` must be used for SNI matching routing and `TCPRoute` for simple TCP forwarding.

![gateway-api-downstream](https://user-images.githubusercontent.com/925513/114881362-38cd4800-9e03-11eb-8bc4-77d1424ec482.png)

Do the `Gateway.Listener.Hostname` has any impact on the `TLSRoute` SNI matching?
   - If yes, how do we manage it? That means `TCPRoute` will use the listener hostname to apply SNI matching routing and `TLCRoute` has to take the hostname into account.
   - If no, that means that the only way to route on SNI is to use the `TLSRoute`.

**Comment by stevesloka** [comment]
@SantoDE were you going to work on this? Just wanted to confirm so we don't duplicate efforts.

**Comment by SantoDE** [comment]
I want to! Either tomorow or early next week. If you want go first, feel free tough :)

**Comment by robscott** [comment]
Hey @SantoDE, thanks for offering to take this on! Do you think it would be possible to get a PR in for this tomorrow? We're hoping to cut v0.3.0 on Thursday and it would be awesome if this could make it into that release. If not, let me know and @stevesloka or I can take it on.

**Comment by SantoDE** [comment]
Yeah I will work on it today my time and try to finish it. Otherwise I gonna continue tommorow my time (Wednesday)
