### ISSUE TITLE
Provide admission server builds for CPU architectures other than amd64

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#627]
**What would you like to be added**:

Admission server builds are currently only available for amd64 architecture.
We should provide builds for other architectures as well.

**Why is this needed**:
Our users could be running k8s clusters on other CPU architectures.

**Comment by hbagdi** [comment]
For some context, #621 was the first attempt to get an image built and published. We decided to take an incremental approach to building out our images. There is no blocker for building docker images for other CPU architectures.

**Comment by youngnick** [comment]
/good-first-issue

Outstanding work here is to update our webhook admission build to some other architectures, `linux/arm64` for certain, and to make sure we can add more if needed.

**Comment by akankshakumari393** [comment]
Quick question - 
1. what all arch do we want to add?
2. All arch images need to use to repo that has arch information in its name, earlier we were using `${REGISTRY}/admission-server:${VERSION_TAG}`. Now it should be `${REGISTRY}/admission-server-${ARCH}:${VERSION_TAG}`. So do we need to create new repo or is it handled by infra team.

**Comment by youngnick** [comment]
I think that `amd64` and `arm64` are probably okay for now, we can add more later if required.

I didn't know that was a requirement, maybe we can check with some other things like ingress-nginx as to how they handle this (I don't think that other Kubernetes projects have the arch in the repo name?)

**Comment by shaneutt** [comment]
We now have a multi-arch build with new `arm64` support:

https://console.cloud.google.com/gcr/images/k8s-staging-gateway-api/global/admission-server@sha256:5dd8c42658daeb0a26ba0e4ac5e33c3bba2f1f4cd0f41685f837dd4a3684d2f0/details?tab=pull
