### ISSUE TITLE
Create a release checklist document

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#646]
**What would you like to be added**:

A document outlining the release steps to be followed to perform a release of this API. This should include things like ordering of various tasks (merges, git-tag, release creation, update docs etc) to be performed, notifications to be sent out to the world and more things as we grow. 

**Why is this needed**:
- These are usually ad-hoc in every release. Documenting it makes it easy for other maintainers and community members to help out.
- Release is a high-impact thing and making it as simple/dump as possible helps.
- As number of components increase (admission-webhook coming in shortly), having these steps written down avoids confusion. Git is the source of truth.
-

**Comment by youngnick** [comment]
/lifecycle frozen

Feels like whoever is doing the v1alpha2 release should take notes and then turn it into a checklist?

**Comment by shaneutt** [comment]
We now have https://github.com/kubernetes-sigs/gateway-api/blob/main/RELEASE.md#release-steps
