### ISSUE TITLE
Figure out versioning strategy for validating webhook server

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#647]
## Background

We are very close (#487) to getting automated validating webhook server builds working.
For a good user-experience, the validating webhook will either need to be part of the default installation of Gateway API spec into a cluster or we (or every implementation) will need to make it super-easy to do so.

The first path in that direction is deciding the versioning strategy and release cadence for the validating webhook. 

## Proposal 1

The webhook-server image  follows the same versioning strategy as the Go API of this repository.
Meaning, when `v0.4.0` is released, we will tag the Docker image of the webhook-server as `v0.4.0`.
This essentially ties up release of the webhook-server with the release process of this API.
Pros:
- Less communications to the external world
- Fewer versions to maintain and no need to create compatibility matrix

Cons:
- Once the API is stable/frozen, how will the webhook server updates go out?
- If the webhook-server needs more frequent updates, the API will also need to be released, even though that might not be required.

**Comment by robscott** [comment]
This may not scale long term, but I think it's fine to tie the webhook versioning to the version of this project as a whole. I think what we've been doing here for versioning is similar in concept to what upstream already does. Each new minor project version can include:

- new functionality
- backwards compatible updates to an existing API version
- introduction of a new API version

Given that, I think it's possible to say that we could have new versions of this project in the future that only included 1 of the above (such as new functionality). Whenever I get conformance tests in, I think we'll also have similar considerations for versioning as well, but I think that should also work well.

**Comment by hbagdi** [comment]
> Given that, I think it's possible to say that we could have new versions of this project in the future that only included 1 of the above (such as new functionality). Whenever I get conformance tests in, I think we'll also have similar considerations for versioning as well, but I think that should also work well.

That works well. One con I can think of is that this package could have many versions and many versions can confuse users.

Having said that, I'm in favor of versioning the webhook-server same as this repository as well.
If we have consensus, we can post the decision and close this issue out.

**Comment by robscott** [comment]
> One con I can think of is that this package could have many versions and many versions can confuse users.

I think we'll have 2 versions here:
- Project version (currently v0.3.0), similar in concept to Kubernetes version (currently v1.21)
- Supported API versions (currently networking.x-k8s.io/v1alpha1), similar in concept to the long list of API versions supported with each upstream release

Although Kubernetes versioning has some complexity, if we follow a similar approach here, it should at least be familiar for anyone using the API.

In each case I think we have pretty clear parallels from upstream:

- APIs -> Kubernetes API Types
- Webhook -> Validation packages
- Conformance -> e2e test suite

Most new minor Kubernetes releases introduce changes to all of the above, and I'm guessing that will be true for most of the upcoming Gateway API releases as well. 

Also interested in if this lines up with what others were thinking here:

/cc @bowei @danehans @jpeach

**Comment by bowei** [comment]
Just to be clear, is the proposal (version numbers are fake):

| webhook release | supported K8s versions |
| ---- | ---- | 
| 0.50 | v1alpha1 |
| 0.60 | v1alpha1, v1alpha2 |
| ... | |
| 1.2 | (drop v1alpha1), v1alpha2, v1beta1 |

**Comment by robscott** [comment]
I think we should follow the upstream Kubernetes versioning model. That would mean that all components included in the project supported all API versions associated with the project version (primarily including validating webhook and conformance tests).

| Project Version | Supported API Versions |
|-|-|
| v0.3.0 | v1alpha1 |
| v0.4.0 | v1alpha2, v1alpha1 |
| v0.5.0 | v1alpha2, v1alpha1 |
| v0.6.0 | v1beta1, v1alpha2 |

**Comment by hbagdi** [comment]
Having heard no objects or arguments the versioning strategy proposed here and as summarized in https://github.com/kubernetes-sigs/gateway-api/issues/647#issuecomment-832874418, we will be using it for now.
Please re-open the issue if you disagree or feel that this requires more discussion.
/close
