### ISSUE TITLE
Clarify Gateway.Listener.Hostname interaction with HTTPRoute

### ISSUE THREAD

**Issue by stevesloka** [kubernetes-sigs/gateway-api#654]
I had a question when implementing `Gateway.Listener.Hostname` and how it interacts with `HTTPRoute.Spec.Hostnames` on Slack (Thread here: https://kubernetes.slack.com/archives/CR0H13KGA/p1620328409212700) with @hbagdi, @jpeach, & @robscott. 

My understanding of how it works was incorrect and wanted to open this issue to clarify how it should work so I could help update the docs. 

- An HTTPRoute that binds to a listener on the gateway MUST have hostnames that are a subset of the hostname(s) defined on the listener.
- A listener with `unspecified`, `“”, or *as hostname, then a HTTPRoute can have **any** hostname.
- A listener with `test.foo.com` as hostname, then a HTTPRoute can **only have the hostname** `test.foo.com`. All others won't match the Gateway and should function similar to `[RouteGateways](https://gateway-api.sigs.k8s.io/references/spec/#networking.x-k8s.io/v1alpha1.RouteGateways)`?
- A listener with `*.foo.com` as hostname, then a HTTPRoute can have `test.foo.com` or `*.foo.com` or `steve.foo.com`. A HTTPRoute with `bar.com` would not match the Gateway and should function similar to `[RouteGateways](https://gateway-api.sigs.k8s.io/references/spec/#networking.x-k8s.io/v1alpha1.RouteGateways)`?

In the example above where the Gateway has `*.foo.com`. What if my HTTPRoute had `test.foo.com` as well as `steve.bar.com` where one hostname matches, but another doesn't. Should we route on only `test.foo.com` or make the Route invalid? (Or maybe do both?)

**Comment by jpeach** [comment]
It’s a single label. I thought that the spec had some explicit language about that?

**Comment by sunjayBhatia** [comment]
sorry to clarify i mean the docs should be explicit about the wildcard case in the Listener field and HTTPRoute hostname field interaction, e.g. if a Gateway specifies `*.foo.com`, the HTTPRoute docs should mention that the hostname field there can only be something like `steve.foo.com` not `bob.steve.foo.com`

**Comment by youngnick** [comment]
I think that in all cases, an error with a hostname is grounds for being rejected, and the whole Route should be marked as `Admitted` with a status of `false`.

I think we can resolve the other two questions by changing the last bullet point like this:

* A listener with *.foo.com as hostname, then all hostnames in the  HTTPRoute must have any single label where the star is, and the rest of the hostname must match. So, `test.foo.com`,  `*.foo.com` or `steve.foo.com` would match. `steve.test.foo.com`, `steve.bar.com`, or `bar.com` would not. Not matching means that the HTTPRoute must have an `Admitted` condition added, with `status: false`. No further processing will be performed.

If we all agree this makes things clear, I'll do a PR to add it to the HTTPRoute object.

Note that there is similar behavior for TLSRoute, but that has some other interactions with certificates that would need some thought.

**Comment by jpeach** [comment]
> I think that in all cases, an error with a hostname is grounds for being rejected, and the whole Route should be marked as `Admitted` with a status of `false`.
> 
> I think we can resolve the other two questions by changing the last bullet point like this:
> 
> * A listener with *.foo.com as hostname, then all hostnames in the  HTTPRoute must have any single label where the star is, and the rest of the hostname must match. 

In all cases, we should be only matching a single label. This rule comes from TLS SNI matching rules, and I think it's easier if we just apply it everywhere.

> If we all agree this makes things clear, I'll do a PR to add it to the HTTPRoute object.

Suggest hoisting this language up to the `Hostname` type so it's applied consistently everywhere.

> Note that there is similar behavior for TLSRoute, but that has some other interactions with certificates that would need some thought.

HTTPRoute can be used with http and https schemes, so I think the matching rules apply universally.

**Comment by robscott** [comment]
Agree with the conclusions here, thanks for raising this issue @stevesloka. If anyone wants to take on this docs update, add a comment here to let us know you're working on it.

**Comment by youngnick** [comment]
I'll take this one.

/assign

**Comment by sunjayBhatia** [comment]
Question from the contour issue above ^

Can you have a Gateway Listener with hostname `a.b.com` and HTTPRoute hostname `*.b.com`

My first instinct is no, b/c the Gateway is a precise match and `*.b.com` is a superset of what the Gateway specifies (even if you end up programming only `a.b.com`, but hoping we can clarify this as well

**Comment by howardjohn** [comment]
> Can you have a Gateway Listener with hostname a.b.com and HTTPRoute hostname *.b.com

How it works in Istio, which I think is a good part of the API, is it is essentially a bidirection handshake. So we take the intersection of hosts in GW and HTTPRoute.

So in this case, the route would apply, but only for a.b.com, not c.b.com.

**Comment by jpeach** [comment]
> > Can you have a Gateway Listener with hostname a.b.com and HTTPRoute hostname *.b.com
> 
> How it works in Istio, which I think is a good part of the API, is it is essentially a bidirection handshake. So we take the intersection of hosts in GW and HTTPRoute.
> 
> So in this case, the route would apply, but only for a.b.com, not c.b.com.

Yup, agreed. In some other PR, I described this as a 2 level filter. Requests would first have to match the Listener hostname (via SNI or Host header), then they have to match one of the attached routes.

**Comment by youngnick** [comment]
I've updated #674 with an idea about this.
