### ISSUE TITLE
Transition from maps to lists of named subobjects

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#658]
**What happened**:
Maps were used several places throughout the API. Including, but likely not limited to:

* Query Param Matching (#657)
* Header Matching (#657)
* Header Modification (assignee: @hbagdi, #681)

This is also the case for TLS options, but I think it's likely appropriate in that case.

**What you expected to happen**:
Lists of named subojects should be used to match the [API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps).

**Comment by hbagdi** [comment]
@robscott I have opened up #681 to handle the header modifier filter. Do we want to go ahead with TLS or not? I don't have strong feelings either way.
