### ISSUE TITLE
Should spec be optional/omitempty?

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#665]
In v1alpha1 of Gateway API, `spec` section for all API types are optional.
This leads to bugs like #661 where empty resources with empty spec sections can be created for all resource types.

`omitempty` was redacted in #664 which make spec required but as @robscott [pointed out](https://github.com/kubernetes-sigs/gateway-api/pull/664#issuecomment-840167442), almost every type in Kubernetes/kubernetes has `spec` field marked as `omitempty`, meaning optional. Although these are marked as optional, validation in k/k prevents creation of empty resources (at least with Deployment, Service, Pod).

If it turns out that `spec` should indeed be optional, then how should we perform validation?

The purpose of this issue it to figure out the right thing to do in this case with some guidance from SIG apimachinery.

**Comment by jpeach** [comment]
I think that unless an empty spec is meaningful and results in some valid configuration, it should not be allowed.

**Comment by hbagdi** [comment]
Linking a slack thread with SIG apimachinery: https://kubernetes.slack.com/archives/C0EG7JC6T/p1626218466356300

**Comment by jpeach** [comment]
> Linking a slack thread with SIG apimachinery: https://kubernetes.slack.com/archives/C0EG7JC6T/p1626218466356300

I read that thread but the conclusion wasn't clear to me. Should spec be required or not?

```
$ git grep -B1  Spec.*json..spec ./apis/v1alpha2/
apis/v1alpha2/backendpolicy_types.go-   // Spec defines the desired state of BackendPolicy.
apis/v1alpha2/backendpolicy_types.go:   Spec BackendPolicySpec `json:"spec"`
--
apis/v1alpha2/gateway_types.go- // Spec defines the desired state of Gateway.
apis/v1alpha2/gateway_types.go: Spec GatewaySpec `json:"spec"`
--
apis/v1alpha2/gatewayclass_types.go-    // Spec defines the desired state of GatewayClass.
apis/v1alpha2/gatewayclass_types.go:    Spec GatewayClassSpec `json:"spec"`
--
apis/v1alpha2/httproute_types.go-       // Spec defines the desired state of HTTPRoute.
apis/v1alpha2/httproute_types.go:       Spec HTTPRouteSpec `json:"spec"`
--
apis/v1alpha2/tcproute_types.go-        // Spec defines the desired state of TCPRoute.
apis/v1alpha2/tcproute_types.go:        Spec TCPRouteSpec `json:"spec"`
--
apis/v1alpha2/tlsroute_types.go-        // Spec defines the desired state of TLSRoute.
apis/v1alpha2/tlsroute_types.go:        Spec TLSRouteSpec `json:"spec"`
--
apis/v1alpha2/udproute_types.go-        // Spec defines the desired state of UDPRoute.
apis/v1alpha2/udproute_types.go:        Spec UDPRouteSpec `json:"spec"`

```

**Comment by youngnick** [comment]
I think the answer was "It's okay to have spec be required, as long as you curate the default values inside it".

**Comment by jpeach** [comment]
> I think the answer was "It's okay to have spec be required, as long as you curate the default values inside it".

So we can close this out with no further action?

**Comment by robscott** [comment]
>So we can close this out with no further action?

I'd agree with that conclusion.

/close
