### ISSUE TITLE
Need v1alpha1 equivalent examples for v1alpha2

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#666]
**What happened**:

There is not way to write examples for v1alpha2 resources.

**What you expected to happen**:

There should be a way to write v1alpha2 examples.

**Comment by hbagdi** [comment]
One solution that I can think of is to have a v1alpha2 directory inside the existing examples directory, copy over the existing examples, change their API versions and go from there.
We can't change the existing examples because they are referenced in docs site.

**Comment by robscott** [comment]
I made some assumptions for this in https://github.com/kubernetes-sigs/gateway-api/pull/657 where I created a new v1alpha2 directory in /examples.

**Comment by robscott** [comment]
It's possible that we should copy all examples over to that in one go, but instead I just copied them over as they changed.

**Comment by hbagdi** [comment]
Should we copy these over first in a PR and then change them as we go forward? I can send a PR if that works.
It might have happen that some never change and we might miss some of those examples, which will then later break our docs site once it switches to v1alpha2.

**Comment by robscott** [comment]
I don't have a strong opinion here, but would lean towards copying examples over as they're needed. One advantage of this approach is that we won't end up with stale examples that we never reference or use. It provides a natural way to get rid of examples from v1alpha1 that are no longer useful.

**Comment by youngnick** [comment]
I tend to agree with @robscott here, but maybe we need to add a release checklist note to review the examples and bring forward any that are still relevant?

**Comment by robscott** [comment]
>maybe we need to add a release checklist note to review the examples and bring forward any that are still relevant?

Yep, that's a great idea

**Comment by youngnick** [comment]
/lifecycle frozen

@robscott we should probably look at this one soon.

**Comment by robscott** [comment]
@youngnick Added to v1alpha2 milestone. Now that API is mostly finalized, it probably makes sense to split examples into v1alpha1 and v1alpha2 directories, and ensure that we have v1alpha2 examples to correspond with all v1alpha1 examples.

**Comment by youngnick** [comment]
Agreed. My current plan is to do exactly that - I'll move the currently-unversioned examples into a `v1alpha1` directory and update the v1alpha1 guides, then we can do the v1alpha2 stuff as we get the guides and examples updated.

Additionally, I think that having the examples be in a directory each will greatly help using them in the guides, since we can include the example YAML in the guide when it's rendered.
