### ISSUE TITLE
Change Kind to resource in all object references as Kind is computationally inefficient

### ISSUE THREAD

**Issue by bowei** [kubernetes-sigs/gateway-api#689]
It looks like the use of Kind to reference objects is computationally expensive for the API server.

There is a proposal in OwnerReference to change to resource.

https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2336-OwnerReference-resource-field/README.md

As we are making a breaking change in v1alpha2, we should consider fixing this.

**Comment by howardjohn** [comment]
Does this apply to us? It seems like the controller knows all types it will handle and can just make a mapping of resource <-> kind for all types they know which is trivial.

That also means the inverse is true and `resource` is probably almost just as easy though

**Comment by jpeach** [comment]
ObjectReference uses Kind, so if we switch to Resource, are we going to end up as that one weird API that does things differently?

**Comment by bowei** [comment]
Given the above KEP, it sounds like it will be the norm to fix this in all of the APIs, but I have to look at KEP in more detail.

**Comment by robscott** [comment]
I think the upstream KEP will actually result in both Kind and Resource being fields in OwnerReferences, with Resource taking precedence over Kind when it is specified. Given the relative newness of this concept, and that it applies to a field that most users don't write to, I think we'd likely also want to have both fields. I see the value of this proposal as it allows for more precision while writing references, but I think it's probably a bit too early to drop Kind altogether.

Maybe authors of the KEP and/or members of sig-apimachinery have an opinion on what we should be doing as a new API here.

/cc @deads2k @caesarxuchao @lavalamp

**Comment by lavalamp** [comment]
> use of Kind to reference objects is computationally expensive for the API server

No -- resource is preferred because it is unambiguous. apiserver won't be doing any processing on references.

**Comment by lavalamp** [comment]
> what we should be doing as a new API here

Please follow the advice we just merged here: https://github.com/kubernetes/community/pull/5748

Re: that KEP: I am not sure we will be changing this in existing types, as schema changes are extremely disruptive.

**Comment by robscott** [comment]
@lavalamp Thanks for the reference! Do you know of any widespread uses of `resource` fields (instead of `kind`) in object refs? We actually originally used `resource` fields before our initial release but reverted them due to our concerns about it potential confusing users: https://github.com/kubernetes-sigs/gateway-api/issues/293. Of course at that point I don't think there was any clear guidance like you referenced above though.

**Comment by lavalamp** [comment]
@robscott So far, this (using "resource") is prescriptive, not descriptive :)

This guidance is only like a week old, yeah.

**Comment by robscott** [comment]
API conventions have been updated so this is no longer necessary: https://github.com/kubernetes/community/pull/5748.

/close
