### ISSUE TITLE
Change API group from x-k8s.io to k8s.io

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#690]
After some discussion with @thockin, @liggitt, and an earlier [Slack thread](https://kubernetes.slack.com/archives/C09QYUH5W/p1618570463278100) with @aojea, it sounds like we should be moving to the k8s.io API group as part of the v1alpha2 release.

As I understand it, `x-k8s.io` is intended to represent experimental Kubernetes APIs while `k8s.io` is intended to represent official Kubernetes APIs that are subject to all the standard API reviews as APIs within k/k. Given that, `x-k8s.io` was likely the correct choice for v1alpha1, but no longer correct as we're approaching a release where we want to achieve some form of stability, including:

- conversion support with future API versions
- hopefully no breaking changes in future releases

Unfortunately changing to a new API group will result in the CRDs being distinct. This means that both v1alpha1 and v1alpha2 could be represented as different CRDs (and `kubectl get httproute` could refer to either without fully specifying). Although that's not great, I don't think we want to be an experimental API long term, and this v1alpha2 release feels like an appropriate time to make the transition.

We can't simply go from `networking.x-k8s.io` to `networking.k8s.io` because that API is already being served from k/k. Some alternatives I've thought of:

- routing.k8s.io
- gateway.networking.k8s.io
- routing.networking.k8s.io

Any other ideas would be very welcome. I think this discussion is also highly relevant to network-policy team, so CCing them here as well:

/cc @rikatz @jayunit100

**Comment by youngnick** [comment]
I think `gateway.networking.k8s.io` makes the most sense to me, this is the *Gateway* API, after all, and I think that the Gateway object is the key one. Interested to hear if people with wider context agree though.

**Comment by howardjohn** [comment]
Is `gateway.k8s.io` an option? Just to be slightly shorter

**Comment by robscott** [comment]
>Is gateway.k8s.io an option? Just to be slightly shorter

I don't think there are currently any conflicts with that, but it might be a bit more likely to conflict with something in the future? Agree that a short name is helpful, especially if we're going to have to advise users to use fully qualified names in their kubectl calls.

**Comment by abhiraut** [comment]
i have a couple of questions (from the perspective of network-policy-api subgroup)
1. seems like apiGroup `x-k8s.io` for experimental v1alpha1 was the right choice? Is that the recommendation for future network policy APIs as well; for example, with ClusterNetworkPolicy APIs, shall we continue with `x-k8s.io` group or directly move to `k8s.io` to avoid difficulties present in transitions?
2. The new names suggested in this issue are very gateway APIs specific. Does it make sense to have a common group name for both gateway APIs and NetworkPolicy APIs, or we continue to think about two separate groups.. or something on the lines of what @youngnick suggested, `gateway.networking.k8s.io` and perhaps `something-netpol-related.networking.k8s.io`

**Comment by robscott** [comment]
Hey @abhiraut, these are great questions.  

> shall we continue with x-k8s.io group or directly move to k8s.io to avoid difficulties present in transitions?

I think it's likely easier to start with `k8s.io` now that there's a bit of precedent here. Transitioning between API groups is unfortunately not a great experience.

> Does it make sense to have a common group name for both gateway APIs and NetworkPolicy APIs, or we continue to think about two separate groups.

I think it will be simpler to manage separate API groups here. I like the idea of grouping them under `*.networking.k8s.io`, but that also results in pretty long fully qualified names when compared with `gateway.k8s.io`. At the very least, I think we should coordinate to make sure we're following the same pattern, whatever that ends up being.

**Comment by abhiraut** [comment]
Thanks for your quick reply!

We would really like to avoid the transition pains so we will go ahead and use `k8s.io` group for network policy stuff for now.
I will keep an eye out on the proposed name for gateway APIs so we follow a similar pattern (personally prefer the `gateway.networking.k8s.io` name)

**Comment by bowei** [comment]
Just to call out some things that are subtle:

* A given API group can only be served via a single mechanism, e.g. built into the core (like networking.k8s.io) or via CRDs. These cannot be mixed.
* API group transition means that objects need to be migrated between the two via an external process -- (download, modify, reapply). There is no version conversion across group boundaries.

**Comment by qabpea** [comment]
> * routing.k8s.io
> * gateway.networking.k8s.io
> * routing.networking.k8s.io

Routing is an overloaded term in networking, it is used in many layers of the NW stack. 
My first association will always be L3 packet routing and not message or mail routing....

//Per

**Comment by robscott** [comment]
We discussed this at sig-network on June 24 where @dcbw, @thockin, and others preferred gateway.networking.k8s.io. We also discussed this at the June 29 Gateway API meeting and that name also seemed to win. Given that that option seems to be popular on this thread as well, I'll create a PR to make that change.
