### ISSUE TITLE
Add support for multiple `kinds` within a single Gateway listener

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#699]
**What would you like to be added**:
Replace `kind` with `kinds` in gateway listener

**Why is this needed**:

We may want to select multiple kinds. For example, perhaps I have a listener I want TCP and TLS routes on. Or I make a custom GrpcRoute and want it on the same port as an HTTPRoute. Or I have a legacy resource (say Istio VirtualService) which I want on the same port as HTTPRoute.

The primary alternative would be to have multiple listeners defined and merge them. However, in some cases this is impossible. For example, if two listeners for the same domain are configure with different TLS properties, merging is ~impossible. Having multiple kinds seems more desirable.

Another alternative: make `kind` optional. If left empty, the controller will decide which routes to use based on the protocol. This may be desirable for other reasons as well (simpler config - `protocol: HTTP` will probably always have `kind: HTTPRoute`)

**Comment by hbagdi** [comment]
> Another alternative: make kind optional. If left empty, the controller will decide which routes to use based on the protocol. This may be desirable for other reasons as well (simpler config - protocol: HTTP will probably always have kind: HTTPRoute)

I think it would be best to be explicit about `kind` in configuratoin for two reasons:
- Makes the controller behavior deterministic and makes the controller a little dumber (in a good way)
- [Cluster operators](https://gateway-api.sigs.k8s.io/concepts/security-model/) continue to have explicit control over which routes are being selected to route traffic.

**Comment by howardjohn** [comment]
> Isn't this already possible?

In your example it is, although quite verbose. But that only works well if listeners are merge-able. For example:

> ```yaml
> listeners:
>   - protocol: HTTPS
>     hostname: foo.com
>     port: 80
>     routes:
>       kind: HTTPRoute
>     tls: passthrough
>   - protocol: HTTPS
>     hostname: foo.com
>     port: 443
>     routes:
>       kind: VirtualService
>     tls: terminate
> ```

We cannot merge these together since TLS settings are not compatible. This means it will become very unclear when we can actually merge them and when we cannot, and subtle changes may lead to breakage as they all need to be kept in sync, etc. Additionally, for our use case we will almost always want multiple `kinds`, so that would require all users to duplicate listeners.

Allowing optional also makes the GW more portable. If I just want to declare I am opening an HTTP port 80, why do I need to say what type of routes? I may be fine with any routes that the controller understands that will handle HTTP traffic.

> Makes the controller behavior deterministic and makes the controller a little dumber (in a good way)
> Cluster operators continue to have explicit control over which routes are being selected to route traffic.

Both of these are up to the controller. The controller and the gateway owner can _choose_ to support many kinds by default or not, so it seems fairly explicit - in some ways you have more control than today as you can choose to allow a single kind or more; today you have no choice.

**Comment by jpeach** [comment]
@howardjohn Does using multiple kinds really solve your example? By definition, if you had multiple kinds in the same listener, they would have the same TLS properties, which means that the equivalent multi-listener configuration would (or at least could) be merged.

**Comment by howardjohn** [comment]
I would expect that our users will always want to define at least two route kinds - possibly more in the future. This means they not only need to duplicate every listener, they also need to make sure the configurations are exactly in sync or they will not be able to merge properly which will unexpectedly break their configuration.

Even with just 1 kind, I don't see why we want to make users declare the kind in common cases. They already have to declare the protocol as `HTTP`, so its pretty easy for the controller implementation to look for any kinds it supports that are for HTTP. For a core implementation that would be just HTTPRoute, for others that may be HTTPRoute+GrpcRoute or whatever else they come up with.

**Comment by jpeach** [comment]
This might feel a bit icky, but an implementation could support "virtual resource categories" in the object reference. So for Istio

```yaml
listeners:
  - protocol: HTTPS
    hostname: foo.com
    port: 80
    routes:
      group: virtualresources.istio.io
      kind: HTTP # This means any HTTP route types that Istio groups together as fungible for HTTP routing.
    tls: passthrough
```

**Comment by howardjohn** [comment]
One issue with that is its not portable, unless we add it to the core spec?

**Comment by robscott** [comment]
I think as we get more Route types, it could be beneficial to support multiple Route kinds being attached to the same Gateway listener. Although most of our initial use cases have been focused on Gateway -> HTTPRoute, it does seem likely that implementations will want to support more than that, especially as concepts like grpc start to come into play. I agree with @hbagdi's points above that it's good to keep this config explicit, so I would be in favor of a `kind` to `kinds` change. 

Doing this would introduce more edge cases (implementation supports selecting FooRoute but not BarRoute), but I don't think that's a sufficient reason to prevent us from doing this. I think that the kinds of supported routes are really a parallel concept to the namespaces a Gateway listener supports, so allowing admins to specify multiple for both seems reasonable.

**Comment by jpeach** [comment]
Explicit config of multiple kinds here seems pretty verbose though. I do get the use case it's just not very ergonomic.

**Comment by jpeach** [comment]
> I think as we get more Route types, it could be beneficial to support multiple Route kinds being attached to the same Gateway listener. 

```Go
type Listener struct {    
...
        // +kubebuilder:validation:MinItems=1 
        Routes []RouteBindingSelector `json:"routes"`
}
```
