### ISSUE TITLE
Discussion Boards

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#708]
**What would you like to be added**:

Github Discussions for this repository.

**Why is this needed**:

While similar it's less formal than Github Issues and can promote forum and conversations which will be easier to search and catalog than Slack messages. Worst case you can just turn them off later if they don't work out, right?

**Comment by robscott** [comment]
I haven't used GitHub discussions very much, do we know if we're using them anywhere else for k8s projects? Is there any overlap with discuss.kubernetes.io? For example Cluster API seemed to use that for some time: https://discuss.kubernetes.io/c/contributors/cluster-api/23.

/cc @mrbobbytables @bowei

**Comment by mrbobbytables** [comment]
They aren't being used too much - but there are a few groups that are using them:
- https://github.com/kubernetes/sig-release/discussions
- https://github.com/kubernetes-sigs/kubebuilder/discussions

The general issue is that they can't be labeled, if you want to apply any sort of taxonomy on top of them, or assign someone a follow up they should be issues.

**Comment by hbagdi** [comment]
How do we arrive at a decision to move this forward or not?

**Comment by youngnick** [comment]
Probably talk about it in a meeting? I think it seems like it might be useful. and if we do turn it on, either it's useful and we keep it, or noone uses it and we turn it off.

**Comment by robscott** [comment]
Added to agenda for Monday's meeting.

**Comment by youngnick** [comment]
In the Monday meeting, we discussed this, and there's no objections to doing this, but none of us have the bandwidth to set things up properly.

If anyone wants to figure out:
- what we need to do to enable
- how we should manage the discussions

Then please feel free.

I suggest
/lifecycle frozen
but I'm not sure if I have perms.

**Comment by shaneutt** [comment]
> what we need to do to enable

Under the repository "settings" simply checking the checkbox to enable discussions is enough to turn everything on.

> how we should manage the discussions

I suggest a light handed approach: let it happen organically but we can write an welcome message to remind people that if someone feels a discussion needs further attention they are welcome to put it on the community sync agenda, and/or transferring it to issues for normal grooming (Github has a link on each discussion to do this if desired).

I'm happy to write up the Welcome message.

**Comment by youngnick** [comment]
@robscott, would you mind doing the honors and turning on the setting?

**Comment by robscott** [comment]
I don't think I have enough access, maybe @bowei does? If not, maybe there's some yaml we need to change somewhere

**Comment by hbagdi** [comment]
> maybe there's some yaml we need to change somewhere

😂

**Comment by bowei** [comment]
I will enable it

**Comment by shaneutt** [comment]
The discussion boards are open :+1:
