### ISSUE TITLE
GEP: Enable cross namespace references from Routes

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#709]
**What would you like to be added**:
This GEP attempts to tackle both cross namespace forwarding and route inclusion (proposed earlier by @stevesloka). These are closely related concepts that can likely be solved with the ReferencePolicy concept originally proposed by @youngnick.

**Why is this needed**:
Both cross namespace forwarding and route inclusion are common feature requests. ReferencePolicy provides a way to safely accomplish this. This is closely related to #411, #582, and #634. 

Relevant docs include:
- [Gateway API Reference Policy](https://docs.google.com/document/d/18MoabVA-fr5XL9cYdf6cxclqRwFpOvHUXV_UYzSiooY/edit)
- [Selection Policy Proposal](https://docs.google.com/document/d/1S9t4YiDBwe1X7q915zKO0meZ8O_UPa8bzBLWBY8_XdM/edit?usp=sharing)
- [Route Inclusion Proposal](https://docs.google.com/document/d/1-0mgRRAY784OgGQ1_LCOshpLLbeAtIr4eXd0YVYK4RY/edit#heading=h.8cfxzle5tmqb)
- [Cross Namespace Forwarding Proposal](https://docs.google.com/document/d/1_B1G9JcNw3skNYLtdK7lTTzOeyz5w2hpa84cKA_MGKk/edit)

Note: Although the Gateway -> Route relationship is closely related to this discussion, I've decided to tackle that in a later GEP.

**Comment by youngnick** [comment]
I'll take this one.

/assign
