### ISSUE TITLE
Document the supported Kubernetes versions

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#737]
**What would you like to be added**:

Gateway API documents the supported Kubernetes version.

**Why this is needed**:

Users and implementers can have the right expectations from Gateway API.

**Comment by robscott** [comment]
I think it's still generally true that we support Kubernetes 1.16+, but certain features like AppProtocol depend on Kubernetes 1.18 (opt-in) or 1.19 (on by default). I can't think of any other exceptions to the 1.16+ guideline right now.

**Comment by hbagdi** [comment]
Great. Let's get that into the site.
Is https://gateway-api.sigs.k8s.io/references/implementations/ a good place for this?

**Comment by jpeach** [comment]
> Great. Let's get that into the site.
> Is https://gateway-api.sigs.k8s.io/references/implementations/ a good place for this? (Not ideal but I couldn't find any better one)

A FAQ entry probably makes sense as well.

**Comment by ccfishk** [comment]
willing to take over this issue.
