### ISSUE TITLE
Clarify if psuedo-headers are supported within HTTP header matching

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#740]
**What happened**:

Pseudo-headers can be used to specify matches against non-header properties of HTTP requests: https://github.com/kubernetes-sigs/gateway-api/pull/733#discussion_r676935043

**What you expected to happen**:

The documentation of the API clarify if pseudo-headers are supported or not.

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Comment by hbagdi** [comment]
Another reason: Pseudo-headers are not very popular (at least I have not encountered them for matching purposes before) so mentioning them explicitly would be helpful to users and maintainers.

**Comment by jpeach** [comment]
Validation to reject pseudo headers was added in https://github.com/kubernetes-sigs/gateway-api/pull/772

**Comment by youngnick** [comment]
oof, that is a good point. That validation will also need to be fixed if we are going to allow pseudo-headers. In that PR, I was slightly in favor of not allowing them in favor of explicit config, but it's not a strong preference.

**Comment by hbagdi** [comment]
The guidance on this is now present:
https://github.com/kubernetes-sigs/gateway-api/blob/5ac109cf2d1c98006e2672e4484e352ec320a412/apis/v1alpha2/httproute_types.go#L270-L281

/close
