### ISSUE TITLE
Validation should require port when BackendRef refers to a Service

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#753]
**What would you like to be added**:
In `BackendObjectReference` we note that "Port is required when the referent is a Kubernetes Service". We should validate that with the webhook.

**Why this is needed**:
This is a clear example of where the webhook could improve UX.

**Comment by tao12345666333** [comment]
let me try.

/assign

**Comment by youngnick** [comment]
@robscott, I think this may not be required now we've changed how the service reference works?

**Comment by bowei** [comment]
It seems like it should still be relevant? 

https://github.com/kubernetes-sigs/gateway-api/blob/master/apis/v1alpha2/object_reference_types.go#L127

**Comment by robscott** [comment]
Changing how the Service reference works made this less ambiguous, but it would still be helpful to have webhook validation here to ensure port was always set when the BackendRef.Kind was "Service"

**Comment by shaneutt** [comment]
@tao12345666333 I've unassigned you as it's been about a year since we last heard from you on this. If you're still wanting to have a go at this, let us know.

**Comment by tao12345666333** [comment]
sorry for the delay. I forgot about this 😅

I haven't had time to work on it lately, I'll be happy to pick it up once I'm free and the issue is still open

**Comment by rushi47** [comment]
I will try to give a short on this one, I might need some help.

**Comment by shaneutt** [comment]
Sounds good @rushi47, reach out in here in this issue if you need some assistance :+1: 

/assign @rushi47

**Comment by rushi47** [comment]
Hello Team,
I got chance to review the code and I wanted to confirm my understanding (Apologies itself if my understanding is wrong as this is the first time, I am touching the code base)

Should we actually call Control plane API & validate`Service` object to confirm the port, when service is actually deployed and running in cluster ?

If not, I see port is kind of being validated here : https://github.com/kubernetes-sigs/gateway-api/blob/main/apis/v1beta1/validation/httproute.go#L92

Which is being called in Admission Server, in places like :
https://github.com/kubernetes-sigs/gateway-api/blob/main/pkg/admission/server.go#L173
https://github.com/kubernetes-sigs/gateway-api/blob/main/pkg/admission/server.go#L181

**Comment by robscott** [comment]
You're completely right @rushi47! Sorry for the confusion here. It looks like we fixed this but never closed out the issue. Thanks for the references to where this is already implemented!

**Comment by rushi47** [comment]
Np ! but that means i need to find new issue @robscott lol
