### ISSUE TITLE
Unclear the meaning of references of vendor configurations in GatewayTLSConfig

### ISSUE THREAD

**Issue by nak3** [kubernetes-sigs/gateway-api#759]
**What happened**:

The section `GatewayTLSConfig` in API spec doc lists the references for the vendor configurations of TLS as:

https://gateway-api.sigs.k8s.io/references/spec/#networking.x-k8s.io/v1alpha1.GatewayTLSConfig

![image](https://user-images.githubusercontent.com/2138339/128814670-b9943151-0c99-4f9a-b597-bb9c66f371c4.png)

But are these references useful for the configurations or implementations? Actually as an user, I was confused what I can refer to.

**What you expected to happen**:

I think the references could be removed.

**How to reproduce it (as minimally and precisely as possible)**:

Go to https://gateway-api.sigs.k8s.io/references/spec/#networking.x-k8s.io/v1alpha1.GatewayTLSConfigb

**Anything else we need to know?**:

One of the link (envoy) below is deprecated. __If__ the references are necessary, the link should be updated.

https://github.com/kubernetes-sigs/gateway-api/blob/fff8c09b010d4a3923f6061a8ef8b6e0f485303f/apis/v1alpha2/gateway_types.go#L304

**Comment by robscott** [comment]
Thanks for catching this! I agree these should be removed.

**Comment by nak3** [comment]
Thank you! I will send the PR then.
