### ISSUE TITLE
Stricter regex-based validation 

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#767]
**What would you like to be added**:

Add regex based validation in the API: https://github.com/kubernetes-sigs/gateway-api/pull/754#discussion_r687174710

**Why this is needed**:

Decreasing the surface area of the API further. We can relax (not a breaking change) these validations later on when need be.

**Comment by robscott** [comment]
Some helpful regex examples from upstream: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go
