### ISSUE TITLE
Document how and when to create custom route resources

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#776]
**What would you like to be added**:
One of the core extension mechanisms in Gateway API is the ability to create custom Route resources. It would be good to document how to do that.

**Why this is needed**:
This is an important way to extend the API.

**Comment by youngnick** [comment]
I think that supplying a skeleton Route object would be really useful, since it will include all the status bits, it could also be used as a ducktype later. I'll can take this one early next week, but understand we may want to get it in before then.
