### ISSUE TITLE
Clarify the meaning of ProtocolType in the Listener block

### ISSUE THREAD

**Issue by bowei** [kubernetes-sigs/gateway-api#784]
There is some amount of ambiguity for new users as to the full meaning of `ProtocolType` in the Listener block.

We should expand on what this represents as it may cause confusion for users expecting a strict layering model .

**Comment by youngnick** [comment]
I think that the suggestion (I think it was @jpeach 's?) we discussed on the issue is a good one - using `ListenerType` instead of `ProtocolType` would seem to remove some of this ambiguity,

**Comment by hbagdi** [comment]
Why not simply `type Protocol string` because all of those are protocols anyway?
I was a bit surprised that we don't even have a `Protocol` as a Go type in our API.

**Comment by youngnick** [comment]
That sounds good to me too.

**Comment by jpeach** [comment]
> Why not simply `type Protocol string` because all of those are protocols anyway?
> I was a bit surprised that we don't even have a `Protocol` as a Go type in our API.

```
apis/v1alpha2/gateway_types.go:type ProtocolType string
```

**Comment by youngnick** [comment]
I really think it's the use of the word `protocol` that's the problem here - it seems like some people have specific ideas about what constitutes a protocol. That's why I think that `ListenerType` is better - it dodges this issue entirely.

**Comment by hbagdi** [comment]
I think this is sufficiently resolved with the following Go doc from master:
https://github.com/kubernetes-sigs/gateway-api/blob/25607266669cc3616ed90404db4ff6e6d854a3b7/apis/v1alpha2/gateway_types.go#L234-L261

Please re-open if needed.
/close
