### ISSUE TITLE
Output from test failures is not as helpful as it could be

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#785]
**What happened**:
When tests fail, we currently just output the verify script that failed, not how or why it failed.

**What you expected to happen**:
To have some kind of information on the test failure so I don't have to recreate it locally.

**How to reproduce it (as minimally and precisely as possible)**:
Example here: https://github.com/kubernetes-sigs/gateway-api/pull/714#issuecomment-900515751

**Anything else we need to know?**:
We previously output everything from these verification scripts but unfortunately Prow was unable to highlight the actual failure message, so it was even harder to understand the problem. At least part of that was due to the noise of docs generation which is no longer an issue, but code generation and even verifying examples is still rather noisy. Ideally we'd find a way to reduce that noise while still providing meaningful output.

**Comment by shaneutt** [comment]
Is there any reason that introducing a full Golang test suite to the repository would be unacceptable as a solution to this?

**Comment by robscott** [comment]
>Is there any reason that introducing a full Golang test suite to the repository would be unacceptable as a solution to this?

That may be helpful. Most of our tests are pretty tied to shell scripts right now, things like `go lint`, codegen, and spinning up a kind cluster to install examples would all be relatively complicated to verify with Go unless we were just using `exec` to run the same commands as before and using Go to provide better output.

**Comment by shaneutt** [comment]
> > Is there any reason that introducing a full Golang test suite to the repository would be unacceptable as a solution to this?
> 
> That may be helpful. Most of our tests are pretty tied to shell scripts right now, things like `go lint`, codegen, and spinning up a kind cluster to install examples would all be relatively complicated to verify with Go unless we were just using `exec` to run the same commands as before and using Go to provide better output.

That sounds good to me and will probably lead to overall better testing and CI long term is my thought.

I'm interested in working on this if nobody else is, but given the `v1alpha2` release and the work I'm already doing on documentation for that I wont be starting on this _immediately_ so if anyone else wants to jump in go for it.

Otherwise, if nobody else picks this up once I have time for it again I'll update the thread here and start on it.
