### ISSUE TITLE
Support additional redirect status codes

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#793]
**What would you like to be added**:
Currently we only support 301 and 302 redirects. It would make sense to expand that to [all possible values](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#redirection_messages).

**Why this is needed**:
Although 301 and 302 are most common, there's no reason not to support the rest. This likely means we'll need to distinguish support levels per value (Core: 301,302, Extended: 303+)

**Comment by robscott** [comment]
This was suggested by @bowei in https://github.com/kubernetes-sigs/gateway-api/pull/772#discussion_r692452704.

**Comment by hbagdi** [comment]
> This likely means we'll need to distinguish support levels per value (Core: 301,302, Extended: 303+)

I think supporting conformance at such a granular level is pushing a lot of pain on to the user. We should avoid this at all costs.

**Comment by bowei** [comment]
Harry -- are you saying to not say anything or to mandate more conformance?

**Comment by hbagdi** [comment]
For something as granular as a field inside a filter, we should not have a conformance like "x value is core but y is extended". Users would be pulling their hair out debugging it.
Instead a specific field should either be core or not core. Somewhere in the middle feels really trappy.

I would go so far as saying that a filter is the smallest block on which we should have conformance, but we don't agree on that front so I will let it be.

**Comment by bowei** [comment]
I am inclined to agree -- especially until we get a good sense of how specific the conformance tests could possibly be.

**Comment by shaneutt** [comment]
While grooming we saw that this one was open for a long period of time without anyone with a strong use case to champion it. We're going to close this as we don't expect anyone's ready to drive it forward, but if you still want this feature and have a strong use case we will be happy to reconsider this and re-open.
