### ISSUE TITLE
docs bikeshed: put apiVersion before kind in yaml samples

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#810]
Example from our docs:
```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
```

Example output from `kubectl get`, as well as almost all kubernetes.io docs:
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
```

I think it would be preferable to use the more familiar format below, for consistency with kubernetes.io and kubectl. Since most people copy+paste everything from the docs, whatever we do will probably trickle throughout the k8s ecosystem

**Comment by bowei** [comment]
Send the PR -- I will approve.
