### ISSUE TITLE
Decide if kind should be renamed to resource

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#816]
**What would you like to be added**:

Rename kind to resource for object references as per API conventions: https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2336-OwnerReference-resource-field/README.md

**Why this is needed**:

Upstream API conventions recommend "resource" over "kind"

### Concerns

Some concerns were raise in the community meeting (not exhaustive):
- Do client-go or controller-runtime supported?
- This is a change of a large magnitude and nobody on the call really seems to be aware of these details.

**Comment by hbagdi** [comment]
@robscott I tried digging up the convention but couldn't find one.
This one seems to be outdated still: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources

**Comment by hbagdi** [comment]
xref https://github.com/kubernetes-sigs/gateway-api/issues/689

**Comment by robscott** [comment]
As referenced in #689, I think https://github.com/kubernetes/community/pull/5748#discussion_r626118844 is probably the best summary of the rationale for this change, will continue to follow up on this one.

**Comment by youngnick** [comment]
I think the biggest thing we, as a community will need to do, is do more education of what users will actually need to put in there. Usually it's lower-case, pluralised, instead of Initialcase, so we should probably put in some examples in the docs for the field.

**Comment by robscott** [comment]
Followed up on mailing lists: https://groups.google.com/g/kubernetes-sig-architecture/c/WhHTjTDzcQg

**Comment by robscott** [comment]
Working on update to API conventions: https://github.com/kubernetes/community/pull/5973

**Comment by youngnick** [comment]
Feels like we agreed that, as long as the API conventions update goes in, we will *not* be changing Kind to Resource. Other maintainers thoughts?

**Comment by robscott** [comment]
API conventions have been updated (https://github.com/kubernetes/community/pull/5748), I think the only remaining step is to document why we chose Kind over Resource and more importantly, what that means for implementations of this API.
