### ISSUE TITLE
Cleartext HTTP/2 (h2c) should be allowed on HTTP listeners

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/gateway-api#817]
>         // Accepts cleartext HTTP/1.1 sessions over TCP.    
>        HTTPProtocolType ProtocolType = "HTTP" 

Though this isn't couched in spec language (MUST, SHOULD, etc), this argues against allowing implementations to support HTTP/2 over cleartext. Implementations should be allowed to offer h2c when the "HTTP" protocol is specified.

**Comment by hbagdi** [comment]
@jpeach Can we close #204 then?

**Comment by hbagdi** [comment]
xref #687

**Comment by youngnick** [comment]
So, the action on this one is to make a PR to this godoc that clarifies that "HTTP" includes "h2c"? And should we allow "h2c" as an option there?

**Comment by howardjohn** [comment]
I think we may he interested in a single protocol that is h1 or H2 rather than a distinct h2c protocol. It's not a hard requirement, but in our case envoy can support both at once so there generally isn't much benefit to making the user chose one or the other

**Comment by youngnick** [comment]
Okay, so we just define that "HTTP" includes cleartext HTTP/2? That seems like a straightforward change.

**Comment by howardjohn** [comment]
I would be fine with that personally. I don't know if others have use cases to make it explicitly one or the other, or if other implementations can support both automatically though. https://github.com/kubernetes-sigs/gateway-api/issues/687 is pretty relevant as well but it only applies to HTTPS.

**Comment by hbagdi** [comment]
FWIW, Nginx doesn't support this (although that's an implementation-specific problem): https://trac.nginx.org/nginx/ticket/816

**Comment by youngnick** [comment]
As I said, very much not ideal, so I'm not sure how to proceed.

**Comment by robscott** [comment]
This is a tricky one. It seems like many implementations and users would appreciate the flexibility of a generic "HTTP" listener that could handle both HTTP/1.1 and h2c. Maybe what @jpeach said to start this issue is best - "implementations should be allowed to...". Going with that, maybe our spec should be updated to the following:

```
   // Accepts cleartext HTTP/1.1 sessions over TCP. Implementations MAY also
   // support HTTP/2 over cleartext.
   HTTPProtocolType ProtocolType = "HTTP" 
```
