### ISSUE TITLE
Create utils to make it easier to work with custom types

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#826]
**What would you like to be added**:
Helper funcs that help with type conversion, especially from and to pointers, for our custom types. Examples of these types include `Hostname`, `Namespace`, and `Group`.

**Why this is needed**:
To simplify CRD validation, we've created a lot of custom types. Unfortunately this makes it difficult to work with our APIs with go. It would be very helpful if we had some utils that made this easier to work with. Otherwise each implementation will likely end up implementing their own set of these.

**Comment by hbagdi** [comment]
Want to make sure I understand you right. Are you referring to something like?
```go
func NamespacePtr(ns string) *gwapi.Namespace
func Namespace(ns string) gwapi.Namespace
```

**Comment by skriss** [comment]
:+1:, see https://github.com/projectcontour/contour/blob/main/internal/gatewayapi/helpers.go for some examples of what we've needed for the Contour implementation. Would love to see these upstreamed.

**Comment by robscott** [comment]
That's a great set of helpers! I think I've seen similar helpers in at least the Istio code base, @howardjohn is there much overlap here? Agree that it would be great to move any broadly shared code into Gateway.

/remove-lifecycle stale

**Comment by youngnick** [comment]
/remove-lifecycle stale

ping @howardjohn, what do you think about upstreaming some helpers like the Contour ones above?

**Comment by youngnick** [comment]
/remove-lifecycle rotten
/lifecycle frozen

This is still a reasonably good first issue, as described in Rob's initial comment.

**Comment by shaneutt** [comment]
Hey @abhijit-dev82  just checking in, everything going good with this one? Is there anything we can do to support/help?

**Comment by abhijit-dev82** [comment]
HI @shaneutt I had dropped a message on slack to @robscott asking for some pointers .  Will cover the below list of custom types to start off with. Please let me know if I have missed out on any.

Hostname
Namespace
Kind
Group
SectionName
PortNumber 
PreciseHostname
ObjectName
GatewayController
