### ISSUE TITLE
Validation should prevent protocol specific config errors on Gateways

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#827]
**What would you like to be added**:
We should validate the following:

TLSConfig is empty when the protocol is HTTP, TCP, or UDP.
Hostname is empty when the protocol is TCP or UDP.

**Why this is needed**:
This would help provide a better UX.

**Comment by robscott** [comment]
Hey @sayantani11, we currently have Gateway validation defined here: https://github.com/kubernetes-sigs/gateway-api/blob/master/apis/v1alpha2/validation/gateway.go. For each Gateway listener, we need validation that prevents the fields described above from being set when the protocol does not allow it.

**Comment by bishtsaurabh5** [comment]
Hey I am also interested in picking this issue , @sayantani11 have you started working on this ?

**Comment by sayantani11** [comment]
@bishtsaurabh5 No. I haven't. You can work on it. All yours.

**Comment by bishtsaurabh5** [comment]
Thanks for the update @sayantani11
