### ISSUE TITLE
CI tests are failing

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/gateway-api#828]
**What happened**:

CI test are failing with this error:

```
`Error from server (Invalid): error when creating "config/crd/v1alpha2/gateway.networking.k8s.io_gatewayclasses.yaml": CustomResourceDefinition.apiextensions.k8s.io "gatewayclasses.gateway.networking.k8s.io" is invalid: metadata.annotations[api-approved.kubernetes.io]: Required value: protected groups must have approval annotation "api-approved.kubernetes.io", see https://github.com/kubernetes/enhancements/pull/1111
```

**What you expected to happen**:

Applying CRDs should succeed.

**How to reproduce it (as minimally and precisely as possible)**:

Run CI for any PR.

**Anything else we need to know?**:

https://github.com/kubernetes/enhancements/pull/1111

**Comment by robscott** [comment]
This was a dumb hack by me to workaround this (https://github.com/kubernetes-sigs/gateway-api/blob/master/hack/update-codegen.sh#L63), and the precise version is probably causing the issue with #824 since it bumps the version of that tool.

**Comment by robscott** [comment]
It looks like #830 fixed this, feel free to reopen if I missed anything.

/close
