### ISSUE TITLE
docs suggestion: add perma-links to headers in API reference

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#835]
We can link to specific sections of the API. For example, https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRequestMirrorFilter.

However, there is no way to click no the header and generate a link. Many docs have a little anchor icon there to get it, or make the text itself a link 
![2021-27-08_12-09-46](https://user-images.githubusercontent.com/623453/131177253-c891cfc9-b3be-415f-b4b1-ee509c798ef7.png)

It would be great to have similar

**Comment by jpeach** [comment]
I've done this with [anchorjs](https://www.bryanbraun.com/anchorjs/) previously. It works pretty well.

**Comment by shaneutt** [comment]
While grooming we saw that this one was open for a long period of time without anyone with a strong use case to champion it. We're going to close this as we don't expect anyone's ready to drive it forward, but if you still want this feature and have a strong use case we will be happy to reconsider this and re-open.

**Comment by robscott** [comment]
Actually I think we completed this one and just never closed it, either way, thanks for closing this one out.

**Comment by shaneutt** [comment]
:+1:

**Comment by mikemorris** [comment]
This was completed in https://github.com/kubernetes-sigs/gateway-api/pull/1046
