### ISSUE TITLE
Invalid parent references are challenging to implement status for 

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#836]
```
spec:
  parentRefs:
  - kind: Gaway
    name: foo
```

Lets say I have a route like ^. I made a typo on the kind. In this case, the route will be totally ineffective (assuming no controller implements a `Gaway` type). However, there is no way to actually report this to a user. No controller can write "Unknown kind Gaway" or equivalent, since they don't know if its truely unknown, or just not known to _them_, but is known to another controller.

The same also applies to `name`/`namespace` not matching.

Essentially, we need a valid parentRef in order to report status on a parent, which makes it impossible to report invalid parentRefs.

One option that could work is to suggest that controllers report invalid parentRefs IFF there is not already another controller that wrote the status for that parent. This means for an invalid ref, the first controller will "win" and report an error. If that reference becomes valid later (say another controller understands it) it will overwrite it with a valid status; the old "winner" will now stop reporting any errors.

**Comment by robscott** [comment]
In #839 I added a note to Route status describing this limitation.

**Comment by jpeach** [comment]
I expect that the specific case of an invalid kind could be caught by the admission validation. I don't think that we can require the referent object to actually exist at this time though maybe the validation can resolve the reference and set an initial status condition.

**Comment by howardjohn** [comment]
Can a mutating webhook actually set status?

> We have the same problem if a Gateway specifies an invalid/missing GatewayClass

The same solution could actually apply, that controllers should set the "unknown GatewayClass" IFF no other controller has set it. That way a controller will never turn a positive condition to a negative, but can turn negative to positive (and thus "take ownership" of the field)

**Comment by youngnick** [comment]
Yeah, I think it should be every controller's responsibility to set the status to "looks like there's a really bad problem" unless they see something else has done that previously.

So yes, a race, but a race that should solve itself quickly.

**Comment by jpeach** [comment]
> Can a mutating webhook actually set status?
> 
> > We have the same problem if a Gateway specifies an invalid/missing GatewayClass

We default the gateway status so it's clear that is is not getting reconciled.
