### ISSUE TITLE
Plan for updating to EasyCLA?

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/gateway-api#846]
**What would you like to be added**:

Update the CLA signing tooling to use the new workflow described at https://docs.linuxfoundation.org/lfx/easycla/contributors

**Why this is needed**:

The existing workflow uses https://identity.linuxfoundation.org/, which indicates it is being migrated to a new platform.
(Links to the older workflow below for reference.)
- https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement
- https://identity.linuxfoundation.org/projects/cncf

**Comment by mrbobbytables** [comment]
We'll be rolling it out at an org level hopefully soonish 👍 
Theres nothing for you to do. :)

**Comment by robscott** [comment]
Thanks for letting us know @mrbobbytables! I'm going to go ahead and close this since it seems out of our control + is on the way to being updated.

/close
