### ISSUE TITLE
Add Hostnames to Status for HTTP and TLS Routes

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#848]
**What would you like to be added**:
A new `hostnames` field in `RouteParentStatus` that could be used to indicate which hostnames a Route was attached with.

**Why this is needed**:
This could be useful if a Route was attached to different Gateways for different hostnames. For example, it could be attached to Gateway `foo` for `foo.com` and Gateway `bar` for `bar.com`. This would happen if the Route specified both hostnames but each Gateway only specified one of the hostnames. 

For reference: This idea was came from a [comment thread](https://github.com/kubernetes-sigs/gateway-api/pull/839#discussion_r700722952) with @youngnick

**Comment by youngnick** [comment]
Given I suggested it, I can hardly avoid a +1 here. 😄 

It does seem like it would nice to have a way to know what hostnames a Route is exposed on, particularly once we add multiple TLS details, Listener hostnames, and Route hostnames.

**Comment by tokers** [comment]
Is this issue already in-progress? If not, I'd like to do this :).

**Comment by robscott** [comment]
@tokers thanks for volunteering to take this one on! I don't think anyone's working on this one. This feels a bit borderline, but it may benefit from a tiny GEP before adding it to the API.

**Comment by tokers** [comment]
> @tokers thanks for volunteering to take this one on! I don't think anyone's working on this one. This feels a bit borderline, but it may benefit from a tiny GEP before adding it to the API. 

Sure, I'll think about the GEP firstly.

**Comment by nak3** [comment]
Any news for this? I'm looking forward ti this feature :smile:

**Comment by robscott** [comment]
@tokers are you working on a GEP for this? If not, we can add a "help wanted" label to the issue.

**Comment by tokers** [comment]
> @tokers are you still able to work on a GEP for this? If not, we can add a "help wanted" label to the issue.

I'm so sorry for the delay, I focus on other business things these days, I'm afraid the status will continue for some time, so you can help me to re-assign this issue to other friends.
