### ISSUE TITLE
Consider renaming "AllowedRoutes" to "RouteConstraints"

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#862]
**What would you like to be added**:
Rename `listener.allowedRoutes` to `listener.routeConstraints`

**Why this is needed**:
One of the bits of feedback we got from the sig-network review is that `listener.routes` no longer seemed like an appropriate field name. I suggested renaming to `allowedRoutes` and the PR that contained that change merged recently. After chatting with @mark-church and reading the updates he and @shaneutt made to our cross-namespace routing guide, I think `routeConstraints` is a better name for this field.

**Comment by youngnick** [comment]
I think this name does describe what it does more accurately, and is much clearer. Strong + 1 from me.

**Comment by hbagdi** [comment]
`routeConstraints` is an improvement so +1.

**Comment by howardjohn** [comment]
Not to bikeshed here but "constraints" is a more complex word than "allow".
Given this will be a very very common field, it may be nice to pick
something simpler.

**Comment by robscott** [comment]
We discussed this at the community meeting yesterday and there was some hesitation + no one felt strongly enough to push for this change, going to close this out.

/close
