### ISSUE TITLE
Webhook and CRD validation overlaps

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#868]
**What happened**:
Hostname string validation was enforced by both the webhook and CRD.

**What you expected to happen**:
Validation to only be implemented in one place, _probably_ just the CRD. It is much nicer to be able to reuse upstream validation functions in the webhook, but CRD validation is likely going to be more universally deployed. I'm interested in what others think here.

**Comment by howardjohn** [comment]
Big +1 to doing it in the CRD > doing it in the wehook. You get IDE support, avoid roundtrip to webhook, better errors, etc

**Comment by youngnick** [comment]
Big +1 from me too that CRD validation is preferred to webhook, and we should only have one.

In either case, the validation is an important part of the API, and we will need to be careful about changing it.

**Comment by we4tech** [comment]
Hi @robscott, 
I am taking this as my first assignment. Please correct me if I grasped the idea. 

#### Current state:
- We are validating the `hostname` by the CRD schema. Here is the [reference](https://github.com/kubernetes-sigs/gateway-api/blob/c5c4e077e0c6a85bff5a6c049ceaf0ca03a2e8a2/config/crd/v1alpha2/gateway.networking.k8s.io_gateways.yaml#L286).
- Also, validating from the Webhook [here](https://github.com/kubernetes-sigs/gateway-api/blob/c5c4e077e0c6a85bff5a6c049ceaf0ca03a2e8a2/apis/v1alpha1/validation/validation.go#L63)

#### Desire change

- Remove the validation pattern from the CRD
- Leave as it is at the Webhook

Thanks

**Comment by we4tech** [comment]
Just noticed you already have a PR :)

**Comment by youngnick** [comment]
Ah, @we4tech, I think this request is the other way around. We should have only the CRD validation, and not check in the webhook as well.

**Comment by we4tech** [comment]
Thanks, @youngnick for the clarification.
