### ISSUE TITLE
Clarify what common elements must exists for all Route objects

### ISSUE THREAD

**Issue by youngnick** [kubernetes-sigs/gateway-api#874]
In #861, @thockin raised a great question:
> Is it fair to say that every type of Route must have a field which is a list of ParentRef? E.g. can I assert that, for any given route, I can use reflect to find that? If so, let's say that. If not, ... ?

This issue covers the work to clarify what common elements all Route objects must have.

**Comment by youngnick** [comment]
My personal opinion is that we should supply a skeleton Route object that contains the minimum fields for both Spec and Status that all Routes must have. That can then serve as the basis for other people's custom Routes, and also provides a basis for some sort of duck-typing of Routes, if we ever need it.

**Comment by robscott** [comment]
> My personal opinion is that we should supply a skeleton Route object that contains the minimum fields for both Spec and Status that all Routes must have.

Agreed, maybe we can copy what we did for policy attachment?
https://gateway-api.sigs.k8s.io/v1alpha2/references/policy-attachment/#policy-boilerplate

**Comment by hbagdi** [comment]
Don't we do this already with the following?

https://github.com/kubernetes-sigs/gateway-api/blob/1a2aceb6cd131e17cf1142311639ed7615beb9b5/apis/v1alpha2/shared_types.go#L101

https://github.com/kubernetes-sigs/gateway-api/blob/1a2aceb6cd131e17cf1142311639ed7615beb9b5/apis/v1alpha2/shared_types.go#L225

**Comment by robscott** [comment]
Good point, maybe all we need right now is a "MUST" instead of should for those. I think a full docs page covering how custom Routes can be built + some boilerplate would also be helpful, but isn't strictly required to address Tim's feedback here.
