### ISSUE TITLE
Incorrect url present in validation package

### ISSUE THREAD

**Issue by bishtsaurabh5** [kubernetes-sigs/gateway-api#884]
**What would you like to be added**:
There are bunch of incorrect urls pointing to 404 page
Following is the list alongwith the file in which the respective urls are present
httproute.go -->https://gateway-api.sigs.k8s.io/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRoute
gatewayclass.go --> https://gateway-api.sigs.k8s.io/spec/#gateway.networking.k8s.io/v1alpha2.GatewayClass
gateway.go --> https://gateway-api.sigs.k8s.io/spec/#gateway.networking.k8s.io/v1alpha2.Gateway

**Why this is needed**:
This will point the users reading docs to correct urls.
The urls should ideally point to the api specification

**Comment by bowei** [comment]
Can you add which URLs are incorrect.

**Comment by bishtsaurabh5** [comment]
@bowei urls updated in the description
