### ISSUE TITLE
Publish webhook docker image to k8s production container registry

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#916]
**What would you like to be added**:

- Publish a production image of 0.4.0 tag for admission-server 
- Document the steps necessary so that future maintainers doing a release can do this
- 
**Why this is needed**:

We should have users relying on the production image rather than the staging ones.

Additional context:
- https://console.cloud.google.com/gcr/images/k8s-staging-gateway-api/global/admission-server

**Comment by robscott** [comment]
Update: We are working on this. @youngnick updated the build script and we released v0.4.2 to test it out, unfortunately not quite working yet: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-gateway-api-push-images/1503442368546738176

/lifecycle frozen

**Comment by youngnick** [comment]
Okay, with #1043 and #1044 merged, we've validated that we've got images correctly labelled and in the staging GCR. Now to figure out how to get it to prod.

**Comment by youngnick** [comment]
The folks at ingress-nginx have really great RELEASE docs that include how they handle promoting images: https://github.com/kubernetes/ingress-nginx/blob/main/RELEASE.md#3-promote-the-images

In short:
- we PR to [kubernetes/k8s.io](https://github.com/kubernetes/k8s.io), adding the SHA of the image we sent to staging to a YAML file.
- Once that PR is merged, that tag (and only that tag) will be promoted.

This means that once we do this, our *release* YAMLs will be able to use `k8s.gcr.io/gateway-api/controller:<semver>`.

I think we should keep our `master` YAMLs using the staging repo and `:latest`, maybe?

**Comment by hbagdi** [comment]
> I think we should keep our master YAMLs using the staging repo and :latest, maybe?

That sounds good as long as we make sure to have YAML in the release tag pointing to the production image. I expect implemeneters to point to the repo with a release tag to do installation. That is what we do in our docs as well: https://gateway-api.sigs.k8s.io/v1alpha2/guides/getting-started/#installing-gateway-api-crds-manually

**Comment by shaneutt** [comment]
@youngnick where did we leave off with this one?

**Comment by youngnick** [comment]
It's still TODO, but I think that following what the ingress-nginx folks do seems like the way to go to me.

**Comment by gauravkghildiyal** [comment]
I've taken a shot at this. Would like to direct attention to PR https://github.com/kubernetes/k8s.io/pull/5030 as that is outside this repo and might get missed
