### ISSUE TITLE
About protocol conversion rules

### ISSUE THREAD

**Issue by Patrick0308** [kubernetes-sigs/gateway-api#919]
**What would you like to be added**:
I want to discuss protocol conversion at here. It is very common on many gateways. For example gloo edge has [a grpc-to-rest feature](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/grpc_to_rest/). Although now we can add a custom backend which specify grpc service and method. However, we can not customize the conversion rules on a specific HttpRoute such as mapping a rest's path parameter to a protobuf's body field.

**Why this is needed**:

**Comment by youngnick** [comment]
/remove-lifecycle rotten

Once we decide what we do with #1004, we will have a place to start from to discuss REST-to-gRPC translation.

**Comment by shaneutt** [comment]
Despite this issue being quite old, we the maintainers are still pretty convinced that we want to have this functionality in a future release. We are marking this `help wanted` as we're looking for contributors with strong use cases to help champion and drive this forward.

**Comment by keithmattix** [comment]
I wonder if protocol conversion is part of the scope of https://github.com/kubernetes-sigs/gateway-api/pull/1333

**Comment by youngnick** [comment]
I think there's definitely some bits of #1333 and GEP-1282s that affect it, yeah. Let's make a note to come back and check this once we're done with GEP-1282?

**Comment by shaneutt** [comment]
@youngnick with #1333 merged, it seems we just need to capture the desire here in that GEP in an upcoming iteration to consider this resolve, yes?

**Comment by youngnick** [comment]
Actually, #1333 and #1282 are actually basically "Declined" as they are now - I'll make a note to update the GEP accordingly. (That's the BackendProperties GEP for those of you playing at home).

I think that we'll need to handle this is some other way, so sadly this one will need to stick around.

**Comment by shaneutt** [comment]
> I think that we'll need to handle this is some other way, so sadly this one will need to stick around.

What's the impetus for handling this right now? Given the age and the lack of someone to champion and move it forward wouldn't it be better to consider this one closed (keeping in mind that closed does not mean we will never work on it, just that we have absolutely _no_ priority for it at the time)?

**Comment by youngnick** [comment]
Yeah, okay, that's a good way to put it. Anyone who finds this issue, this close is "noone is able to work on this right now, and we don't see when we'll get to it", so if you would like this, please comment and we'll reopen.
