### ISSUE TITLE
GRPCRoute for routing based on gRPC metadata

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#921]
**What would you like to be added**:

Ability to route based on gRPC request metadata using a dedicated route. gRPC request metadata could include things like service name and rpc name to begin with.
Advanced introspection of the request/response body would be out of scope for a core/extended API.

**Why this is needed**:

Users use HTTP/2 proxy capabilities to route gRPC from outside the network to the service. A native gRPC routing mechanism helps with observability, authn/z, routing, traffic splitting, etc.

**Comment by hbagdi** [comment]
There was no issue tracking this so I created one to gauge interest from the community.

**Comment by jpeach** [comment]
xref #920

**Comment by howardjohn** [comment]
One thing I would like to see for this is a side-by-side of using a (theoretical) gRPC Route vs HTTP Route (since grpc is http/2, after all, httproute should be useable - just perhaps not ergonomic).

**Comment by shaneutt** [comment]
While grooming we saw that this one was open for a long period of time without anyone with a strong use case to champion it. We're going to close this as we don't expect anyone's ready to drive it forward, but if you still want this feature and have a strong use case we will be happy to reconsider this and re-open.
