### ISSUE TITLE
Develop validation package that can be imported by implementations

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#926]
**What would you like to be added**:
A validation package that can be used to identify unexpected and/or unsafe values in Gateway API resources.

**Why this is needed**:
This is a follow up from https://github.com/kubernetes-sigs/gateway-api/pull/923#discussion_r744031322 where we noted that any validation provided with CRDs can be bypassed. Our best/only way to avoid that bypass possibility is for implementations to run a set of validation locally before processing a Gateway API resource.

**Notes:**
If/when this is accomplished, we'll need to update GEP 922 to recommend or require that implementations use this package. (More context in https://github.com/kubernetes-sigs/gateway-api/pull/923#discussion_r747063534).

**Comment by hbagdi** [comment]
x-ref #346

**Comment by youngnick** [comment]
In #346, @howardjohn showed how we can import the apiserver validation code and use it in-controller. That means that this may actually be much easier to solve than we, (well, I) thought. The question then becomes if we make a wrapper `Validate()` function or similar that will do the validation in a standard way, that we will then require projects to run. I _suspect_ that if we do that, and include it in the release bundle, then it may help to ensure that implementations can handle CRD schema version skew better.

**Comment by shaneutt** [comment]
While grooming we saw that this one was open for a long period of time without anyone with a strong use case to champion it. We're going to close this as we don't expect anyone's ready to drive it forward, but if you still want this feature and have a strong use case we will be happy to reconsider this and re-open.
