### ISSUE TITLE
Document HTTPRoute Filter Compatibility

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#928]
With GEP #726, we're introducing a filter that is incompatible with another existing one (Rewrite vs Redirect). This will likely not be the only time this happens. It would be helpful to add clear documentation about what filters we expect to be compatible with each other. At this point, it may be fair to say something like the following:

> All filters are expected to be compatible with each other except for the URLRewrite and RequestRedirect filters which may not be combined. If an implementation can not support other combinations of filters, they must clearly document that limitation. In all cases where incompatible or unsupported filters are specified, implementations MUST add a warning condition to status.

I believe @jpeach is already working on a standard status condition for that last point.

**Comment by hbagdi** [comment]
Will documenting this after v1beta1 be considered a breaking change?
