### ISSUE TITLE
`make uninstall` and `hack/delete-crds.sh` is outdated

### ISSUE THREAD

**Issue by nak3** [kubernetes-sigs/gateway-api#930]
**What happened**:

`hack/delete-crds.sh` still uses `networking.x-k8s.io` instead of `gateway.networking.k8s.io`.

https://github.com/kubernetes-sigs/gateway-api/blob/32db2da1647e3a78afd8f5a00ee0c41bd240b6ce/hack/delete-crds.sh#L23

And in my opinion, this script and `make uninstall` should be removed instead of update. It deletes resources so it is dangerous if somebody accidentally runs `make uninstall` against their production cluster.

**What you expected to happen**:

`make uninstall` and `hack/delete-crds.sh` should be removed from this repo.

**Comment by hbagdi** [comment]
make driven workflows here are intended for development so I don't share the concern for production.
PR to switch this to v1alpa2 would be welcome.

**Comment by nak3** [comment]
Okay, I see. I sent the PR https://github.com/kubernetes-sigs/gateway-api/pull/936 to switch it to v1alpha2.
