### ISSUE TITLE
GEP: Route Port Matching

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#957]
**What would you like to be added**: support for port matching in routes

**Why this is needed**:

_Mesh_ (primary use case): for mesh, we are using a parentRef of `Mesh`, instead of Gateway. As such, there is no port matching available, since we do not get ports in the Gateway.listener like we do with Gateway cases. Matching on ports is quite common in mesh; for example, if I am defining some policy for google.com, I know I only need this for port 80 since google isn't serve on 8080.
_Ingress_ (secondary use case): This is similar to hostname attachment in many ways. Rather than requiring a bunch of `sectionNames`, I want to attach to multiple sections at once by filtering by port instead of explicit listener reference

Prior art: https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest has a port field

Design ideas:
- Add it to `TrafficMatches` from https://github.com/kubernetes-sigs/gateway-api/pull/932. This only applies to TCP/UDP route though; we would need this in HTTP and TLS as well
- Use `sectionName` (ie `sectionName: "80"`). This would work but is a bit odd since port is a string here. Would only apply to mesh
- Add a new `port` field to parentRef. For Gateway, this would act as an additional filter on listeners bound. For mesh, this would scope to that port.

**Comment by robscott** [comment]
Leaving this open until this GEP either graduates to standard or is removed from the API.

/kind gep
/reopen
