### ISSUE TITLE
AddressType with domain-prefixed strings for "NamedAddress"

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#958]
**What would you like to be added**:

While working on [GEP 735](https://github.com/kubernetes-sigs/gateway-api/blob/master/site-src/geps/gep-735.md) the `AddressType` type was used to describe the type of an address used when matching ingress traffic for `TCPRoute` and `UDPRoute` objects. This type was historically used in the `Gateway` resource and the `NamedAddress` option for this type has been brought up in community syncs previously as being somewhat confusing and possibly something we would want to remove before `v1beta1`. At the same time `NamedAddress` also has a lot of versatility and is in-use in multiple implementations.

In the first iteration of GEP 735 @youngnick [suggested](https://github.com/kubernetes-sigs/gateway-api/pull/932/files#r750893985) that we could provide some obvious constants (like `IPAddress` or `Host`) but for things like `NamedAddress` where each implementation might do something slightly (or largely) different with the value we could avoid having specific constants for that and accept a domain-prefixed string instead, e.g.:

```
implementation.io/NamedAddress
```

The open-ended domain-prefixed type can then be `ImplementationSpecific`.

**Why this is needed**:

- avoids version compatibility problems
- enables better definition of our support policy for `AddressType` constants
- this allows us to move forward into `v1beta1` without being bound to an explicit `NamedAddress` type which has been historically contentious

**Comment by hbagdi** [comment]
This could also be something like a universal resource name, for example: https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html.

+1 to this, requires a small GEP.

**Comment by youngnick** [comment]
/remove-lifecycle stale

This is definitely still implementable, but as @hbagdi said, will require a small GEP.

/label good-first-issue

since writing a small GEP like this is a great way to get started with the Gateway API.

**Comment by mehabhalodiya** [comment]
Still not 100% clear about what needs to be done but then too I would like to work on this.
I will ask and learn what changes are required for this particular.
/assign

**Comment by youngnick** [comment]
Deliverables here are:
- [ ] Move AddressType from an Enum to a pattern validation, and provide constants for all Core and Extended support values.
- [ ] Update AddressType documentation to make clear that domain-prefixed strings are allowed
- [ ] Update AddressType validation to allow both bareword `CamelCase` values and `domain.io/DomainPrefixed` values are allowed.

**Comment by youngnick** [comment]
This is blocking the release of v0.5.0, so I'm going to knock it out. Sorry @mehabhalodiya.

**Comment by youngnick** [comment]
PR is open, please check it out everyone.
