### ISSUE TITLE
Add validation on HTTPPathMatch.Value

### ISSUE THREAD

**Issue by stevesloka** [kubernetes-sigs/gateway-api#960]
**What happened**:

Would be good to have some kubebuilder validation on the HTTPPathMatch.Value that verifies it starts with a `/`. In Contour, we've handled this internally (https://github.com/projectcontour/contour/pull/4209), but had to set a new condition type and could be caught automatically with the validation. 

// ref: https://github.com/kubernetes-sigs/gateway-api/blob/d734fa140c6b0bef92433d1893cf2d910bb3d9b0/apis/v1alpha2/httproute_types.go#L266

**Comment by hbagdi** [comment]
+1 to having a regex match that at least ensures that the field beings with a `/` - something as basic as that sometimes catches the user's attention in really beneficial ways.
Are there any places where the leading slash wouldn't be present?

If we are at this, we should also consider a `type Path string` in the Go package and then reference that type whenever the input value is a path. Currently, this is a string in a lot of places.

cc @robscott

**Comment by robscott** [comment]
I think the reason we avoided kubebuilder validation here is that we support different path types that may support a different subset of characters and may not necessarily start with `/` (RegEx). I think this would be appropriate validation to add to webhook validation for exact and prefix match types though.

/area webhook

**Comment by howardjohn** [comment]
FWIW CONNECT will not have a /. Not sure if we claim to support that though

**Comment by robscott** [comment]
Good call, we do have that as a type definition, presumably that would either go along with no path match or an exact one though.

https://github.com/kubernetes-sigs/gateway-api/blob/master/apis/v1alpha2/httproute_types.go#L405

**Comment by youngnick** [comment]
/remove-lifecycle stale

Seems like the action here is to add validation for exact and prefix match types in the webhook?

**Comment by robscott** [comment]
@stevesloka I think this may have already been solved by our webhook validation: 

https://github.com/kubernetes-sigs/gateway-api/blob/74099119128328127ecd625816256779daa53c44/apis/v1alpha2/validation/httproute.go#L128)

I'm going to close this one out for now, but feel free to reopen and/or let me know if I missed anything.
