### ISSUE TITLE
Docs mentions Reencrypt for HTTPRoute and TLSRoute is available

### ISSUE THREAD

**Issue by nak3** [kubernetes-sigs/gateway-api#968]
**What happened**:

[Route summary table](https://gateway-api.sigs.k8s.io/concepts/api-overview/?h=reencrypt#route-summary-table) explains as HTTPRoute and TLSRoute as:

HTTPRoute
> Terminated only, can be reencrypted

TLSRoute
> Passthrough or terminated, can be reencrypted if terminated.	

https://github.com/kubernetes-sigs/gateway-api/blob/1deb7bc86193f670c149acf35426dd1ceaf588a5/site-src/concepts/api-overview.md?plain=1#L115-L116

![image](https://user-images.githubusercontent.com/2138339/146707937-fa460c36-965d-4259-9bf7-98418c1513e0.png)

But `reencrypt` is not available yet from my understanding. The docs should not mention about reencrypted? Or I am wrong and reencrypted is actually possible?

**What you expected to happen**:

`reencrypted` is not available yet from my understanding. The docs should not mention about reencrypted. (Again, I'm sorry if I misunderstand it.)

**How to reproduce it (as minimally and precisely as possible)**:

If Reencrypt is possible, how to configure it :sweat_smile: 

**Anything else we need to know?**:

TLSRoute with terminated is also still under discussion as https://github.com/kubernetes-sigs/gateway-api/pull/730

**Comment by howardjohn** [comment]
I agree its confusing but it is possible. The API doesn't provide a way to do it directly, but extensions may, so it does make sense the spec would describe how extensions should behave. Definitely could be more clear in the docs though

**Comment by hbagdi** [comment]
Whoops. My memory is a bit fuzzy around this and I can't seem to recall that we ever added this.
This is a pretty big omission IMHO and this needs to be fixed at a pretty high priority.

We should also ship v1beta1 only after we have a concrete plan for this feature since I think a lot of users may not use Gateway API without a way to TLS between gateway and upstream service. Critiques welcome.

Proposals are welcome. I've none over the top of my head right now.

**Comment by youngnick** [comment]
@robscott Harry has called out that this should block `v1beta1`, which seems reasonable to me. What do you think?

**Comment by bowei** [comment]
If I understand this, "reencrypt" as a specific feature is somewhat confusing as it's not something specific to termination, or the backend, but basically a result of the fact that we can communicate with backends using TLS. It is technically "encrypted again", but there is no relationship between the decryption in the frontend and the use of encryption in the backend, e.g. they can use different certs, chain-of-trust, ciphers, etc.

**Comment by robscott** [comment]
@youngnick @hbagdi My personal preference would be to not block beta on this issue. I've been trying to get together a rough set of characteristics for an issue that should block beta, and so far I think it's fair to say that we should consider something blocking if any of the following are true:

* Would require a breaking API change (new required field, rename, tightening validation, etc).
* Would be quite challenging to add later, even if it would not be a breaking change.
* The lack of this would make the API unusable for a large portion of users.

I personally don't think this qualifies, but want to get others perspective here. I am interested in a GEP for this, but I don't think it needs to block v1beta1.

**Comment by youngnick** [comment]
I'm fine with leaving it out of v1beta1, since as you say it's a compatible change, but we probably should update the reference to say that support for encrypted upstreams/backends is still pending.

**Comment by costinm** [comment]
The main issue for encrypted upstreams is how to verify the SAN, which is particularly complex if spiffee is used. 
Just to use TLS or not on the gateway->backend connection shouldn't require explicit config - an implementation that supports this can use labels or other info about the backend, or have its own extension or settings.

We probably should have some common way to indicate that a Pod accepts TLS connections - and what SAN/root is used, but not sure this is something to put in HttpRoute.

**Comment by robscott** [comment]
We discussed this issue at today's community meeting. I think there's broad interest in building a standardized way to configure this for implementations that can support this functionality. It's not clear exactly what that will look like yet. It will likely be an "extended" feature of the API, and may be included within an existing Gateway API resource or as part of a new policy that uses our policy attachment model. Although there's significant interest in this, we also agreed that this did not need to block a beta release as it would be an entirely optional addition to the API.
