### ISSUE TITLE
Add predefined reasons to use with RouteConditionType

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/gateway-api#972]
Back in v1alpha1, there was a `RouteConditionReason` type, but that was lost in the review process when we transitioned to v1alpha2. 

In v1alpha2, we have 

```Go
RouteConditionType string
ConditionRouteAccepted RouteConditionType = "Accepted"
ConditionRouteResolvedRefs RouteConditionType = "ResolvedRefs"
```

We ought to at least predefine a `RouteConditionReason` type with values to express "the route was accepted" and "the route's references were successfully resolved".  Failure reasons are probably useful as well, but would benefit from implementation experience. Various `HTTPRoute` reference fields document that a `"RefNotPermitted"` reason should be used with `ConditionRouteResolvedRefs`.

**Comment by robscott** [comment]
Very interesting, not sure how we lost the `RouteConditionReason` type here. It looks like we just had 2 possible reasons: https://github.com/kubernetes-sigs/gateway-api/blob/release-0.4/apis/v1alpha1/shared_types.go#L169-L187. I agree that it would make sense to add some possible reasons here for each possible condition type.

**Comment by jpeach** [comment]
Another reason for a false "Accepted" condition is where the parent ref is known but dangling (e.g. no matching section name).
