### ISSUE TITLE
Specify load-balancing behavior for each service that is being proxied

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#98]
**What would you like to be added**:

For any service that is exposed via service-apis, a service owner should be able to specify the load-balancing behavior that should be used. This can include a common set of algorithms like round-robin, weighted, hash based routing, cookie/session based routing.

**Why is this needed**:

Most services in Kubernetes are designed to scale horizontally. A lot of legacy services that are ported to run on Kubernetes have the requirement of stick sessions. Most proxies and load balancers support load-balancing as well and this is a widely adopted feature in most of current ingress implementations.

**Comment by hbagdi** [comment]
There is certainly an overlap with kube-proxy and the `corev1.Service` resource here.

**Comment by bowei** [comment]
Yes, this API would give us an opportunity to add better load balancing knobs without adding more to the `core.Service` bucket

**Comment by hbagdi** [comment]
@robscott Seems like there is already an issue open for load-balancing.

**Comment by hbagdi** [comment]
In search for a solution, we were unsuccessful in coming up with a portable way to support this feature.
As a compromise, we came up with an easy and portable way to support such implementation-specific features in a consistent manner. The solution is documented in #713.

If there are more portable ways to tackle this, we would love to hear about them.

For now, I'll close this issue.
/close
