### ISSUE TITLE
Clearly document that listener SectionName field values must be unique within a Gateway

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/gateway-api#984]
**What would you like to be added**:

The spec should say whether the listener SectionName field values need to be unique within a Gateway. If so, the validation package should enforce it.

**Why this is needed**:

The listener status includes the SectionName field, so it's a reasonable implication that you should be able to match this up to the SectionName field in the Gateway spec. If SectionName values are not unique, then the matching is ambiguous.

**Comment by howardjohn** [comment]
:+1: to making them unique, matches service name which I think is a good property

**Comment by jpeach** [comment]
In GatewaySpec:
https://github.com/kubernetes-sigs/gateway-api/blob/4e3cc7a10e078aefde46d8a775618e0d73089d19/apis/v1alpha2/gateway_types.go#L110-L114

In GatewayStatus:
https://github.com/kubernetes-sigs/gateway-api/blob/4e3cc7a10e078aefde46d8a775618e0d73089d19/apis/v1alpha2/gateway_types.go#L531-L535

So, SectionName uniqueness is required and enforced, it's just not obvious from reading the docs :)
