### ISSUE TITLE
Route references to unknown types need to be followed before checking GatewayClass ownership

### ISSUE THREAD

**Issue by jpeach** [kubernetes-sigs/gateway-api#988]
**What happened**:

If a controller observes a change in a route, it needs to follow the parent refs to see whether it attaches to a gateway class that the controller is implementing. If a user specifies a (valid) parent group and kind that the controller doesn't implement, it can't follow the reference to know whether it was supposed to configure the route or not.

ParentRef says:
```
// References to objects with invalid Group and Kind are not valid, and must
// be rejected by the implementation, with appropriate Conditions set
// on the containing object.
```

**What you expected to happen**:

If the route parent is a reference to a type the controller doesn't understand (e.g. "Mesh"), the controller should be able to know that it should not update the route status.

**Comment by jpeach** [comment]
cc @michaelbeaumont

**Comment by robscott** [comment]
This was a good catch @jpeach, adding it to v1b1 milestone since I think it's a fairly simple clarification.

/remove-lifecycle stale
