### ISSUE TITLE
Explicit LoadBalancing Configurations for HTTPBackendRefs

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/gateway-api#992]
**What would you like to be added**:

Clear, explicit and top-level configuration for the load-balancing strategy when using multiple `HTTPBackendRefs` in an `HTTPRoute` ruleset.

**Why this is needed**:

Currently only a "weighted" load-balancing strategy is supported, and it's effectively _implicit_ (rather than ideally _explicit_) in configuration currently. There is no way to define other strategies, or for implementations to have their own specific strategies available.

**Comment by howardjohn** [comment]
One thing to consider is if this is a property of the route or of the backend itself (eg a Policy attached to Service)

**Comment by shaneutt** [comment]
I'm writing up a GEP right now, which I would appreciate your feedback on but I basically considered this and my current inclination is that this is a property adjacent to the list of refs, e.g.: `obj.Spec.Rules[0].BackendRefs.LoadBalancerStrategy`

**Comment by howardjohn** [comment]
I think Route is the wrong place for this - or at least the wrong place to be the exclusive location. if its a Policy, then it can attach at different points. I think the most important points are Service and global. For example, global is useful if you want to say "All services should use the 'failover to another region' load balance strategy". Probably not all your services in the cluster need to define that. Another example would be a cluster admin could decide they like Round Robin by default, but a specific service needs sticky load balancer or something.

Briefly looking at some proxies, it seems most are putting things at the backend level?:
Google: https://cloud.google.com/compute/docs/reference/rest/v1/backendServices
Envoy: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto.html?highlight=load
Possibly nginx (not as familiar): https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/
haproxy: https://www.digitalocean.com/community/tutorials/an-introduction-to-haproxy-and-load-balancing-concepts

One implementation note for those proxies is that you end up needing to create extra backends on the order of `backends * number of routes configuring backend properties`. This can explode to very large numbers

**Comment by shaneutt** [comment]
I get what you're saying. For the moment I've thrown up a draft PR:

https://github.com/kubernetes-sigs/gateway-api/pull/993

I would appreciate your early feedback on that, and if you'd like to collaborate directly with me on that branch I would be all for it.

**Comment by hbagdi** [comment]
xref https://github.com/kubernetes-sigs/gateway-api/issues/611 https://github.com/kubernetes-sigs/gateway-api/issues/196 https://github.com/kubernetes-sigs/gateway-api/issues/98

**Comment by shaneutt** [comment]
There's a pause on my priority for this so the draft is closed for the time being. Available for someone else in the meantime if there's interest, otherwise I expect I'll come back to this one at a later time.

**Comment by shaneutt** [comment]
We talked about this in the community sync today, and along with the feedback on the draft PR: policy objects are the mechanism we have today to solve for this and after discussion and highlighting a lot of the complexities with trying to add something simpler I am convinced that using policy is the right approach for now. I consider this closed but if someone else thinks on some other ways in which we could implement this and wants to re-open this I would be interested to see.
