### ISSUE TITLE
doc: missing example in policy-attachment

### ISSUE THREAD

**Issue by woodgear** [kubernetes-sigs/gateway-api#999]
[drainTimeout ](https://gateway-api.sigs.k8s.io/v1alpha2/references/policy-attachment/#:~:text=we%20can%20see%20how%20the%20override%20attached%20to%20the%20Gateway%20has%20precedence%20over%20the%20default%20drainTimeout%20value%20attached%20to%20the%20Route.)
it seems should have an example about override drainTimeout with policy attachment, but I could not find it.

**Comment by robscott** [comment]
I think this is a duplicate of #1000, let me know if not.

/close
